import type {AnalysisDataset} from "./research-analysis.ts";
import {buildResearchBundle,RESEARCH_BUNDLE_SCHEMA_VERSION,type ResearchBundle} from "./research-bundle.ts";
import {previewControlledResearchMatrix} from "./research-matrix.ts";
import type {ResearchSelectionStore} from "./research-selections.ts";

const rows=(text:string)=>text.split(/\r?\n/).filter(Boolean).map(x=>JSON.parse(x) as Record<string,unknown>);
const count=(xs:readonly Record<string,unknown>[],predicate:(x:Record<string,unknown>)=>boolean)=>xs.filter(predicate).length;
export function buildAcceptanceSummary(input:ResearchSelectionStore|ResearchBundle|AnalysisDataset,generatedAtUtc?:string){
 let run:Record<string,unknown>,tables:Record<string,readonly Record<string,unknown>[]>,matrix:ReturnType<typeof previewControlledResearchMatrix>|null=null;
 if("events" in input&&Array.isArray(input.events)){const store=input as ResearchSelectionStore,bundle=buildResearchBundle(store,generatedAtUtc??store.updatedAtUtc);run=bundle.run;tables=Object.fromEntries(Object.entries(bundle.files).filter(([n])=>n.endsWith(".jsonl")).map(([n,v])=>[n.slice(0,-6),rows(v)]));matrix=previewControlledResearchMatrix(store,"full");}
 else if("files" in input){const bundle=input as ResearchBundle;run=bundle.run;tables=Object.fromEntries(Object.entries(bundle.files).filter(([n])=>n.endsWith(".jsonl")).map(([n,v])=>[n.slice(0,-6),rows(v)]));}
 else {const dataset=input as AnalysisDataset;run={...dataset.run};tables=dataset.tables;}
 const events=tables.events??[],candidates=tables.candidates??[],valuations=tables.valuations??[],outcomes=tables.outcomes??[],margins=tables.margin_scenarios??[],futures=tables.futures_comparisons??[],fpath=tables.futures_path??[];
 const reasons=(family:string,xs:readonly Record<string,unknown>[])=>Object.fromEntries([...xs.flatMap(x=>Array.isArray(x.reason_codes)?x.reason_codes.map(String):[])].sort().reduce((m,x)=>m.set(x,(m.get(x)??0)+1),new Map<string,number>()));
 return {identity:{generated_timestamp_utc:generatedAtUtc??run.generated_at_utc??null,dataset_id:run.dataset_id??null,bundle_schema_version:run.schema_version??RESEARCH_BUNDLE_SCHEMA_VERSION,app_build_commit:run.application_commit_build_id??null,event_count:events.length,generated_denominator:run.generated_denominator_count??0,selected_structural_count:new Set(candidates.map(x=>x.candidate_id)).size,execution_row_count:candidates.length},engine_versions:{immediate:"immediate-scenario-v2",reference:run.valuation_methodology_version??"causal-reference",delayed:"causal-delayed-v2",modeled:"modeled-execution-v2",settlement:"inverse-settlement-v2",margin:"deribit-standard-margin-v2",futures:run.futures_engine_version??"unavailable"},controlled_matrix:{current_selection:new Set(candidates.map(x=>x.candidate_id)).size,full_target:matrix},track_coverage:{reference:count(candidates,x=>Boolean(x.reference_valuation&&JSON.stringify(x.reference_valuation).includes('valued'))),immediate_maker:count(candidates,x=>x.execution_scenario==="maker"&&x.execution_scenario_status==="evaluated"),immediate_taker:count(candidates,x=>x.execution_scenario==="taker"&&x.execution_scenario_status==="evaluated"),settlement:count(outcomes,x=>x.outcome_type==="settlement"&&x.status==="evaluated"),standard_margin:count(margins,x=>x.margin_status==="available"),valuation_points:valuations.length},underlying_resolution:Object.fromEntries(["vpoc_first","invalidation_first","ambiguous","unresolved"].map(k=>[k,count(events,x=>x.sequence_status===k)])),economics:{reference_positions:count(candidates,x=>x.reference_valuation!=null),observed_maker:count(candidates,x=>x.execution_scenario==="maker"&&x.execution_scenario_status==="evaluated"),observed_taker:count(candidates,x=>x.execution_scenario==="taker"&&x.execution_scenario_status==="evaluated"),margin_capital_days:count(margins,x=>typeof x.capital_days_margin==="number")},futures:{events_eligible:events.length,reference_series_available:new Set(fpath.map(x=>x.event_id)).size,observed_execution_supported:count(futures,x=>x.observed_execution_status==="available"),funding_available:count(futures,x=>x.funding_status==="available"),full_net_economics_available:count(futures,x=>typeof x.net_pnl_usd==="number"),equal_risk_available:count(futures,x=>typeof x.quantity==="number"),equal_capital_available:count(futures,x=>x.equal_capital_status==="available"),margin_available:count(futures,x=>x.futures_margin_status==="available"),unavailable_reasons:reasons("futures",futures)},missing_data_ledger:{A_source:reasons("source",[...candidates,...futures]),B_structural:matrix?.unavailableCounterparts??{},C_capability:{cross_sm_unsupported:events.length,historical_pm_unsupported:events.length,futures_margin_unverified:count(futures,x=>x.futures_margin_status!=="available")},D_implementation_defect:{count:0,reasons:[]}},deterministic:true} as const;
}
