import { createHash } from "node:crypto";
import { priceInverseOption } from "./inverse-option-pricing.ts";

export const CAUSAL_VALUATION_VERSION = "causal-inverse-surface/1.0.0";
export type ValuationTier = "exact-trade"|"official-mark"|"same-expiry-interpolation"|"adjacent-expiry-total-variance"|"bounded-extrapolation"|"dvol-smile-prior"|"unavailable";
export type QualityGrade = "A"|"B"|"C"|"D"|"unavailable";
export interface SurfaceAnchor { instrument:string; timestamp:number; expiryTimestamp:number; strike:number; optionType:"call"|"put"; indexPrice:number; forwardPrice?:number; ivDecimal?:number; priceBtc?:number; source:"trade"|"official-mark"; amount?:number }
export interface DvolObservation { timestamp:number; volatilityDecimal:number; source:"deribit-volatility-index" }
export interface SmilePrior { trainingCutoff:number; calibratedAt:number; fingerprint:string; logMoneynessSlope:number }
export interface ContractTarget { instrument:string; timestamp:number; expiryTimestamp:number; strike:number; optionType:"call"|"put"; indexPrice:number; forwardPrice?:number }
export interface LegValuation { status:"priced"|"unavailable"; pointEstimate?:number; lowerBound?:number; upperBound?:number; ivDecimal?:number; sourceTier:ValuationTier; anchorCount:number; maximumAnchorAgeMs?:number; interpolationStatus:"exact"|"interpolation"|"extrapolation"|"proxy"|"unavailable"; moneynessDistance?:number; calibrationVersion:string; reasonCodes:string[]; qualityGrade:QualityGrade; executionEvidenceSufficient:boolean; valuationAnchorOnly:boolean }

const validIv=(x:number|undefined):x is number=>x!==undefined&&Number.isFinite(x)&&x>=.05&&x<=3;
function impliedVol(target:ContractTarget,price:number){if(!(price>=0&&price<2))return undefined;let lo=.01,hi=5;for(let i=0;i<80;i++){const mid=(lo+hi)/2,r=priceInverseOption({optionType:target.optionType,indexPrice:target.indexPrice,strike:target.strike,valuationTimestamp:target.timestamp,expiryTimestamp:target.expiryTimestamp,forwardPrice:target.forwardPrice,ivDecimal:mid});if(r.status!=="priced")return undefined;if(r.priceBtc<price)lo=mid;else hi=mid;}const iv=(lo+hi)/2,r=priceInverseOption({optionType:target.optionType,indexPrice:target.indexPrice,strike:target.strike,valuationTimestamp:target.timestamp,expiryTimestamp:target.expiryTimestamp,forwardPrice:target.forwardPrice,ivDecimal:iv});return r.status==="priced"&&Math.abs(r.priceBtc-price)<1e-7?iv:undefined;}
function normalizedIv(a:SurfaceAnchor){return validIv(a.ivDecimal)?a.ivDecimal:a.priceBtc===undefined?undefined:impliedVol({...a,timestamp:a.timestamp},a.priceBtc);}
const k=(strike:number,forward:number)=>Math.log(strike/forward);
function result(target:ContractTarget,iv:number,tier:ValuationTier,anchors:SurfaceAnchor[],status:LegValuation["interpolationStatus"],reasons:string[],grade:QualityGrade):LegValuation{
 const priced=priceInverseOption({optionType:target.optionType,indexPrice:target.indexPrice,strike:target.strike,valuationTimestamp:target.timestamp,expiryTimestamp:target.expiryTimestamp,forwardPrice:target.forwardPrice,ivDecimal:iv});if(priced.status!=="priced")return unavailable("model-failure");
 const ages=anchors.map(a=>target.timestamp-a.timestamp),distance=anchors.length?Math.min(...anchors.map(a=>Math.abs(k(target.strike,target.forwardPrice??target.indexPrice)-k(a.strike,a.forwardPrice??a.indexPrice)))):undefined;
 const uncertainty=tier==="exact-trade"?.02:tier==="official-mark"?.03:tier==="same-expiry-interpolation"?.08:tier==="adjacent-expiry-total-variance"?.12:tier==="bounded-extrapolation"?.2:.3;
 const low=priceInverseOption({optionType:target.optionType,indexPrice:target.indexPrice,strike:target.strike,valuationTimestamp:target.timestamp,expiryTimestamp:target.expiryTimestamp,forwardPrice:target.forwardPrice,ivDecimal:Math.max(.05,iv*(1-uncertainty))}),high=priceInverseOption({optionType:target.optionType,indexPrice:target.indexPrice,strike:target.strike,valuationTimestamp:target.timestamp,expiryTimestamp:target.expiryTimestamp,forwardPrice:target.forwardPrice,ivDecimal:Math.min(3,iv*(1+uncertainty))});
 return{status:"priced",pointEstimate:priced.priceBtc,lowerBound:low.status==="priced"?low.priceBtc:priced.priceBtc,upperBound:high.status==="priced"?high.priceBtc:priced.priceBtc,ivDecimal:iv,sourceTier:tier,anchorCount:anchors.length,maximumAnchorAgeMs:ages.length?Math.max(...ages):undefined,interpolationStatus:status,moneynessDistance:distance,calibrationVersion:CAUSAL_VALUATION_VERSION,reasonCodes:reasons,qualityGrade:grade,executionEvidenceSufficient:false,valuationAnchorOnly:tier==="exact-trade"};
}
function unavailable(code:string):LegValuation{return{status:"unavailable",sourceTier:"unavailable",anchorCount:0,interpolationStatus:"unavailable",calibrationVersion:CAUSAL_VALUATION_VERSION,reasonCodes:[code],qualityGrade:"unavailable",executionEvidenceSufficient:false,valuationAnchorOnly:false};}
/** A deterministic, causal ladder. Marks only exist when explicitly supplied; DVOL is only a level prior. */
export function valueContract(target:ContractTarget,input:{anchors:SurfaceAnchor[];dvol?:DvolObservation;prior?:SmilePrior;maxExtrapolationLogMoneyness?:number}):LegValuation{
 if(!(target.indexPrice>0))return unavailable("missing-underlying");if(!(target.strike>0&&target.expiryTimestamp>target.timestamp))return unavailable("no-contract-metadata");
 const causal=input.anchors.filter(a=>a.timestamp<=target.timestamp).map(a=>({...a,ivDecimal:normalizedIv(a)})).filter((a):a is SurfaceAnchor&{ivDecimal:number}=>validIv(a.ivDecimal));
 const exact=causal.filter(a=>a.instrument===target.instrument).sort((a,b)=>b.timestamp-a.timestamp);const trade=exact.find(a=>a.source==="trade");if(trade)return result(target,trade.ivDecimal,"exact-trade",[trade],"exact",[trade.amount!==undefined&&trade.amount<1?"print-anchor-insufficient-for-execution":"print-anchor-not-fill"],"A");
 const mark=exact.find(a=>a.source==="official-mark");if(mark)return result(target,mark.ivDecimal,"official-mark",[mark],"exact",["official-mark-actually-supplied"],"A");
 const same=causal.filter(a=>a.expiryTimestamp===target.expiryTimestamp&&a.optionType===target.optionType).sort((a,b)=>a.strike-b.strike),below=same.filter(a=>a.strike<target.strike).at(-1),above=same.find(a=>a.strike>target.strike);
 if(below&&above){const x=k(target.strike,target.forwardPrice??target.indexPrice),x0=k(below.strike,below.forwardPrice??below.indexPrice),x1=k(above.strike,above.forwardPrice??above.indexPrice),iv=below.ivDecimal+(above.ivDecimal-below.ivDecimal)*(x-x0)/(x1-x0);if(validIv(iv))return result(target,iv,"same-expiry-interpolation",[below,above],"interpolation",["piecewise-linear-sparse-fit","parameter-count-2"],"B");}
 const expiries=[...new Set(causal.map(a=>a.expiryTimestamp))].sort((a,b)=>a-b),e0=expiries.filter(e=>e<target.expiryTimestamp).at(-1),e1=expiries.find(e=>e>target.expiryTimestamp);if(e0&&e1){const nearest=(e:number)=>causal.filter(a=>a.expiryTimestamp===e).sort((a,b)=>Math.abs(k(a.strike,a.forwardPrice??a.indexPrice)-k(target.strike,target.forwardPrice??target.indexPrice))-Math.abs(k(b.strike,b.forwardPrice??b.indexPrice)-k(target.strike,target.forwardPrice??target.indexPrice)))[0],a=nearest(e0),b=nearest(e1);if(a&&b){const t=(target.expiryTimestamp-target.timestamp)/31536e6,t0=(e0-target.timestamp)/31536e6,t1=(e1-target.timestamp)/31536e6,w0=a.ivDecimal*a.ivDecimal*t0,w1=b.ivDecimal*b.ivDecimal*t1,iv=Math.sqrt((w0+(w1-w0)*(t-t0)/(t1-t0))/t);if(validIv(iv))return result(target,iv,"adjacent-expiry-total-variance",[a,b],"interpolation",["calendar-total-variance-interpolation"],"C");}}
 if(same.length){const nearest=same.sort((a,b)=>Math.abs(a.strike-target.strike)-Math.abs(b.strike-target.strike))[0],distance=Math.abs(k(target.strike,target.forwardPrice??target.indexPrice)-k(nearest.strike,nearest.forwardPrice??nearest.indexPrice));if(distance<=(input.maxExtrapolationLogMoneyness??.25))return result(target,nearest.ivDecimal,"bounded-extrapolation",[nearest],"extrapolation",["flat-local-vol","bounded-extrapolation"],"D");}
 if(input.dvol&&input.dvol.timestamp<=target.timestamp&&validIv(input.dvol.volatilityDecimal)){if(input.prior&&input.prior.trainingCutoff>target.timestamp)return unavailable("future-trained-prior-rejected");const slope=input.prior?.logMoneynessSlope??0,iv=Math.max(.05,Math.min(3,input.dvol.volatilityDecimal*(1+slope*k(target.strike,target.forwardPrice??target.indexPrice))));return result(target,iv,"dvol-smile-prior",[],"proxy",["dvol-level-prior-not-contract-iv",input.prior?`prior:${input.prior.fingerprint}`:"flat-shape-assumption"],"D");}
 return unavailable(input.dvol?"extrapolation-outside-bounds":"no-volatility-level-input");
}
export function createSmilePrior(trainingCutoff:number,calibratedAt:number,slope:number){const payload=`${trainingCutoff}|${calibratedAt}|${slope}|${CAUSAL_VALUATION_VERSION}`;return{trainingCutoff,calibratedAt,fingerprint:createHash("sha256").update(payload).digest("hex").slice(0,16),logMoneynessSlope:slope};}

export interface ExecutionScenarios {fair_value:number;modeled_expected_execution?:number;modeled_conservative_execution:number;assumptionSensitivity?:Array<{penaltyBps:number;credit:number}>;calibrationSampleSize:number;expectedEstimatorPromoted:boolean}
export function executionScenarios(fairCredit:number,overlapPenaltiesBps:number[],minimum=30):ExecutionScenarios{const clean=overlapPenaltiesBps.filter(x=>Number.isFinite(x)&&x>=0),apply=(bps:number)=>fairCredit-Math.abs(fairCredit)*bps/1e4;if(clean.length<minimum)return{fair_value:fairCredit,modeled_conservative_execution:apply(500),assumptionSensitivity:[50,100,250,500].map(penaltyBps=>({penaltyBps,credit:apply(penaltyBps)})),calibrationSampleSize:clean.length,expectedEstimatorPromoted:false};const sorted=[...clean].sort((a,b)=>a-b),median=sorted[Math.floor(sorted.length/2)],tail=sorted[Math.floor(sorted.length*.9)];return{fair_value:fairCredit,modeled_expected_execution:apply(median),modeled_conservative_execution:apply(Math.max(median,tail)),calibrationSampleSize:clean.length,expectedEstimatorPromoted:true};}

export function validateLeaveOneOut(rows:Array<{id:string;observed:number;modeled:number;observedIv?:number;modeledIv?:number}>){const ordered=[...rows].sort((a,b)=>a.id.localeCompare(b.id)),errors=ordered.map(r=>r.modeled-r.observed),abs=errors.map(Math.abs).sort((a,b)=>a-b),signErrors=ordered.filter(r=>Math.sign(r.observed)!==Math.sign(r.modeled)).length;return{n:ordered.length,bias:errors.length?errors.reduce((a,b)=>a+b,0)/errors.length:null,mae:abs.length?abs.reduce((a,b)=>a+b,0)/abs.length:null,medianAbsolutePercentageError:ordered.filter(r=>r.observed!==0).length?ordered.filter(r=>r.observed!==0).map(r=>Math.abs((r.modeled-r.observed)/r.observed)).sort((a,b)=>a-b)[Math.floor(ordered.filter(r=>r.observed!==0).length/2)]:null,tailAbsoluteErrorP95:abs.length?abs[Math.floor((abs.length-1)*.95)]:null,signErrors,rows:ordered};}
