import { aggregateRoutedFees, calculateOptionFee, STANDARD_INVERSE_BTC_OPTION_FEE } from "./accounting.ts";
import type { BacktestEvent, Candle, ContractSeries, ContractTrade, ExecutionMode, InstrumentAmountMetadata, RetrievedSpread } from "./backtester.ts";
import { tapeDirectionFor } from "./execution-side.ts";
import { DELAYED_MAXIMUM_LEG_SYNCHRONIZATION_MS, synchronizationQuality } from "./execution-policy.ts";
import { expiryPayoff } from "./expiry-payoff.ts";
import { validateOfficialDeliveryPrice, SETTLEMENT_ACCOUNTING_VERSION, DELIVERY_FEE_SCHEDULE_VERSION } from "./settlement-provenance.ts";

export const ENTRY_TIMING_POLICY_VERSION = "causal-progressive-entry/2.0.0" as const;
export type DelayBucketId = "0-2h"|"2-4h"|"4-8h"|"8-12h"|"12-24h"|"next-trading-day";
export interface EntryTimingWindow { id:DelayBucketId; startMs:number; endMs:number }
export interface EntryTimingPolicy { id:string; version:typeof ENTRY_TIMING_POLICY_VERSION; maximumDelayMs:number; maximumLegSynchronizationMs:number; requirePositiveNetCredit:boolean; windows:EntryTimingWindow[] }
export function createEntryTimingPolicy(input:Partial<Pick<EntryTimingPolicy,"maximumDelayMs"|"maximumLegSynchronizationMs"|"requirePositiveNetCredit">>={}):EntryTimingPolicy {
 const maximumDelayMs=input.maximumDelayMs??48*3_600_000;
 if(maximumDelayMs<24*3_600_000)throw new Error("maximumDelayMs must include the first 24 hours");
 return{id:`${ENTRY_TIMING_POLICY_VERSION}/max-${maximumDelayMs}`,version:ENTRY_TIMING_POLICY_VERSION,maximumDelayMs,maximumLegSynchronizationMs:input.maximumLegSynchronizationMs??DELAYED_MAXIMUM_LEG_SYNCHRONIZATION_MS,requirePositiveNetCredit:input.requirePositiveNetCredit??true,windows:[
  {id:"0-2h",startMs:0,endMs:2*3_600_000},{id:"2-4h",startMs:2*3_600_000,endMs:4*3_600_000},{id:"4-8h",startMs:4*3_600_000,endMs:8*3_600_000},{id:"8-12h",startMs:8*3_600_000,endMs:12*3_600_000},{id:"12-24h",startMs:12*3_600_000,endMs:24*3_600_000},{id:"next-trading-day",startMs:24*3_600_000,endMs:maximumDelayMs}]};
}

export type PreEntryResolution="entered-before-vpoc"|"entered-before-invalidation"|"vpoc-occurred-before-entry"|"invalidation-occurred-before-entry"|"ambiguous-same-timestamp"|"expired-before-entry"|"no-qualifying-execution-before-maximum-delay";
export type DelayedReasonCode="missing-exact-contract"|"no-compatible-short-evidence"|"no-compatible-long-evidence"|"insufficient-short-amount"|"insufficient-long-amount"|"synchronization-failure"|"expired-before-entry"|"debit-at-delayed-entry"|"nonpositive-net-credit"|"invalid-size-metadata"|"no-qualifying-execution-before-maximum-delay";
export interface DelayedLegEvidence {instrumentName:string;action:"buy"|"sell";requiredTapeDirection:"buy"|"sell";requestedAmount:number;supportedAmount:number;remainingAmount:number;tradeCount:number;firstEvidenceTimestamp:number;completionTimestamp:number;evidenceIds:string[];rawQualifyingAmount:number;vwapBtc:number;slippedPriceBtc:number;supportingTrades:ContractTrade[]}
export interface DelayedEconomics {underlyingIndex:number;remainingDte:number;shortPriceBtc:number;longPriceBtc:number;grossCreditBtc:number;openingFeesBtc:number;slippageBps:number;netCreditBtc:number;breakevenUsd:number;maximumEconomicLossBtc:number;legacyMaximumEconomicLossProxyBtc:number;entryQuality:"green"|"yellow"|"red"}
export interface DelayedPathPoint {timestamp:number;hoursFromEntry:number;underlyingIndex:number;remainingDte:number;intrinsicSpreadBtc:number;estimatedPnlBtc:number;maxLossDays:number}
export interface LeggingRiskDiagnostics {shortCompletionTimestamp:number;longCompletionTimestamp:number;firstCompletedLeg:"short"|"long"|"simultaneous";temporaryPartialPositionDurationMs:number;underlyingIndexAtFirstLeg?:number;underlyingIndexAtSecondLeg?:number;underlyingMoveBetweenLegs?:number;interpretation:"diagnostic-only-not-realized-legging-pnl"}
export interface DelayedSettlementOutcome {status:"settlement-benchmark-priced"|"official-delivery-price-unavailable";benchmarkOnly:true;deliveryPrice?:number;deliveryTimestamp?:number;deliveryPriceSource?:string;priceIndex?:string;feeScheduleVersion:string;settlementCalculationVersion:string;netPnlBtc?:number;netPnlUsd?:number;reason:string}
export interface DelayedObservation {settlementOutcome?:DelayedSettlementOutcome;status:"delayed observed opportunity"|"delayed taker execution proxy"|"observed-but-policy-rejected"|"missed-entry"|"unavailable";scenario:ExecutionMode;policyId:string;window:EntryTimingWindow;signalTimestamp:number;entryTimestamp?:number;delayMs?:number;shortLeg?:DelayedLegEvidence;longLeg?:DelayedLegEvidence;synchronizationGapMs?:number;synchronizationQuality?:"green"|"yellow"|"red";leggingRiskDiagnostics?:LeggingRiskDiagnostics;economics?:DelayedEconomics;preEntryResolution:PreEntryResolution;reasonCode?:DelayedReasonCode;reason?:string;historicalMinimumSizeMetadataAvailable:boolean;postEntryPath:DelayedPathPoint[];operationalHoldingHours?:number;maxLossDays?:number;thesisResolutionHours?:number}
export interface DelayedSizeResult {size:number;isPrimary:boolean;validAgainstMetadata:boolean;metadataLimitation?:string;maker:DelayedObservation[];taker:DelayedObservation[]}
export interface DelayedExecutionAnalysis {policy:EntryTimingPolicy;primarySize:number;declaredSizes:number[];results:DelayedSizeResult[];coverageByDelayBucket:Record<DelayBucketId,{maker:number;taker:number;rejected:number}>}

const unique=(trades:ContractTrade[])=>{const seen=new Set<string>();return trades.filter((t,i)=>{const key=t.tradeId?`id:${t.tradeId}`:`row:${t.instrumentName}:${t.timestamp}:${t.direction}:${t.price}:${t.amount}:${i}`;if(seen.has(key))return false;seen.add(key);return true})};
function sizeValid(size:number,metadata?:InstrumentAmountMetadata){if(!metadata)return true;const units=(size-metadata.minimumTradeAmount)/metadata.amountStep;return size>=metadata.minimumTradeAmount-1e-12&&Math.abs(units-Math.round(units))<1e-9}
function candidates(series:ContractSeries,action:"buy"|"sell",mode:ExecutionMode,amount:number,start:number,end:number,slippageBps:number){
 const direction=tapeDirectionFor(action,mode),rows=unique(series.trades).filter(t=>t.instrumentName===series.instrumentName&&t.timestamp>start&&t.timestamp<=end&&t.direction===direction&&t.amount>0&&t.price>=0).sort((a,b)=>a.timestamp-b.timestamp||String(a.tradeId??"").localeCompare(String(b.tradeId??"")));
 const out:DelayedLegEvidence[]=[];for(let from=0;from<rows.length;from++){let remaining=amount,notional=0;const used:ContractTrade[]=[];for(let i=from;i<rows.length&&remaining>1e-12;i++){const take=Math.min(remaining,rows[i].amount);used.push({...rows[i],amount:take});notional+=take*rows[i].price;remaining-=take;if(remaining<=1e-12){const vwap=notional/amount;out.push({instrumentName:series.instrumentName,action,requiredTapeDirection:direction,requestedAmount:amount,supportedAmount:amount,remainingAmount:0,tradeCount:used.length,firstEvidenceTimestamp:used[0].timestamp,completionTimestamp:rows[i].timestamp,evidenceIds:used.map((t,j)=>t.tradeId??`${t.instrumentName}:${t.timestamp}:${t.direction}:${j}`),rawQualifyingAmount:rows.slice(from,i+1).reduce((s,t)=>s+t.amount,0),vwapBtc:vwap,slippedPriceBtc:vwap*(action==="buy"?1+slippageBps/10_000:1-slippageBps/10_000),supportingTrades:used});break}}}return{direction,rows,out};
}
function resolution(event:BacktestEvent,entry:number|undefined,expiry:number,none=false):{classification:PreEntryResolution;hours?:number}{
 if(entry===undefined)return{classification:none?"no-qualifying-execution-before-maximum-delay":"expired-before-entry"};if(entry>=expiry)return{classification:"expired-before-entry"};
 const points=[event.vpocTimestamp&&{kind:"vpoc" as const,t:event.vpocTimestamp},event.exitTimestamp&&{kind:"invalidation" as const,t:event.exitTimestamp}].filter(Boolean) as {kind:"vpoc"|"invalidation";t:number}[];points.sort((a,b)=>a.t-b.t);const first=points[0];if(!first)return{classification:"entered-before-vpoc"};const hours=(first.t-(event.entryTimestamp??entry))/3_600_000;if(first.t===entry)return{classification:"ambiguous-same-timestamp",hours};if(first.t<entry)return{classification:first.kind==="vpoc"?"vpoc-occurred-before-entry":"invalidation-occurred-before-entry",hours};return{classification:first.kind==="vpoc"?"entered-before-vpoc":"entered-before-invalidation",hours};
}

/** Convert the diagnostic ladder into the persisted, analytics-facing tracks. */
export function delayedExecutionSnapshot(analysis:DelayedExecutionAnalysis,referenceNetCreditBtc?:number){
 const primary=analysis.results.find(r=>r.isPrimary)!;
 const track=(mode:ExecutionMode)=>{const attempts=primary[mode];const completed=attempts.find(a=>a.status==="delayed observed opportunity"||a.status==="delayed taker execution proxy");
  if(!completed){const terminal=attempts.find(a=>a.status==="missed-entry"||a.status==="observed-but-policy-rejected")??attempts.at(-1)!;return{status:"unavailable" as const,reason:terminal.reason??"No complete two-leg scenario before the configured maximum delay.",reasonCode:terminal.reasonCode??"no-qualifying-execution-before-maximum-delay",preEntryResolution:terminal.preEntryResolution,policy:analysis.policy,attempts};}
  const e=completed.economics!;return{status:"evaluated" as const,reason:null,source:mode==="maker"?"delayed observed maker opportunity":"delayed conservative taker tape proxy",entrySnapshot:{valuationTimestamp:completed.entryTimestamp,targetTimestamp:completed.entryTimestamp,requestedOrderTimestamp:completed.signalTimestamp+completed.window.startMs,delayHours:completed.delayMs!/3_600_000,requestedDelayHours:completed.window.startMs/3_600_000,actualDteRemaining:e.remainingDte,entryTargetIndex:e.underlyingIndex,grossSpreadBtc:e.grossCreditBtc,openingFeesBtc:e.openingFeesBtc,netOpeningCashFlowBtc:e.netCreditBtc,creditChangeVsReferenceBtc:referenceNetCreditBtc===undefined?null:e.netCreditBtc-referenceNetCreditBtc,estimateQuality:e.entryQuality,shortLeg:completed.shortLeg,longLeg:completed.longLeg,synchronizationGapMs:completed.synchronizationGapMs,policyId:completed.policyId,provenance:{observed:true,makerQueueFillClaimed:false,causalAfterRequestedOrder:true}},valuationPathSnapshot:completed.postEntryPath,outcomeSnapshots:completed.postEntryPath.length?[{label:"terminal delayed path",valuationTimestamp:completed.postEntryPath.at(-1)!.timestamp,estimatedNetPnlBtc:completed.postEntryPath.at(-1)!.estimatedPnlBtc}]:[],preEntryResolution:completed.preEntryResolution,policy:analysis.policy,attempts};};
 return{version:ENTRY_TIMING_POLICY_VERSION,policy:analysis.policy,maker:track("maker"),taker:track("taker")};
}
function path(candles:Candle[],entry:number,expiry:number,e:DelayedEconomics,spread:RetrievedSpread,amount:number){const width=Math.abs((spread.resolvedSoldStrike??spread.soldStrike)-(spread.resolvedBoughtStrike??spread.boughtStrike));return candles.filter(c=>c.closeTime>entry&&c.closeTime<=expiry).sort((a,b)=>a.closeTime-b.closeTime).map(c=>{const short=spread.optionType==="P"?Math.max((spread.resolvedSoldStrike??spread.soldStrike)-c.close,0):Math.max(c.close-(spread.resolvedSoldStrike??spread.soldStrike),0),long=spread.optionType==="P"?Math.max((spread.resolvedBoughtStrike??spread.boughtStrike)-c.close,0):Math.max(c.close-(spread.resolvedBoughtStrike??spread.boughtStrike),0),intrinsic=Math.min(width,Math.max(0,short-long))/c.close*amount,h=(c.closeTime-entry)/3_600_000;return{timestamp:c.closeTime,hoursFromEntry:h,underlyingIndex:c.close,remainingDte:Math.max(0,(expiry-c.closeTime)/86_400_000),intrinsicSpreadBtc:intrinsic,estimatedPnlBtc:e.netCreditBtc-intrinsic,maxLossDays:e.maximumEconomicLossBtc*h/24}})}

export function analyzeDelayedExecution(input:{spread:RetrievedSpread;event:BacktestEvent;signalTimestamp:number;underlyingCandles:Candle[];primarySize:number;sizeGrid?:number[];slippageBps?:number;policy?:EntryTimingPolicy}):DelayedExecutionAnalysis{
 const policy=input.policy??createEntryTimingPolicy(),slippage=input.slippageBps??0,sizes=[input.primarySize,...(input.sizeGrid??[])].filter((x,i,a)=>x>0&&a.indexOf(x)===i),expiry=input.spread.expiryTimestamp??input.spread.soldContract?.expiryTimestamp??0;
 const coverage=Object.fromEntries(policy.windows.map(w=>[w.id,{maker:0,taker:0,rejected:0}])) as DelayedExecutionAnalysis["coverageByDelayBucket"];
 const results=sizes.map(size=>{const metadataAvailable=Boolean(input.spread.soldContract?.amountMetadata&&input.spread.boughtContract?.amountMetadata),valid=sizeValid(size,input.spread.soldContract?.amountMetadata)&&sizeValid(size,input.spread.boughtContract?.amountMetadata);const evaluate=(mode:ExecutionMode)=>policy.windows.map(window=>{
  const base:DelayedObservation={status:"unavailable",scenario:mode,policyId:policy.id,window,signalTimestamp:input.signalTimestamp,preEntryResolution:"no-qualifying-execution-before-maximum-delay",historicalMinimumSizeMetadataAvailable:metadataAvailable,postEntryPath:[]};
  if(!input.spread.soldContract||!input.spread.boughtContract)return{...base,reasonCode:"missing-exact-contract" as const,reason:"Both exact contracts are required."};if(!valid)return{...base,reasonCode:"invalid-size-metadata" as const,reason:"Declared size violates historically applicable contract amount metadata."};
  const start=input.signalTimestamp+window.startMs,end=Math.min(input.signalTimestamp+window.endMs,expiry);if(start>=expiry)return{...base,preEntryResolution:"expired-before-entry" as const,reasonCode:"expired-before-entry" as const,reason:"The option expired before this delayed window began."};
  const s=candidates(input.spread.soldContract,"sell",mode,size,start,end,slippage),l=candidates(input.spread.boughtContract,"buy",mode,size,start,end,slippage);let pair:{s:DelayedLegEvidence;l:DelayedLegEvidence}|undefined;for(const sc of s.out)for(const lc of l.out){if(Math.abs(sc.completionTimestamp-lc.completionTimestamp)<=policy.maximumLegSynchronizationMs&&(!pair||Math.max(sc.completionTimestamp,lc.completionTimestamp)<Math.max(pair.s.completionTimestamp,pair.l.completionTimestamp)))pair={s:sc,l:lc}}
  if(!pair){if(expiry<=input.signalTimestamp+window.endMs)return{...base,preEntryResolution:"expired-before-entry" as const,reasonCode:"expired-before-entry" as const,reason:"Expiry occurred before both delayed legs could qualify."};const reasonCode:DelayedReasonCode=!s.rows.length?"no-compatible-short-evidence":!l.rows.length?"no-compatible-long-evidence":!s.out.length?"insufficient-short-amount":!l.out.length?"insufficient-long-amount":"synchronization-failure";return{...base,reasonCode,reason:reasonCode==="synchronization-failure"?"Both legs qualified independently, but no deterministic pair met the synchronization bound.":"The delayed window lacked sufficient compatible causal tape."};}
  const entry=Math.max(pair.s.completionTimestamp,pair.l.completionTimestamp),spot=pair.s.supportingTrades.at(-1)!.indexPrice||pair.l.supportingTrades.at(-1)!.indexPrice,width=Math.abs(input.spread.soldStrike-input.spread.boughtStrike),gross=(pair.s.slippedPriceBtc-pair.l.slippedPriceBtc)*size,fees=aggregateRoutedFees([{side:"sell",fee:calculateOptionFee(pair.s.slippedPriceBtc,size,mode,STANDARD_INVERSE_BTC_OPTION_FEE)},{side:"buy",fee:calculateOptionFee(pair.l.slippedPriceBtc,size,mode,STANDARD_INVERSE_BTC_OPTION_FEE)}],"synchronized-leg-proxy").finalFee,net=gross-fees,maxLoss=Math.max(0,width/spot*size-net),economics:DelayedEconomics={underlyingIndex:spot,remainingDte:Math.max(0,(expiry-entry)/86_400_000),shortPriceBtc:pair.s.slippedPriceBtc,longPriceBtc:pair.l.slippedPriceBtc,grossCreditBtc:gross,openingFeesBtc:fees,slippageBps:slippage,netCreditBtc:net,breakevenUsd:input.spread.soldStrike+(input.spread.optionType==="P"?-1:1)*(net/size)*spot,maximumEconomicLossBtc:maxLoss,legacyMaximumEconomicLossProxyBtc:maxLoss,entryQuality:Math.abs(pair.s.completionTimestamp-pair.l.completionTimestamp)<=policy.maximumLegSynchronizationMs/2?"green":"yellow"};
  const rr=resolution(input.event,entry,expiry),missed=["vpoc-occurred-before-entry","invalidation-occurred-before-entry","ambiguous-same-timestamp","expired-before-entry"].includes(rr.classification),rejected=gross<=0||policy.requirePositiveNetCredit&&net<=0,status:DelayedObservation["status"]=missed?"missed-entry":rejected?"observed-but-policy-rejected":mode==="maker"?"delayed observed opportunity":"delayed taker execution proxy",reasonCode:DelayedReasonCode|undefined=gross<=0?"debit-at-delayed-entry":net<=0?"nonpositive-net-credit":undefined,p=path(input.underlyingCandles,entry,expiry,economics,input.spread,size),last=p.at(-1);if(status.startsWith("delayed"))coverage[window.id][mode]++;else if(rejected)coverage[window.id].rejected++;
  const delivery=validateOfficialDeliveryPrice(input.spread);let settlementOutcome:DelayedSettlementOutcome|undefined;if(!missed&&!rejected){if(!delivery.ok)settlementOutcome={status:"official-delivery-price-unavailable",benchmarkOnly:true,feeScheduleVersion:DELIVERY_FEE_SCHEDULE_VERSION,settlementCalculationVersion:SETTLEMENT_ACCOUNTING_VERSION,reason:delivery.reason};else{const payoff=expiryPayoff({optionType:input.spread.optionType,shortStrike:input.spread.soldContract.strike,longStrike:input.spread.boughtContract.strike,shortEntryPremiumBtc:economics.shortPriceBtc,longEntryPremiumBtc:economics.longPriceBtc,entryIndex:economics.underlyingIndex,amount:size,openingFeesBtc:economics.openingFeesBtc,expiryTimestamp:expiry},delivery.deliveryPrice,"btc-settlement"),usd=expiryPayoff({optionType:input.spread.optionType,shortStrike:input.spread.soldContract.strike,longStrike:input.spread.boughtContract.strike,shortEntryPremiumBtc:economics.shortPriceBtc,longEntryPremiumBtc:economics.longPriceBtc,entryIndex:economics.underlyingIndex,amount:size,openingFeesBtc:economics.openingFeesBtc,expiryTimestamp:expiry},delivery.deliveryPrice,"usd-cash-flow");settlementOutcome={status:"settlement-benchmark-priced",benchmarkOnly:true,deliveryPrice:delivery.deliveryPrice,deliveryTimestamp:expiry,deliveryPriceSource:input.spread.deliveryPriceSource,priceIndex:delivery.priceIndex,feeScheduleVersion:DELIVERY_FEE_SCHEDULE_VERSION,settlementCalculationVersion:SETTLEMENT_ACCOUNTING_VERSION,netPnlBtc:payoff.pnl,netPnlUsd:usd.pnl,reason:"Official settlement benchmark from this delayed track opening ledger."};}}
  const gap=Math.abs(pair.s.completionTimestamp-pair.l.completionTimestamp),shortIndex=pair.s.supportingTrades.at(-1)?.indexPrice,longIndex=pair.l.supportingTrades.at(-1)?.indexPrice,first=pair.s.completionTimestamp===pair.l.completionTimestamp?"simultaneous" as const:pair.s.completionTimestamp<pair.l.completionTimestamp?"short" as const:"long" as const,firstIndex=first==="short"?shortIndex:first==="long"?longIndex:shortIndex,secondIndex=first==="short"?longIndex:first==="long"?shortIndex:longIndex;
  return{...base,status,settlementOutcome,entryTimestamp:entry,delayMs:entry-input.signalTimestamp,shortLeg:pair.s,longLeg:pair.l,synchronizationGapMs:gap,synchronizationQuality:synchronizationQuality(gap),leggingRiskDiagnostics:{shortCompletionTimestamp:pair.s.completionTimestamp,longCompletionTimestamp:pair.l.completionTimestamp,firstCompletedLeg:first,temporaryPartialPositionDurationMs:gap,underlyingIndexAtFirstLeg:firstIndex,underlyingIndexAtSecondLeg:secondIndex,underlyingMoveBetweenLegs:firstIndex&&secondIndex?secondIndex-firstIndex:undefined,interpretation:"diagnostic-only-not-realized-legging-pnl"},economics,preEntryResolution:rr.classification,reasonCode,reason:rejected?"Observed later tape, but delayed economics violate the configured credit-entry policy.":missed?"The thesis resolved before both legs completed; this is a missed entry.":mode==="maker"?"Opposing-aggressor tape supports only a delayed observed opportunity; queue fill is not claimed.":"Same-side causal tape supports a delayed taker execution proxy.",postEntryPath:missed||rejected?[]:p,operationalHoldingHours:last?.hoursFromEntry,maxLossDays:last?.maxLossDays,thesisResolutionHours:rr.hours};
 });return{size,isPrimary:size===input.primarySize,validAgainstMetadata:valid,metadataLimitation:metadataAvailable?undefined:"Historical minimum-size metadata is unavailable; declared sizes could not be exchange-increment validated.",maker:evaluate("maker"),taker:evaluate("taker")}});
 // Persistence is JSON by contract. Removing optional `undefined` members here
 // makes an exported/imported analysis structurally identical, not merely
 // semantically equivalent.
 return JSON.parse(JSON.stringify({policy,primarySize:input.primarySize,declaredSizes:sizes,results,coverageByDelayBucket:coverage})) as DelayedExecutionAnalysis;
}
