/** Standalone, causal trade-vs-fair calibration observations (not runtime execution). */
import {priceInverseOption, INVERSE_OPTION_MODEL} from "./inverse-option-pricing.ts";
import {admitCrossSection, dedupePrints, tradeIdentityKey, type RawOptionPrint} from "./volatility/cross-section.ts";
import {aggregateSlice} from "./volatility/strike-aggregation.ts";
import {estimateHybrid, estimateLinearInterpolation, HYBRID_METHOD_VERSION, type EstimationTarget} from "./volatility/surface-models.ts";
import {REFERENCE_GEOMETRY_RULE, REFERENCE_VALUATION_METHOD_VERSION, RULE_C_MINIMUM_UNIQUE_STRIKES} from "./volatility/reference-hybrid.ts";
import {contentHash} from "./volatility/reference-series.ts";

export const EXECUTION_CALIBRATION_DATASET_ID="execution_calibration_observations" as const;
export const EXECUTION_CALIBRATION_METHOD_VERSION="execution-calibration-observations-v1" as const;
export const DIRECTION_SEMANTICS_VERSION="deribit-public-trades-direction-aggressor-v1" as const;
export const RELATIVE_PRICE_MINIMUM_FAIR_BTC=1e-8;
const MIN=60_000, DAY=86_400_000, YEAR=365*DAY;

export type CalibrationStatus="eligible_primary_calibration"|"invalid_trade_iv"|"invalid_trade_price"|"contract_not_listed"|"source_window_incomplete"|"independent_reference_not_bracketed"|"independent_reference_too_sparse"|"fair_reference_unavailable"|"direction_semantics_unavailable";
export interface CalibrationFeatures {same_instrument_count_5m:number;same_instrument_count_15m:number;same_instrument_count_60m:number;same_instrument_amount_5m:number;same_instrument_amount_15m:number;same_instrument_amount_60m:number;seconds_since_previous_same_instrument:number|null;same_expiry_count_60m:number;same_expiry_amount_60m:number;same_expiry_unique_strikes_60m:number;utc_hour:number;day_of_week:number;calendar_date:string;calendar_week:string;calendar_month:string;expiry_date_group:string;instrument_group:string;expiry_date_group_id:string;utc_hour_block:string}
export interface ExecutionCalibrationObservation {observation_id:string;dataset_id:string;method_version:string;status:CalibrationStatus;trade_id:string|null;trade_seq:number|null;instrument_name:string;trade_timestamp_ms:number;trade_timestamp_utc:string;source_host:string;retrieval_shard_id:string;retrieval_content_hash:string;source_window_complete:boolean;strike:number;option_type:"C"|"P";expiry_timestamp_ms:number;expiry_timestamp_utc:string;actual_dte_days:number;creation_timestamp_ms:number|null;settlement_period:string|null;contract_size:number|null;minimum_trade_amount:number|null;log_moneyness:number|null;trade_price_btc:number|null;trade_iv_decimal:number|null;trade_iv_api_percentage:number|null;index_price:number|null;mark_price_btc:number|null;amount:number|null;direction:string|null;tick_direction:number|null;direction_is_aggressor:boolean;primary_fair_iv_decimal:number|null;primary_fair_price_btc:number|null;production_hybrid_fair_iv_decimal:number|null;production_hybrid_fair_price_btc:number|null;pricing_model_version:string;fair_value_method_version:string;geometry_rule:string;forward_convention:"forward_equals_index_rate_zero";rate_assumption:0;fair_reference_observation_count:number;fair_reference_unique_strike_count:number;lower_strike:number|null;upper_strike:number|null;max_evidence_age_minutes:number|null;signed_iv_residual_decimal:number|null;signed_iv_residual_vol_points:number|null;adverse_iv_concession_decimal:number|null;adverse_iv_concession_vol_points:number|null;signed_price_residual_btc:number|null;adverse_price_concession_btc:number|null;relative_adverse_price_concession_bps:number|null;features:CalibrationFeatures}

export const calibrationObservationId=(p:RawOptionPrint)=>`cal~${contentHash(tradeIdentityKey(p))}`;
export function adverseConcession(direction:string|null,trade:number,fair:number):number|null{return direction==="buy"?trade-fair:direction==="sell"?fair-trade:null}
export function relativeConcessionBps(adverse:number|null,fair:number|null):number|null{return adverse===null||fair===null||Math.abs(fair)<RELATIVE_PRICE_MINIMUM_FAIR_BTC?null:adverse/Math.abs(fair)*1e4}
const week=(ms:number)=>{const d=new Date(ms),x=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return `${x.getUTCFullYear()}-W${String(Math.ceil((((+x-(+y))/DAY)+1)/7)).padStart(2,"0")}`};
export function causalFeatures(target:RawOptionPrint,tape:readonly RawOptionPrint[]):CalibrationFeatures {const prior=tape.filter(p=>p.timestampMs<target.timestampMs);const inst=prior.filter(p=>p.instrumentName===target.instrumentName),expiry=prior.filter(p=>p.expiryTimestampMs===target.expiryTimestampMs);const window=(xs:readonly RawOptionPrint[],m:number)=>xs.filter(p=>p.timestampMs>=target.timestampMs-m*MIN);const amount=(xs:readonly RawOptionPrint[])=>xs.reduce((s,p)=>s+(typeof p.amount==="number"&&Number.isFinite(p.amount)?p.amount:0),0);const i5=window(inst,5),i15=window(inst,15),i60=window(inst,60),e60=window(expiry,60),last=inst.reduce((v,p)=>Math.max(v,p.timestampMs),-Infinity);const d=new Date(target.timestampMs),date=d.toISOString().slice(0,10),exp=new Date(target.expiryTimestampMs).toISOString().slice(0,10);return{same_instrument_count_5m:i5.length,same_instrument_count_15m:i15.length,same_instrument_count_60m:i60.length,same_instrument_amount_5m:amount(i5),same_instrument_amount_15m:amount(i15),same_instrument_amount_60m:amount(i60),seconds_since_previous_same_instrument:Number.isFinite(last)?(target.timestampMs-last)/1000:null,same_expiry_count_60m:e60.length,same_expiry_amount_60m:amount(e60),same_expiry_unique_strikes_60m:new Set(e60.map(p=>p.strike)).size,utc_hour:d.getUTCHours(),day_of_week:d.getUTCDay(),calendar_date:date,calendar_week:week(target.timestampMs),calendar_month:date.slice(0,7),expiry_date_group:exp,instrument_group:target.instrumentName,expiry_date_group_id:`${exp}~${date}`,utc_hour_block:`${date}T${String(d.getUTCHours()).padStart(2,"0")}`}}

export function buildCalibrationObservation(input:{target:RawOptionPrint;tape:readonly RawOptionPrint[];sourceHost:string;retrievalShardId:string;retrievalContentHash:string;sourceWindowComplete:boolean;contractSize?:number|null;minimumTradeAmount?:number|null;directionSemanticsVerified?:boolean}):ExecutionCalibrationObservation {
 const t=input.target, ts=t.timestampMs,index=typeof t.indexPrice==="number"&&t.indexPrice>0?t.indexPrice:null,iv=typeof t.ivApiPercent==="number"&&t.ivApiPercent>0?t.ivApiPercent/100:null,price=typeof t.price==="number"&&Number.isFinite(t.price)&&t.price>=0?t.price:null,created=typeof t.contractCreatedAtMs==="number"?t.contractCreatedAtMs:null,dte=(t.expiryTimestampMs-ts)/DAY,k=index?Math.log(t.strike/index):null;
 const baseStatus:CalibrationStatus=!input.sourceWindowComplete?"source_window_incomplete":created!==null&&created>ts?"contract_not_listed":iv===null?"invalid_trade_iv":price===null?"invalid_trade_price":"fair_reference_unavailable";
 const strictlyPrior=dedupePrints(input.tape.filter(p=>p.timestampMs<ts&&p.instrumentName!==t.instrumentName&&p.expiryTimestampMs===t.expiryTimestampMs)).prints;
 const admitted=index===null?[]:admitCrossSection({prints:strictlyPrior,targetTimestampMs:ts,underlyingPrice:index,sourceHost:input.sourceHost,excludedInstruments:[t.instrumentName]}).observations;
 const points=aggregateSlice(admitted), target:EstimationTarget={strike:t.strike,optionType:t.optionType,logMoneyness:k??0,timeToExpiryYears:(t.expiryTimestampMs-ts)/YEAR,underlyingPrice:index??0,targetTimestampMs:ts,expiryTimestampMs:t.expiryTimestampMs};
 const unique=new Set(points.map(p=>p.strike)).size, lower=k===null?null:points.filter(p=>p.log_moneyness<k).sort((a,b)=>b.log_moneyness-a.log_moneyness)[0]?.strike??null,upper=k===null?null:points.filter(p=>p.log_moneyness>k).sort((a,b)=>a.log_moneyness-b.log_moneyness)[0]?.strike??null,bracketed=lower!==null&&upper!==null;
 const primary=baseStatus==="fair_reference_unavailable"&&bracketed&&unique>=RULE_C_MINIMUM_UNIQUE_STRIKES?estimateLinearInterpolation(points,target):null;
 const priorAnchor=input.tape.filter(p=>p.instrumentName===t.instrumentName&&p.timestampMs<ts&&typeof p.ivApiPercent==="number"&&p.ivApiPercent>0).sort((a,b)=>b.timestampMs-a.timestampMs)[0];
 const hybrid=baseStatus==="fair_reference_unavailable"?estimateHybrid({points,anchor:priorAnchor?{instrument_name:priorAnchor.instrumentName,timestamp_ms:priorAnchor.timestampMs,age_minutes:(ts-priorAnchor.timestampMs)/MIN,iv_decimal:priorAnchor.ivApiPercent!/100}:null,target,rule:"rule_c_min_5_strikes"}):null;
 const fairIv=primary?.status==="available"?primary.iv_decimal:null, fairPrice=fairIv!==null&&index!==null?priceInverseOption({optionType:t.optionType==="C"?"call":"put",indexPrice:index,strike:t.strike,valuationTimestamp:ts,expiryTimestamp:t.expiryTimestampMs,ivDecimal:fairIv}):null,fp=fairPrice?.status==="priced"?fairPrice.priceBtc:null;
 const hybridIv=hybrid?.status==="available"?hybrid.iv_decimal:null,hp=hybridIv!==null&&index!==null?priceInverseOption({optionType:t.optionType==="C"?"call":"put",indexPrice:index,strike:t.strike,valuationTimestamp:ts,expiryTimestamp:t.expiryTimestampMs,ivDecimal:hybridIv}):null,hfp=hp?.status==="priced"?hp.priceBtc:null;
 let status:CalibrationStatus=baseStatus;if(baseStatus==="fair_reference_unavailable"){status=!bracketed?"independent_reference_not_bracketed":unique<RULE_C_MINIMUM_UNIQUE_STRIKES?"independent_reference_too_sparse":fairIv===null||fp===null?"fair_reference_unavailable":input.directionSemanticsVerified===false?"direction_semantics_unavailable":"eligible_primary_calibration"}
 const directionVerified=input.directionSemanticsVerified!==false&&(t.direction==="buy"||t.direction==="sell"),air=iv!==null&&fairIv!==null?iv-fairIv:null,aiv=air===null?null:adverseConcession(directionVerified?t.direction??null:null,iv!,fairIv!),spr=price!==null&&fp!==null?price-fp:null,ap=price!==null&&fp!==null?adverseConcession(directionVerified?t.direction??null:null,price,fp):null;
 return{observation_id:calibrationObservationId(t),dataset_id:EXECUTION_CALIBRATION_DATASET_ID,method_version:EXECUTION_CALIBRATION_METHOD_VERSION,status,trade_id:t.tradeId??null,trade_seq:t.tradeSeq??null,instrument_name:t.instrumentName,trade_timestamp_ms:ts,trade_timestamp_utc:new Date(ts).toISOString(),source_host:input.sourceHost,retrieval_shard_id:input.retrievalShardId,retrieval_content_hash:input.retrievalContentHash,source_window_complete:input.sourceWindowComplete,strike:t.strike,option_type:t.optionType,expiry_timestamp_ms:t.expiryTimestampMs,expiry_timestamp_utc:new Date(t.expiryTimestampMs).toISOString(),actual_dte_days:dte,creation_timestamp_ms:created,settlement_period:t.settlementPeriod??null,contract_size:input.contractSize??null,minimum_trade_amount:input.minimumTradeAmount??null,log_moneyness:k,trade_price_btc:price,trade_iv_decimal:iv,trade_iv_api_percentage:t.ivApiPercent??null,index_price:index,mark_price_btc:t.markPrice??null,amount:t.amount??null,direction:t.direction??null,tick_direction:t.tickDirection??null,direction_is_aggressor:directionVerified,primary_fair_iv_decimal:fairIv,primary_fair_price_btc:fp,production_hybrid_fair_iv_decimal:hybridIv,production_hybrid_fair_price_btc:hfp,pricing_model_version:INVERSE_OPTION_MODEL,fair_value_method_version:REFERENCE_VALUATION_METHOD_VERSION,geometry_rule:REFERENCE_GEOMETRY_RULE,forward_convention:"forward_equals_index_rate_zero",rate_assumption:0,fair_reference_observation_count:admitted.length,fair_reference_unique_strike_count:unique,lower_strike:lower,upper_strike:upper,max_evidence_age_minutes:points.length?Math.max(...points.map(p=>p.effective_age_minutes)):null,signed_iv_residual_decimal:air,signed_iv_residual_vol_points:air===null?null:air*100,adverse_iv_concession_decimal:aiv,adverse_iv_concession_vol_points:aiv===null?null:aiv*100,signed_price_residual_btc:spr,adverse_price_concession_btc:ap,relative_adverse_price_concession_bps:relativeConcessionBps(ap,fp),features:causalFeatures(t,input.tape)}
}

export function calibrationContentHash(rows:readonly ExecutionCalibrationObservation[]):string{return contentHash([...rows].sort((a,b)=>a.observation_id.localeCompare(b.observation_id)).map(r=>r))}
