import type {JsonValue,ResearchSelectionEvent} from "./research-selections.ts";

export const FUTURES_ENGINE_VERSION="deribit-btc-perpetual-baseline-v1" as const;
export type FuturesPolicy="vpoc"|"invalidation"|"fixed_3d"|"fixed_5d"|"fixed_7d";
export interface FuturesPathRow {event_id:string;comparison_id:string;instrument:string;timestamp_utc:string;futures_price:number;index_price:number|null;source:"deribit";series_kind:"futures";observation_kind:"reference";verified:true;funding_rate:number|null;unrealized_pnl_usd:number|null}
export type FuturesComparisonRow=Record<string,JsonValue>;
const object=(x:unknown)=>x&&typeof x==="object"&&!Array.isArray(x)?x as Record<string,unknown>:{};
const number=(x:unknown)=>typeof x==="number"&&Number.isFinite(x)?x:null;
const atOrAfter=<T extends {timestamp:number}>(xs:readonly T[],time:number)=>xs.find(x=>x.timestamp>=time);
const atOrBefore=<T extends {timestamp:number}>(xs:readonly T[],time:number)=>[...xs].reverse().find(x=>x.timestamp<=time);
const endpoint=(event:ResearchSelectionEvent,policy:FuturesPolicy,entry:number)=>{const source=object(event.sourceRun),e=object(source.event??source);if(policy==="vpoc")return number(e.vpocTimestamp);if(policy==="invalidation"){const level=number(e.invalidationPrice),direction=e.direction;const hit=level===null?undefined:event.generationSnapshot.underlyingHourlyPath.find(c=>c.openTime>=entry&&(direction==="long"?c.low<=level:c.high>=level));return hit?.closeTime??null}return entry+({fixed_3d:3,fixed_5d:5,fixed_7d:7}[policy]??0)*864e5};
/** Pure event-level benchmark. It never reads option legs, spot prices, or option margin. */
export function buildEventFuturesBaseline(event:ResearchSelectionEvent,policy:FuturesPolicy="vpoc"):{comparison:FuturesComparisonRow;path:FuturesPathRow[]}{
 const market=event.generationSnapshot.futuresMarket,source=object(event.sourceRun),e=object(source.event??source),signal=number(e.entryTimestamp)??(typeof e.entryDate==="string"?Date.parse(`${e.entryDate}T00:00:00Z`):null),latency=number(object(event.generationSnapshot.configuration.modelAssumptions).executionLatencyMs)??0,order=signal===null?null:signal+latency,id=`deribit~futures~${event.eventId}~${policy}`,base={event_id:event.eventId,comparison_id:id,engine_version:FUTURES_ENGINE_VERSION,benchmark:"Deribit BTC perpetual",policy,signal_timestamp_utc:signal===null?null:new Date(signal).toISOString(),decision_available_timestamp_utc:signal===null?null:new Date(signal).toISOString(),order_available_timestamp_utc:order===null?null:new Date(order).toISOString()};
 if(!market)return{comparison:{...base,availability:"unavailable",reason_codes:["futures_instrument_unavailable"]},path:[]};
 if(market.source!=="deribit"||market.instrumentKind!=="perpetual"||market.instrument!=="BTC-PERPETUAL")return{comparison:{...base,instrument:market.instrument,availability:"unavailable",reason_codes:["unsupported_futures_instrument"]},path:[]};
 if(order===null||!market.reference.length)return{comparison:{...base,instrument:market.instrument,availability:"unavailable",reason_codes:["futures_reference_series_unavailable"]},path:[]};
 const refs=[...market.reference].sort((a,b)=>a.timestamp-b.timestamp),entry=atOrAfter(refs,order),end=endpoint(event,policy,order);if(!entry||end===null)return{comparison:{...base,instrument:market.instrument,availability:"unavailable",reason_codes:[entry?"matched_endpoint_unavailable":"futures_reference_series_unavailable"]},path:[]};const exit=atOrBefore(refs,end);if(!exit||exit.timestamp<entry.timestamp)return{comparison:{...base,instrument:market.instrument,availability:"unavailable",reason_codes:["matched_endpoint_unavailable"]},path:[]};
 const direction=e.direction==="long"?"long":e.direction==="short"?"short":null,sign=direction==="long"?1:direction==="short"?-1:0,invalidation=number(e.invalidationPrice),distance=invalidation===null?0:Math.abs(entry.price-invalidation),riskBudget=Math.max(0,...event.selectedStructures.map(s=>number(object(s.marginSnapshot).theoreticalMaximumSpreadLossBtc)??0))*entry.price,quantity=riskBudget>0&&distance>0?riskBudget/distance:null,trades=[...(market.trades??[])].sort((a,b)=>a.timestamp-b.timestamp),observed=trades.find(t=>t.timestamp>=order&&((direction==="long"&&t.direction==="buy")||(direction==="short"&&t.direction==="sell"))),feeRate=number(market.feeRate),fees=quantity!==null&&feeRate!==null?(entry.price+exit.price)*quantity*feeRate:null,funding=market.funding?market.funding.filter(f=>f.timestamp>entry.timestamp&&f.timestamp<=exit.timestamp).reduce((n,f)=>n-sign*entry.price*(quantity??0)*f.rate,0):null,gross=quantity===null?null:sign*(exit.price-entry.price)*quantity;
 const path=refs.filter(p=>p.timestamp>=entry.timestamp&&p.timestamp<=exit.timestamp).map(p=>({event_id:event.eventId,comparison_id:id,instrument:market.instrument,timestamp_utc:new Date(p.timestamp).toISOString(),futures_price:p.price,index_price:p.indexPrice??null,source:"deribit" as const,series_kind:"futures" as const,observation_kind:"reference" as const,verified:true as const,funding_rate:market.funding?.find(f=>f.timestamp===p.timestamp)?.rate??null,unrealized_pnl_usd:quantity===null?null:sign*(p.price-entry.price)*quantity}));
 return{comparison:{...base,instrument:market.instrument,direction,availability:"available",reference_status:"available",observed_execution_status:observed?"available":"unavailable",observed_entry_price:observed?.price??null,observed_entry_timestamp_utc:observed?new Date(observed.timestamp).toISOString():null,observed_evidence_ids:observed?[observed.tradeId]:[],reference_entry_price:entry.price,reference_entry_timestamp_utc:new Date(entry.timestamp).toISOString(),exit_price:exit.price,exit_timestamp_utc:new Date(exit.timestamp).toISOString(),quantity,equal_risk_sizing_method:"option_max_economic_loss_usd / abs(futures_entry - structural_invalidation)",risk_budget_usd:riskBudget||null,gross_trading_pnl_usd:gross,entry_exit_fees_usd:fees,funding_usd:funding,net_pnl_usd:gross!==null&&fees!==null&&funding!==null?gross-fees+funding:null,funding_status:market.funding?"available":"unavailable",futures_margin_status:"unavailable",equal_capital_status:"unavailable",reason_codes:[...(observed?[]:["observed_futures_execution_unavailable"]),...(market.funding?[]:["funding_unavailable"]),"futures_margin_unavailable"]},path};
}
