import { aggregateRoutedFees, calculateOptionFee, STANDARD_INVERSE_BTC_OPTION_FEE } from "./accounting.ts";
import { deterministicFingerprint, executionScenarios, validateLeaveOneOut } from "./causal-valuation.ts";
import type { JsonValue, ResearchSelectionStore } from "./research-selections.ts";

export const MODELED_EXECUTION_VERSION = "modeled-execution-v2";
export const MINIMUM_EXECUTION_CALIBRATION = 30;
export const EXECUTION_CONCESSION_DENOMINATOR = "absolute fair gross spread credit; bps unavailable below 1e-8 BTC";
type Rec=Record<string,unknown>;
const rec=(v:unknown):Rec=>v!==null&&typeof v==="object"&&!Array.isArray(v)?v as Rec:{};
const num=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:undefined;
const timestamp=(v:unknown)=>num(v)??(typeof v==="string"&&Number.isFinite(Date.parse(v))?Date.parse(v):undefined);

export type CalibrationScenario="maker"|"taker";
export interface ExecutionCalibrationRecord {id:string;candidateId:string;eventId:string;scenario:CalibrationScenario;source:"immediate"|"delayed";observedTimestamp:number;referenceTimestamp:number;fairCredit:number;observedCredit:number;concessionBtc:number;concessionBps:number;amount?:number;dteDays?:number;optionType?:string;width?:number;referenceSourceTier?:string;observedExecutionQuality?:string;synchronizationMs?:number}

/** One completed execution is one row. A reference mark must exist at that exact completion timestamp. */
export function buildExecutionCalibrationRecords(store:ResearchSelectionStore):ExecutionCalibrationRecord[]{
 const rows:ExecutionCalibrationRecord[]=[];
 for(const event of store.events)for(const structure of event.selectedStructures){
  const reference=rec(structure.referenceValuation),entry=rec(reference.entrySnapshot),path=Array.isArray(reference.valuationPathSnapshot)?reference.valuationPathSnapshot.map(rec):[];
  const add=(scenario:CalibrationScenario,source:"immediate"|"delayed",raw:unknown)=>{const observed=rec(raw);if(!["evaluated","available"].includes(String(observed.status)))return;const oe=rec(observed.entrySnapshot),ot=timestamp(oe.evidenceCompletionTimestamp)??timestamp(oe.valuationTimestamp)??timestamp(oe.targetTimestamp);if(ot===undefined)return;const refPoint=(timestamp(entry.valuationTimestamp)??timestamp(entry.targetTimestamp))===ot?entry:path.find(p=>timestamp(p.valuationTimestamp)===ot||timestamp(p.timestamp)===ot);if(!refPoint)return;const fair=num(refPoint.grossSpreadBtc)??num(refPoint.grossSpreadCreditBtc),actual=num(oe.grossSpreadBtc)??num(oe.grossSpreadCreditBtc);if(fair===undefined||actual===undefined||Math.abs(fair)<1e-8)return;const concession=fair-actual,bps=concession/Math.abs(fair)*1e4;if(!Number.isFinite(bps)||bps<0)return;const id=`${event.eventId}|${structure.candidateId}|${scenario}|${source}|${ot}`;rows.push({id,candidateId:structure.candidateId,eventId:event.eventId,scenario,source,observedTimestamp:ot,referenceTimestamp:ot,fairCredit:fair,observedCredit:actual,concessionBtc:concession,concessionBps:bps,amount:num(oe.amount)??structure.quantity,dteDays:num(oe.remainingDte),optionType:String(rec(structure.candidateSnapshot).optionType??""),width:num(rec(structure.candidateSnapshot).actualWidth),referenceSourceTier:String(reference.sourceTier??reference.source??"unavailable"),observedExecutionQuality:String(oe.estimateQuality??"unavailable"),synchronizationMs:num(oe.synchronizationGapMs)??(num(oe.synchronizationGapMinutes)!==undefined?num(oe.synchronizationGapMinutes)!*60_000:undefined)});};
  for(const scenario of ["maker","taker"] as const){add(scenario,"immediate",rec(structure.executionScenarios)[scenario]);add(scenario,"delayed",rec(structure.delayedExecution)[scenario]);}
 }
 return [...new Map(rows.map(r=>[r.id,r])).values()].sort((a,b)=>a.observedTimestamp-b.observedTimestamp||a.id.localeCompare(b.id));
}

const calibrationMeta=(scenario:CalibrationScenario,rows:ExecutionCalibrationRecord[],target:number)=>{const causal=rows.filter(r=>r.scenario===scenario&&r.observedTimestamp<target),penalties=causal.map(r=>r.concessionBps).sort((a,b)=>a-b),median=penalties.length?penalties[Math.floor(penalties.length/2)]:null,tail=penalties.length?penalties[Math.floor(penalties.length*.9)]:null,fingerprint=deterministicFingerprint(causal.map(r=>r.id).join("\n"));return{scenario,status:causal.length>=MINIMUM_EXECUTION_CALIBRATION?"empirically_calibrated":"uncalibrated_sensitivity",count:causal.length,minimum:MINIMUM_EXECUTION_CALIBRATION,trainingPolicy:"rolling historical; observed completion timestamp < modeled entry timestamp",cutoffExclusive:target,sampleFingerprint:fingerprint,medianPenaltyBps:median,upperTailPenaltyBps:tail,records:causal,validation:validateLeaveOneOut(causal.map(r=>({id:r.id,observed:r.observedCredit,modeled:r.fairCredit*(1-(median??500)/1e4)})))};};

function modeledTrack(reference:Rec,penaltyBps:number,meta:ReturnType<typeof calibrationMeta>,method:"empirical_median"|"empirical_upper_tail"|"declared_assumption"){
 const fair=rec(reference.entrySnapshot),amount=num(fair.amount)??1,short=num(rec(fair.sold).priceBtcPerContract),long=num(rec(fair.bought).priceBtcPerContract),fairGross=num(fair.grossSpreadBtc)??(short!==undefined&&long!==undefined?(short-long)*amount:undefined);
 if(short===undefined||long===undefined||fairGross===undefined||fairGross<=0)return{status:"unavailable",reason:"Reference entry lacks positive-credit, leg-level accounting inputs.",source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION,calibration:meta};
 const concession=Math.abs(fairGross)*penaltyBps/1e4,perLeg=concession/(2*amount),sold=Math.max(0,short-perLeg),bought=long+perLeg,gross=(sold-bought)*amount;
 const fees=aggregateRoutedFees([{side:"sell",fee:calculateOptionFee(sold,amount,"taker",STANDARD_INVERSE_BTC_OPTION_FEE)},{side:"buy",fee:calculateOptionFee(bought,amount,"taker",STANDARD_INVERSE_BTC_OPTION_FEE)}],"synchronized-leg-proxy").finalFee,net=gross-fees;
 if(gross<=0||net<=0)return{status:"unavailable",reason:"Modeled concession produces a non-economic/nonpositive credit after authoritative fees.",source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION,penaltyBps,calibration:meta};
 const modeledEntry={...fair,sold:{...rec(fair.sold),priceBtcPerContract:sold},bought:{...rec(fair.bought),priceBtcPerContract:bought},grossSpreadBtcPerContract:sold-bought,grossSpreadBtc:gross,openingFeesBtc:fees,netOpeningCashFlowBtc:net,executionConcessionNative:fairGross-gross,executionConcessionBps:penaltyBps,valuationMode:"modeled-execution",priceSource:"modeled-concession"};
 const expiry=timestamp(rec(reference.provenance).expiryTimestamp),path=(Array.isArray(reference.valuationPathSnapshot)?reference.valuationPathSnapshot:[]).map(rec).filter(p=>{const t=timestamp(p.timestamp)??timestamp(p.valuationTimestamp);return t!==undefined&&t>=(timestamp(fair.targetTimestamp)??timestamp(fair.valuationTimestamp)??0)&&(expiry===undefined||t<=expiry);}).map(p=>{const close=num(p.closingSpreadValueBtc)??num(p.grossCloseBtc),closingFee=num(p.closingFeesBtc)??0;return{...p,valuationSource:"reference-mark",observed:false,...(close===undefined?{}:{estimatedNetPnlBtc:net+close-closingFee})};});
 const typedPath:Rec[]=path;
 const fairNet=num(fair.netOpeningCashFlowBtc)??fairGross;
 const outcomes=(Array.isArray(reference.outcomeSnapshots)?reference.outcomeSnapshots:[]).map(rec).map(o=>{const capture=String(o.label??o.outcome_type??"").match(/(25|50|70)%/),threshold=capture?Number(capture[1])/100:undefined,point=threshold===undefined?typedPath.find(p=>(timestamp(p.timestamp)??timestamp(p.valuationTimestamp))===timestamp(o.valuationTimestamp)):typedPath.find(p=>(num(p.estimatedNetPnlBtc)??-Infinity)>=gross*threshold);const authoritativePnl=num(o.estimatedNetPnlBtc),recomputed=point?num(point.estimatedNetPnlBtc):authoritativePnl===undefined?undefined:authoritativePnl+net-fairNet;return{...o,...(capture?{valuationTimestamp:point?timestamp(point.timestamp)??timestamp(point.valuationTimestamp):undefined,status:point?"estimated":"not-hit"}:{}),valuationSource:"reference-mark",observed:false,...(recomputed===undefined?{}:{estimatedNetPnlBtc:recomputed})};});
 return{status:"evaluated",reason:null,source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION,penaltyBps,assumptionOrCalibration:method,calibrationCount:meta.count,calibration:meta,entryTimestamp:timestamp(fair.targetTimestamp)??timestamp(fair.valuationTimestamp),entrySnapshot:modeledEntry,valuationPathSnapshot:path,outcomeSnapshots:outcomes,uncertainty:reference.uncertainty??null,referenceQuality:{sourceTier:reference.sourceTier??reference.source??null,qualityGrade:rec(reference.provenance).quality??null,extrapolation:Boolean(reference.extrapolation),dvolProxy:Boolean(reference.dvolProxy)},provenance:{historicalExecution:false,entry:"action-aware adverse modeled concession",postEntry:"causal reference marks; never observed execution",feeSchedule:STANDARD_INVERSE_BTC_OPTION_FEE.effectiveDate,concessionFormula:`fair credit - executable credit; ${EXECUTION_CONCESSION_DENOMINATOR}`}};
}

export function buildModeledExecution(referenceValue:unknown,calibrationRows:ExecutionCalibrationRecord[]=[]) : JsonValue {
 const reference=rec(referenceValue),fair=rec(reference.entrySnapshot),target=timestamp(fair.targetTimestamp)??timestamp(fair.valuationTimestamp);
 if(!["valued","evaluated"].includes(String(reference.status))||target===undefined)return {expected:{status:"unavailable",reason:"Causal reference valuation is unavailable.",source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION},conservative:{status:"unavailable",reason:"Causal reference valuation is unavailable.",source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION},penaltySensitivity:{status:"unavailable",reason:"Causal reference valuation is unavailable.",source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION}};
 const gross=num(fair.grossSpreadBtc)??0,maker=calibrationMeta("maker",calibrationRows,target),taker=calibrationMeta("taker",calibrationRows,target),makerScenarios=executionScenarios(gross,maker.records.map(r=>r.concessionBps)),takerScenarios=executionScenarios(gross,taker.records.map(r=>r.concessionBps));
 const expected=makerScenarios.expectedEstimatorPromoted?modeledTrack(reference,maker.medianPenaltyBps!,maker,"empirical_median"):{status:"unavailable",reason:`Insufficient empirical Maker calibration (${maker.count}/${MINIMUM_EXECUTION_CALIBRATION}); expected estimator not promoted.`,source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION,calibrationCount:maker.count,calibration:maker};
 const conservativePenalty=takerScenarios.expectedEstimatorPromoted?Math.max(taker.medianPenaltyBps!,taker.upperTailPenaltyBps!):500,conservative=modeledTrack(reference,conservativePenalty,taker,takerScenarios.expectedEstimatorPromoted?"empirical_upper_tail":"declared_assumption");
 const grid=[0,50,100,250,500].map(penaltyBps=>({penaltyBps,label:penaltyBps===0?"fair reference":`${penaltyBps}bp assumption`,track:modeledTrack(reference,penaltyBps,taker,"declared_assumption")}));
 return {expected,conservative,penaltySensitivity:{status:"evaluated",reason:null,source:"modeled_execution_sensitivity",modelVersion:MODELED_EXECUTION_VERSION,calibrationCount:taker.count,calibration:taker,assumptionGrid:true,grid,provenance:{historicalExecution:false,description:"Deterministic assumptions, not observed bid/ask or fills."}}} as unknown as JsonValue;
}
