import { aggregateRoutedFees, calculateOptionFee, STANDARD_INVERSE_BTC_OPTION_FEE } from "./accounting.ts";
import { deterministicFingerprint, validateLeaveOneOut } from "./causal-valuation.ts";
import type { JsonValue, ResearchSelectionStore } from "./research-selections.ts";
import {priceInverseOption} from "./inverse-option-pricing.ts";
import {EMPIRICAL_TAKER_EXECUTION_VERSION,EXECUTION_BUCKET_POLICY_VERSION,QUANTILE_METHOD,type ExecutionCalibrationIndex,type BucketEstimate,type ReferenceEstimate} from "./empirical-taker-execution.ts";
import {EXECUTION_CALIBRATION_DATASET_ID,EXECUTION_CALIBRATION_METHOD_VERSION} from "./execution-calibration.ts";

export const MODELED_EXECUTION_VERSION = "modeled-execution-v4-empirical-taker";
export const MINIMUM_EXECUTION_CALIBRATION = 30;
export const EXECUTION_CONCESSION_DENOMINATOR = "absolute fair gross spread credit; bps unavailable below 1e-8 BTC";
type Rec=Record<string,unknown>;
const rec=(v:unknown):Rec=>v!==null&&typeof v==="object"&&!Array.isArray(v)?v as Rec:{};
const num=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:undefined;
const timestamp=(v:unknown)=>num(v)??(typeof v==="string"&&Number.isFinite(Date.parse(v))?Date.parse(v):undefined);

export type CalibrationScenario="maker"|"taker";
export interface ExecutionCalibrationRecord {id:string;candidateId:string;eventId:string;scenario:CalibrationScenario;source:"immediate"|"delayed";observedTimestamp:number;referenceTimestamp:number;fairCredit:number;observedCredit:number;concessionBtc:number;concessionBps:number;amount?:number;dteDays?:number;optionType?:string;width?:number;referenceSourceTier?:string;observedExecutionQuality?:string;synchronizationMs?:number}

/** One completed execution is one row. A reference mark must exist at that exact completion timestamp. */
/** @deprecated Diagnostic legacy selected-structure spread-bps sample. Never trains authoritative modeled execution. */
export function buildExecutionCalibrationRecords(store:ResearchSelectionStore):ExecutionCalibrationRecord[]{
 const rows:ExecutionCalibrationRecord[]=[];
 for(const event of store.events)for(const structure of event.selectedStructures){
  const reference=rec(structure.referenceValuation),entry=rec(reference.entrySnapshot),path=Array.isArray(reference.valuationPathSnapshot)?reference.valuationPathSnapshot.map(rec):[];
  const add=(scenario:CalibrationScenario,source:"immediate"|"delayed",raw:unknown)=>{const observed=rec(raw);if(!["evaluated","available"].includes(String(observed.status)))return;const oe=rec(observed.entrySnapshot),ot=timestamp(oe.evidenceCompletionTimestamp)??timestamp(oe.valuationTimestamp)??timestamp(oe.targetTimestamp);if(ot===undefined)return;const refPoint=(timestamp(entry.valuationTimestamp)??timestamp(entry.targetTimestamp))===ot?entry:path.find(p=>timestamp(p.valuationTimestamp)===ot||timestamp(p.timestamp)===ot);if(!refPoint)return;const fair=num(refPoint.grossSpreadBtc)??num(refPoint.grossSpreadCreditBtc),actual=num(oe.grossSpreadBtc)??num(oe.grossSpreadCreditBtc);if(fair===undefined||actual===undefined||Math.abs(fair)<1e-8)return;const concession=fair-actual,bps=concession/Math.abs(fair)*1e4;if(!Number.isFinite(bps)||bps<0)return;const id=`${event.eventId}|${structure.candidateId}|${scenario}|${source}|${ot}`;rows.push({id,candidateId:structure.candidateId,eventId:event.eventId,scenario,source,observedTimestamp:ot,referenceTimestamp:ot,fairCredit:fair,observedCredit:actual,concessionBtc:concession,concessionBps:bps,amount:num(oe.amount)??structure.quantity,dteDays:num(oe.remainingDte),optionType:String(rec(structure.candidateSnapshot).optionType??""),width:num(rec(structure.candidateSnapshot).actualWidth),referenceSourceTier:String(reference.sourceTier??reference.source??"unavailable"),observedExecutionQuality:String(oe.estimateQuality??"unavailable"),synchronizationMs:num(oe.synchronizationGapMs)??(num(oe.synchronizationGapMinutes)!==undefined?num(oe.synchronizationGapMinutes)!*60_000:undefined)});};
  for(const scenario of ["maker","taker"] as const){add(scenario,"immediate",rec(structure.executionScenarios)[scenario]);add(scenario,"delayed",rec(structure.delayedExecution)[scenario]);}
 }
 return [...new Map(rows.map(r=>[r.id,r])).values()].sort((a,b)=>a.observedTimestamp-b.observedTimestamp||a.id.localeCompare(b.id));
}

const calibrationMeta=(scenario:CalibrationScenario,rows:ExecutionCalibrationRecord[],target:number)=>{const causal=rows.filter(r=>r.scenario===scenario&&r.observedTimestamp<target),penalties=causal.map(r=>r.concessionBps).sort((a,b)=>a-b),median=penalties.length?penalties[Math.floor(penalties.length/2)]:null,tail=penalties.length?penalties[Math.floor(penalties.length*.9)]:null,fingerprint=deterministicFingerprint(causal.map(r=>r.id).join("\n"));return{scenario,status:causal.length>=MINIMUM_EXECUTION_CALIBRATION?"empirically_calibrated":"uncalibrated_sensitivity",count:causal.length,minimum:MINIMUM_EXECUTION_CALIBRATION,trainingPolicy:"rolling historical; observed completion timestamp < modeled entry timestamp",cutoffExclusive:target,sampleFingerprint:fingerprint,medianPenaltyBps:median,upperTailPenaltyBps:tail,records:causal,validation:validateLeaveOneOut(causal.map(r=>({id:r.id,observed:r.observedCredit,modeled:r.fairCredit*(1-(median??500)/1e4)})))};};

function modeledTrack(reference:Rec,penaltyBps:number,meta:ReturnType<typeof calibrationMeta>,method:"empirical_median"|"empirical_upper_tail"|"declared_assumption"){
 const fair=rec(reference.entrySnapshot),amount=num(fair.amount)??1,short=num(rec(fair.sold).priceBtcPerContract),long=num(rec(fair.bought).priceBtcPerContract),fairGross=num(fair.grossSpreadBtc)??(short!==undefined&&long!==undefined?(short-long)*amount:undefined);
 if(short===undefined||long===undefined||fairGross===undefined||fairGross<=0)return{status:"unavailable",reason:"Reference entry lacks positive-credit, leg-level accounting inputs.",source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION,calibration:meta};
 const concession=Math.abs(fairGross)*penaltyBps/1e4,perLeg=concession/(2*amount),sold=Math.max(0,short-perLeg),bought=long+perLeg,gross=(sold-bought)*amount;
 const fees=aggregateRoutedFees([{side:"sell",fee:calculateOptionFee(sold,amount,"taker",STANDARD_INVERSE_BTC_OPTION_FEE)},{side:"buy",fee:calculateOptionFee(bought,amount,"taker",STANDARD_INVERSE_BTC_OPTION_FEE)}],"synchronized-leg-proxy").finalFee,net=gross-fees;
 if(gross<=0||net<=0)return{status:"unavailable",reason:"Modeled concession produces a non-economic/nonpositive credit after authoritative fees.",source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION,penaltyBps,calibration:meta};
 const modeledEntry={...fair,sold:{...rec(fair.sold),priceBtcPerContract:sold},bought:{...rec(fair.bought),priceBtcPerContract:bought},grossSpreadBtcPerContract:sold-bought,grossSpreadBtc:gross,openingFeesBtc:fees,netOpeningCashFlowBtc:net,executionConcessionNative:fairGross-gross,executionConcessionBps:penaltyBps,valuationMode:"modeled-execution",priceSource:"modeled-concession"};
 const expiry=timestamp(rec(reference.provenance).expiryTimestamp),path=(Array.isArray(reference.valuationPathSnapshot)?reference.valuationPathSnapshot:[]).map(rec).filter(p=>{const t=timestamp(p.timestamp)??timestamp(p.valuationTimestamp);return t!==undefined&&t>=(timestamp(fair.targetTimestamp)??timestamp(fair.valuationTimestamp)??0)&&(expiry===undefined||t<=expiry);}).map(p=>{const close=num(p.closingSpreadValueBtc)??num(p.grossCloseBtc),closingFee=num(p.closingFeesBtc)??0;return{...p,valuationSource:"reference-mark",observed:false,...(close===undefined?{}:{estimatedNetPnlBtc:net+close-closingFee})};});
 const typedPath:Rec[]=path;
 const fairNet=num(fair.netOpeningCashFlowBtc)??fairGross;
 const outcomes=(Array.isArray(reference.outcomeSnapshots)?reference.outcomeSnapshots:[]).map(rec).map(o=>{const capture=String(o.label??o.outcome_type??"").match(/(25|50|70)%/),threshold=capture?Number(capture[1])/100:undefined,point=threshold===undefined?typedPath.find(p=>(timestamp(p.timestamp)??timestamp(p.valuationTimestamp))===timestamp(o.valuationTimestamp)):typedPath.find(p=>(num(p.estimatedNetPnlBtc)??-Infinity)>=gross*threshold);const authoritativePnl=num(o.estimatedNetPnlBtc),recomputed=point?num(point.estimatedNetPnlBtc):authoritativePnl===undefined?undefined:authoritativePnl+net-fairNet;return{...o,...(capture?{valuationTimestamp:point?timestamp(point.timestamp)??timestamp(point.valuationTimestamp):undefined,status:point?"estimated":"not-hit"}:{}),valuationSource:"reference-mark",observed:false,...(recomputed===undefined?{}:{estimatedNetPnlBtc:recomputed})};});
 return{status:"evaluated",reason:null,source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION,penaltyBps,assumptionOrCalibration:method,calibrationCount:meta.count,calibration:meta,entryTimestamp:timestamp(fair.targetTimestamp)??timestamp(fair.valuationTimestamp),entrySnapshot:modeledEntry,valuationPathSnapshot:path,outcomeSnapshots:outcomes,uncertainty:reference.uncertainty??null,referenceQuality:{sourceTier:reference.sourceTier??reference.source??null,qualityGrade:rec(reference.provenance).quality??null,extrapolation:Boolean(reference.extrapolation),dvolProxy:Boolean(reference.dvolProxy)},provenance:{historicalExecution:false,entry:"action-aware adverse modeled concession",postEntry:"causal reference marks; never observed execution",feeSchedule:STANDARD_INVERSE_BTC_OPTION_FEE.effectiveDate,concessionFormula:`fair credit - executable credit; ${EXECUTION_CONCESSION_DENOMINATOR}`}};
}

type EmpiricalProvider=Pick<ExecutionCalibrationIndex,"execution"|"reference"|"artifact">;
function empiricalTrack(reference:Rec,provider:EmpiricalProvider,kind:"expected"|"conservative"){
 const fair=rec(reference.entrySnapshot),target=timestamp(fair.targetTimestamp)??timestamp(fair.valuationTimestamp),amount=num(fair.amount)??1;
 const legs=[{key:"sold",action:"sell" as const},{key:"bought",action:"buy" as const}];if(target===undefined)return{status:"unavailable",reason:"Reference entry timestamp unavailable.",source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION};
 const estimates=[] as Array<{key:string;action:"buy"|"sell";price:number;execution:BucketEstimate;reference:ReferenceEstimate;fairIv:number;adjustment:number}>;
 for(const leg of legs){const raw=rec(fair[leg.key]),model=rec(raw.model),fairIv=num(model.anchorIvDecimal)??num(raw.ivDecimal),index=num(model.targetIndex)??num(fair.entryTargetIndex),strike=num(model.strike)??num(raw.strike),expiry=timestamp(model.expiryTimestamp)??timestamp(rec(reference.provenance).expiryTimestamp),forward=num(model.forwardPrice),dte=num(model.dte)??(expiry!==undefined?(expiry-target)/864e5:undefined);if([fairIv,index,strike,expiry,forward,dte].some(v=>v===undefined))return{status:"unavailable",reason:`Reference ${leg.key} leg lacks IV/forward pricing provenance required for empirical execution.`,source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION};const m=Math.log(strike!/forward!),execution=provider.execution({action:leg.action,dteDays:dte!,amount,forwardMoneyness:m,cutoffMs:target}),uncertainty=provider.reference({dteDays:dte!,cutoffMs:target});if(!execution||!uncertainty)return{status:"unavailable",reason:"Insufficient causal empirical taker calibration; declared sensitivity remains available.",source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION};const adjustment=(kind==="expected"?execution.q50VolPoints:execution.q90VolPoints)/100,iv=leg.action==="buy"?fairIv!+adjustment:fairIv!-adjustment;if(!(iv>0))return{status:"unavailable",reason:"Empirical adjustment produced invalid/nonpositive IV.",source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION};const priced=priceInverseOption({optionType:String(model.optionType??raw.optionType).toUpperCase().startsWith("C")?"call":"put",indexPrice:index!,strike:strike!,valuationTimestamp:target,expiryTimestamp:expiry!,forwardPrice:forward!,ivDecimal:iv});if(priced.status!=="priced")return{status:"unavailable",reason:priced.reason,source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION};estimates.push({key:leg.key,action:leg.action,price:priced.priceBtc,execution,reference:uncertainty,fairIv:fairIv!,adjustment})}
 const sold=estimates[0]!,bought=estimates[1]!,gross=(sold.price-bought.price)*amount,fees=aggregateRoutedFees([{side:"sell",fee:calculateOptionFee(sold.price,amount,"taker",STANDARD_INVERSE_BTC_OPTION_FEE)},{side:"buy",fee:calculateOptionFee(bought.price,amount,"taker",STANDARD_INVERSE_BTC_OPTION_FEE)}],"synchronized-leg-proxy").finalFee,net=gross-fees;if(gross<=0||net<=0)return{status:"unavailable",reason:"Empirical modeled execution produces nonpositive credit after authoritative fees.",source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION};
 const meta=estimates.map(e=>({action:e.action,targetDte:e.execution.dteBand,targetAmount:amount,chosenDteBand:e.execution.dteBand,chosenAmountBand:e.execution.amountBand,bucketFallbackLevel:e.execution.fallbackLevel,tradeCount:e.execution.tradeCount,calendarDayCount:e.execution.calendarDayCount,expiryDayGroupCount:e.execution.expiryDayGroupCount,q50ExecutionConcessionVolPoints:e.execution.q50VolPoints,q90ExecutionConcessionVolPoints:e.execution.q90VolPoints,q90ReferenceUncertaintyVolPoints:e.reference.q90VolPoints,referenceFallbackLevel:e.reference.fallbackLevel,appliedAdjustmentVolPoints:e.adjustment*100}));
 const entry={...fair,sold:{...rec(fair.sold),priceBtcPerContract:sold.price},bought:{...rec(fair.bought),priceBtcPerContract:bought.price},grossSpreadBtcPerContract:sold.price-bought.price,grossSpreadBtc:gross,openingFeesBtc:fees,netOpeningCashFlowBtc:net,valuationMode:"modeled-execution",priceSource:"empirical-mark-iv-concession"};const rebuilt=modeledTrack(reference,0,{count:provider.artifact.tradeCount} as ReturnType<typeof calibrationMeta>,"declared_assumption") as Rec,fairNet=num(fair.netOpeningCashFlowBtc)??num(fair.grossSpreadBtc)??0,delta=net-fairNet,shift=(xs:unknown)=>Array.isArray(xs)?xs.map(v=>{const r=rec(v),p=num(r.estimatedNetPnlBtc);return p===undefined?r:{...r,estimatedNetPnlBtc:p+delta}}):xs;return{...rebuilt,status:"evaluated",reason:null,entrySnapshot:entry,valuationPathSnapshot:shift(rebuilt.valuationPathSnapshot),outcomeSnapshots:shift(rebuilt.outcomeSnapshots),modelVersion:MODELED_EXECUTION_VERSION,assumptionOrCalibration:kind==="expected"?"empirical_median":"empirical_upper_tail",provenance:{historicalExecution:false,estimatorVersion:EMPIRICAL_TAKER_EXECUTION_VERSION,sourceDatasetId:EXECUTION_CALIBRATION_DATASET_ID,calibrationObservationMethod:EXECUTION_CALIBRATION_METHOD_VERSION,datasetFingerprint:provider.artifact.sourceDatasetFingerprint,artifactHash:provider.artifact.artifactHash,coverageStartMs:provider.artifact.coverageStartMs,coverageEndMs:provider.artifact.coverageEndMs,causalCutoffExclusive:target,bucketPolicyVersion:EXECUTION_BUCKET_POLICY_VERSION,quantileMethod:QUANTILE_METHOD,forwardMethod:"option-trade-implied-forward-v1",description:kind==="expected"?"Expected execution uses the per-leg empirical Q50 taker concession only; Reference Q90 is reported separately and does not alter execution IV.":"Conservative execution uses the per-leg empirical Q90 taker concession only; Reference Q90 is reported separately. No assumption is made that execution Q90 and Reference Q90 occur simultaneously; this is not a joint spread P90.",legs:meta,postEntry:"causal reference marks; never observed execution"}};
}

export function buildModeledExecution(referenceValue:unknown,provider?:EmpiricalProvider) : JsonValue {
 const reference=rec(referenceValue),fair=rec(reference.entrySnapshot),target=timestamp(fair.targetTimestamp)??timestamp(fair.valuationTimestamp);
 if(!["valued","evaluated"].includes(String(reference.status))||target===undefined)return {expected:{status:"unavailable",reason:"Causal reference valuation is unavailable.",source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION},conservative:{status:"unavailable",reason:"Causal reference valuation is unavailable.",source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION},penaltySensitivity:{status:"unavailable",reason:"Causal reference valuation is unavailable.",source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION}};
 const taker=calibrationMeta("taker",[],target),expected=provider?empiricalTrack(reference,provider,"expected"):{status:"unavailable",reason:"Empirical taker calibration artifact unavailable; Node/local recompute may populate this track.",source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION},conservative=provider?empiricalTrack(reference,provider,"conservative"):{status:"unavailable",reason:"Empirical taker calibration artifact unavailable; no 500 bp substitution is permitted.",source:"modeled_execution",modelVersion:MODELED_EXECUTION_VERSION};
 const grid=[0,50,100,250,500].map(penaltyBps=>({penaltyBps,label:penaltyBps===0?"fair reference":`${penaltyBps}bp assumption`,track:modeledTrack(reference,penaltyBps,taker,"declared_assumption")}));
 return {expected,conservative,penaltySensitivity:{status:"evaluated",reason:null,source:"modeled_execution_sensitivity",modelVersion:MODELED_EXECUTION_VERSION,calibrationCount:0,calibration:taker,assumptionGrid:true,label:"DECLARED ASSUMPTION / SENSITIVITY",grid,provenance:{historicalExecution:false,description:"Deterministic assumptions, not empirical execution, observed bid/ask, or fills."}}} as unknown as JsonValue;
}

/** Rehydrates persisted modeled tracks from the one canonical reference mark path. */
export function reconstructModeledExecution(referenceValue:unknown,persistedValue:unknown):JsonValue{
 const reference=rec(referenceValue),persisted=rec(persistedValue),referencePath=Array.isArray(reference.valuationPathSnapshot)?reference.valuationPathSnapshot.map(rec):[];
 const track=(value:unknown)=>{const saved=rec(value);if(saved.status!=="evaluated"||Array.isArray(saved.valuationPathSnapshot))return saved as unknown as JsonValue;const entry=rec(saved.entrySnapshot),net=num(entry.netOpeningCashFlowBtc);const valuationPathSnapshot=referencePath.map(point=>{const close=num(point.closingSpreadValueBtc)??num(point.grossCloseBtc),fee=num(point.closingFeesBtc)??0;return{...point,valuationSource:"reference-mark",observed:false,...(net===undefined||close===undefined?{}:{estimatedNetPnlBtc:net+close-fee})};});return{...saved,valuationPathSnapshot} as unknown as JsonValue;};
 const sensitivity=rec(persisted.penaltySensitivity),grid=Array.isArray(sensitivity.grid)?sensitivity.grid.map(row=>{const r=rec(row);return{...r,track:track(r.track)}}):[];
 return{...persisted,expected:track(persisted.expected),conservative:track(persisted.conservative),penaltySensitivity:{...sensitivity,grid}} as unknown as JsonValue;
}
