import { aggregateRoutedFees, buildOptionSettlementLedger, calculateOptionFee, OPTION_TO_FUTURE_EFFECTIVE_AT, STANDARD_INVERSE_BTC_OPTION_FEE, type ExecutionRoute, type OptionSettlementLedger, type RoutedFees } from "./accounting.ts";
import { buildExecutedValuationPath, executionClock, firstTouch, simulateTakerExit, simulateTakerSpread, type BacktestEvent, type Candle, type DiagnosticValuationPoint, type ExecutionClock, type ExitExecution, type RetrievedSpread, type SpreadExecution } from "./backtester.ts";
import { DEFAULT_DEPLOYMENT, estimateStandardOptionMargin, portfolioMarginResult, type MarginResult } from "./margin.ts";

export const OBSERVATION_SCHEMA_VERSION = "strategy-observation/2.0.0";
export type ObservationOutcome = "executed" | "no-trade:no-listed-structure" | "no-trade:no-entry-fill" | "data-unavailable" | "entered-exit-unfilled" | "settled" | "exit-policy-unconfigured";
export type SelectedExitPolicy = { rule: "vpoc-target"; fallback: "settlement" } | { rule: "fixed-time"; afterMs: number; fallback: "settlement" } | { rule: "none"; fallback?: never };
export interface PortfolioMarginEvidence { response: { margin_model: string; initial_margin: number; maintenance_margin: number; margin_balance?: number; available_funds?: number }; accountState: unknown; simulationTimestamp: number }
export interface StrategyVariantConfig {
  targetExpiryHorizonDays: number; widthUsd: number; spreadKind: "credit" | "debit"; expirySelectionPolicy: string; candidateRankPolicy: "rank-1-only"; amount: number;
  primaryExecutionScenario: "taker-tape-proxy"; latencyMs: number; fillWaitMs: number; synchronizationThresholdMs: number; slippageBps: number; exitPolicy: SelectedExitPolicy;
  requestedPackaging: "legs" | "combo"; executionRoute: ExecutionRoute; officialComboEvidence?: boolean; feeTier: "standard"; marginModel: "segregated_sm" | "cross_sm" | "segregated_pm" | "cross_pm";
  portfolioMarginEvidence?: PortfolioMarginEvidence;
}
export interface CashFlowLedger { grossBtc: number; feesBtc: number; netBtc: number; conversionTimestamp: number; conversionPriceUsdPerBtc: number; conversionSource: string; netUsd: number }
export interface SelectedExitLifecycle { rule: string; triggerTimestamp?: number; decisionTimestamp?: number; orderTimestamp?: number; fillTimestamp?: number; status: "not-triggered" | "filled" | "triggered-unfilled" | "settled" | "unconfigured"; fallbackRule?: "settlement"; reasonCode: string; execution?: ExitExecution }
export interface StrategyObservation {
  eventId: string; strategyVariantId: string; eventOutcome: ObservationOutcome; configuredAmount: number; strategyConfiguration: StrategyVariantConfig;
  signalClock: ExecutionClock; candidateSelection: { policy: string; selectedCandidateId?: string; selectedRank?: number; reason: string };
  candidateAttempts: Array<{ candidateId: string; rank?: number; status: string; executable: boolean; reason: string }>;
  entryExecution?: SpreadExecution; entryCashFlow?: CashFlowLedger; valuationPath?: DiagnosticValuationPoint[];
  independentExitOutcomes?: Array<{ rule: string; triggerTimestamp?: number; status: string; reasonCode: string }>;
  selectedExitLifecycle?: SelectedExitLifecycle; closingCashFlow?: CashFlowLedger; settlementLedger?: { legs: OptionSettlementLedger[]; cashFlowBtc: number; deliveryFeesBtc: number };
  feeLedger?: { route: ExecutionRoute; opening: RoutedFees; closing?: RoutedFees; deliveryFeesBtc: number; requestedPackaging: string; officialComboEvidence: boolean };
  marginResult?: MarginResult; executedNetPnl?: { btc: number; usd: number; conversionTimestamp: number; conversionPriceUsdPerBtc: number; conversionSource: string; identity: string };
  settlementNetPnl?: { btc: number; usd: number; conversionTimestamp: number; conversionPriceUsdPerBtc: number; conversionSource: string; identity: string };
  unavailableReason?: string; spread?: RetrievedSpread;
}
export interface EventBacktestInput { event: BacktestEvent; candidates: RetrievedSpread[]; candles: Candle[]; config: StrategyVariantConfig }
export interface ObservationRequest extends EventBacktestInput { requestKey: string }
export interface LedgerValidationError { observationKey?: string; code: string; path: string; message: string }

export function stableVariantId(config: StrategyVariantConfig) {
  return ["v2", `dte=${config.targetExpiryHorizonDays}`, `width=${config.widthUsd}`, `kind=${config.spreadKind}`, `expiry=${config.expirySelectionPolicy}`, `rank=${config.candidateRankPolicy}`, `amount=${config.amount}`, `exec=${config.primaryExecutionScenario}`, `latency=${config.latencyMs}`, `wait=${config.fillWaitMs}`, `sync=${config.synchronizationThresholdMs}`, `slip=${config.slippageBps}`, `exit=${config.exitPolicy.rule}${config.exitPolicy.rule === "fixed-time" ? `-${config.exitPolicy.afterMs}` : ""}`, `fallback=${"fallback" in config.exitPolicy ? config.exitPolicy.fallback ?? "none" : "none"}`, `packaging=${config.requestedPackaging}`, `route=${config.executionRoute}`, `official=${Boolean(config.officialComboEvidence)}`, `fee=${config.feeTier}`, `margin=${config.marginModel}`].join("|");
}
function observationKey(eventId: string, variantId: string) { return `${eventId}::${variantId}`; }
function routedFees(soldPrice: number, boughtPrice: number, amount: number, route: ExecutionRoute, closing = false) { return aggregateRoutedFees([{ side: closing ? "buy" : "sell", fee: calculateOptionFee(soldPrice, amount, "taker", STANDARD_INVERSE_BTC_OPTION_FEE) }, { side: closing ? "sell" : "buy", fee: calculateOptionFee(boughtPrice, amount, "taker", STANDARD_INVERSE_BTC_OPTION_FEE) }], route); }
function effectiveRoute(config: StrategyVariantConfig): ExecutionRoute { return config.executionRoute === "official-combo" && !config.officialComboEvidence ? "synchronized-leg-proxy" : config.executionRoute; }
function cashFlow(grossBtc: number, feesBtc: number, conversionPrice: number, timestamp: number, source: string): CashFlowLedger { const netBtc = grossBtc - feesBtc; return { grossBtc, feesBtc, netBtc, conversionTimestamp: timestamp, conversionPriceUsdPerBtc: conversionPrice, conversionSource: source, netUsd: netBtc * conversionPrice }; }
function pnl(btc: number, price: number, timestamp: number, source: string, identity: string) { return { btc, usd: btc * price, conversionTimestamp: timestamp, conversionPriceUsdPerBtc: price, conversionSource: source, identity }; }
function zeroPnl(timestamp: number, price: number) { return pnl(0, price, timestamp, "event-entry-price", "complete no-trade event-level PnL = 0"); }
function marginFor(config: StrategyVariantConfig, selected: RetrievedSpread, entry: SpreadExecution, event: BacktestEvent, grossEntry: number): MarginResult {
  const deployment = { ...DEFAULT_DEPLOYMENT, model: config.marginModel };
  const maxLoss = Math.max(0, (Math.abs(selected.soldContract!.strike - selected.boughtContract!.strike) / event.entryPrice) * config.amount - grossEntry);
  if (config.marginModel.endsWith("_pm")) {
    if (!config.portfolioMarginEvidence) return { deployment: { ...deployment, marginSource: "portfolio-simulation" }, requestedModel: config.marginModel, theoreticalMaximumSpreadLossBtc: maxLoss, state: "unavailable", unavailabilityReason: "Historical portfolio-margin simulation evidence was not supplied." };
    const result = portfolioMarginResult({ deployment, theoreticalMaximumSpreadLossBtc: maxLoss, ...config.portfolioMarginEvidence });
    return { ...result, requestedModel: config.marginModel, evidenceModel: config.portfolioMarginEvidence.response.margin_model };
  }
  return { ...estimateStandardOptionMargin({ side: "short", optionType: selected.optionType, amount: entry.sold.filledAmount, strike: selected.soldContract!.strike, indexPrice: entry.sold.supportingTrades.at(-1)?.indexPrice, markPriceBtc: entry.sold.supportingTrades.at(-1)?.markPrice ?? entry.sold.fillPriceBtc, observationTimestamp: entry.sold.fillTimestamp!, theoreticalMaximumSpreadLossBtc: maxLoss, deployment }), requestedModel: config.marginModel, evidenceModel: config.marginModel };
}

export function runEventBacktest(input: EventBacktestInput): StrategyObservation {
  const { event, candles, config } = input;
  const signalCandle = event.entryTimeSource === "resolved" ? candles.find(c => c.openTime <= (event.entryTimestamp ?? 0) && c.closeTime >= (event.entryTimestamp ?? 0)) : undefined;
  const signalTimestamp = event.entryTimestamp ?? Date.parse(`${event.entryDate}T00:00:00Z`);
  const signalClock = executionClock({ signalTimestamp, signalSourceTimestamp: signalCandle?.openTime ?? signalTimestamp, signalSourceCandle: signalCandle, signalTimePrecision: signalCandle ? "candle" : event.entryTimeSource === "manual" ? "manual" : "second", configuredLatencyMs: config.latencyMs, maxFillWaitMs: config.fillWaitMs });
  const candidates = [...input.candidates].sort((a,b)=>(a.expiryRank ?? Infinity)-(b.expiryRank ?? Infinity)); const selected = candidates.find(c=>c.expiryRank===1) ?? candidates[0];
  const attempts = candidates.map(candidate => ({ candidateId: candidate.id, rank: candidate.expiryRank, status: candidate.dataStatus === "data-unavailable" ? "data-unavailable" : candidate.retrievalStatus, executable: candidate.id === selected?.id, reason: candidate.id === selected?.id ? "Rank-1 candidate selected before execution." : "Retained diagnostic alternative; causal fallback was not configured." }));
  const base = { eventId:event.id, strategyVariantId:stableVariantId(config), configuredAmount:config.amount, strategyConfiguration:config, signalClock, candidateSelection:{policy:config.candidateRankPolicy,selectedCandidateId:selected?.id,selectedRank:selected?.expiryRank,reason:selected?"Only the pre-ranked primary candidate may execute.":"No candidate was available."},candidateAttempts:attempts };
  if (!selected) return {...base,eventOutcome:"no-trade:no-listed-structure",executedNetPnl:zeroPnl(signalClock.orderSubmittedAt,event.entryPrice),unavailableReason:"Complete manifest evidence contains no listed structure for this strategy variant."};
  if (selected.dataStatus === "data-unavailable" || selected.retrievalStatus === "partial") return {...base,spread:selected,eventOutcome:"data-unavailable",unavailableReason:selected.retrievalNote||"Required contract retrieval was incomplete."};
  if (!selected.soldContract||!selected.boughtContract||!selected.expiryTimestamp||selected.retrievalStatus!=="ready") return {...base,spread:selected,eventOutcome:"data-unavailable",unavailableReason:selected.retrievalNote||"Resolved contract identity or history is incomplete."};
  const entryExecution=simulateTakerSpread(selected,signalClock,config.amount,config.slippageBps,config.synchronizationThresholdMs);
  if(entryExecution.status!=="filled") return {...base,spread:selected,eventOutcome:"no-trade:no-entry-fill",entryExecution,executedNetPnl:zeroPnl(signalClock.orderSubmittedAt,event.entryPrice),unavailableReason:entryExecution.reason};
  const route=effectiveRoute(config); const opening=routedFees(entryExecution.sold.fillPriceBtc!,entryExecution.bought.fillPriceBtc!,config.amount,route);
  const grossEntry=(entryExecution.sold.fillPriceBtc!-entryExecution.bought.fillPriceBtc!)*config.amount; const entryTimestamp=Math.max(entryExecution.sold.fillTimestamp!,entryExecution.bought.fillTimestamp!);
  const entryCashFlow=cashFlow(grossEntry,opening.finalFee,event.entryPrice,entryTimestamp,"entry-fill-index");
  const marginResult=marginFor(config,selected,entryExecution,event,grossEntry);
  const valuationPath=buildExecutedValuationPath(selected,event,candles,{soldFillPriceBtc:entryExecution.sold.fillPriceBtc!,boughtFillPriceBtc:entryExecution.bought.fillPriceBtc!,filledAmount:config.amount,soldFillTimestamp:entryExecution.sold.fillTimestamp!,boughtFillTimestamp:entryExecution.bought.fillTimestamp!,openingFeesBtc:opening.finalFee,netOpeningCashFlowBtc:entryCashFlow.netBtc,executionRoute:route,entryIndexUsdPerBtc:event.entryPrice,entryIndexSource:"event-entry-price"},candles.map(c=>c.closeTime));
  const trigger=config.exitPolicy.rule==="vpoc-target"&&event.vpocPrice?firstTouch(candles,event.vpocPrice,signalClock.orderSubmittedAt):config.exitPolicy.rule==="fixed-time"?{openTime:signalClock.orderSubmittedAt+config.exitPolicy.afterMs,closeTime:signalClock.orderSubmittedAt+config.exitPolicy.afterMs}:undefined;
  const independentExitOutcomes=[{rule:"VPOC target",triggerTimestamp:trigger?.closeTime,status:trigger?"triggered":"not-triggered",reasonCode:trigger?"causal-candle-close":"not-hit-or-unconfigured"},{rule:"Expiry settlement",triggerTimestamp:selected.expiryTimestamp,status:"available",reasonCode:"configured-fallback"}];
  const common={...base,spread:selected,entryExecution,entryCashFlow,valuationPath,independentExitOutcomes,marginResult};
  if(config.exitPolicy.rule==="none") return {...common,eventOutcome:"exit-policy-unconfigured",selectedExitLifecycle:{rule:"none",status:"unconfigured",reasonCode:"exit-policy-unconfigured"},feeLedger:{route,opening,deliveryFeesBtc:0,requestedPackaging:config.requestedPackaging,officialComboEvidence:Boolean(config.officialComboEvidence)}};
  if(trigger&&trigger.closeTime<selected.expiryTimestamp){const triggerCandle=candles.find(c=>c.openTime===trigger.openTime&&c.closeTime===trigger.closeTime);const exitClock=executionClock({signalTimestamp:trigger.closeTime,signalSourceTimestamp:trigger.openTime,signalSourceCandle:triggerCandle,signalTimePrecision:triggerCandle?"candle":"second",configuredLatencyMs:config.latencyMs,maxFillWaitMs:config.fillWaitMs});const close=simulateTakerExit(selected,exitClock,trigger.closeTime,config.amount,config.slippageBps,config.synchronizationThresholdMs);if(close.exitStatus==="filled"){const closing=routedFees(close.sold.fillPriceBtc!,close.bought.fillPriceBtc!,config.amount,route,true);const closeGross=(close.bought.fillPriceBtc!-close.sold.fillPriceBtc!)*config.amount;const closeIndex=close.bought.supportingTrades.at(-1)?.indexPrice??event.entryPrice;const closingCashFlow=cashFlow(closeGross,closing.finalFee,closeIndex,close.exitFillTimestamp!,"exit-fill-index");const netBtc=entryCashFlow.netBtc+closingCashFlow.netBtc;return {...common,eventOutcome:"executed",selectedExitLifecycle:{rule:config.exitPolicy.rule,triggerTimestamp:trigger.closeTime,decisionTimestamp:exitClock.decisionAvailableTimestamp,orderTimestamp:exitClock.orderSubmittedAt,fillTimestamp:close.exitFillTimestamp,status:"filled",fallbackRule:"settlement",reasonCode:"causal-taker-fill",execution:close},closingCashFlow,feeLedger:{route,opening,closing,deliveryFeesBtc:0,requestedPackaging:config.requestedPackaging,officialComboEvidence:Boolean(config.officialComboEvidence)},executedNetPnl:pnl(netBtc,closeIndex,close.exitFillTimestamp!,"exit-fill-index",`net opening ${entryCashFlow.netBtc} + net closing ${closingCashFlow.netBtc}`)}}}
  if(selected.deliveryPrice===undefined)return {...common,eventOutcome:"entered-exit-unfilled",selectedExitLifecycle:{rule:config.exitPolicy.rule,triggerTimestamp:trigger?.closeTime,decisionTimestamp:trigger?.closeTime,orderTimestamp:trigger?trigger.closeTime+config.latencyMs:undefined,status:trigger?"triggered-unfilled":"not-triggered",fallbackRule:"settlement",reasonCode:"settlement-data-unavailable"},feeLedger:{route,opening,deliveryFeesBtc:0,requestedPackaging:config.requestedPackaging,officialComboEvidence:Boolean(config.officialComboEvidence)},unavailableReason:"Official delivery price required by the configured settlement fallback is unavailable."};
  const legs=[buildOptionSettlementLedger({expiryTimestamp:selected.expiryTimestamp,optionType:selected.optionType,side:"short",amount:config.amount,strike:selected.soldContract.strike,deliveryPrice:selected.deliveryPrice,dailyOption:false}),buildOptionSettlementLedger({expiryTimestamp:selected.expiryTimestamp,optionType:selected.optionType,side:"long",amount:config.amount,strike:selected.boughtContract.strike,deliveryPrice:selected.deliveryPrice,dailyOption:false})];
  const settlementCash=legs.reduce((s,l)=>s+l.futureEconomicPnlBtc,0);const deliveryFees=legs.reduce((s,l)=>s+l.aggregateDeliveryFeeBtc,0);const netBtc=entryCashFlow.netBtc+settlementCash-deliveryFees;
  return {...common,eventOutcome:"settled",selectedExitLifecycle:{rule:config.exitPolicy.rule,triggerTimestamp:trigger?.closeTime,decisionTimestamp:trigger?.closeTime,orderTimestamp:trigger?trigger.closeTime+config.latencyMs:undefined,status:"settled",fallbackRule:"settlement",reasonCode:trigger?"triggered-unfilled-carried-to-settlement":"primary-not-triggered-carried-to-settlement"},settlementLedger:{legs,cashFlowBtc:settlementCash,deliveryFeesBtc:deliveryFees},feeLedger:{route,opening,deliveryFeesBtc:deliveryFees,requestedPackaging:config.requestedPackaging,officialComboEvidence:Boolean(config.officialComboEvidence)},settlementNetPnl:pnl(netBtc,selected.deliveryPrice,selected.expiryTimestamp,"deribit-delivery-price",`net opening ${entryCashFlow.netBtc} + settlement ${settlementCash} - delivery fees ${deliveryFees}`)};
}

export function buildUniqueObservationRequests(event:BacktestEvent,candidates:RetrievedSpread[],candles:Candle[],configFor:(candidate:RetrievedSpread)=>StrategyVariantConfig):ObservationRequest[]{
  const groups=new Map<string,ObservationRequest>();
  for(const candidate of candidates){const config=configFor(candidate);const variant=stableVariantId(config);const key=observationKey(event.id,variant);const current=groups.get(key);if(current)current.candidates.push(candidate);else groups.set(key,{requestKey:key,event,candidates:[candidate],candles,config});}
  return [...groups.values()].map(request=>({...request,candidates:[...request.candidates].sort((a,b)=>(a.expiryRank??Infinity)-(b.expiryRank??Infinity))}));
}
export function buildAndRunObservationRequests(event:BacktestEvent,candidates:RetrievedSpread[],candles:Candle[],configFor:(candidate:RetrievedSpread)=>StrategyVariantConfig){
  const map=new Map<string,StrategyObservation>();for(const request of buildUniqueObservationRequests(event,candidates,candles,configFor)){const observation=runEventBacktest(request);const key=observationKey(observation.eventId,observation.strategyVariantId);if(map.has(key))throw new Error(`duplicate-observation-key:${key}`);map.set(key,observation);}return [...map.values()];
}
export function aggregateObservations(observations:StrategyObservation[]){const groups=new Map<string,StrategyObservation[]>();observations.forEach(o=>groups.set(o.strategyVariantId,[...(groups.get(o.strategyVariantId)??[]),o]));return [...groups].map(([strategyVariantId,rows])=>{const unavailable=rows.filter(r=>r.eventOutcome==="data-unavailable").length;const complete=rows.length-unavailable;const trades=rows.filter(r=>["executed","settled"].includes(r.eventOutcome)).length;const noTrades=rows.filter(r=>r.eventOutcome.startsWith("no-trade:")).length;const pnlRows=rows.map(r=>r.executedNetPnl??r.settlementNetPnl).filter((p):p is NonNullable<typeof p>=>p!==undefined);const total=pnlRows.reduce((s,p)=>s+p.btc,0);return{strategyVariantId,totalOriginalSignals:rows.length,completeEvents:complete,executedTrades:trades,noTrades,unavailableEvents:unavailable,executionRate:complete?trades/complete:0,coverage:rows.length?complete/rows.length:0,averageNetPnlBtcPerCompleteSignal:complete?total/complete:undefined,averageNetPnlBtcPerExecutedTrade:trades?rows.filter(r=>["executed","settled"].includes(r.eventOutcome)).reduce((s,r)=>s+((r.executedNetPnl??r.settlementNetPnl)?.btc??0),0)/trades:undefined};});}

const EPS=1e-10; const close=(a:number|undefined,b:number|undefined)=>a!==undefined&&b!==undefined&&Math.abs(a-b)<=EPS*Math.max(1,Math.abs(a),Math.abs(b));
export function validateObservationLedger(observations:StrategyObservation[],exportedAggregates=aggregateObservations(observations)){const errors:LedgerValidationError[]=[];const add=(o:StrategyObservation|undefined,code:string,path:string,message:string)=>errors.push({observationKey:o?observationKey(o.eventId,o.strategyVariantId):undefined,code,path,message});const seen=new Set<string>();
 const observationFields=new Set(["eventId","strategyVariantId","eventOutcome","configuredAmount","strategyConfiguration","signalClock","candidateSelection","candidateAttempts","entryExecution","entryCashFlow","valuationPath","independentExitOutcomes","selectedExitLifecycle","closingCashFlow","settlementLedger","feeLedger","marginResult","executedNetPnl","settlementNetPnl","unavailableReason","spread"]);const scenarioNames=/^(scenarioInput|scenarioResult|scenarioAmount|scenarioOutcomes|calculatorScenario|calculatorState|openingCapital|openingCapitalScenario)$/i;const scanScenario=(o:StrategyObservation,value:unknown,path:string)=>{if(!value||typeof value!=="object")return;for(const [name,nested] of Object.entries(value)){const next=path?`${path}.${name}`:name;if(scenarioNames.test(name))add(o,"unexpected-field",next,"Scenario calculator material is forbidden in the primary observation schema.");else scanScenario(o,nested,next);}};
 for(const o of observations){for(const field of Object.keys(o))if(!observationFields.has(field))add(o,"unexpected-field",field,`Unknown primary observation field: ${field}.`);scanScenario(o,o,"");const key=observationKey(o.eventId,o.strategyVariantId);if(seen.has(key))add(o,"duplicate-observation-key","observations",`Duplicate ${key}.`);seen.add(key);const e=o.entryExecution;const clock=o.signalClock;if(clock.decisionAvailableTimestamp>clock.orderSubmittedAt)add(o,"entry-order-chronology","signalClock.orderSubmittedAt","Entry order precedes decision availability.");
  if(e?.status==="filled"){for(const [legName,leg] of [["sold",e.sold],["bought",e.bought]] as const){if(leg.fillTimestamp===undefined||leg.fillTimestamp<=clock.orderSubmittedAt)add(o,`entry-${legName}-fill-chronology`,`entryExecution.${legName}.fillTimestamp`,"Entry fill must be strictly post-order.");if(leg.supportingTradeTimestamps.some(t=>t<=clock.orderSubmittedAt))add(o,`entry-${legName}-print-chronology`,`entryExecution.${legName}.supportingTradeTimestamps`,"Every supporting print must be strictly post-order.");if(!close(leg.filledAmount,o.configuredAmount))add(o,`entry-${legName}-amount`,`entryExecution.${legName}.filledAmount`,"Filled amount must equal configured amount.");}if(!close(e.sold.filledAmount,e.bought.filledAmount))add(o,"entry-leg-amount-mismatch","entryExecution","Entry leg amounts disagree.");
   if(o.entryCashFlow){const gross=(e.sold.fillPriceBtc!*e.sold.filledAmount)-(e.bought.fillPriceBtc!*e.bought.filledAmount);if(!close(o.entryCashFlow.grossBtc,gross))add(o,"entry-gross-cash-flow","entryCashFlow.grossBtc","Gross entry cash flow does not equal sold proceeds minus bought cost.");if(!close(o.entryCashFlow.netBtc,gross-o.entryCashFlow.feesBtc))add(o,"entry-net-cash-flow","entryCashFlow.netBtc","Net entry cash flow identity failed.");}else add(o,"missing-entry-cash-flow","entryCashFlow","Filled entry requires cash-flow evidence.");
  }
  const fees=o.feeLedger;if(fees){if(fees.route==="official-combo")add(o,"combo-evidence-required","feeLedger.route","Official-combo fee waiver requires matching historical execution evidence; a route flag is not evidence.");for(const [group,routed] of [["opening",fees.opening],["closing",fees.closing]] as const){if(!routed)continue;let buy=0,sell=0;for(const [i,leg] of routed.legs.entries()){const f=leg.fee;const expectedExecution=group==="opening"?e:o.selectedExitLifecycle?.execution;const expectedLeg=i===0?expectedExecution?.sold:expectedExecution?.bought;if(expectedLeg&&(!close(f.inputPriceBtc,expectedLeg.fillPriceBtc)||!close(f.absoluteAmount,expectedLeg.filledAmount)))add(o,"fee-input-mismatch",`feeLedger.${group}.legs[${i}].fee`,"Fee price and amount must match the authoritative causal fill.");const gross=Math.min(f.baseFeeRate,f.premiumCap*Math.max(0,f.inputPriceBtc))*f.absoluteAmount;if(f.tier!=="standard"||f.scheduleEffectiveDate!==STANDARD_INVERSE_BTC_OPTION_FEE.effectiveDate||!close(f.grossFee,gross)||!close(f.finalFee,gross*(1-f.discount)))add(o,"fee-leg-identity",`feeLedger.${group}.legs[${i}].fee`,"Fee schedule, input, cap, rate, tier, or amount identity failed.");if(leg.side==="buy")buy+=f.finalFee;else sell+=f.finalFee;}const expected=routed.executionRoute==="official-combo"?Math.max(buy,sell):buy+sell;if(!close(routed.buyAggregate,buy)||!close(routed.sellAggregate,sell)||!close(routed.finalFee,expected))add(o,"fee-aggregate-identity",`feeLedger.${group}`,"Routed fee aggregate identity failed.");}}
  const x=o.selectedExitLifecycle;if(x?.status==="filled"){const c=x.execution;if(!c||c.exitStatus!=="filled")add(o,"executed-exit-evidence","selectedExitLifecycle.execution","Filled exit lacks complete execution evidence.");else{if(x.triggerTimestamp!>x.decisionTimestamp!||x.decisionTimestamp!>x.orderTimestamp!)add(o,"exit-decision-chronology","selectedExitLifecycle","Exit trigger/decision/order chronology failed.");for(const [name,leg] of [["short",c.sold],["long",c.bought]] as const){if(leg.fillTimestamp===undefined||leg.fillTimestamp<=x.orderTimestamp!)add(o,`exit-${name}-fill-chronology`,`selectedExitLifecycle.execution.${name}.fillTimestamp`,"Close fill must be strictly post-order.");if(leg.supportingTradeTimestamps.some(t=>t<=x.orderTimestamp!))add(o,`exit-${name}-print-chronology`,`selectedExitLifecycle.execution.${name}.supportingTradeTimestamps`,"Every close print must be post-order.");if(!close(leg.filledAmount,o.configuredAmount))add(o,`exit-${name}-amount`,`selectedExitLifecycle.execution.${name}.filledAmount`,"Close amount must equal open amount.");}const gross=c.bought.fillPriceBtc!*c.bought.filledAmount-c.sold.fillPriceBtc!*c.sold.filledAmount;if(!o.closingCashFlow||!close(o.closingCashFlow.grossBtc,gross))add(o,"exit-gross-cash-flow","closingCashFlow.grossBtc","Gross closing cash flow identity failed.");else if(!close(o.closingCashFlow.netBtc,gross-o.closingCashFlow.feesBtc))add(o,"exit-net-cash-flow","closingCashFlow.netBtc","Net closing cash flow identity failed.");if(!o.executedNetPnl||!close(o.executedNetPnl.btc,(o.entryCashFlow?.netBtc??NaN)+(o.closingCashFlow?.netBtc??NaN)))add(o,"executed-net-pnl","executedNetPnl.btc","Executed PnL must equal net opening plus net closing cash flow.");}}
  if(o.eventOutcome==="settled"){if(!o.settlementLedger||!o.spread?.soldContract||!o.spread.boughtContract||o.spread.deliveryPrice===undefined)add(o,"missing-settlement-evidence","settlementLedger","Settled outcome requires complete settlement evidence.");else{const sl=o.settlementLedger;const expected=[buildOptionSettlementLedger({expiryTimestamp:o.spread.expiryTimestamp!,optionType:o.spread.optionType,side:"short",amount:o.configuredAmount,strike:o.spread.soldContract.strike,deliveryPrice:o.spread.deliveryPrice,dailyOption:false}),buildOptionSettlementLedger({expiryTimestamp:o.spread.expiryTimestamp!,optionType:o.spread.optionType,side:"long",amount:o.configuredAmount,strike:o.spread.boughtContract.strike,deliveryPrice:o.spread.deliveryPrice,dailyOption:false})];expected.forEach((leg,i)=>{const got=sl.legs[i];if(!got||got.version!==(o.spread!.expiryTimestamp!<OPTION_TO_FUTURE_EFFECTIVE_AT?"legacy-direct-cash":"option-to-future")||!close(got.intrinsicValueBtc,leg.intrinsicValueBtc)||!close(got.generatedFutureUsd,leg.generatedFutureUsd)||!close(got.futureEconomicPnlBtc,leg.futureEconomicPnlBtc)||!close(got.aggregateDeliveryFeeBtc,leg.aggregateDeliveryFeeBtc)||got.entries.slice(1).some(e=>e.deliveryFeeBtc!==0))add(o,"settlement-leg-identity",`settlementLedger.legs[${i}]`,"Settlement version, ITM/OTM value, generated future, direction, economic PnL, or delivery fee failed.");});const cash=sl.legs.reduce((s,l)=>s+l.futureEconomicPnlBtc,0),delivery=sl.legs.reduce((s,l)=>s+l.aggregateDeliveryFeeBtc,0);if(!close(sl.cashFlowBtc,cash))add(o,"settlement-cash-flow","settlementLedger.cashFlowBtc","Settlement cash flow identity failed.");if(!close(sl.deliveryFeesBtc,delivery)||!close(fees?.deliveryFeesBtc,delivery))add(o,"settlement-delivery-fee","settlementLedger.deliveryFeesBtc","Settlement delivery-fee identity failed.");if(!o.settlementNetPnl||!close(o.settlementNetPnl.btc,(o.entryCashFlow?.netBtc??NaN)+cash-delivery))add(o,"settlement-net-pnl","settlementNetPnl.btc","Settlement net PnL identity failed.");}}
  if(o.eventOutcome.startsWith("no-trade:")&&(e?.status==="filled"||!o.executedNetPnl||o.executedNetPnl.btc!==0))add(o,"no-trade-outcome-semantics","eventOutcome","Complete no-trade must have no filled execution and zero event PnL.");if(o.eventOutcome==="data-unavailable"&&(o.executedNetPnl||o.settlementNetPnl))add(o,"unavailable-pnl-semantics","eventOutcome","Unavailable outcome must not contain PnL.");if(x?.status==="triggered-unfilled"&&(o.closingCashFlow||o.executedNetPnl))add(o,"triggered-unfilled-pnl-semantics","selectedExitLifecycle","Triggered-unfilled exit cannot contain fabricated close PnL.");if(o.eventOutcome==="executed"&&x?.status!=="filled")add(o,"executed-outcome-semantics","eventOutcome","Executed outcome requires a filled terminal lifecycle.");
 }
 const recomputed=aggregateObservations(observations);const actual=new Map(exportedAggregates.map(g=>[g.strategyVariantId,g]));for(const expected of recomputed){const got=actual.get(expected.strategyVariantId);for(const field of ["totalOriginalSignals","completeEvents","executedTrades","noTrades","unavailableEvents","executionRate","coverage","averageNetPnlBtcPerCompleteSignal","averageNetPnlBtcPerExecutedTrade"] as const)if(!got||!close(got[field],expected[field]))add(undefined,"aggregate-mismatch",`aggregateGroups.${expected.strategyVariantId}.${field}`,`Aggregate ${field} does not reconcile to observations.`);}if(actual.size!==recomputed.length)add(undefined,"aggregate-group-mismatch","aggregateGroups","Aggregate group count does not reconcile to observations.");return{valid:errors.length===0,errors};}
function serializePrimaryObservation(o:StrategyObservation):StrategyObservation {
 const copy=<T>(value:T):T=>structuredClone(value);
 const serialized:StrategyObservation={eventId:o.eventId,strategyVariantId:o.strategyVariantId,eventOutcome:o.eventOutcome,configuredAmount:o.configuredAmount,strategyConfiguration:copy(o.strategyConfiguration),signalClock:copy(o.signalClock),candidateSelection:copy(o.candidateSelection),candidateAttempts:copy(o.candidateAttempts)};
 if(o.entryExecution)serialized.entryExecution=copy(o.entryExecution);if(o.entryCashFlow)serialized.entryCashFlow=copy(o.entryCashFlow);if(o.valuationPath)serialized.valuationPath=copy(o.valuationPath);if(o.independentExitOutcomes)serialized.independentExitOutcomes=copy(o.independentExitOutcomes);if(o.selectedExitLifecycle)serialized.selectedExitLifecycle=copy(o.selectedExitLifecycle);if(o.closingCashFlow)serialized.closingCashFlow=copy(o.closingCashFlow);if(o.settlementLedger)serialized.settlementLedger=copy(o.settlementLedger);if(o.feeLedger)serialized.feeLedger=copy(o.feeLedger);if(o.marginResult)serialized.marginResult=copy(o.marginResult);if(o.executedNetPnl)serialized.executedNetPnl=copy(o.executedNetPnl);if(o.settlementNetPnl)serialized.settlementNetPnl=copy(o.settlementNetPnl);if(o.unavailableReason)serialized.unavailableReason=o.unavailableReason;if(o.spread)serialized.spread=copy(o.spread);return serialized;
}
export function buildObservationExport(observations:StrategyObservation[],strategyConfiguration:unknown,originalEvents:BacktestEvent[],generatedAt=new Date().toISOString(),aggregateGroups=aggregateObservations(observations)){const validation=validateObservationLedger(observations,aggregateGroups);const serialized=observations.map(serializePrimaryObservation);return{schemaVersion:OBSERVATION_SCHEMA_VERSION,generatedAt,valid:validation.valid,validationErrors:validation.errors,strategyConfiguration:structuredClone(strategyConfiguration),originalEvents:structuredClone(originalEvents),strategyVariants:[...new Set(serialized.map(o=>o.strategyVariantId))],observations:serialized,aggregateGroups:structuredClone(aggregateGroups)};}
