/* eslint-disable @typescript-eslint/ban-ts-comment */
// Canonical rows are schema-open and have already passed bundle validation.
// @ts-nocheck
import type {AnalysisDataset} from "./research-analysis.ts";
import {analyzeStructurePoliciesEconomics,schedulePolicy,type PricingTrack} from "./structure-policy-economics.ts";

type Row=Readonly<Record<string,unknown>>;
export interface AnalysisConfiguration {pricingTrack:PricingTrack|null;executionAssumption:string|null;includedQualityLevels:string[];exitPolicy:string|null;trainingEndTimestampUtc:string|null;accountEquity:number|null;maximumRiskPerTrade:number|null;maximumMarginUtilization:number|null;dteMinimumDays:number|null;dteMaximumDays:number|null;maximumTailLossRiskUnits:number|null;maximumDrawdown:number|null;minimumCellEvents:number;uncertaintySeed:number}
export const DEFAULT_ANALYSIS_CONFIGURATION:AnalysisConfiguration={pricingTrack:null,executionAssumption:null,includedQualityLevels:[],exitPolicy:null,trainingEndTimestampUtc:null,accountEquity:null,maximumRiskPerTrade:null,maximumMarginUtilization:null,dteMinimumDays:null,dteMaximumDays:null,maximumTailLossRiskUnits:null,maximumDrawdown:null,minimumCellEvents:5,uncertaintySeed:271828};
export const REQUIRED_CONFIGURATION_FIELDS=["pricingTrack","executionAssumption","includedQualityLevels","exitPolicy","trainingEndTimestampUtc","accountEquity","maximumRiskPerTrade","maximumMarginUtilization","dteMinimumDays","dteMaximumDays","maximumTailLossRiskUnits","maximumDrawdown"] as const;
export interface TimelinePoint {timestampUtc:string;concurrentPositions:number;aggregateMaximumEconomicLoss:number;openingMargin:number|null;peakMargin:number|null;availableFunds:number|null;equity:number;drawdown:number;btcCollateralDrawdownUsd:number|null;capitalLocked:number;bullish:number;bearish:number}
export interface PortfolioPosition {candidateId:string;eventId:string;entryTimestampUtc:string;exitTimestampUtc:string;quantity:number;riskUnits:number;pnl:number;maximumEconomicLoss:number;margin:number|null;cohort:"training"|"validation";direction:string}
export interface MatrixCell {row:string;column:string;eventN:number;candidateN:number;executableCoverage:number|null;expectancyPerOpportunityRu:number;tailResult:number|null;confidenceInterval:[number,number]|null;missingRate:number;status:"ok"|"sparse"|"unavailable"}
export interface InteractionMatrix {id:string;title:string;cells:MatrixCell[]}
export interface ConstraintResult {constraint:string;configured:boolean;passed:boolean|null;detail:string}
export interface StrategyRow {key:string;cohort:"training"|"validation";events:number;expectancyPerOpportunityRu:number;tail:number|null;drawdown:number;stable:boolean;rank:number}
export interface PortfolioStrategyResult {configuration:AnalysisConfiguration;pdfMetadata:{analysisConfiguration:AnalysisConfiguration;generatedDeterministically:boolean};configured:boolean;missingConfiguration:string[];portfolio:{positions:PortfolioPosition[];timeline:TimelinePoint[];rejectedOpportunities:number;noTradeOpportunities:number;marginUtilizationAvailable:boolean;partialMaximumLossPortfolio:boolean};futures:{status:"available"|"blocked";explanation:string;paired:Row[]};matrices:InteractionMatrix[];selection:{objective:string;bestStrategy:string|null;survivingConfigurations:string[];failedConstraints:string[];unstableOrSparse:string[];missingEvidence:string[];nextDataRequired:string[];scorecard:ConstraintResult[];rows:StrategyRow[];stabilitySummary:string};warnings:string[]}

const n=(x:unknown)=>typeof x==="number"&&Number.isFinite(x)?x:null, str=(x:unknown)=>x==null?"":String(x), tm=(x:unknown)=>typeof x==="string"&&Number.isFinite(Date.parse(x))?Date.parse(x):null;
const candidateEntry=(c:Row)=>tm(c.valuation_timestamp_utc)??tm(c.entry_timestamp_utc), dte=(c:Row)=>n(c.actual_dte_days)??(n(c.actual_dte_hours)!==null?n(c.actual_dte_hours)!/24:null), quality=(c:Row)=>str(c.quality_level??c.data_quality??"unknown"), execution=(c:Row)=>str(c.execution_mode??c.execution_assumption??"unknown");
function complete(c:AnalysisConfiguration){return REQUIRED_CONFIGURATION_FIELDS.filter(k=>k==="includedQualityLevels"?!c[k].length:c[k]===null||c[k]===undefined||c[k]==="")}
function hash(seed:number,s:string){let x=seed|0;for(const ch of s)x=Math.imul(x^ch.charCodeAt(0),16777619);return(x>>>0)/4294967296}
function quantile(x:number[],p:number){if(!x.length)return null;const s=[...x].sort((a,b)=>a-b),i=(s.length-1)*p,l=Math.floor(i),u=Math.ceil(i);return s[l]+(s[u]-s[l])*(i-l)}
function clusteredCi(rows:{eventId:string;value:number}[],seed:number):[number,number]|null{const ids=[...new Set(rows.map(x=>x.eventId))];if(ids.length<2)return null;const by=new Map(ids.map(id=>[id,rows.filter(x=>x.eventId===id).reduce((a,b)=>a+b.value,0)]));const samples:number[]=[];for(let b=0;b<400;b++){let sum=0;for(let i=0;i<ids.length;i++)sum+=by.get(ids[Math.floor(hash(seed+b*7919+i,ids[i]+b)*ids.length)])??0;samples.push(sum/ids.length)}return[quantile(samples,.025)!,quantile(samples,.975)!]}

export function analyzePortfolioAndSelectStrategy(dataset:Pick<AnalysisDataset,"tables"|"run"|"eventUniverseComplete">,configuration:AnalysisConfiguration):PortfolioStrategyResult{
 const t=dataset.tables,all=t.candidates??[],availability=t.availability??[],events=t.events??[],outcomes=t.outcomes??[],vals=t.valuations??[],margins=t.margin_scenarios??[],econ=analyzeStructurePoliciesEconomics(dataset as never).economics.filter(x=>x.track===configuration.pricingTrack),missing=complete(configuration),configured=!missing.length,byEvent=new Map(events.map(e=>[str(e.event_id),e]));
 const candidates=all.filter(c=>(!configuration.executionAssumption||execution(c)===configuration.executionAssumption)&&(!configuration.includedQualityLevels.length||configuration.includedQualityLevels.includes(quality(c)))&&(dte(c)===null||configuration.dteMinimumDays===null||dte(c)!>=configuration.dteMinimumDays)&&(dte(c)===null||configuration.dteMaximumDays===null||dte(c)!<=configuration.dteMaximumDays)).sort((a,b)=>(candidateEntry(a)??Infinity)-(candidateEntry(b)??Infinity));
 const positions:PortfolioPosition[]=[],timeline:TimelinePoint[]=[];let equity=configuration.accountEquity??0,peak=equity,rejected=0;const riskDollars=(configuration.accountEquity??0)*(configuration.maximumRiskPerTrade??0), active:PortfolioPosition[]=[];
 for(const c of candidates){const entry=candidateEntry(c),e=econ.find(x=>x.candidateId===str(c.candidate_id)),maxLoss=e?.maximumEconomicLoss??null,exit=configuration.exitPolicy&&configuration.pricingTrack?schedulePolicy(c,outcomes.filter(x=>x.candidate_id===c.candidate_id),vals.filter(x=>x.candidate_id===c.candidate_id),configuration.exitPolicy,configuration.pricingTrack):null;if(entry===null||!maxLoss||!exit){rejected++;continue}for(let i=active.length-1;i>=0;i--)if(Date.parse(active[i].exitTimestampUtc)<=entry)active.splice(i,1);const marginRow=margins.find(x=>x.candidate_id===c.candidate_id&&x.margin_status==="available"),margin=n(marginRow?.incremental_initial_margin),marginCap=(configuration.accountEquity??0)*(configuration.maximumMarginUtilization??0),riskQty=Math.floor(riskDollars/maxLoss),marginQty=margin===null?Infinity:Math.floor(Math.max(0,marginCap-active.reduce((s,x)=>s+(x.margin??0),0))/margin),qty=Math.max(0,Math.min(riskQty,marginQty));if(!qty){rejected++;continue}const pnl=exit.pnl*qty,riskUnits=riskDollars?pnl/riskDollars:0,pos={candidateId:str(c.candidate_id),eventId:str(c.event_id),entryTimestampUtc:new Date(entry).toISOString(),exitTimestampUtc:new Date(exit.decision).toISOString(),quantity:qty,riskUnits,pnl,maximumEconomicLoss:maxLoss*qty,margin:margin===null?null:margin*qty,cohort:(configuration.trainingEndTimestampUtc&&entry<=Date.parse(configuration.trainingEndTimestampUtc)?"training":"validation") as "training"|"validation",direction:str(byEvent.get(str(c.event_id))?.direction??c.option_type)};positions.push(pos);active.push(pos);equity+=pnl;peak=Math.max(peak,equity);const locked=active.reduce((s,x)=>s+x.maximumEconomicLoss,0),marginKnown=active.every(x=>x.margin!==null),m=marginKnown?active.reduce((s,x)=>s+x.margin!,0):null;timeline.push({timestampUtc:pos.entryTimestampUtc,concurrentPositions:active.length,aggregateMaximumEconomicLoss:locked,openingMargin:m,peakMargin:m,availableFunds:m===null?null:equity-m,equity,drawdown:peak?Math.max(0,(peak-equity)/peak):0,btcCollateralDrawdownUsd:n(c.entry_index_price)===null?null:Math.max(0,peak-equity),capitalLocked:locked,bullish:active.filter(x=>/long|put/i.test(x.direction)).length,bearish:active.filter(x=>/short|call/i.test(x.direction)).length})}
 const opportunityEvents=new Set(availability.map(x=>str(x.event_id)).filter(Boolean)),tradedEvents=new Set(positions.map(x=>x.eventId)),noTrade=Math.max(0,opportunityEvents.size-tradedEvents.size),denominator=Math.max(opportunityEvents.size,new Set(events.map(x=>str(x.event_id))).size,1);
 const dims:[string,string,(c:Row)=>string,(c:Row)=>string][]=[
  ["dte-width","DTE × width",c=>str(dte(c)??"missing"),c=>str(c.actual_width??c.width??"missing")],
  ["dte-exit","DTE × exit policy",c=>str(dte(c)??"missing"),()=>configuration.exitPolicy??"unset"],
  ["strike-width","Short-strike method × width",c=>str(c.short_strike_method??c.strike_method??"unknown"),c=>str(c.actual_width??c.width??"missing")],
  ["dte-speed","DTE × resolution speed",c=>str(dte(c)??"missing"),c=>str(byEvent.get(str(c.event_id))?.resolution_speed_cohort??byEvent.get(str(c.event_id))?.sequence_status??"unresolved")],
  ["structure-execution","Structure × maker/taker",c=>str(c.structure_type??c.option_type??"unknown"),c=>execution(c)],
  ["structure-quality","Structure × quality inclusion",c=>str(c.structure_type??c.option_type??"unknown"),c=>quality(c)],
 ];
 const matrices=dims.map(([id,title,rf,cf])=>{const groups=new Map<string,Row[]>();for(const c of candidates){const k=`${rf(c)}\u0000${cf(c)}`;groups.set(k,[...(groups.get(k)??[]),c])}const cells=[...groups.entries()].map(([k,cs])=>{const [row,column]=k.split("\u0000"),ids=new Set(cs.map(c=>str(c.event_id))),ps=positions.filter(p=>cs.some(c=>str(c.candidate_id)===p.candidateId)),values=[...ids].map(eventId=>({eventId,value:ps.filter(p=>p.eventId===eventId).reduce((s,p)=>s+p.riskUnits,0)})),coverage=cs.length?ps.length/cs.length:null,tail=quantile(values.map(x=>x.value),.05),sparse=ids.size<configuration.minimumCellEvents;return{row,column,eventN:ids.size,candidateN:cs.length,executableCoverage:coverage,expectancyPerOpportunityRu:values.reduce((s,x)=>s+x.value,0)/denominator,tailResult:tail,confidenceInterval:clusteredCi(values,configuration.uncertaintySeed),missingRate:1-(coverage??0),status:(ps.length?sparse?"sparse":"ok":"unavailable") as MatrixCell["status"]}});return{id,title,cells}});
 const strategyKeys=[...new Set(candidates.map(c=>[str(c.structure_type??c.option_type??"unknown"),str(dte(c)??"missing"),str(c.actual_width??c.width??"missing"),str(c.short_strike_method??c.strike_method??"unknown")].join(" · ")))];const rows:StrategyRow[]=[];for(const cohort of ["training","validation"] as const){const cohortPositions=positions.filter(p=>p.cohort===cohort);const raw=strategyKeys.map(key=>{const pcs=cohortPositions.filter(p=>{const c=candidates.find(x=>str(x.candidate_id)===p.candidateId)!;return key===[str(c.structure_type??c.option_type??"unknown"),str(dte(c)??"missing"),str(c.actual_width??c.width??"missing"),str(c.short_strike_method??c.strike_method??"unknown")].join(" · ")}),eventN=new Set(pcs.map(p=>p.eventId)).size,values=pcs.map(p=>p.riskUnits);return{key,cohort,events:eventN,expectancyPerOpportunityRu:values.reduce((a,b)=>a+b,0)/denominator,tail:quantile(values,.05),drawdown:Math.max(0,...timeline.map(x=>x.drawdown)),stable:eventN>=configuration.minimumCellEvents,rank:0}}).sort((a,b)=>b.expectancyPerOpportunityRu-a.expectancyPerOpportunityRu);raw.forEach((x,i)=>{x.rank=i+1;rows.push(x)})}
 const maxDd=Math.max(0,...timeline.map(x=>x.drawdown)),tail=quantile(positions.map(x=>x.riskUnits),.05),scorecard:ConstraintResult[]=[{constraint:"Complete locked analysis configuration",configured,passed:configured,detail:configured?"All mandatory fields set.":`Missing: ${missing.join(", ")}`},{constraint:"Maximum portfolio drawdown",configured:configuration.maximumDrawdown!==null,passed:configuration.maximumDrawdown===null?null:maxDd<=configuration.maximumDrawdown,detail:`Observed ${(maxDd*100).toFixed(2)}%`},{constraint:"Tail-loss floor",configured:configuration.maximumTailLossRiskUnits!==null,passed:configuration.maximumTailLossRiskUnits===null||tail===null?null:tail>=-configuration.maximumTailLossRiskUnits,detail:tail===null?"Unavailable":`${tail.toFixed(3)} RU`},{constraint:"Chronological validation evidence",configured:Boolean(configuration.trainingEndTimestampUtc),passed:positions.some(x=>x.cohort==="validation"),detail:`${positions.filter(x=>x.cohort==="validation").length} validation positions`},{constraint:"Margin utilization",configured:configuration.maximumMarginUtilization!==null,passed:positions.every(x=>x.margin!==null)?true:null,detail:positions.every(x=>x.margin!==null)?"Verified observations used.":"Unavailable; never substituted cash cost."}],failed=scorecard.filter(x=>x.passed===false).map(x=>x.constraint),stable=rows.filter(x=>x.cohort==="validation"&&x.stable&&x.expectancyPerOpportunityRu>0).map(x=>x.key),best=configured&&!failed.length&&scorecard.every(x=>x.passed===true)?stable[0]??null:null;
 const futuresRows=t.futures_path??[],futuresAvailable=futuresRows.some(x=>x.verified===true&&(x.series_kind==="futures"||x.series_kind==="perpetual"));
 return{configuration:{...configuration,includedQualityLevels:[...configuration.includedQualityLevels]},pdfMetadata:{analysisConfiguration:{...configuration,includedQualityLevels:[...configuration.includedQualityLevels]},generatedDeterministically:true},configured,missingConfiguration:missing,portfolio:{positions,timeline,rejectedOpportunities:rejected,noTradeOpportunities:noTrade,marginUtilizationAvailable:positions.length>0&&positions.every(x=>x.margin!==null),partialMaximumLossPortfolio:positions.some(x=>x.margin===null)},futures:{status:futuresAvailable?"available":"blocked",explanation:futuresAvailable?"Verified futures/perpetual path supplied; event pairing requires matching entry, VPOC, invalidation, predefined risk, multiplier, costs and funding.":"Blocked: no verified futures/perpetual instrument and execution path. Spot/index candles are not executed futures prices; paired risk, funding, cohort and capital comparisons are therefore unavailable.",paired:[]},matrices,selection:{objective:"Net expectancy per MR opportunity in predefined risk units",bestStrategy:best,survivingConfigurations:stable,failedConstraints:failed,unstableOrSparse:rows.filter(x=>!x.stable).map(x=>x.key),missingEvidence:[...(!dataset.eventUniverseComplete?["Complete canonical MR opportunity universe"]:[]),...(!futuresAvailable?["Verified futures/perpetual instrument and path"]:[]),...(positions.some(x=>x.margin===null)?["Verified historical margin observations"]:[])],nextDataRequired:[...(!dataset.eventUniverseComplete?["Matching canonical companion trade dataset"]:[]),...(!futuresAvailable?["Futures multiplier, executed prices, commissions/slippage and funding"]:[]),...(positions.some(x=>x.margin===null)?["Entry and peak IM/MM observations"]:[])],scorecard,rows,stabilitySummary:stable.length?`${stable.length} broad validation region(s) survive; compare train/validation ranks rather than trusting an isolated maximum.`:"No broad, adequately sampled positive validation region. Any one-cell winner is suspicious and is not selected."},warnings:["Sizing uses only entry-available maximum loss and margin observations.","Unavailable/no-trade MR opportunities contribute zero to per-opportunity expectancy.","Confidence intervals resample events—not candidates—with a deterministic seed.","Margin metrics are unavailable rather than inferred from long-leg cash cost.","Thresholds are configuration inputs and are never optimized on the evaluated sample."]}
}
