import {generationStructuralConfiguration,type GenerationCandidateSnapshot,type ResearchOnlyStructure,type ResearchSelectionStore} from "./research-selections.ts";

export type ControlledMatrixMode="short_strike"|"width"|"dte"|"full";
export type MatrixReason="buffer_rule_not_applicable"|"counterpart_unselected"|"contract_unavailable"|"reference_unavailable"|"collapsed_actual_structure"|"canonical_materialization_unresolved"|"complete";
export interface ComparativeMaterializationTarget {eventId:string;structuralConfigurationId:string;candidateId:string;attemptCandidateIds:string[]}
export interface MatrixPreview {mode:ControlledMatrixMode;generatedDenominator:number;structuresAdded:string[];structuresRetained:string[];structuresRemoved:string[];newTechnicalBufferedPairs:number;newWidthLadders:number;newDteComparisons:number;unavailableCounterparts:Record<Exclude<MatrixReason,"complete">,number>;collapsedActualStructures:number;estimatedRecomputeCount:number;targetMaterializations:ComparativeMaterializationTarget[];unresolvedConfigurationIds:string[]}

const actualKey=(c:GenerationCandidateSnapshot)=>[c.actualExpiryTimestamp,c.optionType,c.actualStrikes.short,c.actualStrikes.long].join("~");
const strikeCell=(c:GenerationCandidateSnapshot)=>[c.actualExpiryTimestamp,c.optionType,c.actualStrikes.width,c.structure].join("~");
const widthCell=(c:GenerationCandidateSnapshot)=>[c.actualExpiryTimestamp,c.optionType,c.actualStrikes.short,c.strikeMethod,c.structure].join("~");
const dteCell=(c:GenerationCandidateSnapshot)=>[c.optionType,c.actualStrikes.short,c.actualStrikes.width,c.strikeMethod,c.structure].join("~");
const groups=(rows:readonly GenerationCandidateSnapshot[],key:(c:GenerationCandidateSnapshot)=>string)=>{const result=new Map<string,GenerationCandidateSnapshot[]>();for(const candidate of rows){const value=key(candidate);result.set(value,[...(result.get(value)??[]),candidate])}return result};

/** Resolve the producer's persisted causal rank-1 decision; never use row order as a substitute. */
export function canonicalComparativeMaterializations(store:ResearchSelectionStore){const resolved:ComparativeMaterializationTarget[]=[],unresolved:string[]=[];for(const event of store.events){for(const [configurationId,attempts] of groups(event.generationSnapshot.candidates,candidate=>generationStructuralConfiguration(candidate).id??`invalid:${candidate.candidateId}`)){const ranked=attempts.filter(candidate=>candidate.expiryRank===1),candidate=attempts.length===1?attempts[0]:ranked.length===1?ranked[0]:null;if(!candidate||configurationId.startsWith("invalid:")){unresolved.push(`${event.eventId}|${configurationId}`);continue}resolved.push({eventId:event.eventId,structuralConfigurationId:configurationId,candidateId:candidate.candidateId,attemptCandidateIds:[...new Set(attempts.map(attempt=>attempt.candidateId))].sort()})}}return{resolved:resolved.sort((a,b)=>`${a.eventId}|${a.structuralConfigurationId}`.localeCompare(`${b.eventId}|${b.structuralConfigurationId}`)),unresolved:unresolved.sort()}}

/** Pure generated-universe audit. It never mutates availability or deployable Strategy selections. */
export function previewControlledResearchMatrix(store:ResearchSelectionStore,mode:ControlledMatrixMode):MatrixPreview{
 const canonical=canonicalComparativeMaterializations(store),byCandidate=new Map(canonical.resolved.map(target=>[`${target.eventId}|${target.candidateId}`,target])),targetKeys=new Set<string>(),reasons={buffer_rule_not_applicable:0,counterpart_unselected:0,contract_unavailable:0,reference_unavailable:0,collapsed_actual_structure:0,canonical_materialization_unresolved:canonical.unresolved.length};let pairs=0,widths=0,dtes=0,collapsed=0;
 for(const event of store.events){const rows=canonical.resolved.filter(target=>target.eventId===event.eventId).flatMap(target=>{const candidate=event.generationSnapshot.candidates.find(row=>row.candidateId===target.candidateId);return candidate?[candidate]:[]}),add=(candidate:GenerationCandidateSnapshot)=>{const target=byCandidate.get(`${event.eventId}|${candidate.candidateId}`);if(target)targetKeys.add(`${target.eventId}|${target.structuralConfigurationId}`)};for(const same of groups(rows,actualKey).values())if(same.length>1){collapsed+=same.length-1;reasons.collapsed_actual_structure+=same.length-1}
  if(mode==="short_strike"||mode==="full")for(const cell of groups(rows,strikeCell).values()){const technical=cell.find(candidate=>candidate.strikeMethod==="anchor"||candidate.strikeMethod==="technical"),buffered=cell.find(candidate=>candidate.strikeMethod==="buffered");if(!buffered){if(technical)reasons.buffer_rule_not_applicable++;continue}if(!technical)continue;if(technical.status!=="priced"||buffered.status!=="priced"){reasons.contract_unavailable++;continue}add(technical);add(buffered);pairs++}
  if(mode==="width"||mode==="full")for(const ladder of groups(rows,widthCell).values()){const eligible=ladder.filter(candidate=>candidate.status==="priced");if(eligible.length>1){widths++;eligible.forEach(add)}}
  if(mode==="dte"||mode==="full")for(const ladder of groups(rows,dteCell).values()){const eligible=ladder.filter(candidate=>candidate.status==="priced");if(eligible.length>1){dtes++;eligible.forEach(add)}}
 }
 const selectedConfigurations=new Set(store.events.flatMap(event=>event.selectedStructures.flatMap(structure=>{const generated=event.generationSnapshot.candidates.find(candidate=>candidate.candidateId===structure.candidateId),configurationId=generated?generationStructuralConfiguration(generated).id:null;return configurationId?[`${event.eventId}|${configurationId}`]:[]}))),existing=new Set(store.events.flatMap(event=>(event.researchStructures??[]).filter(structure=>structure.researchRole==="comparative_economics").map(structure=>`${event.eventId}|${structure.structuralConfigurationId}`))),targets=canonical.resolved.filter(target=>targetKeys.has(`${target.eventId}|${target.structuralConfigurationId}`)&&!selectedConfigurations.has(`${target.eventId}|${target.structuralConfigurationId}`)),structuresAdded=targets.filter(target=>!existing.has(`${target.eventId}|${target.structuralConfigurationId}`)).map(target=>`${target.eventId}|${target.structuralConfigurationId}`).sort(),structuresRetained=[...existing].filter(key=>targetKeys.has(key)).sort();return{mode,generatedDenominator:store.events.reduce((count,event)=>count+event.generationSnapshot.candidates.length,0),structuresAdded,structuresRetained,structuresRemoved:[],newTechnicalBufferedPairs:pairs,newWidthLadders:widths,newDteComparisons:dtes,unavailableCounterparts:reasons,collapsedActualStructures:collapsed,estimatedRecomputeCount:structuresAdded.length,targetMaterializations:targets,unresolvedConfigurationIds:canonical.unresolved};
}

/** Validate a detached recompute before atomic persistence; selectedStructures is immutable here. */
export function confirmControlledResearchMatrix(original:ResearchSelectionStore,preview:MatrixPreview,recomputed:ResearchSelectionStore,confirmed:boolean){if(!confirmed)throw new Error("Controlled matrix materialization requires explicit user confirmation.");const denominator=(store:ResearchSelectionStore)=>store.events.reduce((count,event)=>count+event.generationSnapshot.candidates.length,0);if(denominator(original)!==preview.generatedDenominator||denominator(recomputed)!==preview.generatedDenominator)throw new Error("Generated availability denominator changed during controlled materialization.");for(const event of original.events){const next=recomputed.events.find(candidate=>candidate.eventId===event.eventId);if(!next||JSON.stringify(next.selectedStructures)!==JSON.stringify(event.selectedStructures))throw new Error("Comparative Economics materialization must not mutate selected Strategy structures.")}
 const comparative=new Map<string,ResearchOnlyStructure[]>();for(const event of recomputed.events)for(const structure of event.researchStructures??[]){if(structure.researchRole!=="comparative_economics")continue;const key=`${event.eventId}|${structure.structuralConfigurationId}`,rows=comparative.get(key)??[];rows.push(structure);comparative.set(key,rows)}for(const target of preview.targetMaterializations){const key=`${target.eventId}|${target.structuralConfigurationId}`,rows=comparative.get(key)??[];if(rows.length!==1)throw new Error(`Comparative Economics requires exactly one canonical materialization for ${key}.`);const structure=rows[0]!;if(structure.candidateId!==target.candidateId||JSON.stringify([...new Set(structure.attemptCandidateIds??[])].sort())!==JSON.stringify(target.attemptCandidateIds))throw new Error(`Comparative Economics materialization for ${key} does not match the persisted ex-ante rank-1 decision and attempt provenance.`)}return recomputed;
}
