import type {GenerationCandidateSnapshot,ResearchSelectionStore} from "./research-selections.ts";
export type ControlledMatrixMode="short_strike"|"width"|"dte"|"full";
export type MatrixReason="buffer_rule_not_applicable"|"counterpart_unselected"|"contract_unavailable"|"reference_unavailable"|"collapsed_actual_structure"|"complete";
export interface MatrixPreview {mode:ControlledMatrixMode;generatedDenominator:number;structuresAdded:string[];structuresRetained:string[];structuresRemoved:string[];newTechnicalBufferedPairs:number;newWidthLadders:number;newDteComparisons:number;unavailableCounterparts:Record<Exclude<MatrixReason,"complete">,number>;collapsedActualStructures:number;estimatedRecomputeCount:number;targetCandidateIds:string[]}
const actualKey=(c:GenerationCandidateSnapshot)=>[c.actualExpiryTimestamp,c.optionType,c.actualStrikes.short,c.actualStrikes.long].join("~");
const strikeCell=(c:GenerationCandidateSnapshot)=>[c.actualExpiryTimestamp,c.optionType,c.actualStrikes.width,c.structure].join("~");
const widthCell=(c:GenerationCandidateSnapshot)=>[c.actualExpiryTimestamp,c.optionType,c.actualStrikes.short,c.strikeMethod,c.structure].join("~");
const dteCell=(c:GenerationCandidateSnapshot)=>[c.optionType,c.actualStrikes.short,c.actualStrikes.width,c.strikeMethod,c.structure].join("~");
const groups=(rows:GenerationCandidateSnapshot[],key:(c:GenerationCandidateSnapshot)=>string)=>{const m=new Map<string,GenerationCandidateSnapshot[]>();for(const c of rows)m.set(key(c),[...(m.get(key(c))??[]),c]);return m};
/** Pure generated-universe audit. It never mutates availability and never uses margin as an eligibility filter. */
export function previewControlledResearchMatrix(store:ResearchSelectionStore,mode:ControlledMatrixMode):MatrixPreview{
 const selected=new Set(store.events.flatMap(e=>e.selectedStructures.map(s=>s.candidateId))),target=new Set(selected),reasons={buffer_rule_not_applicable:0,counterpart_unselected:0,contract_unavailable:0,reference_unavailable:0,collapsed_actual_structure:0};let pairs=0,widths=0,dtes=0,collapsed=0;
 for(const event of store.events){const rows=event.generationSnapshot.candidates,byActual=groups(rows,actualKey);for(const same of byActual.values())if(same.length>1){collapsed+=same.length-1;reasons.collapsed_actual_structure+=same.length-1;}
  if(mode==="short_strike"||mode==="full")for(const cell of groups(rows,strikeCell).values()){const technical=cell.find(c=>c.strikeMethod==="anchor"||c.strikeMethod==="technical"),buffered=cell.find(c=>c.strikeMethod==="buffered");if(!buffered){if(technical)reasons.buffer_rule_not_applicable++;continue}if(!technical)continue;if(technical.status!=="priced"||buffered.status!=="priced"){reasons.contract_unavailable++;continue}const ids=[technical.candidateId,buffered.candidateId];if(ids.some(id=>!selected.has(id)))reasons.counterpart_unselected++;ids.forEach(id=>target.add(id));pairs++;}
  if(mode==="width"||mode==="full")for(const ladder of groups(rows,widthCell).values()){const eligible=[...new Map(ladder.filter(c=>c.status==="priced").map(c=>[actualKey(c),c])).values()];if(eligible.length>1){widths++;eligible.forEach(c=>target.add(c.candidateId));}}
  if(mode==="dte"||mode==="full")for(const ladder of groups(rows,dteCell).values()){const eligible=[...new Map(ladder.filter(c=>c.status==="priced").map(c=>[c.actualExpiryTimestamp,c])).values()];if(eligible.length>1){dtes++;eligible.forEach(c=>target.add(c.candidateId));}}
 }
 const structuresAdded=[...target].filter(x=>!selected.has(x)).sort(),structuresRetained=[...selected].sort();return{mode,generatedDenominator:store.events.reduce((n,e)=>n+e.generationSnapshot.candidates.length,0),structuresAdded,structuresRetained,structuresRemoved:[],newTechnicalBufferedPairs:pairs,newWidthLadders:widths,newDteComparisons:dtes,unavailableCounterparts:reasons,collapsedActualStructures:collapsed,estimatedRecomputeCount:structuresAdded.length,targetCandidateIds:[...target].sort()};
}
/** Confirmation is deliberately explicit. The caller supplies a detached fully recomputed store; this function validates denominator and target selection before returning it for atomic persistence. */
export function confirmControlledResearchMatrix(original:ResearchSelectionStore,preview:MatrixPreview,recomputed:ResearchSelectionStore,confirmed:boolean){if(!confirmed)throw new Error("Controlled matrix selection requires explicit user confirmation.");const denominator=(s:ResearchSelectionStore)=>s.events.reduce((n,e)=>n+e.generationSnapshot.candidates.length,0);if(denominator(original)!==preview.generatedDenominator||denominator(recomputed)!==preview.generatedDenominator)throw new Error("Generated availability denominator changed during controlled selection.");const actual=new Set(recomputed.events.flatMap(e=>e.selectedStructures.map(s=>s.candidateId)));if(preview.targetCandidateIds.some(id=>!actual.has(id)))throw new Error("Detached recompute is incomplete; atomic save refused.");return recomputed;}
