import { aggregateRoutedFees, calculateOptionFee, STANDARD_INVERSE_BTC_OPTION_FEE, type ExecutionRoute } from "./accounting.ts";
import type { BacktestEvent, Candle, ContractSeries, ContractTrade, QualityFlag, RetrievedSpread } from "./backtester.ts";
import { INVERSE_OPTION_MODEL, priceInverseOption } from "./inverse-option-pricing.ts";

export const RESEARCH_METHODOLOGY_VERSION = "simple-model-reconstruction/1.0.0";
export const RESEARCH_ESTIMATE_DISCLAIMER = "Theoretical estimate; not an actual or confirmed fill and not proof that the requested size could execute.";
export const MODEL_TOOLTIP = "The model reprices each exact option at the target BTC index using its nearest observed implied volatility. It estimates a theoretical mark, not an executable historical quote.";
export const FORWARD_ASSUMPTION = "Forward unavailable — using forward = index and rate = 0";
export const RESEARCH_WINDOWS_MINUTES = [30, 60, 120] as const;
export type PricingAssumption = "research-estimate" | "conservative-tape-check";
export type EstimateQuality = QualityFlag | "unavailable";
export type ResearchPriceSource = "direct-vwap" | "model-reconstructed";
export type ModelIvSource = "local-observed-IV" | "constant-entry-IV" | "intrinsic-at-expiry" | "unavailable";
export type PathUnavailableReason = "missing-target-index" | "missing-short-entry-iv" | "missing-long-entry-iv" | "short-model-input-invalid" | "long-model-input-invalid" | "model-output-invalid" | "after-expiry" | "contract-unresolved";
export interface ResolvedUnderlyingIndex { index:number; sourceCandleTimestamp:number; lookupMethod:"exact-timestamp"|"containing-candle"|"preceding-completed-candle"; distanceMs:number }

export function expiryWeekday(expiryTimestamp:number){return new Intl.DateTimeFormat("en-US",{weekday:"long",timeZone:"UTC"}).format(new Date(expiryTimestamp));}
export function isFridayExpiry(expiryTimestamp:number){return new Date(expiryTimestamp).getUTCDay()===5;}
export function formatExpiryWithFriday(expiryTimestamp:number|undefined,label?:string){if(expiryTimestamp===undefined)return label??"—";const date=label??new Date(expiryTimestamp).toISOString().slice(0,10);return `${date}${isFridayExpiry(expiryTimestamp)?" · FRI":""}`;}

/** Resolve the close/index used by the trigger engine from hourly open/close keyed candles. */
export function resolveUnderlyingIndex(candles:Candle[],targetTimestamp:number):ResolvedUnderlyingIndex|undefined{
 const ordered=[...candles].filter(c=>Number.isFinite(c.close)&&c.close>0).sort((a,b)=>a.openTime-b.openTime);
 const exact=ordered.find(c=>c.openTime===targetTimestamp||c.closeTime===targetTimestamp);
 if(exact)return{index:exact.close,sourceCandleTimestamp:exact.openTime===targetTimestamp?exact.openTime:exact.closeTime,lookupMethod:"exact-timestamp",distanceMs:0};
 const containing=ordered.find(c=>c.openTime<=targetTimestamp&&targetTimestamp<c.closeTime);
 if(containing)return{index:containing.close,sourceCandleTimestamp:containing.openTime,lookupMethod:"containing-candle",distanceMs:targetTimestamp-containing.openTime};
 const preceding=ordered.filter(c=>c.closeTime<=targetTimestamp).at(-1);if(!preceding)return;
 const interval=Math.max(1,preceding.closeTime-preceding.openTime);const distance=targetTimestamp-preceding.closeTime;
 return distance<=interval?{index:preceding.close,sourceCandleTimestamp:preceding.closeTime,lookupMethod:"preceding-completed-candle",distanceMs:distance}:undefined;
}

export interface ModelEvidence { instrument:string; strike:number; optionType:"C"|"P"; anchorTimestamp:number; anchorIvApiPercent:number; anchorIvDecimal:number; anchorIndex:number; targetIndex:number; dte:number; forwardPrice:number; rate:number; forwardRateAssumption:string; modelPriceBtc:number; modelName:string }
export interface ResearchLegEstimate { instrumentName:string; economicSide:"sold"|"bought"; priceBtcPerContract:number; unslippedPriceBtcPerContract:number; source:ResearchPriceSource; supportingTrades:ContractTrade[]; supportingTimestamps:number[]; observedAmount:number; nearestGapMinutes:number; model?:ModelEvidence }
export interface ResearchEstimate { valuationMode:"research-estimate"; targetTimestamp:number; valuationTimestamp:number; status:"priced"; sold:ResearchLegEstimate; bought:ResearchLegEstimate; grossSpreadBtcPerContract:number; grossSpreadBtc:number; openingFeesBtc:number; netOpeningCashFlowBtc:number; amount:number; evidenceWindowMinutes:30|60|120|720; synchronizationGapMinutes:number; priceSource:ResearchPriceSource; estimateQuality:QualityFlag; qualityReason:string; slippageBps:number; observedAmount:number; observedAmountToRequestedRatio:number; rawStaleComparison?:{soldTimestamp:number;boughtTimestamp:number;synchronizationGapMinutes:number;soldPriceBtc:number;boughtPriceBtc:number}; liquidityWarning?:string; amountStepWarning?:string; disclaimer:string }
export interface UnavailableResearchEstimate { valuationMode:"research-estimate";targetTimestamp:number;status:"unavailable";estimateQuality:"unavailable";reason:string;disclaimer:string }
export type ResearchValuation=ResearchEstimate|UnavailableResearchEstimate;
export interface EstimatedPathPoint { timestamp:number;status:"priced"|"missing";targetIndex?:number;indexResolution?:ResolvedUnderlyingIndex;unavailableReason?:PathUnavailableReason;rawEstimate?:ResearchEstimate;modelEstimate?:ResearchEstimate;/** compatibility alias */ivNormalizedEstimate?:ResearchEstimate;ivSource?:ModelIvSource;soldIvSource?:ModelIvSource;longIvSource?:ModelIvSource;estimatedNetPnlBtc?:number;estimateQuality:EstimateQuality }
export interface EstimatedOutcome { label:string;trigger:string;decisionTimestamp?:number;valuationTimestamp?:number;targetIndex?:number;evidenceSource?:string;evidenceReason?:string;ivSource?:ModelIvSource;estimate?:ResearchEstimate;rawEstimate?:number;modelEstimate?:number;feesBtc?:number;estimatedNetPnl?:number;estimateQuality:EstimateQuality;status:"estimated"|"not-hit"|"unavailable" }

function weighted(rows:ContractTrade[],pick:(row:ContractTrade)=>number){const amount=rows.reduce((sum,row)=>sum+row.amount,0);return amount>0?rows.reduce((sum,row)=>sum+pick(row)*row.amount,0)/amount:undefined;}
function directLeg(series:ContractSeries,target:number,minutes:number,side:"sold"|"bought",slippageBps:number):ResearchLegEstimate|undefined{const rows=series.trades.filter(t=>Math.abs(t.timestamp-target)<=minutes*60_000&&t.amount>0&&t.price>=0);const raw=weighted(rows,r=>r.price);if(raw===undefined)return;const factor=side==="sold"?1-slippageBps/10_000:1+slippageBps/10_000;return{instrumentName:series.instrumentName,economicSide:side,priceBtcPerContract:raw*factor,unslippedPriceBtcPerContract:raw,source:"direct-vwap",supportingTrades:rows,supportingTimestamps:rows.map(r=>r.timestamp),observedAmount:rows.reduce((s,r)=>s+r.amount,0),nearestGapMinutes:Math.min(...rows.map(r=>Math.abs(r.timestamp-target)/60_000))};}

/** Exact-series selection with deterministic distance, earlier timestamp, then stable id tie-breaks. */
export function selectIvAnchor(series:ContractSeries,target:number):ContractTrade|undefined{return series.trades.filter(t=>t.instrumentName===series.instrumentName&&Math.abs(t.timestamp-target)<=720*60_000&&t.ivDecimal!==undefined&&t.ivDecimal>0&&Number.isFinite(t.ivDecimal)&&t.indexPrice>0&&Number.isFinite(t.indexPrice)).sort((a,b)=>Math.abs(a.timestamp-target)-Math.abs(b.timestamp-target)||a.timestamp-b.timestamp||(a.tradeId??"").localeCompare(b.tradeId??""))[0];}
function modelLeg(series:ContractSeries,target:number,targetIndex:number,side:"sold"|"bought",slippageBps:number,anchorOverride?:ContractTrade):ResearchLegEstimate|undefined{const anchor=anchorOverride??selectIvAnchor(series,target);if(!anchor?.ivDecimal)return;const result=priceInverseOption({optionType:series.optionType==="C"?"call":"put",indexPrice:targetIndex,strike:series.strike,valuationTimestamp:target,expiryTimestamp:series.expiryTimestamp,ivDecimal:anchor.ivDecimal});if(result.status==="unavailable")return;const factor=side==="sold"?1-slippageBps/10_000:1+slippageBps/10_000;return{instrumentName:series.instrumentName,economicSide:side,priceBtcPerContract:result.priceBtc*factor,unslippedPriceBtcPerContract:result.priceBtc,source:"model-reconstructed",supportingTrades:[anchor],supportingTimestamps:[anchor.timestamp],observedAmount:anchor.amount,nearestGapMinutes:Math.abs(anchor.timestamp-target)/60_000,model:{instrument:series.instrumentName,strike:series.strike,optionType:series.optionType,anchorTimestamp:anchor.timestamp,anchorIvApiPercent:anchor.ivApiPercent??anchor.ivDecimal*100,anchorIvDecimal:anchor.ivDecimal,anchorIndex:anchor.indexPrice,targetIndex,dte:result.timeYears*365,forwardPrice:result.forwardPrice,rate:result.rate,forwardRateAssumption:FORWARD_ASSUMPTION,modelPriceBtc:result.priceBtc,modelName:INVERSE_OPTION_MODEL}};}
function retainModelAnchor(leg:ResearchLegEstimate,series:ContractSeries,target:number,targetIndex:number){
 const anchor=selectIvAnchor(series,target);if(!anchor?.ivDecimal)return leg;
 const modeled=modelLeg(series,target,targetIndex,leg.economicSide,0,anchor);
 return modeled?.model?{...leg,model:modeled.model}:leg;
}
function unavailable(targetTimestamp:number,reason:string):UnavailableResearchEstimate{return{valuationMode:"research-estimate",targetTimestamp,status:"unavailable",estimateQuality:"unavailable",reason,disclaimer:RESEARCH_ESTIMATE_DISCLAIMER};}
function nearestRaw(series:ContractSeries,target:number){return [...series.trades].sort((a,b)=>Math.abs(a.timestamp-target)-Math.abs(b.timestamp-target)||a.timestamp-b.timestamp||(a.tradeId??"").localeCompare(b.tradeId??""))[0];}
function assemble(input:{spread:RetrievedSpread;targetTimestamp:number;amount:number;slippageBps:number;executionRoute?:ExecutionRoute;sold:ResearchLegEstimate;bought:ResearchLegEstimate;window:30|60|120|720;quality:QualityFlag;reason:string;rawStaleComparison?:ResearchEstimate["rawStaleComparison"]}):ResearchEstimate{const {sold,bought}=input;const route=input.executionRoute??"synchronized-leg-proxy";const fees=aggregateRoutedFees([{side:"sell",fee:calculateOptionFee(sold.priceBtcPerContract,input.amount,"taker",STANDARD_INVERSE_BTC_OPTION_FEE)},{side:"buy",fee:calculateOptionFee(bought.priceBtcPerContract,input.amount,"taker",STANDARD_INVERSE_BTC_OPTION_FEE)}],route).finalFee;const per=sold.priceBtcPerContract-bought.priceBtcPerContract,observed=Math.min(sold.observedAmount,bought.observedAmount);return{valuationMode:"research-estimate",targetTimestamp:input.targetTimestamp,valuationTimestamp:input.targetTimestamp,status:"priced",sold,bought,grossSpreadBtcPerContract:per,grossSpreadBtc:per*input.amount,openingFeesBtc:fees,netOpeningCashFlowBtc:per*input.amount-fees,amount:input.amount,evidenceWindowMinutes:input.window,synchronizationGapMinutes:Math.abs(sold.supportingTimestamps[0]-bought.supportingTimestamps[0])/60_000,priceSource:sold.source==="direct-vwap"&&bought.source==="direct-vwap"?"direct-vwap":"model-reconstructed",estimateQuality:input.quality,qualityReason:input.reason,slippageBps:input.slippageBps,observedAmount:observed,observedAmountToRequestedRatio:observed/input.amount,rawStaleComparison:input.rawStaleComparison,liquidityWarning:observed<input.amount?"Historical tape does not prove execution of this size.":undefined,amountStepWarning:(!input.spread.soldContract?.amountMetadata||!input.spread.boughtContract?.amountMetadata)?"Exchange increment validation was unavailable; this research scenario is not claimed to be exchange-valid.":undefined,disclaimer:RESEARCH_ESTIMATE_DISCLAIMER};}

export function estimateResearchSpread(input:{spread:RetrievedSpread;targetTimestamp:number;targetIndex:number;amount?:number;slippageBps:number;executionRoute?:ExecutionRoute}):ResearchValuation{const amount=input.amount??1,{spread,targetTimestamp,slippageBps}=input;if(!Number.isFinite(amount)||amount<=0||!Number.isFinite(slippageBps)||slippageBps<0||!Number.isFinite(input.targetIndex)||input.targetIndex<=0)return unavailable(targetTimestamp,"Essential numerical inputs are invalid.");if(spread.dataStatus==="data-unavailable"||spread.retrievalStatus==="partial"||!spread.soldContract||!spread.boughtContract||spread.retrievalStatus!=="ready")return unavailable(targetTimestamp,"Both exact contracts must be resolved.");for(const window of RESEARCH_WINDOWS_MINUTES){const directSold=directLeg(spread.soldContract,targetTimestamp,window,"sold",slippageBps),directBought=directLeg(spread.boughtContract,targetTimestamp,window,"bought",slippageBps);if(directSold&&directBought){const sold=retainModelAnchor(directSold,spread.soldContract,targetTimestamp,input.targetIndex),bought=retainModelAnchor(directBought,spread.boughtContract,targetTimestamp,input.targetIndex);const sync=Math.abs(sold.supportingTimestamps[0]-bought.supportingTimestamps[0])/60_000;const quality:QualityFlag=window===30&&sync<=30?"green":window<=120&&sync<=120?"yellow":"red";return assemble({...input,amount,sold,bought,window,quality,reason:quality==="green"?"Both legs use synchronized direct trades within ±30 minutes.":"Both legs use bounded direct trades within ±2 hours."});}}
 const sold=modelLeg(spread.soldContract,targetTimestamp,input.targetIndex,"sold",slippageBps),bought=modelLeg(spread.boughtContract,targetTimestamp,input.targetIndex,"bought",slippageBps);if(!sold||!bought)return unavailable(targetTimestamp,"Either exact leg lacks a valid IV/index anchor within ±12 hours.");const rawSold=nearestRaw(spread.soldContract,targetTimestamp),rawBought=nearestRaw(spread.boughtContract,targetTimestamp);const rawStaleComparison=rawSold&&rawBought?{soldTimestamp:rawSold.timestamp,boughtTimestamp:rawBought.timestamp,synchronizationGapMinutes:Math.abs(rawSold.timestamp-rawBought.timestamp)/60_000,soldPriceBtc:rawSold.price,boughtPriceBtc:rawBought.price}:undefined;return assemble({...input,amount,sold,bought,window:720,quality:"red",reason:"Exact contracts were synchronized by theoretical reconstruction from bounded IV anchors; quality remains Red.",rawStaleComparison});}

function modelMark(input:{spread:RetrievedSpread;timestamp:number;index:number;entry:ResearchEstimate;slippageBps:number;executionRoute?:ExecutionRoute}):{estimate?:ResearchEstimate;source:ModelIvSource;soldSource:ModelIvSource;longSource:ModelIvSource;reason?:PathUnavailableReason}{const {spread,timestamp,index,entry}=input;if(!spread.soldContract||!spread.boughtContract)return{source:"unavailable",soldSource:"unavailable",longSource:"unavailable",reason:"contract-unresolved"};if(timestamp>spread.soldContract.expiryTimestamp)return{source:"unavailable",soldSource:"unavailable",longSource:"unavailable",reason:"after-expiry"};const expired=timestamp===spread.soldContract.expiryTimestamp;let soldAnchor=selectIvAnchor(spread.soldContract,timestamp),boughtAnchor=selectIvAnchor(spread.boughtContract,timestamp);let soldSource:ModelIvSource=soldAnchor?"local-observed-IV":"constant-entry-IV",longSource:ModelIvSource=boughtAnchor?"local-observed-IV":"constant-entry-IV";if(!soldAnchor&&entry.sold.model)soldAnchor={...entry.sold.supportingTrades[0],timestamp:entry.sold.model.anchorTimestamp,indexPrice:entry.sold.model.anchorIndex,ivDecimal:entry.sold.model.anchorIvDecimal,ivApiPercent:entry.sold.model.anchorIvApiPercent,instrumentName:entry.sold.model.instrument};if(!boughtAnchor&&entry.bought.model)boughtAnchor={...entry.bought.supportingTrades[0],timestamp:entry.bought.model.anchorTimestamp,indexPrice:entry.bought.model.anchorIndex,ivDecimal:entry.bought.model.anchorIvDecimal,ivApiPercent:entry.bought.model.anchorIvApiPercent,instrumentName:entry.bought.model.instrument};if(!soldAnchor?.ivDecimal)return{source:"unavailable",soldSource,longSource,reason:"missing-short-entry-iv"};if(!boughtAnchor?.ivDecimal)return{source:"unavailable",soldSource,longSource,reason:"missing-long-entry-iv"};if(expired){soldSource=longSource="intrinsic-at-expiry";}const sold=modelLeg(spread.soldContract,timestamp,index,"bought",input.slippageBps,soldAnchor);if(!sold)return{source:"unavailable",soldSource,longSource,reason:"short-model-input-invalid"};const bought=modelLeg(spread.boughtContract,timestamp,index,"sold",input.slippageBps,boughtAnchor);if(!bought)return{source:"unavailable",soldSource,longSource,reason:"long-model-input-invalid"};const source:ModelIvSource=expired?"intrinsic-at-expiry":soldSource===longSource?soldSource:"local-observed-IV";return{source,soldSource,longSource,estimate:assemble({...input,targetTimestamp:timestamp,amount:entry.amount,sold,bought,window:720,quality:"red",reason:expired?"Intrinsic value at expiry.":`${soldSource} short; ${longSource} long.`})};}
export function buildEstimatedPath(input:{spread:RetrievedSpread;timestamps:number[];indexAt?:(timestamp:number)=>number|undefined;candles?:Candle[];entry:ResearchEstimate;slippageBps:number;executionRoute?:ExecutionRoute}):EstimatedPathPoint[]{const expiry=input.spread.expiryTimestamp;return [...new Set(input.timestamps)].filter(t=>expiry===undefined||t<=expiry).sort((a,b)=>a-b).map(timestamp=>{const resolution=input.candles?resolveUnderlyingIndex(input.candles,timestamp):undefined;const index=timestamp===expiry&&input.spread.deliveryPrice!==undefined?input.spread.deliveryPrice:resolution?.index??input.indexAt?.(timestamp);if(index===undefined||!Number.isFinite(index)||index<=0)return{timestamp,status:"missing",unavailableReason:"missing-target-index",ivSource:"unavailable",estimateQuality:"unavailable"};const modeled=modelMark({...input,timestamp,index});if(!modeled.estimate)return{timestamp,targetIndex:index,indexResolution:resolution,status:"missing",unavailableReason:modeled.reason??"model-output-invalid",ivSource:"unavailable",soldIvSource:modeled.soldSource,longIvSource:modeled.longSource,estimateQuality:"unavailable"};const mark=modeled.estimate,closingGross=(mark.bought.priceBtcPerContract-mark.sold.priceBtcPerContract)*mark.amount,pnl=input.entry.netOpeningCashFlowBtc+closingGross-mark.openingFeesBtc;return{timestamp,targetIndex:index,indexResolution:resolution,status:"priced",modelEstimate:mark,ivNormalizedEstimate:mark,ivSource:modeled.source,soldIvSource:modeled.soldSource,longIvSource:modeled.longSource,estimatedNetPnlBtc:pnl,estimateQuality:"red"};});}
export function researchOutcomeAt(label:string,trigger:string,timestamp:number|undefined,path:EstimatedPathPoint[]):EstimatedOutcome{if(timestamp===undefined)return{label,trigger,status:"unavailable",estimateQuality:"unavailable",evidenceSource:"unavailable",evidenceReason:"The bounded trigger timestamp is missing."};const point=[...path].filter(p=>p.timestamp>=timestamp).sort((a,b)=>a.timestamp-b.timestamp)[0];if(!point||point.status!=="priced"||point.estimatedNetPnlBtc===undefined)return{label,trigger,decisionTimestamp:timestamp,valuationTimestamp:point?.timestamp,status:"unavailable",estimateQuality:"unavailable",evidenceSource:"unavailable",evidenceReason:"No model valuation is available at or after this outcome timestamp."};const estimate=point.rawEstimate??point.modelEstimate??point.ivNormalizedEstimate;return{label,trigger,decisionTimestamp:timestamp,valuationTimestamp:point.timestamp,targetIndex:point.targetIndex,status:"estimated",estimateQuality:point.estimateQuality,evidenceSource:estimate?.priceSource,evidenceReason:estimate?.qualityReason,ivSource:point.ivSource,estimate,modelEstimate:estimate?.grossSpreadBtc,feesBtc:estimate?.openingFeesBtc,estimatedNetPnl:point.estimatedNetPnlBtc};}
export function buildResearchOutcomes(input:{event:BacktestEvent;spread:RetrievedSpread;entry:ResearchEstimate;path:EstimatedPathPoint[];candles:Candle[]}):EstimatedOutcome[]{const {event,spread,entry,path,candles}=input,start=entry.targetTimestamp;const priced=path.filter(p=>p.status==="priced"&&p.estimatedNetPnlBtc!==undefined);const capture=(threshold:number)=>priced.find(point=>{const estimate=point.rawEstimate??point.modelEstimate??point.ivNormalizedEstimate;if(!estimate||entry.grossSpreadBtc<=0)return false;return(entry.grossSpreadBtc+(estimate.bought.priceBtcPerContract-estimate.sold.priceBtcPerContract)*entry.amount)/entry.grossSpreadBtc>=threshold;});const invalidation=event.invalidationPrice===undefined?undefined:completedCandleTrigger(candles,start,c=>event.direction==="long"?c.close<event.invalidationPrice!:c.close>event.invalidationPrice!);const fixed=(days:number)=>{const timestamp=start+days*864e5;return spread.expiryTimestamp!==undefined&&timestamp>spread.expiryTimestamp?{label:`${days}D`,trigger:`${days} days after entry`,decisionTimestamp:timestamp,status:"unavailable" as const,estimateQuality:"unavailable" as const,evidenceSource:"unavailable",evidenceReason:"Target occurs after contract expiry."}:researchOutcomeAt(`${days}D`,`${days} days after entry`,timestamp,path);};const outcomes=[researchOutcomeAt("VPOC","Bundled VPOC timestamp",event.vpocTimestamp,path),researchOutcomeAt("50% credit","First bounded mark at 50% credit capture",capture(.5)?.timestamp,path),researchOutcomeAt("70% credit","First bounded mark at 70% credit capture",capture(.7)?.timestamp,path),fixed(3),fixed(5),fixed(7),researchOutcomeAt("Invalidation","First completed 1H candle beyond invalidation",invalidation?.closeTime,path)];const expiry=spread.expiryTimestamp;if(expiry===undefined||spread.deliveryPrice===undefined||!spread.soldContract||!spread.boughtContract)return[...outcomes,{label:"Settlement",trigger:"Deribit delivery price",decisionTimestamp:expiry,status:"unavailable",estimateQuality:"unavailable",evidenceSource:"unavailable",evidenceReason:"Resolved contracts and delivery price are required."}];const intrinsic=(s:ContractSeries)=>s.optionType==="C"?Math.max(spread.deliveryPrice!-s.strike,0)/spread.deliveryPrice!:Math.max(s.strike-spread.deliveryPrice!,0)/spread.deliveryPrice!;return[...outcomes,{label:"Settlement",trigger:"Deribit delivery price",decisionTimestamp:expiry,valuationTimestamp:expiry,targetIndex:spread.deliveryPrice,status:"estimated",estimateQuality:"green",ivSource:"intrinsic-at-expiry",evidenceSource:"deribit-delivery-price",evidenceReason:`Versioned intrinsic settlement at ${spread.deliveryPrice}.`,estimatedNetPnl:entry.netOpeningCashFlowBtc+(intrinsic(spread.boughtContract)-intrinsic(spread.soldContract))*entry.amount}];}
export function scaleResearchEstimate(entry:ResearchEstimate,amount:number,executionRoute?:ExecutionRoute):ResearchEstimate{const fees=aggregateRoutedFees([{side:"sell",fee:calculateOptionFee(entry.sold.priceBtcPerContract,amount,"taker",STANDARD_INVERSE_BTC_OPTION_FEE)},{side:"buy",fee:calculateOptionFee(entry.bought.priceBtcPerContract,amount,"taker",STANDARD_INVERSE_BTC_OPTION_FEE)}],executionRoute??"synchronized-leg-proxy").finalFee,gross=entry.grossSpreadBtcPerContract*amount;return{...entry,amount,grossSpreadBtc:gross,openingFeesBtc:fees,netOpeningCashFlowBtc:gross-fees,observedAmountToRequestedRatio:entry.observedAmount/amount,liquidityWarning:entry.observedAmount<amount?"Historical tape does not prove execution of this size.":undefined};}
export function scaleResearchPath(path:EstimatedPathPoint[],entry:ResearchEstimate,amount:number,executionRoute?:ExecutionRoute):EstimatedPathPoint[]{const scaledEntry=scaleResearchEstimate(entry,amount,executionRoute);return path.map(point=>{const mark=point.rawEstimate??point.modelEstimate??point.ivNormalizedEstimate;if(point.status!=="priced"||!mark)return{...point,estimatedNetPnlBtc:undefined};const scaled=scaleResearchEstimate(mark,amount,executionRoute),closing=(scaled.bought.priceBtcPerContract-scaled.sold.priceBtcPerContract)*amount;return{...point,rawEstimate:point.rawEstimate?scaled:undefined,modelEstimate:point.modelEstimate?scaled:undefined,ivNormalizedEstimate:point.ivNormalizedEstimate?scaled:undefined,estimatedNetPnlBtc:scaledEntry.netOpeningCashFlowBtc+closing-scaled.openingFeesBtc};});}
export function completedCandleTrigger(candles:Candle[],after:number,predicate:(c:Candle)=>boolean){return[...candles].sort((a,b)=>a.closeTime-b.closeTime).find(c=>c.closeTime>after&&predicate(c));}
export function buildResearchExport(input:{event:BacktestEvent;spread:RetrievedSpread;entry:ResearchValuation;path?:EstimatedPathPoint[];outcomes?:EstimatedOutcome[]}){return{methodology:{version:RESEARCH_METHODOLOGY_VERSION,pricingModel:INVERSE_OPTION_MODEL,formulaConvention:"Deribit inverse-option Black–Scholes; USD theoretical value divided by target BTC index",ivUnits:{api:"percent",internal:"ivDecimal"},hierarchy:["direct amount-weighted VWAP in ±30 minutes","direct amount-weighted VWAP in ±1 hour","direct amount-weighted VWAP in ±2 hours","model-reconstructed exact-contract price using IV anchors within ±12 hours"],forwardRateAssumption:FORWARD_ASSUMPTION,missingPointPolicy:"constant-entry-IV after entry; unavailable when index or entry IV is missing"},mode:"research-estimate" as const,eventId:input.event.id,expiryWeekday:input.spread.expiryTimestamp===undefined?undefined:expiryWeekday(input.spread.expiryTimestamp),isFridayExpiry:input.spread.expiryTimestamp===undefined?false:isFridayExpiry(input.spread.expiryTimestamp),contracts:{sold:input.spread.soldContract?.instrumentName,bought:input.spread.boughtContract?.instrumentName,soldStrike:input.spread.soldContract?.strike,boughtStrike:input.spread.boughtContract?.strike,expiryTimestamp:input.spread.expiryTimestamp,expiryWeekday:input.spread.expiryTimestamp===undefined?undefined:expiryWeekday(input.spread.expiryTimestamp),isFridayExpiry:input.spread.expiryTimestamp===undefined?false:isFridayExpiry(input.spread.expiryTimestamp)},windowsUsed:input.entry.status==="priced"?[input.entry.evidenceWindowMinutes]:[],priceSource:input.entry.status==="priced"?input.entry.priceSource:"unavailable",modelEvidence:input.entry.status==="priced"?{sold:input.entry.sold.model,bought:input.entry.bought.model}:undefined,quality:input.entry.estimateQuality,slippageAssumptionBps:input.entry.status==="priced"?input.entry.slippageBps:undefined,feesBtc:input.entry.status==="priced"?input.entry.openingFeesBtc:undefined,sourceClassification:input.entry.status==="priced"?input.entry.priceSource:"unavailable",estimateDisclaimer:RESEARCH_ESTIMATE_DISCLAIMER,estimatedEntry:input.entry,estimatedPath:input.path??[],estimatedOutcomes:input.outcomes??[]};}
