import {canonicalJson,comparativeMaterializationId,generationAttemptIdentity,generationStructuralConfiguration,unavailableResearchStructure,type GenerationCandidateSnapshot,type ResearchOnlyStructure,type ResearchSelectionStore,type SelectedStructure} from "./research-selections.ts";

export type ControlledMatrixMode="short_strike"|"width"|"dte"|"full";
export type MatrixReason="buffer_rule_not_applicable"|"counterpart_unselected"|"contract_unavailable"|"reference_unavailable"|"collapsed_actual_structure"|"canonical_materialization_unresolved"|"complete";
export interface ComparativeMaterializationTarget {eventId:string;structuralConfigurationId:string;candidateId:string;generationAttemptIdentities:string[]}
export interface MatrixPreview {mode:ControlledMatrixMode;generatedDenominator:number;structuresAdded:string[];structuresRetained:string[];structuresRemoved:string[];newTechnicalBufferedPairs:number;newWidthLadders:number;newDteComparisons:number;unavailableCounterparts:Record<Exclude<MatrixReason,"complete">,number>;collapsedActualStructures:number;estimatedRecomputeCount:number;targetMaterializations:ComparativeMaterializationTarget[];unresolvedConfigurationIds:string[]}

interface ProducerStructuralFingerprint {candidateId:string;venue:string;quantity:number|null;optionType:unknown;structure:unknown;targetDte:unknown;expiryTimestamp:unknown;shortStrike:unknown;longStrike:unknown;actualWidth:unknown}
const producerFingerprint=(row:SelectedStructure):ProducerStructuralFingerprint=>{const snapshot=row.candidateSnapshot as Record<string,unknown>|undefined;return{candidateId:row.candidateId,venue:row.venue,quantity:typeof row.quantity==="number"?row.quantity:null,optionType:snapshot?.optionType,structure:snapshot?.structure,targetDte:snapshot?.targetDte,expiryTimestamp:snapshot?.expiryTimestamp,shortStrike:snapshot?.shortStrike,longStrike:snapshot?.longStrike,actualWidth:snapshot?.actualWidth}};
const generatedFingerprint=(candidate:GenerationCandidateSnapshot,quantity:number):ProducerStructuralFingerprint=>({candidateId:candidate.candidateId,venue:candidate.venue,quantity,optionType:candidate.optionType,structure:candidate.structure,targetDte:candidate.targetHorizon,expiryTimestamp:candidate.actualExpiryTimestamp,shortStrike:candidate.actualStrikes.short,longStrike:candidate.actualStrikes.long,actualWidth:candidate.actualStrikes.width});
const fingerprintDifferences=(a:ProducerStructuralFingerprint,b:ProducerStructuralFingerprint)=>(Object.keys(a) as (keyof ProducerStructuralFingerprint)[]).filter(key=>a[key]!==b[key]);

const actualKey=(c:GenerationCandidateSnapshot)=>[c.actualExpiryTimestamp,c.optionType,c.actualStrikes.short,c.actualStrikes.long].join("~");
const strikeCell=(c:GenerationCandidateSnapshot)=>[c.actualExpiryTimestamp,c.optionType,c.actualStrikes.width,c.structure].join("~");
const widthCell=(c:GenerationCandidateSnapshot)=>[c.actualExpiryTimestamp,c.optionType,c.actualStrikes.short,c.strikeMethod,c.structure].join("~");
const dteCell=(c:GenerationCandidateSnapshot)=>[c.optionType,c.actualStrikes.short,c.actualStrikes.width,c.strikeMethod,c.structure].join("~");
const groups=(rows:readonly GenerationCandidateSnapshot[],key:(c:GenerationCandidateSnapshot)=>string)=>{const result=new Map<string,GenerationCandidateSnapshot[]>();for(const candidate of rows){const value=key(candidate);result.set(value,[...(result.get(value)??[]),candidate])}return result};

/** Resolve the producer's persisted causal rank-1 decision; never use row order as a substitute. */
export function canonicalComparativeMaterializations(store:ResearchSelectionStore){const resolved:ComparativeMaterializationTarget[]=[],unresolved:string[]=[];for(const event of store.events){for(const [configurationId,attempts] of groups(event.generationSnapshot.candidates,candidate=>generationStructuralConfiguration(candidate).id??`invalid:${candidate.candidateId}`)){const ranked=attempts.filter(candidate=>candidate.expiryRank===1),candidate=attempts.length===1?attempts[0]:ranked.length===1?ranked[0]:null;if(!candidate||configurationId.startsWith("invalid:")){unresolved.push(`${event.eventId}|${configurationId}`);continue}resolved.push({eventId:event.eventId,structuralConfigurationId:configurationId,candidateId:candidate.candidateId,generationAttemptIdentities:attempts.map(generationAttemptIdentity).sort()})}}return{resolved:resolved.sort((a,b)=>`${a.eventId}|${a.structuralConfigurationId}`.localeCompare(`${b.eventId}|${b.structuralConfigurationId}`)),unresolved:unresolved.sort()}}

/**
 * Persist the complete canonical Comparative Economics universe without
 * promoting any row into deployable Strategy selection. `evaluated` is output
 * from the existing Reference/execution engines; rank provenance alone chooses
 * which generation attempt represents a configuration.
 */
export function materializeComparativeEconomics(eventId:string,candidates:readonly GenerationCandidateSnapshot[],evaluated:readonly SelectedStructure[],quantity:number,atUtc:string,shortStrikeEvaluated:readonly SelectedStructure[]=[]):{structures:ResearchOnlyStructure[];unresolved:string[]}{
 const shell:ResearchSelectionStore={schemaVersion:"1.10.0",datasetId:"comparative-materialization",updatedAtUtc:atUtc,events:[{eventId,sourceRun:{},generationSnapshot:{generatedAtUtc:atUtc,configuration:{} as never,candidates:[...candidates],underlyingHourlyPath:[]},selectedStructures:[]}]};
 const canonical=canonicalComparativeMaterializations(shell),byCandidate=new Map<string,SelectedStructure>();
 const validate=(row:SelectedStructure)=>{const candidate=candidates.find(candidate=>candidate.candidateId===row.candidateId);if(!candidate)throw new Error(`Producer structural corruption for ${row.candidateId}: candidate is absent from the authoritative generation snapshot.`);const snapshot=row.candidateSnapshot as Record<string,unknown>|undefined,differences=fingerprintDifferences(producerFingerprint(row),generatedFingerprint(candidate,quantity)),optionalChecks:[string,unknown,unknown][]=[["strikeMethod",snapshot?.strikeMethod,candidate.strikeMethod],["targetHorizon",snapshot?.targetHorizon,candidate.targetHorizon],["requestedStrikes",snapshot?.requestedStrikes,candidate.requestedStrikes],["actualStrikes",snapshot?.actualStrikes,candidate.actualStrikes],["actualExpiryTimestamp",snapshot?.actualExpiryTimestamp,candidate.actualExpiryTimestamp]];for(const [field,persisted,generated] of optionalChecks)if(persisted!==undefined&&JSON.stringify(persisted)!==JSON.stringify(generated))differences.push(field as keyof ProducerStructuralFingerprint);if(differences.length)throw new Error(`Producer structural corruption for ${row.candidateId}: ${[...new Set(differences)].join(", ")} disagree with the authoritative generation candidate.`)};
 const normalById=new Map<string,SelectedStructure>();for(const row of evaluated){validate(row);const prior=normalById.get(row.candidateId);if(prior){const differences=fingerprintDifferences(producerFingerprint(prior),producerFingerprint(row));if(differences.length)throw new Error(`Conflicting full materialized structural identity for ${row.candidateId}: ${differences.join(", ")}.`)}normalById.set(row.candidateId,row)}
 const shortById=new Map<string,SelectedStructure>();for(const row of shortStrikeEvaluated){validate(row);const authoritative=normalById.get(row.candidateId),prior=shortById.get(row.candidateId);if(authoritative){const differences=fingerprintDifferences(producerFingerprint(authoritative),producerFingerprint(row));if(differences.length)throw new Error(`Conflicting producer structural identity for ${row.candidateId}: ${differences.join(", ")}.`)}if(prior){const differences=fingerprintDifferences(producerFingerprint(prior),producerFingerprint(row));if(differences.length)throw new Error(`Conflicting short-strike structural identity for ${row.candidateId}: ${differences.join(", ")}.`)}shortById.set(row.candidateId,row)}
 for(const [candidateId,row] of normalById)byCandidate.set(candidateId,row);for(const [candidateId,row] of shortById)if(!byCandidate.has(candidateId))byCandidate.set(candidateId,row);
 const notEvaluated={status:"not_evaluated" as const,reason:"Research-only Comparative Economics materialization; immediate maker/taker execution was not independently observed or evaluated.",entrySnapshot:null,valuationPathSnapshot:[],outcomeSnapshots:[]};
 const structures=canonical.resolved.map(target=>{const candidate=candidates.find(row=>row.candidateId===target.candidateId&&generationStructuralConfiguration(row).id===target.structuralConfigurationId)!,source=byCandidate.get(target.candidateId)??null,base=source??unavailableResearchStructure(eventId,candidate,quantity,atUtc),rawReference=base.referenceValuation,referenceValuation=rawReference?.status==="valued"||rawReference?.status==="unavailable"?rawReference:unavailableResearchStructure(eventId,candidate,quantity,atUtc).referenceValuation,reason=candidate.availabilityReasons.find(Boolean)??"Canonical Comparative Economics materialization is unavailable.";return{...base,referenceValuation,...(!source?{modeledExecution:{expected:{status:"unavailable",reasonCode:"comparative_candidate_unavailable",reason,source:"modeled_execution",modelVersion:"modeled-execution-v5-empirical-taker",entrySnapshot:null,valuationPathSnapshot:[],outcomeSnapshots:[]},conservative:{status:"unavailable",reasonCode:"comparative_candidate_unavailable",reason,source:"modeled_execution",modelVersion:"modeled-execution-v5-empirical-taker",entrySnapshot:null,valuationPathSnapshot:[],outcomeSnapshots:[]}}}:{}),selectionId:comparativeMaterializationId(eventId,target.structuralConfigurationId),selectedAtUtc:atUtc,researchRole:"comparative_economics" as const,structuralConfigurationId:target.structuralConfigurationId,generationAttemptIdentities:target.generationAttemptIdentities,executionScenarios:{maker:{...notEvaluated},taker:{...notEvaluated}},delayedExecution:undefined,marginSnapshot:null,evidenceTradeSnapshots:[],evidenceUsages:source?.evidenceUsages??[],statusLayers:canonicalJson(source?.statusLayers??null)} satisfies ResearchOnlyStructure}).map(structure=>{const {delayedExecution:_delayed,...persistable}=structure;void _delayed;return persistable}).sort((a,b)=>`${a.structuralConfigurationId}|${a.candidateId}`.localeCompare(`${b.structuralConfigurationId}|${b.candidateId}`));
 return{structures,unresolved:canonical.unresolved};
}

/** Pure generated-universe audit. It never mutates availability or deployable Strategy selections. */
export function previewControlledResearchMatrix(store:ResearchSelectionStore,mode:ControlledMatrixMode):MatrixPreview{
 const canonical=canonicalComparativeMaterializations(store),byCandidate=new Map(canonical.resolved.map(target=>[`${target.eventId}|${target.candidateId}`,target])),targetKeys=new Set<string>(),reasons={buffer_rule_not_applicable:0,counterpart_unselected:0,contract_unavailable:0,reference_unavailable:0,collapsed_actual_structure:0,canonical_materialization_unresolved:canonical.unresolved.length};let pairs=0,widths=0,dtes=0,collapsed=0;
 for(const event of store.events){const rows=canonical.resolved.filter(target=>target.eventId===event.eventId).flatMap(target=>{const candidate=event.generationSnapshot.candidates.find(row=>row.candidateId===target.candidateId);return candidate?[candidate]:[]}),add=(candidate:GenerationCandidateSnapshot)=>{const target=byCandidate.get(`${event.eventId}|${candidate.candidateId}`);if(target)targetKeys.add(`${target.eventId}|${target.structuralConfigurationId}`)};for(const same of groups(rows,actualKey).values())if(same.length>1){collapsed+=same.length-1;reasons.collapsed_actual_structure+=same.length-1}
  if(mode==="short_strike"||mode==="full")for(const cell of groups(rows,strikeCell).values()){const technical=cell.find(candidate=>candidate.strikeMethod==="anchor"||candidate.strikeMethod==="technical"),buffered=cell.find(candidate=>candidate.strikeMethod==="buffered");if(!buffered){if(technical)reasons.buffer_rule_not_applicable++;continue}if(!technical)continue;if(technical.status!=="priced"||buffered.status!=="priced"){reasons.contract_unavailable++;continue}add(technical);add(buffered);pairs++}
  if(mode==="width"||mode==="full")for(const ladder of groups(rows,widthCell).values()){const eligible=ladder.filter(candidate=>candidate.status==="priced");if(eligible.length>1){widths++;eligible.forEach(add)}}
  if(mode==="dte"||mode==="full")for(const ladder of groups(rows,dteCell).values()){const eligible=ladder.filter(candidate=>candidate.status==="priced");if(eligible.length>1){dtes++;eligible.forEach(add)}}
 }
 const selectedConfigurations=new Set(store.events.flatMap(event=>event.selectedStructures.flatMap(structure=>{const generated=event.generationSnapshot.candidates.find(candidate=>candidate.candidateId===structure.candidateId),configurationId=generated?generationStructuralConfiguration(generated).id:null;return configurationId?[`${event.eventId}|${configurationId}`]:[]}))),existing=new Set(store.events.flatMap(event=>(event.researchStructures??[]).filter(structure=>structure.researchRole==="comparative_economics").map(structure=>`${event.eventId}|${structure.structuralConfigurationId}`))),targets=canonical.resolved.filter(target=>targetKeys.has(`${target.eventId}|${target.structuralConfigurationId}`)&&!selectedConfigurations.has(`${target.eventId}|${target.structuralConfigurationId}`)),structuresAdded=targets.filter(target=>!existing.has(`${target.eventId}|${target.structuralConfigurationId}`)).map(target=>`${target.eventId}|${target.structuralConfigurationId}`).sort(),structuresRetained=[...existing].filter(key=>targetKeys.has(key)).sort();return{mode,generatedDenominator:store.events.reduce((count,event)=>count+event.generationSnapshot.candidates.length,0),structuresAdded,structuresRetained,structuresRemoved:[],newTechnicalBufferedPairs:pairs,newWidthLadders:widths,newDteComparisons:dtes,unavailableCounterparts:reasons,collapsedActualStructures:collapsed,estimatedRecomputeCount:structuresAdded.length,targetMaterializations:targets,unresolvedConfigurationIds:canonical.unresolved};
}

/** Validate a detached recompute before atomic persistence; selectedStructures is immutable here. */
export function confirmControlledResearchMatrix(original:ResearchSelectionStore,preview:MatrixPreview,recomputed:ResearchSelectionStore,confirmed:boolean){if(!confirmed)throw new Error("Controlled matrix materialization requires explicit user confirmation.");const denominator=(store:ResearchSelectionStore)=>store.events.reduce((count,event)=>count+event.generationSnapshot.candidates.length,0);if(denominator(original)!==preview.generatedDenominator||denominator(recomputed)!==preview.generatedDenominator)throw new Error("Generated availability denominator changed during controlled materialization.");for(const event of original.events){const next=recomputed.events.find(candidate=>candidate.eventId===event.eventId);if(!next||JSON.stringify(next.selectedStructures)!==JSON.stringify(event.selectedStructures))throw new Error("Comparative Economics materialization must not mutate selected Strategy structures.")}
 const comparative=new Map<string,ResearchOnlyStructure[]>();for(const event of recomputed.events)for(const structure of event.researchStructures??[]){if(structure.researchRole!=="comparative_economics")continue;const key=`${event.eventId}|${structure.structuralConfigurationId}`,rows=comparative.get(key)??[];rows.push(structure);comparative.set(key,rows)}for(const target of preview.targetMaterializations){const key=`${target.eventId}|${target.structuralConfigurationId}`,rows=comparative.get(key)??[];if(rows.length!==1)throw new Error(`Comparative Economics requires exactly one canonical materialization for ${key}.`);const structure=rows[0]!;if(structure.candidateId!==target.candidateId||JSON.stringify([...new Set(structure.generationAttemptIdentities??[])].sort())!==JSON.stringify(target.generationAttemptIdentities))throw new Error(`Comparative Economics materialization for ${key} does not match the persisted ex-ante rank-1 decision and exact attempt provenance.`)}return recomputed;
}
