import { unzipSync, strFromU8 } from "fflate";
import { RESEARCH_BUNDLE_FILES, RESEARCH_BUNDLE_SCHEMA_VERSION, validateResearchBundle } from "./research-bundle";
import { validateTradeDataset, type TradeDataset } from "./trade-datasets";

export type CapabilityStatus="available"|"derivable"|"degraded"|"unavailable";
export interface Capability {id:string;label:string;status:CapabilityStatus;requiredInputs:readonly string[];missingInputs:readonly string[];affectedEventCount:number;affectedCandidateCount:number;reasonCodes:readonly string[]}
export interface AnalysisDataset {readonly filename:string;readonly schemaVersion:string;readonly migratedFrom:string|null;readonly run:Readonly<Record<string,unknown>>;readonly tables:Readonly<Record<string,readonly Readonly<Record<string,unknown>>[]>>;readonly counts:Readonly<Record<string,number>>;readonly venues:readonly string[];readonly sourceRuns:readonly string[];readonly eventUniverseComplete:boolean;readonly capabilities:readonly Capability[]}
export type ImportResult={status:"ready"|"degraded";dataset:AnalysisDataset;warnings:string[]}|{status:"invalid";errors:string[]};
const jsonl=(text:string,name:string)=>text.split(/\r?\n/).filter(Boolean).map((line,i)=>{try{return JSON.parse(line)}catch{throw new Error(`${name}:${i+1} is invalid JSONL.`)}});
const capabilitySpecs=[
 ["underlying-resolution","Underlying resolution",["events.sequence_status","events.observation_end_timestamp_utc"]],
 ["underlying-mfe-mae","Underlying MFE/MAE",["underlying_path.high","underlying_path.low"]],
 ["dte","DTE coverage",["candidates.actual_dte_hours"]], ["valuation-paths","Valuation paths",["valuations.timestamp_utc"]],
 ["credit-capture","Credit capture",["valuations.credit_capture_percentage"]], ["delayed-entry","Delayed entry",["evidence_trades.evidence_role=opening-side"]],
 ["strike-touch","Short-strike touch/breach",["underlying_path.high/low","candidates.actual_strikes"]], ["width","Width comparison",["availability.width"]],
 ["exit-policies","Exit policies",["outcomes.outcome_type"]], ["inverse-payoff","Exact inverse payoff",["candidates.contract_style","candidates.entry_legs"]],
 ["historical-margin","Historical margin",["margin_scenarios historical observation"]], ["current-margin","Current-formula margin scenarios",["margin_scenarios.margin_model"]],
 ["portfolio","Portfolio reconstruction",["candidates.quantity","candidates.selected_at_utc"]], ["futures","Futures comparison",["verified futures_path"]],
 ["pricing-tracks","Raw and modeled pricing tracks",["valuations.pricing_track"]],
] as const;
function assess(t:Record<string,Record<string,unknown>[]>):Capability[]{const events=t.events??[],candidates=t.candidates??[],all=JSON.stringify(t);return capabilitySpecs.map(([id,label,required])=>{let ok=required.every(r=>{if(r.includes("opening-side"))return (t.evidence_trades??[]).some(x=>x.evidence_role==="opening-side");if(r.includes("historical observation"))return (t.margin_scenarios??[]).some(x=>x.margin_status==="available"&&x.data_provenance==="historical");if(r.includes("verified futures"))return (t.futures_path??[]).some(x=>x.series_kind==="futures"&&x.verified===true);const key=r.split(".").at(-1)!.split(/[=/]/)[0];return all.includes(`"${key}"`)});if(id==="current-margin")ok=(t.margin_scenarios??[]).some(x=>x.margin_status==="available");const explicitlyUnavailable=["historical-margin","futures"].includes(id)&&!ok;return{id,label,status:ok?(id==="underlying-resolution"||id==="underlying-mfe-mae"?"derivable":"available"):explicitlyUnavailable?"unavailable":"degraded",requiredInputs:required,missingInputs:ok?[]:required,affectedEventCount:events.length,affectedCandidateCount:candidates.length,reasonCodes:ok?[]:[id==="delayed-entry"?"causal_opening_evidence_unavailable":id==="futures"?"verified_futures_series_unavailable":id==="historical-margin"?"verified_historical_margin_model_unavailable":"required_inputs_missing"]}})}
export function importResearchBundle(bytes:Uint8Array,filename:string,companion?:unknown):ImportResult{let zip:Record<string,Uint8Array>;try{zip=unzipSync(bytes)}catch{return{status:"invalid",errors:["The file is not a readable ZIP archive."]}}const files:Record<string,string>={};for(const name of RESEARCH_BUNDLE_FILES){const value=zip[`research_bundle/${name}`]??zip[name];if(value)files[name]=strFromU8(value)}if(!files["run.json"])return{status:"invalid",errors:["Missing run.json."]};let run:Record<string,unknown>;try{run=JSON.parse(files["run.json"])}catch{return{status:"invalid",errors:["run.json is invalid JSON."]}}let migratedFrom:null|string=null;const warnings:string[]=[];if(run.schema_version==="1.0.0"){migratedFrom="1.0.0";run={...run,schema_version:RESEARCH_BUNDLE_SCHEMA_VERSION};files["run.json"]=JSON.stringify(run)+"\n";warnings.push("Schema 1.0.0 imported in degraded mode; v2 event timing and censoring fields remain missing.")}const checked=validateResearchBundle(files);if(!checked.ok)return{status:"invalid",errors:checked.errors};let tradeDataset:TradeDataset|undefined;if(companion!==undefined){const c=validateTradeDataset(companion);if(!c.ok)return{status:"invalid",errors:c.errors.map(e=>`${e.path}: ${e.message}`)};tradeDataset=c.dataset;if(tradeDataset.datasetId!==run.dataset_id)return{status:"invalid",errors:["Companion dataset_id does not match the bundle."]}}
const tables:Record<string,Record<string,unknown>[]>={};for(const name of RESEARCH_BUNDLE_FILES.filter(x=>x.endsWith(".jsonl")))tables[name.replace(".jsonl","")]=jsonl(files[name],name);const eventIds=new Set(tables.events.map(x=>x.event_id));const total=tradeDataset?.trades.length??eventIds.size,generated=new Set(tables.availability.map(x=>x.event_id)).size,selected=new Set(tables.candidates.map(x=>x.event_id)).size,paths=new Set(tables.underlying_path.map(x=>x.event_id)).size;const complete=Boolean(tradeDataset)&&tradeDataset!.trades.every(x=>eventIds.has(x.id));if(!complete)warnings.push("Event universe is incomplete; per-opportunity statistics must not be claimed.");const dataset:AnalysisDataset=Object.freeze({filename,schemaVersion:String(run.schema_version),migratedFrom,run:Object.freeze(run),tables:Object.freeze(Object.fromEntries(Object.entries(tables).map(([k,v])=>[k,Object.freeze(v.map(Object.freeze))]))),counts:Object.freeze({tradeDatasetMrEvents:total,persistedResearchEvents:eventIds.size,eventsWithGeneratedCandidates:generated,eventsWithSelectedCandidates:selected,eventsWithStoredUnderlyingPaths:paths,selectedCandidates:tables.candidates.length,denominator:tables.availability.length}),venues:Object.freeze([...(run.venues as string[]??[])]),sourceRuns:Object.freeze(((run.source_runs as Record<string,unknown>[]??[]).map(x=>String(x.source_run_id)))),eventUniverseComplete:complete,capabilities:Object.freeze(assess(tables))});return{status:warnings.length?"degraded":"ready",dataset,warnings}}
