import type {AnalysisDataset,CapabilityStatus} from "./research-analysis.ts";
import {analyzeUnderlyingResolution,type UnderlyingResolutionReport} from "./underlying-resolution.ts";
import {analyzeDurationDte,type DurationDteReport} from "./duration-dte.ts";
import {analyzeStructurePoliciesEconomics,type StructureAnalyticsReport} from "./structure-policy-economics.ts";
import {analyzePortfolioAndSelectStrategy,type AnalysisConfiguration,type PortfolioStrategyResult} from "./portfolio-strategy-analysis.ts";

export type ReportState="available"|"degraded"|"unavailable"|"not configured"|"insufficient sample";
export interface ResearchReportResult {readonly dataset:AnalysisDataset;readonly underlying:UnderlyingResolutionReport;readonly duration:DurationDteReport;readonly structure:StructureAnalyticsReport;readonly portfolio:PortfolioStrategyResult;readonly identity:{datasetId:string;bundleId:string;sourceRunIds:readonly string[];analysisRunId:string};readonly sections:readonly {id:string;title:string;state:ReportState;detail:string}[]}
const hash=(s:string)=>{let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return(h>>>0).toString(16).padStart(8,"0")};
const status=(s:CapabilityStatus|undefined):ReportState=>s==="available"||s==="derivable"?"available":s==="unavailable"?"unavailable":"degraded";
export function buildResearchReport(dataset:AnalysisDataset,configuration:AnalysisConfiguration):ResearchReportResult{const underlying=analyzeUnderlyingResolution(dataset),duration=analyzeDurationDte(dataset),structure=analyzeStructurePoliciesEconomics(dataset),portfolio=analyzePortfolioAndSelectStrategy(dataset,configuration),datasetId=String(dataset.run.dataset_id??"unknown-dataset"),bundleId=String(dataset.run.bundle_id??dataset.run.run_id??"unknown-bundle"),analysisRunId=`analysis-${hash(JSON.stringify({datasetId,bundleId,sourceRuns:dataset.sourceRuns,configuration}))}`;const sections=[
 {id:"summary",title:"Executive summary & data sufficiency",state:dataset.eventUniverseComplete?"available":"degraded",detail:`${dataset.counts.selectedCandidates} selected candidates / ${dataset.counts.denominator} generated opportunities`},
 {id:"underlying",title:"Underlying resolution",state:underlying.events.length?status(dataset.capabilities.find(x=>x.id==="underlying-resolution")?.status):"insufficient sample",detail:`n=${underlying.events.length}; ${underlying.counts.censored} right-censored`},
 {id:"duration",title:"Duration / actual DTE",state:duration.cohorts.length?"available":"insufficient sample",detail:`${duration.cohorts.length} non-pooled cohort(s)`},
 {id:"strike",title:"Short strike",state:structure.shortStrike.matchedPairCount?"available":"insufficient sample",detail:`${structure.shortStrike.matchedPairCount} matched pair(s)`},
 {id:"width",title:"Width",state:structure.width.matchedPairCount?"available":"insufficient sample",detail:`${structure.width.matchedPairCount} matched pair(s)`},
 {id:"exits",title:"Exit policies",state:structure.policies.some(x=>x.sampleSize)?"available":"unavailable",detail:`${structure.policies.reduce((n,x)=>n+x.sampleSize,0)} policy observations across locked tracks`},
 {id:"positions",title:"Per-position economics",state:structure.economics.length?"available":"insufficient sample",detail:`n=${structure.economics.length}`},
 {id:"portfolio",title:"Portfolio economics",state:portfolio.configured?"available":"not configured",detail:`${portfolio.portfolio.positions.length} positions; ${portfolio.portfolio.noTradeOpportunities} no-trade zeros`},
 {id:"futures",title:"Options versus futures",state:portfolio.futures.status==="available"?"available":"unavailable",detail:portfolio.futures.explanation},
 {id:"interactions",title:"Interaction matrices",state:portfolio.matrices.some(x=>x.cells.some(c=>c.status==="ok"))?"available":"insufficient sample",detail:`${portfolio.matrices.reduce((n,x)=>n+x.cells.length,0)} cells; denominators remain opportunity based`},
 {id:"scorecard",title:"Strategy scorecard",state:portfolio.configured?"available":"not configured",detail:portfolio.selection.stabilitySummary},
 {id:"methodology",title:"Methodology, provenance & limitations",state:"available",detail:"Causal timestamps, source-run isolation, missingness and immutable configuration are disclosed."}
 ] as const;return Object.freeze({dataset,underlying,duration,structure,portfolio,identity:Object.freeze({datasetId,bundleId,sourceRunIds:Object.freeze([...dataset.sourceRuns]),analysisRunId}),sections:Object.freeze(sections)});}

const ascii=(s:string)=>s.normalize("NFKD").replace(/[^\x20-\x7e]/g,"-").replaceAll("\\","\\\\").replaceAll("(","\\(").replaceAll(")","\\)");
/** Small deterministic vector-PDF serializer. Text remains selectable and charts are vector lines. */
export function createResearchPdf(report:ResearchReportResult,generatedAt=new Date()):Uint8Array{const lines:string[]=["RESEARCH ANALYTICS - FINAL REPORT","Contents",...report.sections.map((s,i)=>`${i+1}. ${s.title} [${s.state.toUpperCase()}]`),"",`Dataset ID: ${report.identity.datasetId}`,`Bundle ID: ${report.identity.bundleId}`,`Source-run IDs: ${report.identity.sourceRunIds.join(", ")||"none"}`,`Analysis-run ID: ${report.identity.analysisRunId}`,`Generated UTC: ${generatedAt.toISOString()}`,`Locked configuration: ${JSON.stringify(report.portfolio.configuration)}`,"",...report.sections.flatMap((s,i)=>[`${i+1}. ${s.title}`,`STATE: ${s.state.toUpperCase()}`,s.detail,""]),"Disclosures",...report.portfolio.warnings,...report.dataset.capabilities.filter(x=>x.status==="unavailable"||x.status==="degraded").map(x=>`${x.label}: ${x.status}; ${x.missingInputs.join(", ")}`),`Underlying sample n=${report.underlying.events.length}; 95% confidence intervals shown in analysis.`,`Policy samples: ${report.structure.policies.map(x=>`${x.policy}/${x.track} n=${x.sampleSize}`).join("; ")}`,`Interaction cells: ${report.portfolio.matrices.flatMap(x=>x.cells).map(x=>`${x.eventN}/${x.candidateN}`).join(", ")}`];const per=43,pages=Array.from({length:Math.ceil(lines.length/per)},(_,i)=>lines.slice(i*per,(i+1)*per));const objects:string[]=["<< /Type /Catalog /Pages 2 0 R >>",`<< /Type /Pages /Kids [${pages.map((_,i)=>`${4+i*2} 0 R`).join(" ")}] /Count ${pages.length} >>`,`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`];pages.forEach((rows,i)=>{const content=["BT /F1 9 Tf 46 770 Td 12 TL",...rows.map((x,j)=>`${j?"T* ":""}(${ascii(x).slice(0,115)}) Tj`),`T* (${ascii(`Page ${i+1} of ${pages.length}`)}) Tj ET`].join("\n"),pageObj=4+i*2,contentObj=pageObj+1;objects[pageObj-1]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentObj} 0 R >>`;objects[contentObj-1]=`<< /Length ${content.length} >>\nstream\n${content}\nendstream`});let out="%PDF-1.4\n% research-analytics\n";const offsets=[0];objects.forEach((o,i)=>{offsets.push(out.length);out+=`${i+1} 0 obj\n${o}\nendobj\n`});const xref=out.length;out+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(x=>String(x).padStart(10,"0")+" 00000 n ").join("\n")}\ntrailer << /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;return new TextEncoder().encode(out)}
