import type { OptionType } from "./backtester.ts";
import { InvalidCreditSpreadError, creditSpreadKind, type ExpiryPayoffInput } from "./expiry-payoff.ts";

type Row=Record<string,unknown>;const obj=(x:unknown):Row=>x&&typeof x==="object"&&!Array.isArray(x)?x as Row:{};const num=(x:unknown)=>typeof x==="number"&&Number.isFinite(x)?x:null;
export class InvalidSpreadSemanticsError extends Error{readonly code="INVALID_SPREAD_SEMANTICS";readonly candidateId:string;readonly eventId:string;constructor(candidateId:string,eventId:string,message:string){super(message);this.name="InvalidSpreadSemanticsError";this.candidateId=candidateId;this.eventId=eventId}}
export interface SpreadDiagnostic{candidateId:string;eventId:string;severity:"reconciled"|"invalid";reason:string;details:Record<string,unknown>}
export interface SemanticResult{row:Row;diagnostics:SpreadDiagnostic[];valid:boolean;payoffInput?:ExpiryPayoffInput}
export const parseInstrument=(name:unknown):{strike:number;optionType:OptionType}|null=>{if(typeof name!=="string")return null;const m=name.match(/-(\d+(?:\.\d+)?)-([CP])(?:$|-)/i);return m?{strike:Number(m[1]),optionType:m[2].toUpperCase() as OptionType}:null};
const opt=(c:Row):OptionType|null=>{const s=String(c.option_type??c.structure_type??"").toUpperCase();if(s.includes("P"))return"P";if(s.includes("C")||s.includes("CALL"))return"C";return null};
const action=(leg:Row)=>String(leg.action??leg.open_action??"").toLowerCase();
export const semanticStrike=(c:Row,leg:"short"|"long")=>num(c[`${leg}_strike`])??num(obj(c.actual_strikes)[leg])??num(obj(obj(c.actual_strikes)[leg]).strike)??num(obj(obj(c.entry_legs)[leg]).strike)??parseInstrument(obj(obj(c.entry_legs)[leg]).instrument??obj(c.instruments)[leg])?.strike??null;
export const semanticWidth=(c:Row)=>num(c.actual_width)??num(obj(c.actual_strikes).width)??(()=>{const s=semanticStrike(c,"short"),l=semanticStrike(c,"long");return s!==null&&l!==null?Math.abs(s-l):null})();
function legEvidence(c:Row,leg:"short"|"long"){const entry=obj(obj(c.entry_legs)[leg]),instrument=entry.instrument??obj(c.instruments)[leg],parsed=parseInstrument(instrument),sources:{source:string;value:number|null}[]=[{source:"top-level fields",value:num(c[`${leg}_strike`])},{source:"actual_strikes",value:num(obj(c.actual_strikes)[leg])??num(obj(obj(c.actual_strikes)[leg]).strike)},{source:"entry_legs",value:num(entry.strike)},{source:"instrument-name parsing",value:parsed?.strike??null}];return{entry,instrument,parsed,action:action(entry),strike:semanticStrike(c,leg),sources};}
const agree=(values:(number|null|undefined)[])=>{const xs=values.filter((x):x is number=>x!==null&&x!==undefined);return xs.length<2||xs.every(x=>Math.abs(x-xs[0])<=1e-9)};
function details(c:Row,s:ReturnType<typeof legEvidence>,l:ReturnType<typeof legEvidence>){return{optionType:opt(c),shortStrike:s.strike,longStrike:l.strike,shortInstrument:s.instrument,longInstrument:l.instrument,entryActions:{short:s.action,long:l.action},strikeSources:{short:s.sources,long:l.sources},actualWidth:semanticWidth(c),grossCredit:num(c.gross_credit_debit_native),netOpening:num(c.net_opening_cash_flow_native)}}
function setLegMetadata(row:Row){const legs=obj(row.entry_legs),short=obj(legs.short),long=obj(legs.long);row.actual_strikes={...obj(row.actual_strikes),short:num(short.strike)??parseInstrument(short.instrument)?.strike??semanticStrike(row,"short"),long:num(long.strike)??parseInstrument(long.instrument)?.strike??semanticStrike(row,"long"),width:Math.abs((num(short.strike)??parseInstrument(short.instrument)?.strike)!-(num(long.strike)??parseInstrument(long.instrument)?.strike)!)};row.instruments={...obj(row.instruments),short:short.instrument??null,long:long.instrument??null};row.short_strike=(row.actual_strikes as Row).short;row.long_strike=(row.actual_strikes as Row).long;}
export function reconcileCandidateSpread(input:Row):SemanticResult{const row:Row={...input,actual_strikes:{...obj(input.actual_strikes)},instruments:{...obj(input.instruments)},entry_legs:{short:{...obj(obj(input.entry_legs).short)},long:{...obj(obj(input.entry_legs).long)}}};const candidateId=String(row.candidate_id??row.id??"unknown-candidate"),eventId=String(row.event_id??"unknown-event"),diags:SpreadDiagnostic[]=[];const optionType=opt(row);let s=legEvidence(row,"short"),l=legEvidence(row,"long");const invalid=(reason:string)=>({row,valid:false,diagnostics:[...diags,{candidateId,eventId,severity:"invalid" as const,reason,details:details(row,s,l)}]});
 if(!optionType)return invalid("Option type is missing or unsupported.");for(const [name,e] of [["short",s],["long",l]] as const){if(e.parsed&&e.parsed.optionType!==optionType)return invalid(`${name} instrument option type disagrees with candidate option type.`);if(!agree(e.sources.map(x=>x.value)))return invalid(`${name} strike sources disagree.`)}
 const ordered=()=>s.strike!==null&&l.strike!==null&&((optionType==="C"&&s.strike<l.strike)||(optionType==="P"&&s.strike>l.strike));const actionsOk=()=>((!s.action&&!l.action)||(s.action==="sell"&&l.action==="buy"));if(!ordered()||!actionsOk()){const shortLooksLong=s.parsed&&s.action==="buy",longLooksShort=l.parsed&&l.action==="sell",reversedObjects=shortLooksLong&&longLooksShort&&s.parsed!.optionType===optionType&&l.parsed!.optionType===optionType&&((optionType==="C"&&l.parsed!.strike<s.parsed!.strike)||(optionType==="P"&&l.parsed!.strike>s.parsed!.strike));if(reversedObjects){const legs=obj(row.entry_legs);row.entry_legs={short:obj(legs.long),long:obj(legs.short)};setLegMetadata(row);diags.push({candidateId,eventId,severity:"reconciled",reason:"Reversed entry leg objects repaired using exact instrument names and buy/sell actions.",details:details(input,legEvidence(input,"short"),legEvidence(input,"long"))});s=legEvidence(row,"short");l=legEvidence(row,"long");}else return invalid(!actionsOk()?"Entry leg actions must be short=sell and long=buy.":optionType==="C"?"A bear call credit requires short strike below long strike.":"A bull put credit requires short strike above long strike.");}
 if(!ordered()||!actionsOk())return invalid("Spread remains invalid after reconciliation.");const width=semanticWidth(row);if(width!==null&&Math.abs(width-Math.abs(s.strike!-l.strike!))>1e-9)return invalid("Actual width disagrees with short/long strike distance.");const sp=num(s.entry.price_native),lp=num(l.entry.price_native),idx=num(row.entry_index_price),amount=num(row.quantity),fees=num(row.opening_fees_native);if(sp!==null&&lp!==null&&sp<lp)return invalid("Credit spread entry prices imply a debit, not a credit.");if([sp,lp,idx,amount,fees].every(x=>x!==null)){const payoffInput={optionType,shortStrike:s.strike!,longStrike:l.strike!,shortEntryPremiumBtc:sp!,longEntryPremiumBtc:lp!,entryIndex:idx!,amount:Math.abs(amount!),openingFeesBtc:fees!,expiryTimestamp:Date.parse(String(row.expiry_timestamp_utc??row.actual_expiry_timestamp_utc))};try{creditSpreadKind(payoffInput);return{row,diagnostics:diags,valid:true,payoffInput}}catch(e){if(e instanceof InvalidCreditSpreadError)return invalid(e.message);throw e}}
 return{row,diagnostics:diags,valid:true};}
export function requireValidCandidateSpread(row:Row){const r=reconcileCandidateSpread(row);if(!r.valid)throw new InvalidSpreadSemanticsError(r.diagnostics.at(-1)!.candidateId,r.diagnostics.at(-1)!.eventId,r.diagnostics.at(-1)!.reason);return r;}
