/* eslint-disable @typescript-eslint/ban-ts-comment */
// Canonical bundle rows are schema-open and validated at the import boundary.
// @ts-nocheck
import type {AnalysisDataset} from "./research-analysis.ts";
import {breakEven,payoffExtrema,type ExpiryPayoffInput} from "./expiry-payoff.ts";
import {reconcileCandidateSpread,InvalidSpreadSemanticsError,semanticStrike as strike,semanticWidth as width} from "./semantic-spread.ts";

type Row=Readonly<Record<string,unknown>>;
export type PricingTrack="raw_vwap"|"iv_normalized";
export interface Coverage {available:number;total:number;rate:number|null}
export interface Tail {expectancy:number|null;median:number|null;p10:number|null;p5:number|null;worst:number|null}
export interface PolicyResult extends Tail {policy:string;track:PricingTrack;executionAssumption:string;sampleSize:number;coverage:Coverage;mae:number|null;surrenderedPostExitMfe:number|null;lossesAvoided:number|null;holdingHours:number|null;capitalDays:number|null;fees:number|null;triggers:Record<string,number>;missingExits:number}
export interface PositionEconomics {candidateId:string;track:PricingTrack;executionAssumption:string;grossCredit:number|null;netCredit:number|null;openingFees:number|null;closingFees:number|null;slippage:number|null;maximumEconomicLoss:number|null;pnlByPolicy:Record<string,number|null>;returnOnMaximumLoss:Record<string,number|null>;capitalOccupancyDays:number|null;incrementalOpeningMargin:number|null;peakMargin:number|null;marginStatus:string;marginAccountModel:string;marginMethodVersion:string|null;marginEffectiveDate:string|null;historicalMarginStatus:string;portfolioMarginStatus:string}
export interface MatchRow {leftId:string;rightId:string;controlKey:string;deltaPnl:number|null;deltaMae:number|null;creditSacrificed:number|null}
export interface StructureAnalyticsReport {shortStrike:{matches:MatchRow[];matchedPairCount:number;excludedCases:number;placements:Row[];conclusion:string};width:{matches:MatchRow[];matchedPairCount:number;excludedCases:number;frontier:Row[];protection:Row[]};policies:PolicyResult[];economics:PositionEconomics[];diagnostics:{includedCandidates:number;excludedCandidates:number;degraded:boolean;rows:readonly {candidateId:string;eventId:string;severity:"reconciled"|"invalid";reason:string;details:Record<string,unknown>}[]};methodology:string[]}

const H=36e5,n=(x:unknown)=>typeof x==="number"&&Number.isFinite(x)?x:null,o=(x:unknown):Row=>x&&typeof x==="object"&&!Array.isArray(x)?x as Row:{},time=(x:unknown)=>typeof x==="string"&&Number.isFinite(Date.parse(x))?Date.parse(x):null;
const q=(xs:number[],p:number)=>{if(!xs.length)return null;const s=[...xs].sort((a,b)=>a-b),i=(s.length-1)*p,l=Math.floor(i),u=Math.ceil(i);return s[l]+(s[u]-s[l])*(i-l)},mean=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:null;
const cov=(a:number,b:number):Coverage=>({available:a,total:b,rate:b?a/b:null});
const pnl=(r:Row)=>n(r.net_pnl_native)??n(r.gross_pnl_native), fee=(r:Row)=>n(r.closing_fees_native)??0;
const execution=(c:Row)=>String(c.execution_mode??c.execution_assumption??"unknown");
const placement=(c:Row)=>String(c.strike_method??c.short_strike_method??"unknown").toLowerCase();
const expiry=(c:Row)=>String(c.actual_expiry_timestamp_utc??c.expiry_timestamp_utc??"missing");
const policyValuation=(valuations:Row[],decision:number)=>valuations.filter(v=>v.valuation_status==="priced"&&(time(v.timestamp_utc)??time(v.valuation_timestamp_utc)??-Infinity)>=decision).sort((a,b)=>(time(a.timestamp_utc)??0)-(time(b.timestamp_utc)??0))[0];

/** Select solely by decision-available time, and then the first causal mark. */
export function schedulePolicy(c:Row,outcomes:Row[],valuations:Row[],family:string,track:PricingTrack){const entry=time(c.valuation_timestamp_utc)??time(c.entry_timestamp_utc),exp=time(c.expiry_timestamp_utc)??time(c.actual_expiry_timestamp_utc);if(entry===null)return null;const eligible:Row[]=[];const add=(kind:string)=>eligible.push(...outcomes.filter(x=>x.outcome_type===kind&&x.outcome_status!=="unavailable"&&x.status!=="unavailable"));if(family==="thesis"){add("vpoc");add("invalidation")}else if(family==="capture_50"){add("vpoc");add("invalidation");add("credit_capture_50")}else if(family==="capture_70"){add("vpoc");add("invalidation");add("credit_capture_70")}else if(family.startsWith("time_cap_")){add("vpoc");add("invalidation")}else add("settlement");const triggers=eligible.flatMap(x=>{const t=time(x.decision_available_timestamp_utc)??time(x.decision_timestamp_utc);return t===null?[]:[{t,row:x,kind:String(x.outcome_type)}]});if(family.startsWith("time_cap_")&&exp!==null){const days=Number(family.match(/\d+/)?.[0]),cap=Math.min(exp,entry+days*24*H);triggers.push({t:cap,row:{},kind:`${days}d_time_cap`})}if(family==="settlement"&&exp!==null&&!triggers.length)triggers.push({t:exp,row:{},kind:"settlement"});triggers.sort((a,b)=>a.t-b.t);const chosen=triggers[0];if(!chosen)return null;const exact=chosen.row.pricing_track===track||!chosen.row.pricing_track?pnl(chosen.row):null;if(exact!==null&&time(chosen.row.valuation_timestamp_utc)!==null&&time(chosen.row.valuation_timestamp_utc)!>=chosen.t)return{trigger:chosen.kind,decision:chosen.t,valuation:chosen.row,pnl:exact};const v=policyValuation(valuations.filter(x=>x.pricing_track===track),chosen.t);return v?{trigger:chosen.kind,decision:chosen.t,valuation:v,pnl:pnl(v)}:null}

export function touchBreach(c:Row,event:Row,path:Row[]){const s=strike(c,"short"),entry=n(event.entry_price)??n(event.entry_underlying_index)??n(c.entry_index_price),direction=String(event.direction??c.option_type??"").toLowerCase(),invalidation=time(event.invalidation_decision_timestamp_utc);if(s===null)return{touched:null,breached:null,invalidationWithoutBreach:null,breachBeforeInvalidation:null,touchTime:null,breachTime:null};let touchTime:number|null=null,breachTime:number|null=null;for(const candle of [...path].sort((a,b)=>(time(a.timestamp_utc)??0)-(time(b.timestamp_utc)??0))){const t=time(candle.timestamp_utc);if(t===null)continue;const adverseHigh=direction.includes("short")||direction.includes("call")||direction==="down"?n(candle.high):n(candle.low),touch=direction.includes("short")||direction.includes("call")||direction==="down"?(adverseHigh!==null&&adverseHigh>=s):(adverseHigh!==null&&adverseHigh<=s),breach=direction.includes("short")||direction.includes("call")||direction==="down"?(adverseHigh!==null&&adverseHigh>s):(adverseHigh!==null&&adverseHigh<s);if(touch&&touchTime===null)touchTime=t;if(breach&&breachTime===null)breachTime=t}return{touched:touchTime!==null,breached:breachTime!==null,invalidationWithoutBreach:invalidation!==null&&(breachTime===null||invalidation<breachTime),breachBeforeInvalidation:breachTime!==null&&(invalidation===null||breachTime<invalidation),touchTime,breachTime,normalizedDistance:s!==null&&entry?Math.abs(s-entry)/entry:null}}

function payoffInput(c:Row):ExpiryPayoffInput|null{const r=reconcileCandidateSpread(c);if(!r.valid)throw new InvalidSpreadSemanticsError(r.diagnostics.at(-1)!.candidateId,r.diagnostics.at(-1)!.eventId,r.diagnostics.at(-1)!.reason);return r.payoffInput??null}
function tail(xs:number[]):Tail{return{expectancy:mean(xs),median:q(xs,.5),p10:q(xs,.1),p5:q(xs,.05),worst:xs.length?Math.min(...xs):null}}

export function analyzeStructurePoliciesEconomics(dataset:Pick<AnalysisDataset,"tables"|"run">):StructureAnalyticsReport{const t=dataset.tables,allCandidates=t.candidates??[],semanticDiagnostics=allCandidates.flatMap(c=>reconcileCandidateSpread(c).diagnostics),invalidIds=new Set(semanticDiagnostics.filter(d=>d.severity==="invalid").map(d=>d.candidateId)),candidates=allCandidates.filter(c=>!invalidIds.has(String(c.candidate_id))),events=t.events??[],paths=t.underlying_path??[],vals=t.valuations??[],outcomes=t.outcomes??[],margins=t.margin_scenarios??[],eventBy=new Map(events.map(x=>[String(x.event_id),x]));const settlement=(id:string,track:PricingTrack)=>outcomes.find(x=>x.candidate_id===id&&x.outcome_type==="settlement"&&(!x.pricing_track||x.pricing_track===track));
 const placements=candidates.map(c=>{const event=eventBy.get(String(c.event_id))??{},seq=touchBreach(c,event,paths.filter(x=>x.event_id===c.event_id)),s=strike(c,"short"),technical=n(event.technical_level)??n(event.invalidation_level),entry=n(event.entry_price)??n(c.entry_index_price);return{candidate_id:c.candidate_id,event_id:c.event_id,placement:placement(c),short_strike:s,technical_level:technical,normalized_distance_entry:s!==null&&entry?Math.abs(s-entry)/entry:null,normalized_distance_technical:s!==null&&technical?Math.abs(s-technical)/technical:null,...seq,pnl_on_touch:seq.touched?pnl(settlement(String(c.candidate_id),"raw_vwap")??{}):null,pnl_on_breach:seq.breached?pnl(settlement(String(c.candidate_id),"raw_vwap")??{}):null}});
 const pair=(kind:"strike"|"width")=>{const buckets=new Map<string,Row[]>();for(const c of candidates){const key=kind==="strike"?[c.event_id,expiry(c),width(c),execution(c),dataset.run.valuation_methodology_version??"unknown",c.exit_policy??"settlement"]:[c.event_id,expiry(c),strike(c,"short"),execution(c),dataset.run.valuation_methodology_version??"unknown",c.exit_policy??"settlement"];const k=key.join("|");buckets.set(k,[...(buckets.get(k)??[]),c])}const result:MatchRow[]=[];for(const [key,rows] of buckets){for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++){if(kind==="strike"&&placement(rows[i])===placement(rows[j]))continue;if(kind==="width"&&width(rows[i])===width(rows[j]))continue;const a=pnl(settlement(String(rows[i].candidate_id),"raw_vwap")??{}),b=pnl(settlement(String(rows[j].candidate_id),"raw_vwap")??{}),ca=n(rows[i].gross_credit_debit_native),cb=n(rows[j].gross_credit_debit_native);result.push({leftId:String(rows[i].candidate_id),rightId:String(rows[j].candidate_id),controlKey:key,deltaPnl:a!==null&&b!==null?b-a:null,deltaMae:null,creditSacrificed:ca!==null&&cb!==null?ca-cb:null})}}return result};const strikeMatches=pair("strike"),widthMatches=pair("width");
 const families=["thesis","capture_50","capture_70","time_cap_3d","time_cap_5d","time_cap_7d","settlement"],policyResults:PolicyResult[]=[];for(const track of ["raw_vwap","iv_normalized"] as PricingTrack[])for(const family of families){const selected=candidates.map(c=>({c,x:schedulePolicy(c,outcomes.filter(o=>o.candidate_id===c.candidate_id),vals.filter(v=>v.candidate_id===c.candidate_id),family,track)})),known=selected.filter(z=>z.x?.pnl!=null),pnls=known.map(z=>z.x!.pnl!),hours=known.map(z=>(time(z.x!.valuation.timestamp_utc)??time(z.x!.valuation.valuation_timestamp_utc)!)-(time(z.c.valuation_timestamp_utc)??0)).map(x=>x/H),fees=known.map(z=>fee(z.x!.valuation)),triggers:Record<string,number>={};known.forEach(z=>triggers[z.x!.trigger]=(triggers[z.x!.trigger]??0)+1);policyResults.push({policy:family,track,executionAssumption:[...new Set(candidates.map(execution))].join(", ")||"unknown",sampleSize:known.length,coverage:cov(known.length,candidates.length),...tail(pnls),mae:pnls.length?Math.min(...pnls):null,surrenderedPostExitMfe:mean(known.flatMap(z=>{const after=vals.filter(v=>v.candidate_id===z.c.candidate_id&&v.pricing_track===track&&(time(v.timestamp_utc)??0)>=z.x!.decision).map(pnl).filter((x):x is number=>x!==null);return after.length?[Math.max(...after)-z.x!.pnl!]:[]})),lossesAvoided:mean(known.flatMap(z=>{const s=pnl(settlement(String(z.c.candidate_id),track)??{});return s===null?[]:[z.x!.pnl!-s]})),holdingHours:mean(hours),capitalDays:mean(hours.map(x=>x/24)),fees:mean(fees),triggers,missingExits:candidates.length-known.length})}
 const economics:PositionEconomics[]=candidates.flatMap(c=>(["raw_vwap","iv_normalized"] as PricingTrack[]).map(track=>{let exact:null|number=null;try{const input=payoffInput(c);exact=input?payoffExtrema(input,"btc-settlement").maximumLoss:null}catch(e){if(e instanceof InvalidSpreadSemanticsError)return null as never;throw e}const maximumEconomicLoss=exact===null?null:Math.abs(Math.min(0,exact)),policy=Object.fromEntries(families.map(f=>[f,schedulePolicy(c,outcomes.filter(o=>o.candidate_id===c.candidate_id),vals.filter(v=>v.candidate_id===c.candidate_id),f,track)?.pnl??null])),margin=margins.find(x=>x.candidate_id===c.candidate_id),entryLegs=o(c.entry_legs),gross=n(c.gross_credit_debit_native)??(()=>{const a=n(o(entryLegs.short).price_native),b=n(o(entryLegs.long).price_native),qty=n(c.quantity);return a!==null&&b!==null&&qty!==null?(a-b)*qty:null})(),open=n(c.opening_fees_native),net=n(c.net_opening_cash_flow_native)??(gross!==null&&open!==null?gross-open:null),close=fee(settlement(String(c.candidate_id),track)??{}),uns=n(o(entryLegs.short).unslipped_price_native),unl=n(o(entryLegs.long).unslipped_price_native),sp=n(o(entryLegs.short).price_native),lp=n(o(entryLegs.long).price_native),qty=n(c.quantity),slippage=[uns,unl,sp,lp,qty].every(x=>x!==null)?((uns!-unl!)-(sp!-lp!))*qty!:null,days=n(c.actual_dte_hours)!==null?n(c.actual_dte_hours)!/24:null;return{candidateId:String(c.candidate_id),track,executionAssumption:execution(c),grossCredit:gross,netCredit:net,openingFees:open,closingFees:close,slippage,maximumEconomicLoss,pnlByPolicy:policy,returnOnMaximumLoss:Object.fromEntries(Object.entries(policy).map(([k,v])=>[k,v!==null&&maximumEconomicLoss?Number(v)/maximumEconomicLoss:null])),capitalOccupancyDays:days,incrementalOpeningMargin:margin?.margin_status==="available"?n(margin.incremental_initial_margin):null,peakMargin:margin?.margin_status==="available"?n(margin.peak_initial_margin):null,marginStatus:margin?.margin_status==="available"?String(margin.calculation_method??"available scenario"):"unavailable — no verified historical observation",marginAccountModel:String(o(margin?.account_configuration).account_model??margin?.margin_model??"unavailable"),marginMethodVersion:margin?.margin_status==="available"?String(margin.method_version??"")||null:null,marginEffectiveDate:margin?.margin_status==="available"?String(margin.effective_date??"")||null:null,historicalMarginStatus:margin?.data_provenance==="historical"?"available":"unavailable",portfolioMarginStatus:margin?.margin_model==="portfolio"&&margin?.margin_status==="available"?"available":"unavailable"}}));
 const economicsClean=economics.filter(Boolean);
 const protection=economicsClean.filter(x=>x.track==="raw_vwap").map(x=>{const c=candidates.find(c=>String(c.candidate_id)===x.candidateId)!,v=vals.find(v=>v.candidate_id===c.candidate_id&&v.pricing_track==="raw_vwap"&&v.valuation_status==="priced"),legs=o(c.entry_legs),closeLegs=o(v?.short_leg),longCloseLeg=o(v?.long_leg),qty=n(c.quantity),shortEntry=n(o(legs.short).price_native),longEntry=n(o(legs.long).price_native),shortClose=n(closeLegs.price_native),longClose=n(longCloseLeg.price_native);return{candidate_id:x.candidateId,spread_pnl:v?pnl(v):null,naked_short_counterfactual:shortEntry!==null&&shortClose!==null&&qty!==null?(shortEntry-shortClose)*qty-(n(c.opening_fees_native)??0)-(n(v?.closing_fees_native)??0):null,long_leg_protection:longEntry!==null&&longClose!==null&&qty!==null?(longClose-longEntry)*qty:null,fees_preserved:true,quantity:qty,margin_comparability:"not comparable — naked-short margin not inferred"}});
 return{shortStrike:{matches:strikeMatches,matchedPairCount:strikeMatches.length,excludedCases:Math.max(0,candidates.length-new Set(strikeMatches.flatMap(x=>[x.leftId,x.rightId])).size),placements,conclusion:strikeMatches.length?"Compare matched lost credit with challenged-position PnL and tail-loss deltas; buffering compensates only when the latter exceeds the former.":"No causal buffering conclusion: no fully controlled matched pairs."},width:{matches:widthMatches,matchedPairCount:widthMatches.length,excludedCases:Math.max(0,candidates.length-new Set(widthMatches.flatMap(x=>[x.leftId,x.rightId])).size),frontier:economicsClean.filter(x=>x.track==="raw_vwap").map(x=>({candidate_id:x.candidateId,width:width(candidates.find(c=>String(c.candidate_id)===x.candidateId)!),credit:x.netCredit,maximum_economic_loss:x.maximumEconomicLoss,return_on_max_loss:x.returnOnMaximumLoss.settlement,breakeven:(()=>{const i=payoffInput(candidates.find(c=>String(c.candidate_id)===x.candidateId)!);return i?breakEven(i,"btc-settlement")?.index??null:null})()})),protection},policies:policyResults,economics:economicsClean,diagnostics:{includedCandidates:candidates.length,excludedCandidates:invalidIds.size,degraded:invalidIds.size>0,rows:semanticDiagnostics},methodology:["Strike controls: event + actual expiry + actual width + execution assumption + pricing track + exit policy.","Width controls: event + actual expiry + short strike + execution assumption + pricing track + exit policy.","Touch uses equality; breach requires crossing. Invalidation is decision-available only after its completed candle.","Policy triggers are ordered only by decision availability; the first permitted mark at or after the trigger is used.","Maximum economic loss uses the canonical inverse-option payoff and delivery-fee accounting; it is not width minus credit.","Historical observed margin, versioned current-formula Standard Margin scenarios, and authenticated Portfolio Margin results remain distinct. No exchange calls are made."]}}
