import type { AnalysisDataset } from "./research-analysis";

export type ResolutionOutcome="vpoc_first"|"invalidation_first"|"unresolved"|"ambiguous";
export interface ResolutionEvent {eventId:string;eventDate:string;direction:"bullish"|"bearish";entryTimestamp:number;observationEnd:number;censoringHours:number;vpocTime:number|null;invalidationTime:number|null;resolutionTime:number|null;outcome:ResolutionOutcome;rangeWidth:number|null;remainingDistance:{absolute:number|null;percentage:number|null;rangeWidths:number|null};invalidationDistance:{absolute:number|null;percentage:number|null;rangeWidths:number|null};mfe:{absolute:number|null;percentage:number|null;rangeWidths:number|null};mae:{absolute:number|null;percentage:number|null;rangeWidths:number|null};reconstructionDisagreements:string[];distanceCohort:string;speedCohort:string}
export interface CurvePoint {hours:number;estimate:number;atRisk:number;events:number;censored:number;lower:number;upper:number}
export interface Quantile {percentile:20|50|80|90;hours:number|null;status:"estimable"|"not_estimable"}
export interface CohortSummary {cohort:string;n:number;observed:number;censored:number;vpocFirst:number;invalidationFirst:number;ambiguous:number;mfeMedian:number|null;maeMedian:number|null}
export interface UnderlyingResolutionReport {events:ResolutionEvent[];counts:{universe:number;observed:number;censored:number;vpocFirst:number;invalidationFirst:number;ambiguous:number;withPath:number};survival:{resolution:CurvePoint[];vpoc:CurvePoint[];invalidation:CurvePoint[]};cumulativeIncidence:{hours:number;vpoc:number;invalidation:number;atRisk:number}[];quantiles:{resolution:Quantile[];vpoc:Quantile[];invalidation:Quantile[]};cohorts:{outcome:CohortSummary[];direction:CohortSummary[];distance:CohortSummary[];speed:CohortSummary[]};boundaries:{distanceRangeWidths:number[];speedHours:number[]};confidenceLevel:number;methodology:string[];missingData:string[];containsOptionPnl:false}

const HOUR=3_600_000, qs=[20,50,80,90] as const;
const n=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:null;
const time=(v:unknown)=>typeof v==="string"&&Number.isFinite(Date.parse(v))?Date.parse(v):null;
const median=(v:number[])=>{if(!v.length)return null;const s=[...v].sort((a,b)=>a-b),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2};
function ci(s:number,variance:number){const se=Math.sqrt(Math.max(0,variance));return[Math.max(0,s-1.96*se),Math.min(1,s+1.96*se)] as const}
function km(rows:{hours:number;event:boolean}[]):CurvePoint[]{let survival=1,greenwood=0;const out:CurvePoint[]=[{hours:0,estimate:1,atRisk:rows.length,events:0,censored:0,lower:1,upper:1}];for(const t of [...new Set(rows.map(x=>x.hours))].sort((a,b)=>a-b)){const risk=rows.filter(x=>x.hours>=t).length,d=rows.filter(x=>x.hours===t&&x.event).length,c=rows.filter(x=>x.hours===t&&!x.event).length;if(d&&risk){survival*=1-d/risk;if(risk>d)greenwood+=d/(risk*(risk-d))}const [lower,upper]=ci(survival,survival*survival*greenwood);out.push({hours:t,estimate:survival,atRisk:risk,events:d,censored:c,lower,upper})}return out}
function quantiles(curve:CurvePoint[]):Quantile[]{return qs.map(percentile=>{const hit=curve.find(x=>1-x.estimate>=percentile/100);return{percentile,hours:hit?.hours??null,status:hit?"estimable":"not_estimable"}})}
function cif(events:ResolutionEvent[]){let survival=1,vpoc=0,invalidation=0;const rows=events.map(e=>({hours:((e.resolutionTime??e.observationEnd)-e.entryTimestamp)/HOUR,outcome:e.outcome}));return [...new Set(rows.map(x=>x.hours))].sort((a,b)=>a-b).map(hours=>{const risk=rows.filter(x=>x.hours>=hours).length,v=rows.filter(x=>x.hours===hours&&x.outcome==="vpoc_first").length,i=rows.filter(x=>x.hours===hours&&x.outcome==="invalidation_first").length,a=rows.filter(x=>x.hours===hours&&x.outcome==="ambiguous").length;const prior=survival;if(risk){vpoc+=prior*v/risk;invalidation+=prior*i/risk;survival*=1-(v+i+a)/risk}return{hours,vpoc,invalidation,atRisk:risk}})}
function cohort(name:string,events:ResolutionEvent[]):CohortSummary{return{cohort:name,n:events.length,observed:events.filter(e=>e.outcome!=="unresolved").length,censored:events.filter(e=>e.outcome==="unresolved").length,vpocFirst:events.filter(e=>e.outcome==="vpoc_first").length,invalidationFirst:events.filter(e=>e.outcome==="invalidation_first").length,ambiguous:events.filter(e=>e.outcome==="ambiguous").length,mfeMedian:median(events.flatMap(e=>e.mfe.rangeWidths===null?[]:[e.mfe.rangeWidths])),maeMedian:median(events.flatMap(e=>e.mae.rangeWidths===null?[]:[e.mae.rangeWidths]))}}
function grouped(events:ResolutionEvent[],key:(e:ResolutionEvent)=>string){return [...new Set(events.map(key))].sort().map(k=>cohort(k,events.filter(e=>key(e)===k)))}

/** Pure analysis of persisted event and underlying tables. It deliberately never reads candidate, valuation or outcome tables. */
export function analyzeUnderlyingResolution(dataset:Pick<AnalysisDataset,"tables"|"counts">):UnderlyingResolutionReport{
 const paths=dataset.tables.underlying_path??[],events=(dataset.tables.events??[]).map(row=>{
  const entry=time(row.entry_timestamp_utc),end=time(row.observation_end_timestamp_utc),entryPrice=n(row.entry_price),vpocPrice=n(row.vpoc_price),invalidPrice=n(row.invalidation_price),low=n(row.range_low),high=n(row.range_high),width=low!==null&&high!==null&&high>low?high-low:null;
  if(entry===null||end===null) return null;
  const bullish=row.direction==="long"||row.direction==="bullish", direction=bullish?"bullish":"bearish" as const;
  const candles=paths.filter(p=>p.event_id===row.event_id).map(p=>({t:time(p.timestamp_utc),high:n(p.high),low:n(p.low)})).filter((p):p is {t:number;high:number|null;low:number|null}=>p.t!==null&&p.t>=entry&&p.t<=end).sort((a,b)=>a.t-b.t);
  // A VPOC touch uses the candle range. Invalidation is only available after the completed candle; hourly timestamps denote candle open.
  const vHit=vpocPrice===null?undefined:candles.find(c=>c.low!==null&&c.high!==null&&c.low<=vpocPrice&&c.high>=vpocPrice),iHit=invalidPrice===null?undefined:candles.find(c=>bullish?c.low!==null&&c.low<=invalidPrice:c.high!==null&&c.high>=invalidPrice);
  const rv=vHit?.t??null,ri=iHit?iHit.t+HOUR:null,ev=time(row.vpoc_trigger_timestamp_utc),ei=time(row.invalidation_decision_timestamp_utc);
  const disagreements:string[]=[];if(rv!==ev)disagreements.push(`VPOC reconstructed ${rv===null?"unobserved":new Date(rv).toISOString()} but export is ${ev===null?"unobserved":new Date(ev).toISOString()}.`);if(ri!==ei)disagreements.push(`Invalidation reconstructed ${ri===null?"unobserved":new Date(ri).toISOString()} but export is ${ei===null?"unobserved":new Date(ei).toISOString()}.`);
  const vpocTime=rv, invalidationTime=ri,first=vpocTime===null?invalidationTime:invalidationTime===null?vpocTime:Math.min(vpocTime,invalidationTime),outcome:ResolutionOutcome=vHit&&iHit&&vHit.t===iHit.t?"ambiguous":vpocTime!==null&&(invalidationTime===null||vpocTime<invalidationTime)?"vpoc_first":invalidationTime!==null?"invalidation_first":"unresolved";
  const until=first??end,observed=candles.filter(c=>c.t<=until),best=entryPrice===null||!observed.length?null:bullish?Math.max(...observed.map(c=>c.high??entryPrice))-entryPrice:entryPrice-Math.min(...observed.map(c=>c.low??entryPrice)),worst=entryPrice===null||!observed.length?null:bullish?entryPrice-Math.min(...observed.map(c=>c.low??entryPrice)):Math.max(...observed.map(c=>c.high??entryPrice))-entryPrice;
  const metric=(value:number|null)=>({absolute:value,percentage:value===null||entryPrice===null||entryPrice===0?null:value/entryPrice*100,rangeWidths:value===null||width===null?null:value/width});
  const remaining=entryPrice===null||vpocPrice===null?null:Math.abs(vpocPrice-entryPrice),invalid=entryPrice===null||invalidPrice===null?null:Math.abs(invalidPrice-entryPrice),distanceRatio=remaining===null||width===null?null:remaining/width,distanceCohort=distanceRatio===null?"missing":distanceRatio<.5?"< 0.5× range":distanceRatio<1?"0.5–<1× range":"≥ 1× range",duration=(first??end)-entry,speedCohort=first===null?"censored":duration<24*HOUR?"< 24h":duration<72*HOUR?"24–<72h":"≥ 72h";
  return{eventId:String(row.event_id),eventDate:new Date(entry).toISOString().slice(0,10),direction,entryTimestamp:entry,observationEnd:end,censoringHours:(end-entry)/HOUR,vpocTime,invalidationTime,resolutionTime:first,outcome,rangeWidth:width,remainingDistance:metric(remaining),invalidationDistance:metric(invalid),mfe:metric(best),mae:metric(worst),reconstructionDisagreements:disagreements,distanceCohort,speedCohort};
 }).filter((x):x is ResolutionEvent=>x!==null);
 const curve=(cause:"resolution"|"vpoc"|"invalidation")=>km(events.map(e=>({hours:(((cause==="resolution"?e.resolutionTime:cause==="vpoc"?e.vpocTime:e.invalidationTime)??e.observationEnd)-e.entryTimestamp)/HOUR,event:cause==="resolution"?e.outcome!=="unresolved":cause==="vpoc"?e.outcome==="vpoc_first":e.outcome==="invalidation_first"})));
 const survival={resolution:curve("resolution"),vpoc:curve("vpoc"),invalidation:curve("invalidation")};
 return{events,counts:{universe:dataset.counts.tradeDatasetMrEvents??events.length,observed:events.filter(e=>e.outcome!=="unresolved").length,censored:events.filter(e=>e.outcome==="unresolved").length,vpocFirst:events.filter(e=>e.outcome==="vpoc_first").length,invalidationFirst:events.filter(e=>e.outcome==="invalidation_first").length,ambiguous:events.filter(e=>e.outcome==="ambiguous").length,withPath:events.filter(e=>(dataset.tables.underlying_path??[]).some(p=>p.event_id===e.eventId)).length},survival,cumulativeIncidence:cif(events),quantiles:{resolution:quantiles(survival.resolution),vpoc:quantiles(survival.vpoc),invalidation:quantiles(survival.invalidation)},cohorts:{outcome:grouped(events,e=>e.outcome==="vpoc_first"?"successful MR":e.outcome==="invalidation_first"?"failed MR":e.outcome),direction:grouped(events,e=>e.direction),distance:grouped(events,e=>e.distanceCohort),speed:grouped(events,e=>e.speedCohort)},boundaries:{distanceRangeWidths:[.5,1],speedHours:[24,72]},confidenceLevel:.95,methodology:["VPOC is the first stored candle whose high-low range touches the VPOC level.","Invalidation is observed only at the close of the first breaching candle; its open is the trigger time.","Unresolved observations are right-censored. Kaplan–Meier and Aalen–Johansen competing-risk estimates retain them."],missingData:[`${events.filter(e=>e.rangeWidth===null).length} event(s) lack a usable range width.`,`${events.filter(e=>e.reconstructionDisagreements.length>0).length} event(s) disagree with exported trigger timing.`],containsOptionPnl:false};
}
