import type {AnalysisDataset} from "../research-analysis.ts";
import type {PositionEconomics} from "./position.ts";
export type EconomicOpportunityStatus="trade"|"explicit_no_trade"|"unavailable";
export type FinalEconomicOpportunityStatus="priced_trade"|"explicit_no_trade"|"unavailable";
export interface ConfigurationOpportunity {eventId:string;structuralConfigurationId:string|null;structuralConfiguration:Readonly<Record<string,unknown>>|null;status:FinalEconomicOpportunityStatus;generationStatus:EconomicOpportunityStatus;candidateId:string|null;pnlBtc:number|null;reasonCode:string|null;reason:string|null}
type Row=Readonly<Record<string,unknown>>;
const rec=(x:unknown):Row=>x&&typeof x==="object"&&!Array.isArray(x)?x as Row:{};
const str=(x:unknown)=>typeof x==="string"&&x?x:null;
export const EXPLICIT_NO_TRADE_CODES=new Set(["empirical_nonpositive_credit_after_fees"]);
export function classifyEconomicOpportunity(value:unknown):{status:EconomicOpportunityStatus;reasonCode:string|null;reason:string|null}{const x=rec(value),code=str(x.reason_code)??str(x.reasonCode),declared=str(x.status),reason=str(x.reason);if(declared==="trade")return{status:"trade",reasonCode:code,reason};if(declared==="explicit_no_trade"||EXPLICIT_NO_TRADE_CODES.has(code??""))return{status:"explicit_no_trade",reasonCode:code,reason};return{status:"unavailable",reasonCode:code??"economic_opportunity_unavailable",reason};}
/** Generation availability is authoritative: selected PositionEconomics only enriches its matching opportunity. */
export function projectConfigurationOpportunities(dataset:AnalysisDataset,positions:readonly PositionEconomics[]):readonly ConfigurationOpportunity[]{const byCandidate=new Map<string,PositionEconomics[]>();for(const p of positions){const key=`${p.eventId}|${p.candidateId}`,rows=byCandidate.get(key)??[];rows.push(p);byCandidate.set(key,rows)}return (dataset.tables.configuration_opportunities??dataset.tables.availability??[]).map(row=>{const eventId=str(row.event_id)??"",candidateId=str(row.candidate_id),matches=candidateId?byCandidate.get(`${eventId}|${candidateId}`)??[]:[],position=matches.length===1?matches[0]:undefined,declared=classifyEconomicOpportunity(row.economic_opportunity),pricedContradiction=declared.status==="explicit_no_trade"&&matches.some(p=>p.status==="priced"&&p.pnlBtc!==null&&Number.isFinite(p.pnlBtc));if(pricedContradiction)return{eventId,structuralConfigurationId:str(row.structural_configuration_id),structuralConfiguration:row.structural_configuration&&typeof row.structural_configuration==="object"?row.structural_configuration as Row:null,status:"unavailable",generationStatus:declared.status,candidateId,pnlBtc:null,reasonCode:"explicit_no_trade_conflicts_with_priced_position",reason:"Canonical explicit no-trade conflicts with a priced selected-policy position."};if(declared.status==="explicit_no_trade")return{eventId,structuralConfigurationId:str(row.structural_configuration_id),structuralConfiguration:row.structural_configuration&&typeof row.structural_configuration==="object"?row.structural_configuration as Row:null,status:"explicit_no_trade",generationStatus:declared.status,candidateId,pnlBtc:0,reasonCode:declared.reasonCode,reason:declared.reason};const pathComplete=Array.isArray(position?.path)&&position.path.length>0,priced=declared.status==="trade"&&matches.length===1&&position?.status==="priced"&&position.pnlBtc!==null&&Number.isFinite(position.pnlBtc)&&pathComplete;const reasonCode=declared.status!=="trade"?declared.reasonCode:matches.length!==1?matches.length?"conflicting_selected_policy_positions":"selected_policy_position_missing":position?.status!=="priced"||position.pnlBtc===null||!Number.isFinite(position.pnlBtc)?"selected_policy_pnl_unavailable":"selected_policy_path_unavailable";return{eventId,structuralConfigurationId:str(row.structural_configuration_id),structuralConfiguration:row.structural_configuration&&typeof row.structural_configuration==="object"?row.structural_configuration as Row:null,status:priced?"priced_trade":"unavailable",generationStatus:declared.status,candidateId,pnlBtc:priced?position!.pnlBtc:null,reasonCode:priced?null:reasonCode,reason:priced?null:declared.status!=="trade"?declared.reason:matches.length!==1?`Expected exactly one selected-policy position; found ${matches.length}.`:position?.missingReason??(!pathComplete?"The intended Q50 trade has no complete selected-policy path.":"The intended Q50 trade has no priced selected-policy result.")};});}
