import type {AnalysisDataset} from "../research-analysis.ts";
import type {AnalysisConfiguration} from "../analysis-configuration.ts";
import {normalizeExitPolicies,type PolicyObservation} from "../exit-policy/normalize.ts";
import type {ExpiryPayoffInput} from "../expiry-payoff.ts";
import {indexByCandidate,readCanonicalStructuralLoss} from "../canonical-structural-loss.ts";
import {canonicalStructuralLoss} from "../maximum-economic-loss.ts";

export interface Available<T>{value:T|null;reason:string|null}
const available=<T,>(value:T):Available<T>=>({value,reason:null});
const unavailable=<T,>(reason:string):Available<T>=>({value:null,reason});
const n=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:null;
const s=(v:unknown)=>typeof v==="string"&&v?v:null;
const at=(v:unknown,...keys:string[])=>keys.reduce<unknown>((x,k)=>x&&typeof x==="object"&&!Array.isArray(x)?(x as Record<string,unknown>)[k]:null,v);
export interface PositionEconomics {sourceRun:string;eventId:string;candidateId:string;structureExecutionId:string;analyticsTrack:import("../research-analytics-model.ts").AnalyticsTrack|null;executionScenario:"maker"|"taker"|null;pricingTrack:"raw_vwap"|"iv_normalized"|null;exitPolicy:string;status:PolicyObservation["status"];missingReason:string|null;direction:string|null;optionType:string|null;instruments:unknown;expiryTimestamp:string|null;entryTimestamp:string|null;exitTimestamp:string|null;actualDteDays:number|null;shortStrike:number|null;longStrike:number|null;actualWidth:number|null;quantity:number|null;shortPremiumBtc:number|null;longPremiumBtc:number|null;grossOpeningCreditBtc:number|null;openingFeesBtc:number|null;netOpeningCashFlowBtc:number|null;executionAdjustmentBtc:number|null;entryIndex:number|null;winningTrigger:string|null;exitIndex:number|null;closingCashFlowBtc:number|null;closingFeesBtc:number|null;deliveryFeesBtc:number|null;totalRealizedFeesBtc:number|null;pnlBtc:number|null;pnlUsd:number|null;maximumStructuralLossBtc:Available<number>;maximumStructuralLossUsd:Available<number>;trackMaximumNetLossBtc:Available<number>;trackMaximumNetLossUsd:Available<number>;incrementalInitialMarginBtc:Available<number>;incrementalMaintenanceMarginBtc:Available<number>;peakInitialMarginBtc:Available<number>;peakMaintenanceMarginBtc:Available<number>;peakMarginTimestamp:string|null;peakInitialMarginTimestamp:string|null;peakMaintenanceMarginTimestamp:string|null;holdingDays:number|null;capitalDaysBtc:Available<number>;returnOnStructuralLoss:Available<number>;returnOnTrackMaximumNetLoss:Available<number>;returnOnOpeningMargin:Available<number>;returnOnPeakCapital:Available<number>;riskMinimumEquityBtc:Available<number>;marginMinimumEquityBtc:Available<number>;minimumEquityBtc:Available<number>;bindingConstraint:"risk"|"margin"|null;endpoints?:readonly EndpointEconomics[];path?:readonly EconomicPathPoint[];strikeMethod?:string|null;requestedWidth?:number|null;structureType?:string|null}
export interface EconomicPathPoint {timestamp:string;pnlBtc:Available<number>;index:number|null;initialMarginBtc:Available<number>;maintenanceMarginBtc:Available<number>}
export interface EndpointEconomics {endpoint:string;status:string;triggerTimestamp:string|null;valuationTimestamp:string|null;pnlBtc:number|null;pnlUsd:number|null;closingFeesBtc:number|null;deliveryFeesBtc:number|null;reason:string|null}

const ratio=(pnl:number|null,den:Available<number>,label:string)=>pnl===null?unavailable<number>("The selected Exit-Policy outcome is unpriced."):den.value===null?unavailable<number>(den.reason??`${label} is unavailable.`):den.value<=0?unavailable<number>(`${label} is not a positive denominator.`):available(pnl/den.value);
export function normalizePositionEconomics(dataset:AnalysisDataset,configuration:AnalysisConfiguration):readonly PositionEconomics[]{
 if(configuration.exitPolicy===null)return [];
 const policy=normalizeExitPolicies(dataset,{capitalBasis:configuration.capitalBasis}).filter(x=>(x.analyticsTrack!==null||!configuration.executionAssumption||x.executionScenario===configuration.executionAssumption)&&(x.analyticsTrack!==null||!configuration.pricingTrack||x.pricingTrack===configuration.pricingTrack)&&(!configuration.exitPolicy||x.policyId===configuration.exitPolicy));
 const structureEconomics=indexByCandidate(dataset.tables.structure_economics);
 return policy.map(exit=>{const row=(dataset.tables.candidates??[]).find(c=>c.structure_execution_id===exit.structureExecutionId);const margin=(dataset.tables.margin_scenarios??[]).find(m=>m.candidate_id===exit.candidateId);const quantity=n(row?.quantity),shortPremium=n(at(row?.entry_legs,"short","price_native")),longPremium=n(at(row?.entry_legs,"long","price_native")),openingFees=n(row?.opening_fees_native),entryIndex=n(row?.entry_index_price),shortStrike=n(at(row?.actual_strikes,"short")),longStrike=n(at(row?.actual_strikes,"long")),expiry=s(row?.expiry_timestamp_utc);let maxBtc:Available<number>=unavailable("Exact strikes, premiums, entry index, quantity, fees or expiry are missing."),maxUsd:Available<number>=unavailable(maxBtc.reason!);
  // Canonical structural risk is CONSUMED, not recomputed. This used to call
  // `canonicalStructuralLoss` unconditionally, so Economic Analysis reported a
  // locally derived figure while Spread Width and the futures comparison
  // reported the exported one -- the same canonical concept with two magnitudes
  // and no integrity error. The exported rows now take priority and the local
  // helper remains only as the documented fallback for bundles that carry
  // neither canonical table.
  {const payoffInput:ExpiryPayoffInput|null=(row?.option_type==="C"||row?.option_type==="P")&&shortStrike!==null&&longStrike!==null&&shortPremium!==null&&longPremium!==null&&openingFees!==null&&entryIndex!==null&&quantity!==null&&expiry
   ?{optionType:row.option_type,shortStrike,longStrike,shortEntryPremiumBtc:shortPremium,longEntryPremiumBtc:longPremium,entryIndex,amount:quantity,openingFeesBtc:openingFees,expiryTimestamp:Date.parse(expiry)}
   :null;
   const loss=readCanonicalStructuralLoss({economics:structureEconomics.get(exit.candidateId),margin,fallback:payoffInput});
   if(loss.status==="available"&&loss.usd!==null&&loss.btc!==null){maxBtc=available(loss.btc);maxUsd=available(loss.usd);}
   else{maxBtc=unavailable(loss.reason??"The canonical maximum structural loss is unavailable for this structure.");maxUsd=unavailable(maxBtc.reason!);}}
  const payoffInput:ExpiryPayoffInput|null=(row?.option_type==="C"||row?.option_type==="P")&&shortStrike!==null&&longStrike!==null&&shortPremium!==null&&longPremium!==null&&openingFees!==null&&entryIndex!==null&&quantity!==null&&expiry?{optionType:row.option_type,shortStrike,longStrike,shortEntryPremiumBtc:shortPremium,longEntryPremiumBtc:longPremium,entryIndex,amount:quantity,openingFeesBtc:openingFees,expiryTimestamp:Date.parse(expiry)}:null;
  const trackLossResult=payoffInput?canonicalStructuralLoss(payoffInput):null,trackLossBtc=trackLossResult?.status==="available"&&trackLossResult.btcAtReferenceIndex!==null?available(trackLossResult.btcAtReferenceIndex):unavailable<number>(trackLossResult?.reason??"Track opening economics are incomplete."),trackLossUsd=trackLossResult?.status==="available"&&trackLossResult.usd!==null?available(trackLossResult.usd):unavailable<number>(trackLossResult?.reason??"Track opening economics are incomplete.");
  const supportedAccount=configuration.marginModel==="standard"&&configuration.collateralMode==="segregated",marginReason=configuration.marginModel==="portfolio"?"Unavailable — historical Portfolio Margin simulation is not supported or verified.":configuration.collateralMode==="cross"?"Unavailable — cross-account Standard Margin reconstruction is not supported; only segregated Standard Margin is verified.":"The canonical Standard Margin path is absent or incomplete.";
  const rawPath=margin?.margin_inputs&&typeof margin.margin_inputs==="object"&&Array.isArray((margin.margin_inputs as Record<string,unknown>).path)?(margin.margin_inputs as {path:unknown[]}).path:[],entryMs=exit.entryTimestamp?Date.parse(exit.entryTimestamp):NaN,terminalMs=exit.valuationTimestamp?Date.parse(exit.valuationTimestamp):NaN,pathPoints=rawPath.flatMap(raw=>{const r=raw&&typeof raw==="object"?raw as Record<string,unknown>:{},timestamp=n(r.timestamp),initial=n(r.initialMarginBtc),maintenance=n(r.maintenanceMarginBtc);return timestamp!==null&&initial!==null&&maintenance!==null?[{timestamp,initial,maintenance}]:[]}).filter(p=>p.timestamp>=entryMs&&p.timestamp<=terminalMs).sort((a,b)=>a.timestamp-b.timestamp);
  const pathComplete=supportedAccount&&margin?.margin_status==="available"&&Number.isFinite(entryMs)&&Number.isFinite(terminalMs)&&terminalMs>=entryMs&&pathPoints.length>0&&pathPoints[0]!.timestamp===entryMs;
  const pathUnavailable=unavailable<number>(supportedAccount?"The canonical Standard Margin path does not begin at the track entry or is incomplete through the selected-policy window.":marginReason),openingIm=pathComplete?available(pathPoints[0]!.initial):pathUnavailable,openingMm=pathComplete?available(pathPoints[0]!.maintenance):pathUnavailable,peakInitialPoint=pathComplete?pathPoints.reduce((a,b)=>b.initial>a.initial?b:a):null,peakMaintenancePoint=pathComplete?pathPoints.reduce((a,b)=>b.maintenance>a.maintenance?b:a):null,peakIm=peakInitialPoint?available(peakInitialPoint.initial):pathUnavailable,peakMm=peakMaintenancePoint?available(peakMaintenancePoint.maintenance):pathUnavailable;
  let integrated=0;if(pathComplete)for(let i=0;i<pathPoints.length;i++){const end=Math.min(terminalMs,pathPoints[i+1]?.timestamp??terminalMs);integrated+=pathPoints[i]!.initial*Math.max(0,end-pathPoints[i]!.timestamp)/864e5}const capitalDays=pathComplete?available(integrated):pathUnavailable;
  const holding=exit.holdingHours===null?null:exit.holdingHours/24,riskMin=configuration.maximumRiskFraction&&trackLossBtc.value!==null?available(trackLossBtc.value/configuration.maximumRiskFraction):unavailable<number>(configuration.maximumRiskFraction===null?"maximumRiskFraction is not configured.":trackLossBtc.reason!);const marginMin=configuration.maximumMarginUtilization&&peakIm.value!==null?available(peakIm.value/configuration.maximumMarginUtilization):unavailable<number>(configuration.maximumMarginUtilization===null?"maximumMarginUtilization is not configured.":peakIm.reason!);const complete=riskMin.value!==null&&marginMin.value!==null;const binding=complete?(riskMin.value!>=marginMin.value!?"risk":"margin"):null;
  const closing=exit.winningTrigger&&exit.valuationTimestamp?(dataset.tables.outcomes??[]).find(o=>o.candidate_id===exit.candidateId&&o.execution_scenario===exit.executionScenario&&o.outcome_type===exit.winningTrigger):undefined;const exitIndex=n(closing?.target_underlying_index)??n(closing?.settlement_index_price);const unsShort=n(at(row?.entry_legs,"short","unslipped_price_native")),unsLong=n(at(row?.entry_legs,"long","unslipped_price_native"));const adjustment=quantity!==null&&shortPremium!==null&&longPremium!==null&&unsShort!==null&&unsLong!==null?((shortPremium-longPremium)-(unsShort-unsLong))*quantity:null;
  // The legacy exit normalizer preserves the source settlement fee in both fields for
  // compatibility. Economics gives it one economic identity: delivery, never closing execution.
  const deliveryFee=exit.winningTrigger==="settlement"?exit.deliveryFeesBtc:exit.deliveryFeesBtc??0,closingExecutionFee=exit.winningTrigger==="settlement"?0:exit.closingFeesBtc;
  const totalFees=openingFees!==null&&closingExecutionFee!==null&&deliveryFee!==null?openingFees+closingExecutionFee+deliveryFee:null;
  const outcomeRows=(dataset.tables.outcomes??[]).filter(o=>o.candidate_id===exit.candidateId&&(!exit.analyticsTrack||!o.analytics_track||o.analytics_track===exit.analyticsTrack));
  const endpoints:EndpointEconomics[]=outcomeRows.map(o=>({endpoint:String(o.outcome_type??"unknown"),status:String(o.status??o.trigger_status??"unavailable"),triggerTimestamp:s(o.trigger_timestamp_utc),valuationTimestamp:s(o.valuation_timestamp_utc),pnlBtc:n(o.net_pnl_native),pnlUsd:n(o.net_pnl_usd),closingFeesBtc:n(o.closing_fees_native),deliveryFeesBtc:String(o.outcome_type).includes("settlement")?n(o.delivery_fees_native)??n(o.closing_fees_native):0,reason:s(o.evidence_reason)}));
  const marginInput=margin?.margin_inputs&&typeof margin.margin_inputs==="object"?margin.margin_inputs as Record<string,unknown>:null,marginPath=supportedAccount&&Array.isArray(marginInput?.path)?marginInput.path:[];
  const marginByTime=new Map(marginPath.flatMap(raw=>{const r=raw&&typeof raw==="object"?raw as Record<string,unknown>:{},ms=n(r.timestamp),ts=s(r.timestamp_utc)??(ms!==null?new Date(ms).toISOString():null);return ts?[ [ts,{im:n(r.initialMarginBtc),mm:n(r.maintenanceMarginBtc)}] as const]:[]}));
  const valuationRows=(dataset.tables.valuations??[]).filter(v=>v.candidate_id===exit.candidateId&&(!exit.analyticsTrack||v.analytics_track===exit.analyticsTrack)&&s(v.timestamp_utc)!==null).filter(v=>!exit.valuationTimestamp||Date.parse(String(v.timestamp_utc))<=Date.parse(exit.valuationTimestamp));
  const path:EconomicPathPoint[]=valuationRows.map(v=>{const ts=String(v.timestamp_utc),m=marginByTime.get(ts),p=n(v.net_pnl_native);return{timestamp:ts,pnlBtc:p===null?unavailable<number>(s(v.evidence_reason)??"Canonical position mark is unavailable."):available(p),index:n(v.underlying_index)??n(v.index_price),initialMarginBtc:m?.im===null||m?.im===undefined?unavailable<number>("Contemporaneous verified IM is unavailable."):available(m.im),maintenanceMarginBtc:m?.mm===null||m?.mm===undefined?unavailable<number>("Contemporaneous verified MM is unavailable."):available(m.mm)}}).sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp));
  return {sourceRun:exit.sourceRun,analyticsTrack:exit.analyticsTrack,eventId:exit.eventId,candidateId:exit.candidateId,structureExecutionId:exit.structureExecutionId,executionScenario:exit.executionScenario,pricingTrack:exit.pricingTrack,exitPolicy:exit.policyId,status:exit.status,missingReason:exit.missingDataReason,direction:s(row?.direction),optionType:s(row?.option_type),instruments:row?.instruments??null,expiryTimestamp:expiry,entryTimestamp:exit.entryTimestamp,exitTimestamp:exit.valuationTimestamp,actualDteDays:n(row?.actual_dte_days)??n(row?.actual_dte),shortStrike,longStrike,actualWidth:n(at(row?.actual_strikes,"width")),quantity,shortPremiumBtc:shortPremium,longPremiumBtc:longPremium,grossOpeningCreditBtc:n(row?.gross_credit_debit_native),openingFeesBtc:openingFees,netOpeningCashFlowBtc:n(row?.net_opening_cash_flow_native),executionAdjustmentBtc:adjustment,entryIndex,winningTrigger:exit.winningTrigger,exitIndex,closingCashFlowBtc:n(closing?.scaled_closing_cash_flow_native),closingFeesBtc:closingExecutionFee,deliveryFeesBtc:deliveryFee,totalRealizedFeesBtc:totalFees,pnlBtc:exit.pnlBtc,pnlUsd:exit.pnlUsd,maximumStructuralLossBtc:maxBtc,maximumStructuralLossUsd:maxUsd,trackMaximumNetLossBtc:trackLossBtc,trackMaximumNetLossUsd:trackLossUsd,incrementalInitialMarginBtc:openingIm,incrementalMaintenanceMarginBtc:openingMm,peakInitialMarginBtc:peakIm,peakMaintenanceMarginBtc:peakMm,peakMarginTimestamp:peakInitialPoint?new Date(peakInitialPoint.timestamp).toISOString():null,peakInitialMarginTimestamp:peakInitialPoint?new Date(peakInitialPoint.timestamp).toISOString():null,peakMaintenanceMarginTimestamp:peakMaintenancePoint?new Date(peakMaintenancePoint.timestamp).toISOString():null,holdingDays:holding,capitalDaysBtc:capitalDays,returnOnStructuralLoss:ratio(exit.pnlBtc,maxBtc,"canonical Reference structural loss"),returnOnTrackMaximumNetLoss:ratio(exit.pnlBtc,trackLossBtc,"track maximum net loss"),returnOnOpeningMargin:ratio(exit.pnlBtc,openingIm,"opening margin"),returnOnPeakCapital:ratio(exit.pnlBtc,peakIm,"policy-window peak capital"),riskMinimumEquityBtc:riskMin,marginMinimumEquityBtc:marginMin,minimumEquityBtc:complete?available(Math.max(riskMin.value!,marginMin.value!)):unavailable("Both track-risk and verified policy-window peak-margin constraints are required for a complete minimum."),bindingConstraint:binding,endpoints,path,strikeMethod:s(row?.strike_method),requestedWidth:n(row?.requested_width),structureType:s(row?.structure_type)??"vertical"} satisfies PositionEconomics;});
}
