import type {AnalysisDataset} from "../research-analysis.ts";
import type {AnalysisConfiguration} from "../analysis-configuration.ts";
import {normalizeExitPolicies,type PolicyObservation} from "../exit-policy/normalize.ts";
import type {ExpiryPayoffInput} from "../expiry-payoff.ts";
import {indexByCandidate,readCanonicalStructuralLoss} from "../canonical-structural-loss.ts";

export interface Available<T>{value:T|null;reason:string|null}
const available=<T,>(value:T):Available<T>=>({value,reason:null});
const unavailable=<T,>(reason:string):Available<T>=>({value:null,reason});
const n=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:null;
const s=(v:unknown)=>typeof v==="string"&&v?v:null;
const at=(v:unknown,...keys:string[])=>keys.reduce<unknown>((x,k)=>x&&typeof x==="object"&&!Array.isArray(x)?(x as Record<string,unknown>)[k]:null,v);
export interface PositionEconomics {sourceRun:string;eventId:string;candidateId:string;structureExecutionId:string;executionScenario:"maker"|"taker";pricingTrack:"raw_vwap"|"iv_normalized";exitPolicy:string;status:PolicyObservation["status"];missingReason:string|null;direction:string|null;optionType:string|null;instruments:unknown;expiryTimestamp:string|null;entryTimestamp:string|null;exitTimestamp:string|null;actualDteDays:number|null;shortStrike:number|null;longStrike:number|null;actualWidth:number|null;quantity:number|null;shortPremiumBtc:number|null;longPremiumBtc:number|null;grossOpeningCreditBtc:number|null;openingFeesBtc:number|null;netOpeningCashFlowBtc:number|null;executionAdjustmentBtc:number|null;entryIndex:number|null;winningTrigger:string|null;exitIndex:number|null;closingCashFlowBtc:number|null;closingFeesBtc:number|null;deliveryFeesBtc:number|null;totalRealizedFeesBtc:number|null;pnlBtc:number|null;pnlUsd:number|null;maximumStructuralLossBtc:Available<number>;maximumStructuralLossUsd:Available<number>;incrementalInitialMarginBtc:Available<number>;incrementalMaintenanceMarginBtc:Available<number>;peakInitialMarginBtc:Available<number>;peakMaintenanceMarginBtc:Available<number>;peakMarginTimestamp:string|null;holdingDays:number|null;capitalDaysBtc:Available<number>;returnOnStructuralLoss:Available<number>;returnOnOpeningMargin:Available<number>;returnOnPeakCapital:Available<number>;riskMinimumEquityBtc:Available<number>;marginMinimumEquityBtc:Available<number>;minimumEquityBtc:Available<number>;bindingConstraint:"risk"|"margin"|null}

const ratio=(pnl:number|null,den:Available<number>,label:string)=>pnl===null?unavailable<number>("The selected Exit-Policy outcome is unpriced."):den.value===null?unavailable<number>(den.reason??`${label} is unavailable.`):den.value<=0?unavailable<number>(`${label} is not a positive denominator.`):available(pnl/den.value);
export function normalizePositionEconomics(dataset:AnalysisDataset,configuration:AnalysisConfiguration):readonly PositionEconomics[]{
 const policy=normalizeExitPolicies(dataset).filter(x=>(!configuration.executionAssumption||x.executionScenario===configuration.executionAssumption)&&(!configuration.pricingTrack||x.pricingTrack===configuration.pricingTrack)&&(!configuration.exitPolicy||x.policyId===configuration.exitPolicy));
 const structureEconomics=indexByCandidate(dataset.tables.structure_economics);
 return policy.map(exit=>{const row=(dataset.tables.candidates??[]).find(c=>c.structure_execution_id===exit.structureExecutionId);const margin=(dataset.tables.margin_scenarios??[]).find(m=>m.candidate_id===exit.candidateId);const quantity=n(row?.quantity),shortPremium=n(at(row?.entry_legs,"short","price_native")),longPremium=n(at(row?.entry_legs,"long","price_native")),openingFees=n(row?.opening_fees_native),entryIndex=n(row?.entry_index_price),shortStrike=n(at(row?.actual_strikes,"short")),longStrike=n(at(row?.actual_strikes,"long")),expiry=s(row?.expiry_timestamp_utc);let maxBtc:Available<number>=unavailable("Exact strikes, premiums, entry index, quantity, fees or expiry are missing."),maxUsd:Available<number>=unavailable(maxBtc.reason!);
  // Canonical structural risk is CONSUMED, not recomputed. This used to call
  // `canonicalStructuralLoss` unconditionally, so Economic Analysis reported a
  // locally derived figure while Spread Width and the futures comparison
  // reported the exported one -- the same canonical concept with two magnitudes
  // and no integrity error. The exported rows now take priority and the local
  // helper remains only as the documented fallback for bundles that carry
  // neither canonical table.
  {const payoffInput:ExpiryPayoffInput|null=(row?.option_type==="C"||row?.option_type==="P")&&shortStrike!==null&&longStrike!==null&&shortPremium!==null&&longPremium!==null&&openingFees!==null&&entryIndex!==null&&quantity!==null&&expiry
   ?{optionType:row.option_type,shortStrike,longStrike,shortEntryPremiumBtc:shortPremium,longEntryPremiumBtc:longPremium,entryIndex,amount:quantity,openingFeesBtc:openingFees,expiryTimestamp:Date.parse(expiry)}
   :null;
   const loss=readCanonicalStructuralLoss({economics:structureEconomics.get(exit.candidateId),margin,fallback:payoffInput});
   if(loss.status==="available"&&loss.usd!==null&&loss.btc!==null){maxBtc=available(loss.btc);maxUsd=available(loss.usd);}
   else{maxBtc=unavailable(loss.reason??"The canonical maximum structural loss is unavailable for this structure.");maxUsd=unavailable(maxBtc.reason!);}}
  const marginReason=configuration.marginModel==="portfolio"?"Portfolio Margin requires a verified portfolio-state simulation; Standard Margin is not substituted.":"The canonical margin scenario does not contain a verified value.";const mv=(key:string):Available<number>=>margin?.margin_status==="available"&&n(margin[key])!==null?available(n(margin[key])!):unavailable(marginReason);const im=mv("incremental_initial_margin"),mm=mv("incremental_maintenance_margin"),peakIm=mv("peak_initial_margin"),peakMm=mv("peak_maintenance_margin");
  const holding=exit.holdingHours===null?null:exit.holdingHours/24,canonicalCapitalDays=margin?.margin_status==="available"?n(margin.capital_days_margin):null,capitalDays=canonicalCapitalDays!==null?available(canonicalCapitalDays):unavailable<number>(margin?.margin_status==="available"?"Canonical margin path capital-days are unavailable.":peakIm.reason??"Verified margin is unavailable.");const riskMin=configuration.maximumRiskFraction&&maxBtc.value!==null?available(maxBtc.value/configuration.maximumRiskFraction):unavailable<number>(configuration.maximumRiskFraction===null?"maximumRiskFraction is not configured.":maxBtc.reason!);const marginMin=configuration.maximumMarginUtilization&&peakIm.value!==null?available(peakIm.value/configuration.maximumMarginUtilization):unavailable<number>(configuration.maximumMarginUtilization===null?"maximumMarginUtilization is not configured.":peakIm.reason!);const complete=riskMin.value!==null&&marginMin.value!==null;const binding=complete?(riskMin.value!>=marginMin.value!?"risk":"margin"):null;
  const closing=exit.winningTrigger&&exit.valuationTimestamp?(dataset.tables.outcomes??[]).find(o=>o.candidate_id===exit.candidateId&&o.execution_scenario===exit.executionScenario&&o.outcome_type===exit.winningTrigger):undefined;const exitIndex=n(closing?.target_underlying_index)??n(closing?.settlement_index_price);const unsShort=n(at(row?.entry_legs,"short","unslipped_price_native")),unsLong=n(at(row?.entry_legs,"long","unslipped_price_native"));const adjustment=quantity!==null&&shortPremium!==null&&longPremium!==null&&unsShort!==null&&unsLong!==null?((shortPremium-longPremium)-(unsShort-unsLong))*quantity:null;
  return {sourceRun:exit.sourceRun,eventId:exit.eventId,candidateId:exit.candidateId,structureExecutionId:exit.structureExecutionId,executionScenario:exit.executionScenario,pricingTrack:exit.pricingTrack,exitPolicy:exit.policyId,status:exit.status,missingReason:exit.missingDataReason,direction:s(row?.direction),optionType:s(row?.option_type),instruments:row?.instruments??null,expiryTimestamp:expiry,entryTimestamp:exit.entryTimestamp,exitTimestamp:exit.valuationTimestamp,actualDteDays:n(row?.actual_dte_days)??n(row?.actual_dte),shortStrike,longStrike,actualWidth:n(at(row?.actual_strikes,"width")),quantity,shortPremiumBtc:shortPremium,longPremiumBtc:longPremium,grossOpeningCreditBtc:n(row?.gross_credit_debit_native),openingFeesBtc:openingFees,netOpeningCashFlowBtc:n(row?.net_opening_cash_flow_native),executionAdjustmentBtc:adjustment,entryIndex,winningTrigger:exit.winningTrigger,exitIndex,closingCashFlowBtc:n(closing?.scaled_closing_cash_flow_native),closingFeesBtc:exit.closingFeesBtc,deliveryFeesBtc:exit.deliveryFeesBtc,totalRealizedFeesBtc:openingFees!==null&&exit.closingFeesBtc!==null?openingFees+exit.closingFeesBtc:null,pnlBtc:exit.pnlBtc,pnlUsd:exit.pnlUsd,maximumStructuralLossBtc:maxBtc,maximumStructuralLossUsd:maxUsd,incrementalInitialMarginBtc:im,incrementalMaintenanceMarginBtc:mm,peakInitialMarginBtc:peakIm,peakMaintenanceMarginBtc:peakMm,peakMarginTimestamp:s(margin?.peak_timestamp_utc),holdingDays:holding,capitalDaysBtc:capitalDays,returnOnStructuralLoss:ratio(exit.pnlBtc,maxBtc,"maximum structural loss"),returnOnOpeningMargin:ratio(exit.pnlBtc,im,"opening margin"),returnOnPeakCapital:ratio(exit.pnlBtc,peakIm,"peak capital"),riskMinimumEquityBtc:riskMin,marginMinimumEquityBtc:marginMin,minimumEquityBtc:complete?available(Math.max(riskMin.value!,marginMin.value!)):unavailable("Both risk and verified peak-margin constraints are required for a complete minimum."),bindingConstraint:binding} satisfies PositionEconomics;});
}
