import type {AnalysisDataset} from "../research-analysis.ts";
import type {AnalysisConfiguration} from "../analysis-configuration.ts";
import {validateEconomicPolicy} from "../analysis-configuration.ts";
import {normalizePositionEconomics} from "./position.ts";
import {reconstructPortfolio} from "./portfolio.ts";
import {datasetForAnalyticsTrack,type AnalyticsTrack} from "../research-analytics-model.ts";
function economicLayer(dataset:AnalysisDataset,configuration:AnalysisConfiguration){const positions=normalizePositionEconomics(dataset,configuration),portfolio=reconstructPortfolio(positions,configuration);return{positions,portfolio};}
export function buildEconomicReport(dataset:AnalysisDataset,configuration:AnalysisConfiguration){const reference=economicLayer(datasetForAnalyticsTrack(dataset,"reference"),{...configuration,pricingTrack:"raw_vwap",executionAssumption:"maker"});const observed={maker:economicLayer(dataset,{...configuration,executionAssumption:"maker"}),taker:economicLayer(dataset,{...configuration,executionAssumption:"taker"})};const modeled=Object.fromEntries((["modeled_expected","modeled_conservative","penalty_sensitivity"] as AnalyticsTrack[]).map(track=>[track,economicLayer(datasetForAnalyticsTrack(dataset,track),{...configuration,pricingTrack:"raw_vwap",executionAssumption:"maker"})]));const positions=reference.positions,portfolio=reference.portfolio;return{configuration:{executionScenario:"reference",pricingTrack:"reference",exitPolicy:configuration.exitPolicy,marginModel:configuration.marginModel,collateralMode:configuration.collateralMode,maximumRiskFraction:configuration.maximumRiskFraction,maximumMarginUtilization:configuration.maximumMarginUtilization},configurationErrors:validateEconomicPolicy(configuration),capabilities:{maximumLoss:positions.some(x=>x.maximumEconomicLossBtc.value!==null),openingMargin:positions.some(x=>x.incrementalInitialMarginBtc.value!==null),peakMargin:positions.some(x=>x.peakInitialMarginBtc.value!==null),portfolioMargin:false},positions,portfolio,reference,observed,modeled,modeledStatus:"Uncalibrated sensitivity" as const};}
export type EconomicReport=ReturnType<typeof buildEconomicReport>;
