import type {AnalysisDataset} from "../research-analysis.ts";
import type {AnalysisConfiguration} from "../analysis-configuration.ts";
import {validateEconomicPolicy} from "../analysis-configuration.ts";
import {normalizePositionEconomics,type PositionEconomics} from "./position.ts";
import {reconstructPortfolio} from "./portfolio.ts";
import {datasetForAnalyticsTrack,type AnalyticsTrack,ANALYTICS_TRACK_METADATA} from "../research-analytics-model.ts";
export interface PortfolioCohort {status:"available"|"not_estimable";positions:readonly PositionEconomics[];reason:string|null;ambiguousEventIds:readonly string[]}
/** A research matrix is not a portfolio. Canonical structural fields must identify no more than one selected structure per MR event. */
export function validatePortfolioCohort(positions:readonly PositionEconomics[]):PortfolioCohort{const priced=positions.filter(p=>p.status==="priced"),byEvent=new Map<string,PositionEconomics[]>();for(const p of priced){const rows=byEvent.get(p.eventId)??[];rows.push(p);byEvent.set(p.eventId,rows)}const ambiguous=[...byEvent].filter(([,rows])=>new Set(rows.map(p=>[p.actualDteDays,p.strikeMethod,p.requestedWidth,p.actualWidth,p.quantity].join("|"))).size>1).map(([id])=>id).sort();return ambiguous.length?{status:"not_estimable",positions:[],ambiguousEventIds:ambiguous,reason:`Portfolio strategy selection is not unique for ${ambiguous.length} MR event(s): ${ambiguous.slice(0,5).join(", ")}${ambiguous.length>5?"…":""}. Select one canonical DTE/strike/width/quantity scenario.`}:{status:"available",positions:[...byEvent.values()].map(rows=>rows.sort((a,b)=>a.candidateId.localeCompare(b.candidateId))[0]!),ambiguousEventIds:[],reason:null}}
function economicLayer(dataset:AnalysisDataset,configuration:AnalysisConfiguration){const positions=normalizePositionEconomics(dataset,configuration),cohort=validatePortfolioCohort(positions),portfolio=cohort.status==="available"?reconstructPortfolio(cohort.positions,configuration):null;return{positions,portfolio,cohort};}
const layer=(dataset:AnalysisDataset,track:AnalyticsTrack,configuration:AnalysisConfiguration)=>economicLayer(datasetForAnalyticsTrack(dataset,track),{...configuration,pricingTrack:null,executionAssumption:null});
export function buildEconomicReport(dataset:AnalysisDataset,configuration:AnalysisConfiguration){
 const reference=layer(dataset,"reference",configuration),central=layer(dataset,"modeled_expected",configuration),conservative=layer(dataset,"modeled_conservative",configuration);
 const observed={maker:layer(dataset,"immediate_maker",configuration),taker:layer(dataset,"immediate_taker",configuration)};
 const modeled={modeled_expected:central,modeled_conservative:conservative,penalty_sensitivity:layer(dataset,"penalty_sensitivity",configuration)};
 const delayed={delayed_maker:layer(dataset,"delayed_maker",configuration),delayed_taker:layer(dataset,"delayed_taker",configuration)};
 const positions=central.positions,portfolio=central.portfolio;
 return{configuration:{executionScenario:null,pricingTrack:null,exitPolicy:configuration.exitPolicy,marginModel:configuration.marginModel,collateralMode:configuration.collateralMode,capitalBasis:configuration.capitalBasis,accountEquity:configuration.accountEquity,maximumRiskFraction:configuration.maximumRiskFraction,maximumMarginUtilization:configuration.maximumMarginUtilization,maximumDrawdown:configuration.maximumDrawdown},configurationErrors:validateEconomicPolicy(configuration),capabilities:{structuralLoss:positions.some(x=>x.maximumStructuralLossBtc.value!==null),openingMargin:positions.some(x=>x.incrementalInitialMarginBtc.value!==null),peakMargin:positions.some(x=>x.peakInitialMarginBtc.value!==null),portfolioMargin:false},positions,portfolio,portfolioCohort:central.cohort,central,reference,conservative,observed,delayed,modeled,modeledMethodology:{centralTrack:"modeled_expected",estimatorVersion:"empirical-taker-execution-v1",modeledExecutionVersion:"modeled-execution-v5-empirical-taker",centralCoverage:{available:positions.filter(x=>x.status==="priced").length,total:dataset.tables.availability?.length??positions.length},conservativeCoverage:{available:conservative.positions.filter(x=>x.status==="priced").length,total:dataset.tables.availability?.length??conservative.positions.length}}};
}
export type EconomicReport=ReturnType<typeof buildEconomicReport>;
export type EconomicLayerRole="central"|"counterfactual"|"conservative"|"diagnostic"|"sensitivity";
export interface EconomicLayerSummary {readonly track:AnalyticsTrack;readonly label:string;readonly role:EconomicLayerRole;readonly status:"available"|"unavailable";readonly reason:string|null;readonly totalOpportunities:number;readonly pricedPositions:number;readonly unavailablePositions:number;readonly eventsRepresented:number;readonly medianGrossCreditBtc:number|null;readonly medianNetOpeningCreditBtc:number|null;readonly medianExecutionAdjustmentBtc:number|null;readonly medianTotalRealizedFeesBtc:number|null;readonly medianExitPnlBtc:number|null;readonly medianStructuralLossBtc:number|null;readonly medianReturnOnStructuralLoss:number|null;readonly medianReturnOnOpeningMargin:number|null;readonly medianReturnOnPeakCapital:number|null;readonly medianHoldingDays:number|null;readonly medianCapitalDaysBtc:number|null;readonly effectiveN:Readonly<Record<string,number>>}
const med=(v:readonly(number|null)[])=>{const a=v.filter((x):x is number=>x!==null&&Number.isFinite(x)).sort((x,y)=>x-y);if(!a.length)return null;const m=a.length>>1;return a.length%2?a[m]!:(a[m-1]!+a[m]!)/2};
function summary(track:AnalyticsTrack,p:readonly PositionEconomics[],total:number):EconomicLayerSummary{const priced=p.filter(x=>x.status==="priced"),role:EconomicLayerRole=track==="modeled_expected"?"central":track==="reference"?"counterfactual":track==="modeled_conservative"?"conservative":track==="penalty_sensitivity"?"sensitivity":"diagnostic",count=(values:readonly (number|null)[])=>values.filter(x=>x!==null&&Number.isFinite(x)).length;const values={gross:priced.map(x=>x.grossOpeningCreditBtc),net:priced.map(x=>x.netOpeningCashFlowBtc),adjustment:priced.map(x=>x.executionAdjustmentBtc),fees:priced.map(x=>x.totalRealizedFeesBtc),pnl:priced.map(x=>x.pnlBtc),loss:priced.map(x=>x.maximumStructuralLossBtc.value),rosl:priced.map(x=>x.returnOnStructuralLoss.value),roim:priced.map(x=>x.returnOnOpeningMargin.value),rop:priced.map(x=>x.returnOnPeakCapital.value),holding:priced.map(x=>x.holdingDays),capitalDays:priced.map(x=>x.capitalDaysBtc.value)};return{track,label:ANALYTICS_TRACK_METADATA[track].label,role,status:priced.length?"available":"unavailable",reason:priced.length?null:p.find(x=>x.missingReason)?.missingReason??"No priced position.",totalOpportunities:total,pricedPositions:priced.length,unavailablePositions:Math.max(0,total-priced.length),eventsRepresented:new Set(priced.map(x=>x.eventId)).size,medianGrossCreditBtc:med(values.gross),medianNetOpeningCreditBtc:med(values.net),medianExecutionAdjustmentBtc:med(values.adjustment),medianTotalRealizedFeesBtc:med(values.fees),medianExitPnlBtc:med(values.pnl),medianStructuralLossBtc:med(values.loss),medianReturnOnStructuralLoss:med(values.rosl),medianReturnOnOpeningMargin:med(values.roim),medianReturnOnPeakCapital:med(values.rop),medianHoldingDays:med(values.holding),medianCapitalDaysBtc:med(values.capitalDays),effectiveN:Object.fromEntries(Object.entries(values).map(([k,v])=>[k,count(v)]))};}
export function economicLayerSummaries(report:EconomicReport){const total=Math.max(report.modeledMethodology.centralCoverage.total,report.positions.length);return [summary("reference",report.reference.positions,total),summary("modeled_expected",report.central.positions,total),summary("modeled_conservative",report.conservative.positions,total),summary("immediate_maker",report.observed.maker.positions,total),summary("immediate_taker",report.observed.taker.positions,total),summary("delayed_maker",report.delayed.delayed_maker.positions,total),summary("delayed_taker",report.delayed.delayed_taker.positions,total),summary("penalty_sensitivity",report.modeled.penalty_sensitivity.positions,total)];}
