import type {AnalysisDataset} from "../research-analysis.ts";
import type {AnalyticsTrack} from "../research-analytics-model.ts";
import {classifyEconomicOpportunity} from "./opportunity.ts";
import type {PositionEconomics} from "./position.ts";
import {structuralConfigurationIdentity} from "./strategy-configuration.ts";

export type Q50EvidenceContradictionCode="explicit_no_trade_conflicts_with_priced_position"|"unavailable_q50_opportunity_conflicts_with_priced_position";
export interface CanonicalTrackOpportunity {eventId:string;structuralConfigurationId:string;candidateId?:string|null;q50Status:"trade"|"explicit_no_trade"|"unavailable"}
export interface Q50EvidenceContradiction {identity:string;eventId:string;structuralConfigurationId:string;reasonCode:Q50EvidenceContradictionCode}
export const structuralEvidenceKey=(eventId:string,configurationId:string)=>`${eventId}|${configurationId}`;
export const positionStructuralEvidenceKey=(position:PositionEconomics)=>structuralEvidenceKey(position.eventId,position.structuralConfigurationId??"");

export function canonicalTrackOpportunities(dataset:AnalysisDataset):readonly CanonicalTrackOpportunity[]{return(dataset.tables.configuration_opportunities??[]).flatMap(row=>{const identity=structuralConfigurationIdentity(row),eventId=typeof row.event_id==="string"?row.event_id:"",structuralConfigurationId=typeof row.structural_configuration_id==="string"?row.structural_configuration_id:identity.id;if(!eventId||!structuralConfigurationId||identity.reason)return[];return[{eventId,structuralConfigurationId,candidateId:typeof row.candidate_id==="string"?row.candidate_id:null,q50Status:classifyEconomicOpportunity(row.economic_opportunity).status}]})}

export function applyCanonicalTrackEvidence(opportunities:readonly CanonicalTrackOpportunity[],positions:readonly PositionEconomics[],track:AnalyticsTrack){const opportunityGroups=new Map<string,CanonicalTrackOpportunity[]>();for(const opportunity of opportunities){const identity=structuralEvidenceKey(opportunity.eventId,opportunity.structuralConfigurationId),rows=opportunityGroups.get(identity)??[];rows.push(opportunity);opportunityGroups.set(identity,rows)}const byIdentity=new Map([...opportunityGroups].flatMap(([identity,rows])=>rows.length===1?[[identity,rows[0]!] as const]:[])),contradictions:Q50EvidenceContradiction[]=[];const eligible=positions.filter(position=>{const identity=positionStructuralEvidenceKey(position),opportunity=byIdentity.get(identity);if(!opportunity||opportunity.candidateId===null||(opportunity.candidateId!==undefined&&position.candidateId!==opportunity.candidateId))return false;if(track!=="modeled_expected"||opportunity.q50Status==="trade")return true;if(position.status==="priced")contradictions.push({identity,eventId:opportunity.eventId,structuralConfigurationId:opportunity.structuralConfigurationId,reasonCode:opportunity.q50Status==="explicit_no_trade"?"explicit_no_trade_conflicts_with_priced_position":"unavailable_q50_opportunity_conflicts_with_priced_position"});return false}),index=indexUniqueStructuralEvidence(eligible);return{admissiblePositions:[...index.unique.values()],contradictions,duplicateIdentities:[...index.duplicates.keys()]}}

export function indexUniqueStructuralEvidence(positions:readonly PositionEconomics[]){const grouped=new Map<string,PositionEconomics[]>();for(const position of positions){const identity=positionStructuralEvidenceKey(position),rows=grouped.get(identity)??[];rows.push(position);grouped.set(identity,rows)}const unique=new Map<string,PositionEconomics>(),duplicates=new Map<string,readonly PositionEconomics[]>();for(const[identity,rows]of grouped)if(rows.length===1)unique.set(identity,rows[0]!);else duplicates.set(identity,rows);return{unique,duplicates}}
