"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import type {ImportResult} from "../../lib/research-analysis";
import {createResearchImportWorker,type ImportStage,type WorkerImportMessage} from "../../lib/research-analysis-worker-client";
import {DurationDteReportView} from "../duration-dte-report";
import {StructurePolicyEconomicsReport} from "../structure-policy-economics-report";
import {DEFAULT_ANALYSIS_CONFIGURATION,type AnalysisConfiguration} from "../../lib/portfolio-strategy-analysis";
import {AnalysisConfigurationForm,PortfolioStrategyReport} from "../portfolio-strategy-report";
import {UnderlyingResolutionReportView} from "../underlying-resolution-report";
import {buildResearchReport,createResearchPdf} from "../../lib/research-report";

export function ResearchAnalytics(){
 const [bundle,setBundle]=useState<File>(),[companion,setCompanion]=useState<File>(),[result,setResult]=useState<ImportResult>(),[importing,setImporting]=useState(false),[stage,setStage]=useState<ImportStage>(),[configuration,setConfiguration]=useState<AnalysisConfiguration>(DEFAULT_ANALYSIS_CONFIGURATION),input=useRef<HTMLInputElement>(null),workerRef=useRef<Worker|null>(null),requestId=useRef(0);
 useEffect(()=>()=>workerRef.current?.terminate(),[]);
 async function load(b=bundle,c=companion){if(!b)return;const id=++requestId.current;setImporting(true);setStage("reading-archive");setResult(undefined);try{const [bytes,companionText]=await Promise.all([b.arrayBuffer(),c?.text()]);workerRef.current?.terminate();const worker=createResearchImportWorker();workerRef.current=worker;worker.onmessage=(event:MessageEvent<WorkerImportMessage>)=>{const msg=event.data;if(msg.id!==requestId.current)return;if(msg.type==="stage")setStage(msg.stage);else{setResult(msg.result);setImporting(false);setStage(undefined);worker.terminate();if(workerRef.current===worker)workerRef.current=null;}};worker.onerror=()=>{if(id===requestId.current){setResult({status:"invalid",errors:["Research bundle worker failed."]});setImporting(false);setStage(undefined)}};worker.postMessage({id,bytes:new Uint8Array(bytes),filename:b.name,companionText},[bytes]);}catch(error){if(id===requestId.current){setResult({status:"invalid",errors:[error instanceof Error?error.message:"Research bundle import failed."]});setImporting(false);setStage(undefined)}}}
 function choose(file?:File){requestId.current++;setBundle(file);setResult(undefined);setStage(undefined);if(file)void load(file,companion)}
 const d=result&&result.status!=="invalid"?result.dataset:undefined,reportResult=useMemo(()=>{if(!d)return undefined;try{return{report:buildResearchReport(d,configuration)}}catch(error){return{error:error instanceof Error?error.message:"Unexpected report calculation error."}}},[d,configuration]),report=reportResult&&"report" in reportResult?reportResult.report:undefined,reportError=reportResult&&"error" in reportResult?reportResult.error:undefined;
 function exportPdf(){if(!report||!report.portfolio.configured)return;const bytes=createResearchPdf(report),blob=new Blob([bytes as BlobPart],{type:"application/pdf"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`research-analysis_${report.identity.datasetId}_${report.identity.analysisRunId}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0)}
 return <section className="research-import" aria-labelledby="research-analytics-title"><p className="shell-eyebrow">Options Lab · Complete report</p><h1 id="research-analytics-title">Research Analytics</h1><p className="import-intro">One immutable analysis result powers the workspace and the downloadable vector PDF. Validation is local; no exchange requests are made.</p>
 <div className="drop-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0])}}><input ref={input} hidden type="file" accept=".zip,application/zip" onChange={e=>choose(e.target.files?.[0])}/><strong>Drop research-bundle ZIP here</strong><button onClick={()=>input.current?.click()}>Choose bundle</button></div><div className="import-controls"><label>Optional canonical trade dataset<input type="file" accept=".json,application/json" onChange={e=>{const f=e.target.files?.[0];setCompanion(f);if(bundle)void load(bundle,f)}}/></label>{bundle&&<><span>{bundle.name}</span><button disabled={importing} onClick={()=>void load()}>Reload</button><button onClick={()=>{requestId.current++;workerRef.current?.terminate();setBundle(undefined);setCompanion(undefined);setResult(undefined);setImporting(false);setStage(undefined)}}>Remove</button></>}</div>
 {importing&&<div className="preflight degraded" aria-live="polite"><h2>Importing research bundle…</h2><p>{stage?.replaceAll("-"," ")??"Preparing import"}</p></div>}
 {result&&<div className={`preflight ${result.status}`}><h2>{result.status==="ready"?"Ready for analysis":result.status==="degraded"?"Degraded":"Invalid"}</h2>{result.status==="invalid"?<ul>{result.errors.slice(0,8).map(x=><li key={x}>{x}</li>)}</ul>:<><dl><dt>Dataset / bundle</dt><dd>{String(d!.run.dataset_id)} / {String(d!.run.bundle_id??d!.run.run_id)}</dd><dt>Venues</dt><dd>{d!.venues.join(", ")||"none"}</dd><dt>Source runs</dt><dd>{d!.sourceRuns.join(", ")||"none"}</dd><dt>Selected / denominator</dt><dd>{d!.counts.selectedCandidates} / {d!.counts.denominator}</dd><dt>Event universe</dt><dd>{d!.eventUniverseComplete?"Complete":"Incomplete"}</dd></dl>{result.warnings.map(x=><p className="preflight-warning" key={x}>{x}</p>)}<div className="count-grid">{Object.entries(d!.counts).map(([k,v])=><span key={k}><b>{v}</b>{k.replaceAll(/([A-Z])/g," $1")}</span>)}</div><div className="capability-table">{d!.capabilities.map(c=><div key={c.id}><strong>{c.label}</strong><em className={c.status}>{c.status}</em><small>{c.missingInputs.length?`Missing: ${c.missingInputs.join(", ")}`:`${c.affectedEventCount} events · ${c.affectedCandidateCount} candidates`}</small></div>)}</div></>}</div>}
 {reportError&&<div className="preflight invalid" role="alert"><h2>Report calculation failed</h2><p>{reportError}</p></div>}
 {report&&<><nav className="report-nav" aria-label="Report contents">{report.sections.map((s,i)=><a href={`#report-${s.id}`} key={s.id}><b>{i+1}. {s.title}</b><small className={`report-state ${s.state.replace(" ","-")}`}>{s.state}</small></a>)}</nav><section id="report-summary" className="workspace-section"><div className="section-heading"><div><p className="eyebrow">1 · Deterministic analysis {report.identity.analysisRunId}</p><h2>Executive Summary &amp; Data Sufficiency</h2></div><button onClick={exportPdf} disabled={!report.portfolio.configured} title={!report.portfolio.configured?"Complete and validate the locked analysis configuration first.":undefined}>Export analysis PDF</button></div><p className="resolution-banner">Unavailable candidates, unresolved events and {report.portfolio.portfolio.noTradeOpportunities} no-trade opportunities remain visible and in the opportunity denominator. Payoff-dependent analytics included {report.structure.diagnostics.includedCandidates} candidate(s) and excluded {report.structure.diagnostics.excludedCandidates} invalid candidate(s).</p>{report.structure.diagnostics.rows.length>0&&<div className="preflight degraded"><h3>Spread semantic diagnostics</h3><ul>{report.structure.diagnostics.rows.map((x,i)=><li key={i}>{x.severity}: {x.candidateId} ({x.eventId}) — {x.reason}</li>)}</ul></div>}<div className="section-status-grid">{report.sections.map(s=><div key={s.id}><strong>{s.title}</strong><em className={s.state.replace(" ","-")}>{s.state}</em><small>{s.detail}</small></div>)}</div></section>
 <section className="global-controls"><h2>Global controls</h2><p><b>Source run:</b> {report.identity.sourceRunIds.join(", ")||"not configured"} · <b>Venue:</b> {d!.venues.join(", ")||"not configured"}. Source runs are displayed as isolated bundle provenance and are never silently pooled.</p></section><AnalysisConfigurationForm value={configuration} onChange={setConfiguration}/>
 <div id="report-underlying"><UnderlyingResolutionReportView report={report.underlying} universeComplete={d!.eventUniverseComplete}/></div><div id="report-duration"><DurationDteReportView report={report.duration}/></div><div id="report-strike"><span id="report-width"/><span id="report-exits"/><span id="report-positions"/><StructurePolicyEconomicsReport report={report.structure}/></div><div id="report-portfolio"><span id="report-futures"/><span id="report-interactions"/><span id="report-scorecard"/><PortfolioStrategyReport report={report.portfolio}/></div><section id="report-methodology" className="workspace-section card"><h2>Methodology, Provenance &amp; Limitations</h2><p>Dataset {report.identity.datasetId}; bundle {report.identity.bundleId}; source runs {report.identity.sourceRunIds.join(", ")||"none"}; analysis {report.identity.analysisRunId}.</p>{[...report.underlying.methodology,...report.duration.methodology,...report.structure.methodology,...report.portfolio.warnings].map((x,i)=><p className="fine-print" key={i}>{x}</p>)}</section></>}
 </section>
}
