import type {ExitPolicyReport} from "../lib/exit-policy/report";
import type {Metric} from "../lib/exit-policy/statistics";
import type {VolatilityReport} from "../lib/volatility/volatility-report";
import {winningExitVolatility} from "../lib/volatility/volatility-report";
import {EmbeddedVolatilityContext} from "./volatility-report";
const number=(x:number|null,d=5)=>x===null?"Unavailable":x.toFixed(d);
const metric=(x:Metric,d=5)=>x.value!==null?`${x.value.toFixed(d)} · N=${x.n}`:x.reason?.includes("insufficient sample")?`Not estimable · N=${x.n} · minimum 10`:x.n===0?"Not estimable · N=0":`Unavailable · N=${x.n}`;
const coverage=(x:{value:number|null;numerator:number;denominator:number})=>x.denominator===0?"Not evaluated":`${(x.value!*100).toFixed(1)}% · ${x.numerator}/${x.denominator}`;
const percent=(x:number|null)=>x===null?"Not estimable":`${(x*100).toFixed(1)}%`;
const label=(report:ExitPolicyReport,id:string)=>report.policies.find(x=>x.policy.id===id)?.policy.label??id;
export function ExitPolicyReportView({report,volatility}:{report:ExitPolicyReport;volatility?:VolatilityReport}){
 const ids=new Set(report.selectedCandidateIds),winningIv=volatility?winningExitVolatility(volatility,report.policies.map(x=>x.observations),ids):[],captures=report.comparisons.filter(x=>x.policyId==="capture_50"||x.policyId==="capture_70"),audit=[...report.policies.flatMap(p=>p.observations.filter(x=>x.missingDataReason).map(x=>({...x,reason:x.missingDataReason!}))),...report.diagnostics.capital.map(x=>({candidateId:x.candidateId,eventId:"",policyId:x.policyId,winningTrigger:null,decisionTimestamp:null,valuationTimestamp:null,status:"unavailable",reason:x.reason??"missing policy-specific capital path"})),...report.comparisons.flatMap(x=>x.postExitUnavailableReasons.map(reason=>({candidateId:"—",eventId:"",policyId:x.policyId,winningTrigger:null,decisionTimestamp:null,valuationTimestamp:null,status:"not_estimable",reason}))),...winningIv.filter(x=>x.unavailableN).map(x=>({candidateId:"—",eventId:"",policyId:x.policyId,winningTrigger:null,decisionTimestamp:null,valuationTimestamp:null,status:"unavailable",reason:`observed IV unavailable: ${x.unavailableN} exact winning endpoint(s)`})),...report.policies.flatMap(p=>p.observations.filter(x=>x.status==="priced"&&x.maximumStructuralLossBtc===null).map(x=>({candidateId:x.candidateId,eventId:x.eventId,policyId:x.policyId,winningTrigger:x.winningTrigger,decisionTimestamp:x.decisionTimestamp,valuationTimestamp:x.valuationTimestamp,status:"unavailable",reason:`structural loss unavailable: ${x.structuralLossReason??"canonical reading absent"}`}))),...([report.observed.maker,report.observed.taker] as const).flatMap(layer=>layer.policies.flatMap(p=>p.observations.filter(x=>x.status==="unavailable"||x.status==="not_evaluated").map(x=>({candidateId:x.candidateId,eventId:x.eventId,policyId:x.policyId,winningTrigger:x.winningTrigger,decisionTimestamp:x.decisionTimestamp,valuationTimestamp:x.valuationTimestamp,status:x.status,reason:`strict ${layer.scope.executionScenario} unavailable: ${x.missingDataReason??x.status}`}))))],groups=Object.entries(audit.reduce<Record<string,number>>((a,x)=>{const key=x.reason.split(":")[0]??"unavailable";a[key]=(a[key]??0)+1;return a},{}));
 if(report.integrity.status==="error")return <section className="workspace-section" data-testid="exit-policy-report"><h2>Exit-Policy Analysis</h2><p className="preflight invalid" role="alert">{report.integrity.message}</p></section>;
 return <section className="workspace-section" data-testid="exit-policy-report">
  <div className="section-heading"><div><p className="eyebrow">Same-structure policy decision</p><h2>Exit-Policy Analysis</h2></div></div>
  <p className="resolution-banner">{report.methodology} Scope: {report.scope.analyticsTrack} · execution scenario {report.scope.executionScenario??"none"} · pricing representation {report.scope.pricingTrack??"canonical"}.</p>
  <h3>Primary paired policy-versus-Thesis decision</h3><p>Δ = alternative − Thesis. Positive PnL is better; negative holding, MAE, fees, or capital-time means less burden.</p>
  <div className="table-wrap"><table><thead><tr><th>Alternative</th><th>Matched structures</th><th>Independent MR events</th><th>Structure median Δ BTC</th><th>Equal-event mean / median Δ BTC</th><th>Median Δ hold</th><th>Median Δ MAE</th><th>Median Δ fees</th><th>Median Δ capital-days</th><th>Common-priced coverage</th></tr></thead><tbody>{report.comparisons.map(x=><tr key={x.policyId}><th>{label(report,x.policyId)}</th><td>{x.matchedStructuresN}</td><td>{x.matchedEventN}</td><td>{metric(x.pnlDifferenceBtc.median)}</td><td>{metric(x.equalEvent.pnlBtc.mean)} / {metric(x.equalEvent.pnlBtc.median)}</td><td>{metric(x.holdingDifferenceHours.median,1)}</td><td>{metric(x.maeDifferenceBtc.median)}</td><td>{metric(x.totalFeeDifferenceBtc.median)}</td><td>{metric(x.capitalDaysDifferenceBtc.median)}</td><td>{x.pairingCoverage.value===null?"Not evaluated":`${percent(x.pairingCoverage.value)} · ${x.pairingCoverage.commonPriced}/${Math.max(x.pairingCoverage.alternativeSelected,x.pairingCoverage.thesisSelected)}`}</td></tr>)}</tbody></table></div>
  <h3>Absolute policy statistics</h3><p><strong>Conditional on priced winning exits.</strong> These are not unconditional strategy expectancy estimates.</p>
  <div className="table-wrap"><table><thead><tr><th>Policy</th><th>Selected</th><th>Determinate</th><th>Priced</th><th>Triggered-unpriced</th><th>Unavailable</th><th>Not evaluated</th><th>Pricing / selected coverage</th><th>Mean / median BTC</th><th>P10 / P5</th><th>Worst / median MAE</th><th>Median hold</th><th>Opening / closing / delivery / total fees</th><th>Capital-days</th></tr></thead><tbody>{report.policies.map(x=><tr key={x.policy.id}><th>{x.policy.label}</th><td>{x.stats.denominators.selectedEligible.n}</td><td>{x.stats.denominators.triggerDeterminate.n}</td><td>{x.stats.denominators.pricedWinningExits.n}</td><td>{x.stats.denominators.triggeredUnpriced.n}</td><td>{x.stats.denominators.unavailable.n}</td><td>{x.stats.denominators.notEvaluated.n}</td><td>{coverage(x.stats.pricingCoverage)} / {coverage(x.stats.selectedCohortCoverage)}</td><td>{metric(x.stats.pnlAmongPricedExits.btc.mean)} / {metric(x.stats.pnlAmongPricedExits.btc.median)}</td><td>{metric(x.stats.pnlAmongPricedExits.btc.p10)} / {metric(x.stats.pnlAmongPricedExits.btc.p5)}</td><td>{metric(x.stats.pnlAmongPricedExits.btc.worst)} / {metric(x.stats.maeAmongPricedExits)}</td><td>{metric(x.stats.holdingAmongPricedExits.hours,1)}</td><td>{metric(x.stats.feesAmongPricedExits.opening)} / {metric(x.stats.feesAmongPricedExits.closing)} / {metric(x.stats.feesAmongPricedExits.delivery)} / {metric(x.stats.feesAmongPricedExits.total)}</td><td>{metric(x.stats.capitalDaysAmongPricedExits)}</td></tr>)}</tbody></table></div>
  <h3>Exit-trigger composition</h3>{report.policies.map(x=><details key={x.policy.id}><summary>{x.policy.label} · determinate N={x.stats.denominators.triggerDeterminate.n}</summary><p>{Object.entries(x.stats.triggerCounts).map(([k,v])=>`${k}: ${percent(v.share)} (${v.n}/${v.denominator})`).join(" · ")||"Not evaluated"}</p></details>)}
  <h3>Fixed-time hierarchy diagnostics</h3><p>Each cap is a hierarchy—VPOC → invalidation → fixed cap → settlement—not a promise to hold for the named duration.</p><div className="count-grid">{(["time_cap_3d","time_cap_5d","time_cap_7d"] as const).map(id=>{const p=report.policies.find(x=>x.policy.id===id)!,d=report.diagnostics.decompositions[id]!,pair=report.comparisons.find(x=>x.policyId===id)!;return <span key={id}><strong>{p.policy.label}</strong>Determinate {p.stats.denominators.triggerDeterminate.n} · cap wins {d.fixedCapWins?.n??0}/{d.fixedCapWins?.denominator??0}<br/>VPOC {p.stats.triggerCounts.vpoc?.n??0} · invalidation {p.stats.triggerCounts.invalidation?.n??0} · settlement {p.stats.triggerCounts.settlement?.n??0}<br/>Median ΔPnL {metric(pair.pnlDifferenceBtc.median)} · Δhold {metric(pair.holdingDifferenceHours.median,1)} · ΔMAE {metric(pair.maeDifferenceBtc.median)}</span>})}</div>
  {volatility&&<EmbeddedVolatilityContext report={volatility} kind="exit" candidateIds={ids}/>}
  <h3>Observed IV at actual winning policy exits</h3><p>Exact candidate + canonical endpoint + exact target timestamp; settlement is deterministic and not applicable.</p><div className="table-wrap"><table><thead><tr><th>Policy</th><th>Determinate / IV applicable</th><th>Short / long / both observed</th><th>Entry → exit short IV / Δ</th><th>Entry → exit long IV / Δ</th><th>Compression / expansion</th><th>Settlement N/A / unavailable</th></tr></thead><tbody>{winningIv.map(x=><tr key={x.policyId}><th>{label(report,x.policyId)}</th><td>{x.determinateN} / {x.ivApplicableN}</td><td>{x.shortObservedN} / {x.longObservedN} / {x.bothObservedN}</td><td>{number(x.medianEntryShortIv,3)} → {number(x.medianExitShortIv,3)} / {number(x.medianDeltaShortIv,3)}</td><td>{number(x.medianEntryLongIv,3)} → {number(x.medianExitLongIv,3)} / {number(x.medianDeltaLongIv,3)}</td><td>{percent(x.shortCompressionShare)} / {percent(x.shortExpansionShare)}</td><td>{x.settlementNotApplicableN} / {x.unavailableN}</td></tr>)}</tbody></table></div>
  <h3>Early-exit opportunity versus protection</h3><p>Opportunity surrendered is additional favorable Reference PnL strictly after early exit through Thesis exit. Downside avoided is subsequent Reference deterioration avoided. Gaps are not interpolated.</p><div className="table-wrap"><table><thead><tr><th>Overlay</th><th>Structures / events</th><th>Median ΔPnL / Δhold / ΔMAE</th><th>Opportunity median / mean</th><th>Downside median / mean</th><th>Winner composition</th></tr></thead><tbody>{captures.map(x=><tr key={x.policyId}><th>{label(report,x.policyId)}</th><td>{x.matchedStructuresN} / {x.matchedEventN}</td><td>{metric(x.pnlDifferenceBtc.median)} / {metric(x.holdingDifferenceHours.median,1)} / {metric(x.maeDifferenceBtc.median)}</td><td>{metric(x.postExitOpportunitySurrendered.median)} / {metric(x.postExitOpportunitySurrendered.mean)}</td><td>{metric(x.postExitDownsideAvoided.median)} / {metric(x.postExitDownsideAvoided.mean)}</td><td>{Object.entries(report.policies.find(p=>p.policy.id===x.policyId)!.stats.triggerCounts).map(([k,v])=>`${k} ${v.n}/${v.denominator}`).join(" · ")}</td></tr>)}</tbody></table></div>
  <h3>70% versus 50% capture</h3>{(()=>{const x=report.diagnostics.capture70Vs50;return <p>Matched structures {x.matchedStructuresN}; independent events {x.matchedEventN}. 70−50 median ΔPnL {metric(x.pnlDifferenceBtc.median)}, Δhold {metric(x.holdingDifferenceHours.median,1)}, ΔMAE {metric(x.maeDifferenceBtc.median)}, Δfees {metric(x.totalFeeDifferenceBtc.median)}, Δcapital-days {metric(x.capitalDaysDifferenceBtc.median)}.</p>})()}
  <h3>Settlement benchmark and near-full-loss</h3>{(()=>{const p=report.policies.find(x=>x.policy.id==="settlement_benchmark")!,n=p.nearFullLoss;return n.status==="not_configured"?<p><strong>Not configured.</strong> No historical threshold or frequency is inferred. The hierarchy remains invalidation → settlement.</p>:<p>Declared threshold {(n.fraction!*100).toFixed(1)}% of canonical maximum structural loss · eligible N={n.eligibleN} · hits N={n.nearFullLossN} · frequency {percent(n.frequency)}. Candidates: {n.candidateIds.join(", ")||"none"}.</p>})()}
  <h3>Strict Maker / Taker execution robustness</h3><p>Conditional on each strict track’s own entry/evidence availability. Missing tape means historical execution was not proven, not that the trade was impossible.</p>{([report.observed.maker,report.observed.taker] as const).map(layer=><details key={layer.scope.analyticsTrack}><summary>{layer.scope.analyticsTrack}</summary><table><thead><tr><th>Policy</th><th>Projected / not evaluated</th><th>Determinate</th><th>Priced / unpriced</th><th>Within-track coverage</th></tr></thead><tbody>{layer.policies.map(x=><tr key={x.policy.id}><th>{x.policy.label}</th><td>{x.stats.denominators.selectedEligible.n} / {x.stats.denominators.notEvaluated.n}</td><td>{x.stats.denominators.triggerDeterminate.n}</td><td>{x.stats.denominators.pricedWinningExits.n} / {x.stats.denominators.triggeredUnpriced.n}</td><td>{coverage(x.stats.pricingCoverage)}</td></tr>)}</tbody></table></details>)}
  <h3>Candidate and missing-data audit</h3><details><summary>{audit.length} candidate-policy issues in {groups.length} reason groups</summary><p>{groups.map(([k,n])=>`${k}: ${n}`).join(" · ")||"No issues"}</p><table><thead><tr><th>Candidate / event</th><th>Policy / winner</th><th>Decision / valuation</th><th>Status</th><th>Reason</th></tr></thead><tbody>{audit.slice(0,200).map((x,i)=><tr key={i}><td>{x.candidateId} / {x.eventId||"—"}</td><td>{x.policyId} / {x.winningTrigger??"—"}</td><td>{x.decisionTimestamp??"—"} / {x.valuationTimestamp??"—"}</td><td>{x.status}</td><td>{x.reason}</td></tr>)}</tbody></table></details>
 </section>;
}
