import type {AnalyticsAttention,AnalyticsEvidenceStatus} from "../lib/analytics-attention";
import {useState} from "react";
export type ResearchEvidenceStatus=AnalyticsEvidenceStatus|"UNUSUAL";
export interface EvidenceAssessment{readonly status:ResearchEvidenceStatus;readonly reason:string|null}
export function evidenceRowProps(assessment:EvidenceAssessment){return {className:`evidence-status-${assessment.status.toLowerCase()}`,title:assessment.status==="VALID"?undefined:assessment.reason??`${assessment.status} evidence`}}
export function ResearchEvidenceBadge({assessment}:{assessment:EvidenceAssessment}){const reason=assessment.reason??`${assessment.status} evidence`;return <span className={`evidence-badge evidence-badge-${assessment.status.toLowerCase()}`} title={assessment.status==="VALID"?undefined:reason} aria-label={`Evidence: ${assessment.status}${assessment.status==="VALID"?"":` — ${reason}`}`}>{assessment.status}</span>}
export function AnalyticsAttentionBadge({attention}:{attention:AnalyticsAttention}){return <span className={`attention-badge attention-badge-${attention.kind.toLowerCase()}`} title={attention.reason} aria-label={`Attention: ${attention.kind} — ${attention.reason}`}>{attention.kind.replace("_"," ")}</span>}
export function ReportKpi({label,value,context}:{label:string;value:React.ReactNode;context:React.ReactNode}){return <div className="exit-kpi"><span>{label}</span><strong>{value}</strong><small>{context}</small></div>}
export function ReportPanel({title,eyebrow,description,primary=false,children}:{title:string;eyebrow?:string;description?:string;primary?:boolean;children:React.ReactNode}){return <section className={`exit-panel${primary?" exit-panel-primary":""}`}><div className="exit-panel-heading"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h3>{title}</h3></div>{description&&<p>{description}</p>}</div>{children}</section>}
export function AuditAttentionControls({invalid=0,partial=0,unavailable=0,unusual=0,lowN=0}:{invalid?:number;partial?:number;unavailable?:number;unusual?:number;lowN?:number}){const flagged=invalid+partial+unavailable+unusual+lowN,[filter,setFilter]=useState(flagged?"attention":"all");const apply=(value:string,e:React.MouseEvent<HTMLButtonElement>)=>{setFilter(value);const root=e.currentTarget.closest<HTMLElement>(".analytics-audit");if(root)root.dataset.filter=value};return <><div className="attention-summary audit-attention-summary" aria-label="Audit attention summary"><span><b>{invalid}</b>Invalid</span><span><b>{partial}</b>Partial</span><span><b>{unavailable}</b>Unavailable</span><span><b>{unusual}</b>Unusual</span><span><b>{lowN}</b>Low N</span></div><div className="audit-filters" role="group" aria-label="Filter attention audit">{[["attention","Attention only"],["invalid","Invalid"],["partial","Partial"],["unavailable","Unavailable"],["unusual","Unusual"],["all","All"]].map(([id,label])=><button key={id} type="button" aria-pressed={filter===id} onClick={e=>apply(id!,e)}>{label}</button>)}</div></>}
