"use client";
import {useMemo,useState,type CSSProperties} from "react";
import type {AnalysisDataset} from "../lib/research-analysis";
import type {PrimaryExitPolicy} from "../lib/analysis-configuration";
import {buildResearchEconomicsReport,configurationEvidenceStatus,type InteractionKind,type ResearchExecutionTrack} from "../lib/research-economics/report";
import {median,type CurrencyStatistic,type ResearchMetric} from "../lib/research-economics/statistics";
import {structuralConfigurationLabel} from "../lib/economics/strategy-configuration";
import {MonetaryValue,useDisplayCurrency} from "./display-currency";
import {ReportKpi,ReportPanel,ResearchEvidenceBadge} from "./research-evidence-status";

type Dimension="dte"|"strike"|"width";
const TRACKS:readonly {id:ResearchExecutionTrack;label:string}[]=[{id:"reference",label:"Reference"},{id:"modeled_expected",label:"Q50 expected"},{id:"modeled_conservative",label:"Q90 conservative"}];
const METRICS:readonly {id:ResearchMetric;label:string;money:boolean;signed:boolean}[]=[{id:"pnl",label:"Net PnL",money:true,signed:true},{id:"totalFees",label:"Fees",money:true,signed:false},{id:"peakIm",label:"Peak IM",money:true,signed:false},{id:"capitalDays",label:"Capital-days",money:true,signed:false},{id:"returnOnPeakCapital",label:"Return / peak IM",money:false,signed:true},{id:"feeDrag",label:"Fee drag",money:false,signed:false}];
const meta=(metric:ResearchMetric)=>METRICS.find(x=>x.id===metric)??{id:metric,label:metric,money:true,signed:false};
const category=(v:unknown,d:Dimension)=>d==="dte"?`${v}D`:d==="width"?`$${Number(v).toLocaleString("en-US")}`:String(v);
const pct=(v:number|null)=>v===null?"Unavailable":`${(v*100).toFixed(1)}%`;
function Toggle<T extends string>({label,value,options,onChange}:{label:string;value:T;options:readonly {id:T;label:string}[];onChange:(v:T)=>void}){return <fieldset className="research-economics-toggle"><legend>{label}</legend>{options.map(x=><button type="button" key={x.id} aria-pressed={value===x.id} onClick={()=>onChange(x.id)}>{x.label}</button>)}</fieldset>}
function Metric({metric,stat}:{metric:ResearchMetric;stat:CurrencyStatistic}){const currency=useDisplayCurrency(),selected=stat[currency],value=selected.value;return <span className={selected.status==="partial"?"metric-partial":undefined}>{meta(metric).money?<MonetaryValue btc={stat.btc.value} usd={stat.usd.value} allowFallback={false}/>:pct(value)}<small>metric events {selected.effectiveEventN} / eligible events {selected.eligibleEventN}{selected.status==="partial"?" · partial":""}</small></span>}
function Delta({metric,delta}:{metric:ResearchMetric;delta:{btc:{medianDelta:number|null;effectivePairedN:number;missingPairedN:number};usd:{medianDelta:number|null;effectivePairedN:number;missingPairedN:number}}}){const currency=useDisplayCurrency(),selected=delta[currency];return <span>{meta(metric).money?<MonetaryValue btc={delta.btc.medianDelta} usd={delta.usd.medianDelta} allowFallback={false}/>:pct(selected.medianDelta)}<small>paired metric N={selected.effectivePairedN} · missing pairs={selected.missingPairedN}</small></span>}
const statValue=(stat:CurrencyStatistic,currency:"btc"|"usd")=>stat[currency].value;

export function ResearchEconomicMatrixReport({dataset,researchExitPolicy}:{dataset:AnalysisDataset;researchExitPolicy:PrimaryExitPolicy|null}){
 const [track,setTrack]=useState<ResearchExecutionTrack>("modeled_expected"),[dimension,setDimension]=useState<Dimension>("dte"),[metric,setMetric]=useState<ResearchMetric>("pnl"),[interaction,setInteraction]=useState<InteractionKind>("dte_width"),[third,setThird]=useState<string>("all"),[executionDimension,setExecutionDimension]=useState<Dimension>("dte"),[executionMetric,setExecutionMetric]=useState<ResearchMetric>("netCredit"),[policyMetric,setPolicyMetric]=useState<ResearchMetric>("pnl");
 const currency=useDisplayCurrency(),report=useMemo(()=>buildResearchEconomicsReport(dataset,researchExitPolicy,track),[dataset,researchExitPolicy,track]);
 if(report.status==="not_configured")return <section className="workspace-section exit-report research-economics-report" data-testid="research-economic-matrix-report"><header className="exit-header"><p className="eyebrow">Full-space position economics</p><h2>Comparative Economics</h2></header><p className="preflight-warning">{report.statusReason}</p></section>;
 const configurations=[...report.configurations].sort((a,b)=>Number(a.configuration.targetDteFamilyDays)-Number(b.configuration.targetDteFamilyDays)||String(a.configuration.strikeMethod).localeCompare(String(b.configuration.strikeMethod))||Number(a.configuration.requestedWidth)-Number(b.configuration.requestedWidth)||String(a.configuration.structureFamily).localeCompare(String(b.configuration.structureFamily))),opportunities=report.canonicalOpportunities.length,priced=configurations.reduce((n,x)=>n+x.trackCoverage.pricedOpportunityN,0),events=new Set(report.canonicalOpportunities.map(x=>x.eventId)).size;
 const configMedian=(metric:ResearchMetric,c:"btc"|"usd")=>median(configurations.flatMap(x=>{const v=x.metrics[metric][c].value;return v===null?[]:[v]}));
 const comparisons=report.matched[dimension],maxDelta=Math.max(1e-12,...comparisons.map(x=>Math.abs(x.metrics[metric][currency].medianDelta??0))),marginals=(["dte","strike","width"] as const).map(d=>report.marginals.find(x=>x.dimension===d)!);
 const thirdDimension=interaction==="dte_width"?"strike":interaction==="dte_strike"?"width":"dte",thirdValues=[...new Set(report.canonicalOpportunities.map(o=>thirdDimension==="strike"?o.structuralConfiguration.strikeMethod:thirdDimension==="width"?o.structuralConfiguration.requestedWidth:o.structuralConfiguration.targetDteFamilyDays).filter(x=>x!==null))].map(String),held=third==="all"?"all":thirdDimension==="strike"?third:Number(third),matrix=report.interactions.find(x=>x.kind===interaction&&x.heldValue===held)!,xs=[...new Set(matrix.cells.map(x=>x.x))],ys=[...new Set(matrix.cells.map(x=>x.y))],matrixMax=Math.max(1e-12,...matrix.cells.map(x=>Math.abs(statValue(x.metrics[metric],currency)??0)));
 const executionGroups=report.execution.groups.filter(x=>x.dimension===executionDimension),invalid=configurations.filter(x=>x.integrity.status==="integrity_error").length,partial=configurations.filter(x=>Object.values(x.metrics).some(s=>s.usd.status==="partial")).length,unavailableMetricConfigurations=configurations.filter(x=>Object.values(x.metrics).some(s=>s.usd.status==="unavailable")).length,q50UnavailableConfigurations=configurations.filter(x=>x.q50.unavailable>0).length,unavailableOpportunities=configurations.reduce((n,x)=>n+x.q50.unavailable,0),lowN=configurations.filter(x=>x.q50.tailPricedN<x.q50.tailMinimum).length,unpaired=report.execution.groups.filter(x=>x.dimension==="configuration").reduce((n,x)=>n+x.comparisons.reduce((m,p)=>m+p.sourceOnlyN+p.destinationOnlyN,0),0);
 return <section className="workspace-section exit-report research-economics-report" data-testid="research-economic-matrix-report">
  <header className="exit-header"><p className="eyebrow">Full-space position economics</p><h2>Comparative Economics</h2><p className="exit-subtitle">Compare position/configuration economics across the canonical ex-ante opportunity space; account deployment remains in Strategy Evaluation.</p><div className="exit-scope"><span>Full canonical opportunity space</span><span>Independent-event weighted</span><span>{researchExitPolicy?.replaceAll("_"," ")}</span><span>{TRACKS.find(x=>x.id===track)!.label}</span></div><Toggle label="Analytical execution view" value={track} options={TRACKS} onChange={setTrack}/><details className="exit-methodology"><summary>Methodology &amp; definitions</summary><p>The opportunity matrix is the immutable Q50 generation baseline. Reference and Q90 attach track-conditional evidence without rewriting trade, explicit-no-trade, or unavailable decisions. Descriptive statistics show metric-specific event coverage; controlled comparisons form canonical opportunity pairs before testing metric availability.</p></details></header>
  <div className="exit-kpis"><ReportKpi label="Independent eligible events" value={String(events)} context={`${opportunities} canonical opportunities`}/><ReportKpi label="Structural configurations" value={String(configurations.length)} context="Canonical ex-ante identities"/><ReportKpi label="Selected-track priced" value={`${priced}/${opportunities}`} context="priced / eligible opportunities"/><ReportKpi label="Median configuration PnL" value={<MonetaryValue btc={configMedian("pnl","btc")} usd={configMedian("pnl","usd")} allowFallback={false}/>} context="Independent currency aggregates"/><ReportKpi label="Q50 explicit no-trades" value={String(configurations.reduce((n,x)=>n+x.q50.explicitNoTrades,0))} context="Canonical generation decisions"/><ReportKpi label="Unavailable opportunities" value={String(unavailableOpportunities)} context={`${q50UnavailableConfigurations} configurations affected`}/></div>
  <ReportPanel primary title="Controlled one-factor comparisons" eyebrow="Primary decision surface" description="Canonical pair universe first; destination − source metric deltas second."><div className="research-economics-controls"><Toggle label="Parameter" value={dimension} options={[{id:"dte",label:"DTE"},{id:"strike",label:"Strike"},{id:"width",label:"Width"}]} onChange={setDimension}/><Toggle label="Metric" value={metric} options={METRICS} onChange={setMetric}/></div><div className="research-economics-deltas" role="img" aria-label={`Zero-centered ${meta(metric).label} destination minus source`}>
   {comparisons.map(x=>{const d=x.metrics[metric][currency],w=Math.abs(d.medianDelta??0)/maxDelta*50;return <div className="research-economics-delta-row" key={`${x.source}-${x.destination}`} tabIndex={0} title={`Eligible pairs ${x.eligiblePairUniverseN}; priced both ${x.pricedBothN}; source-only ${x.sourceOnlyEvidenceN}; destination-only ${x.destinationOnlyEvidenceN}`}><strong>{category(x.source,dimension)} → {category(x.destination,dimension)}</strong><div className="exit-delta-track"><i className="exit-delta-zero"/>{d.medianDelta!==null&&<i className="research-economics-delta-fill" style={{width:`${w}%`,left:d.medianDelta<0?`${50-w}%`:"50%"}}/>}</div><Delta metric={metric} delta={x.metrics[metric]}/><small>eligible pairs={x.eligiblePairUniverseN} · priced both={x.pricedBothN}</small></div>})}
  </div></ReportPanel>
  <div className="research-economics-panel-grid">{marginals.map(group=><ReportPanel key={group.dimension} title={`Economics by ${group.dimension==="dte"?"DTE":group.dimension==="strike"?"Short Strike":"Spread Width"}`} eyebrow="Descriptive / composition-sensitive"><div className="research-economics-bars">{group.cells.map(cell=>{const stat=cell.metrics[metric],v=stat[currency].value,max=Math.max(1e-12,...group.cells.map(c=>Math.abs(c.metrics[metric][currency].value??0))),signed=meta(metric).signed,w=Math.abs(v??0)/max*(signed?50:100);return <div className={`research-economics-bar${signed?" is-signed":""}`} key={String(cell.category)} tabIndex={0}><strong>{category(cell.category,group.dimension as Dimension)}</strong><i>{signed&&<b/>}{v!==null&&<span style={{width:`${w}%`,left:signed?(v<0?`${50-w}%`:"50%"):0}}/>}</i><Metric metric={metric} stat={stat}/><small>{cell.q50.intendedTrades} Q50 trade · {cell.q50.explicitNoTrades} no-trade · {cell.q50.unavailable} unavailable</small></div>})}</div></ReportPanel>)}</div>
  <ReportPanel title="Interaction matrices" eyebrow="Observed canonical cells" description={third==="all"?"All third-variable values · descriptive / composition-sensitive":`Holding ${thirdDimension} fixed at ${third}`}><div className="research-economics-controls"><Toggle label="View" value={interaction} options={[{id:"dte_width",label:"DTE × Width"},{id:"dte_strike",label:"DTE × Strike"},{id:"strike_width",label:"Strike × Width"}]} onChange={v=>{setInteraction(v);setThird("all")}}/><Toggle label="Metric" value={metric} options={METRICS} onChange={setMetric}/><label className="research-economics-select">Fix {thirdDimension}<select value={third} onChange={e=>setThird(e.target.value)}><option value="all">All · composition-sensitive</option>{thirdValues.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="exit-table-scroll"><table className="research-economics-heatmap" aria-label={`${interaction.replaceAll("_"," by ")} value-encoding interaction matrix`}><thead><tr><th>Cell</th>{ys.map(y=><th key={String(y)}>{String(y)}</th>)}</tr></thead><tbody>{xs.map(x=><tr key={String(x)}><th>{String(x)}</th>{ys.map(y=>{const cell=matrix.cells.find(c=>c.x===x&&c.y===y);if(!cell)return <td key={String(y)} className="is-absent">Not observed</td>;const stat=cell.metrics[metric],v=stat[currency].value,intensity=Math.abs(v??0)/matrixMax,style=v===null?undefined:{"--cell-intensity":intensity,"--cell-alpha":`${8+intensity*(meta(metric).signed?38:45)}%`} as CSSProperties;return <td key={String(y)} className={`${meta(metric).signed?`is-diverging ${v!==null&&v<0?"is-negative":"is-positive"}`:"is-sequential"}${v===null?" is-unavailable":""}`} style={style} tabIndex={0} title={`${meta(metric).label}; metric events ${stat[currency].effectiveEventN} / eligible events ${stat[currency].eligibleEventN}`}><Metric metric={metric} stat={stat}/></td>})}</tr>)}</tbody></table></div></ReportPanel>
  <ReportPanel title="Execution survival" eyebrow="Exact event × configuration × policy pairs" description="Lost-from-source and gained-at-destination are separate; no directional attrition assumption."><div className="research-economics-controls"><Toggle label="Dimension" value={executionDimension} options={[{id:"dte",label:"DTE"},{id:"strike",label:"Strike"},{id:"width",label:"Width"}]} onChange={setExecutionDimension}/><Toggle label="Degradation metric" value={executionMetric} options={[{id:"netCredit",label:"Net credit"},{id:"totalFees",label:"Fees"},{id:"pnl",label:"PnL"},{id:"trackMaximumNetLoss",label:"Track max loss"},{id:"returnOnPeakCapital",label:"Return"}]} onChange={setExecutionMetric}/></div><div className="exit-table-scroll"><table className="exit-table"><thead><tr><th>Category / transition</th><th>Eligible opportunities</th><th>Source / destination priced</th><th>Common / source-only / destination-only</th><th>Grouped degradation</th></tr></thead><tbody>{executionGroups.flatMap(g=>g.comparisons.map(p=><tr key={`${g.category}-${p.from}-${p.to}`}><th>{category(g.category,executionDimension)} · {p.from} → {p.to}</th><td>{p.eligibleOpportunityN}</td><td>{p.sourcePricedN} / {p.destinationPricedN}</td><td>{p.commonPricedN} / {p.sourceOnlyN} / {p.destinationOnlyN}</td><td><Delta metric={executionMetric} delta={p.metrics[executionMetric]}/></td></tr>))}</tbody></table></div></ReportPanel>
  <ReportPanel title="Economics by exit policy" eyebrow="Fixed analytical track"><Toggle label="Metric" value={policyMetric} options={METRICS.filter(x=>["pnl","capitalDays","totalFees","holdingDays","returnOnPeakCapital","feeDrag"].includes(x.id))} onChange={setPolicyMetric}/><div className="research-economics-policy-grid">{report.exitPolicies.map((x,i)=><article key={x.policy.id}><span className="exit-policy-chip">{i+1}</span><strong>{x.policy.label}</strong><Metric metric={policyMetric} stat={x.metrics[policyMetric]}/><small>priced opportunities {x.coverage.pricedOpportunityN} / eligible {x.coverage.eligibleOpportunityN}</small></article>)}</div><div className="exit-table-scroll"><table className="exit-table" aria-label="Exit policies paired against Thesis"><thead><tr><th>Policy vs Thesis</th><th>Canonical coverage pairs</th><th>{meta(policyMetric).label} destination − Thesis</th></tr></thead><tbody>{report.exitPolicies.slice(1).map(x=><tr key={x.policy.id}><th>{x.policy.label}</th><td>common priced {x.versusThesis.commonPricedN} · Thesis-only {x.versusThesis.sourceOnlyN} · policy-only {x.versusThesis.destinationOnlyN}</td><td><Delta metric={policyMetric} delta={x.versusThesis.metrics[policyMetric]}/></td></tr>)}</tbody></table></div></ReportPanel>
  <details className="exit-panel research-economics-full-matrix"><summary><strong>Full configuration matrix</strong><small>{configurations.length} canonical configurations · deterministic structural order</small></summary><div className="exit-table-scroll"><table className="exit-table exit-table-wide"><thead><tr><th>Configuration</th><th>Q50 opportunity state</th><th>Selected-track coverage</th><th>Median PnL</th><th>Fees</th><th>Fee drag</th><th>Peak IM</th><th>Capital-days</th><th>Q50 trade-conditional P10 (fixed generation baseline)</th></tr></thead><tbody>{configurations.map(x=><tr key={x.configurationId}><th>{structuralConfigurationLabel(x.configuration)}</th><td>{x.q50.intendedTrades} trade / {x.q50.explicitNoTrades} no-trade / {x.q50.unavailable} unavailable</td><td>{x.trackCoverage.pricedOpportunityN}/{x.trackCoverage.eligibleOpportunityN}</td><td><Metric metric="pnl" stat={x.metrics.pnl}/></td><td><Metric metric="totalFees" stat={x.metrics.totalFees}/></td><td><Metric metric="feeDrag" stat={x.metrics.feeDrag}/></td><td><Metric metric="peakIm" stat={x.metrics.peakIm}/></td><td><Metric metric="capitalDays" stat={x.metrics.capitalDays}/></td><td>{currency==="btc"?x.q50.p10.btc?.value===null?`Not estimable · ${x.q50.p10.btc.reason}`:<MonetaryValue btc={x.q50.p10.btc?.value??null} usd={null} allowFallback={false}/>:x.q50.p10.usd?.value===null?`Not estimable · ${x.q50.p10.usd.reason}`:<MonetaryValue btc={null} usd={x.q50.p10.usd?.value??null} allowFallback={false}/>}</td></tr>)}</tbody></table></div></details>
  <ReportPanel title="Missingness & attention audit" eyebrow="Explicit units"><div className="research-economics-audit-summary"><span><b>{invalid}</b>Invalid configurations</span><span><b>{unavailableMetricConfigurations}</b>Configurations with unavailable canonical USD metrics</span><span><b>{partial}</b>Partial canonical-USD configurations</span><span><b>{q50UnavailableConfigurations}</b>Configurations with Q50 unavailable opportunities<small>{unavailableOpportunities} Q50 unavailable opportunities</small></span><span><b>{lowN}</b>Low-N tail configurations</span><span><b>{unpaired}</b>Execution identities unpaired</span></div><details className="exit-details"><summary>Configuration evidence details</summary>{configurations.map(x=>{const assessment=configurationEvidenceStatus(x);return <p key={x.configurationId}><ResearchEvidenceBadge assessment={assessment}/> {structuralConfigurationLabel(x.configuration)}</p>})}</details></ReportPanel>
 </section>
}
