"use client";
import {useMemo,useState} from "react";
import type {AnalysisDataset} from "../lib/research-analysis";
import type {PrimaryExitPolicy} from "../lib/analysis-configuration";
import {buildInteractionCells,buildResearchEconomicsReport,type InteractionKind,type ResearchExecutionTrack} from "../lib/research-economics/report";
import type {ResearchMetric} from "../lib/research-economics/statistics";
import {structuralConfigurationLabel} from "../lib/economics/strategy-configuration";
import {MonetaryValue,useDisplayCurrency} from "./display-currency";
import {AuditAttentionControls,ReportKpi,ReportPanel,ResearchEvidenceBadge} from "./research-evidence-status";

type Dimension="dte"|"strike"|"width";
type DisplayMetric="pnlUsd"|"totalFeesUsd"|"peakImUsd"|"capitalDaysUsd"|"returnOnPeakCapital"|"feeDrag";
const TRACKS:readonly {id:ResearchExecutionTrack;label:string}[]=[{id:"reference",label:"Reference"},{id:"modeled_expected",label:"Q50 expected"},{id:"modeled_conservative",label:"Q90 conservative"}];
const METRICS:readonly {id:DisplayMetric;label:string;money:boolean}[]=[{id:"pnlUsd",label:"Net PnL",money:true},{id:"totalFeesUsd",label:"Fees",money:true},{id:"peakImUsd",label:"Peak IM",money:true},{id:"capitalDaysUsd",label:"Capital-days",money:true},{id:"returnOnPeakCapital",label:"Return / peak IM",money:false},{id:"feeDrag",label:"Fee drag",money:false}];
const labelMetric=(id:DisplayMetric)=>METRICS.find(x=>x.id===id)!;
const pct=(v:number|null)=>v===null?"Unavailable":`${(v*100).toFixed(1)}%`;
const category=(value:unknown,dimension:Dimension)=>dimension==="dte"?`${value}D`:dimension==="width"?`$${Number(value).toLocaleString("en-US")}`:String(value);
function Money({usd,btc=null}:{usd:number|null;btc?:number|null}){return <MonetaryValue usd={usd} btc={btc} allowFallback={false}/>}
function MetricValue({metric,value,btc=null}:{metric:DisplayMetric;value:number|null;btc?:number|null}){return labelMetric(metric).money?<Money usd={value} btc={btc}/>:<>{pct(value)}</>}
function Toggle<T extends string>({label,value,options,onChange}:{label:string;value:T;options:readonly {id:T;label:string}[];onChange:(value:T)=>void}){return <fieldset className="research-economics-toggle"><legend>{label}</legend>{options.map(x=><button key={x.id} type="button" aria-pressed={value===x.id} onClick={()=>onChange(x.id)}>{x.label}</button>)}</fieldset>}

export function ResearchEconomicMatrixReport({dataset,researchExitPolicy}:{dataset:AnalysisDataset;researchExitPolicy:PrimaryExitPolicy|null}){
 const [track,setTrack]=useState<ResearchExecutionTrack>("modeled_expected"),[dimension,setDimension]=useState<Dimension>("dte"),[metric,setMetric]=useState<DisplayMetric>("pnlUsd"),[interaction,setInteraction]=useState<InteractionKind>("dte_width"),[third,setThird]=useState<string>("all"),[executionDimension,setExecutionDimension]=useState<Dimension>("dte"),[executionMetric,setExecutionMetric]=useState<ResearchMetric>("netCreditUsd"),[policyMetric,setPolicyMetric]=useState<DisplayMetric>("pnlUsd");
 const currency=useDisplayCurrency(),report=useMemo(()=>buildResearchEconomicsReport(dataset,researchExitPolicy,track),[dataset,researchExitPolicy,track]);
 if(report.status==="not_configured")return <section className="workspace-section exit-report research-economics-report" data-testid="research-economic-matrix-report"><header className="exit-header"><p className="eyebrow">Full-space position economics</p><h2>Comparative Economics</h2><p className="exit-subtitle">Compare position/configuration economics across the ex-ante research space; account-level deployment remains in Strategy Evaluation.</p></header><div className="preflight degraded"><strong>Not configured</strong><p>{report.statusReason}</p></div></section>;
 const configurations=[...report.configurations].sort((a,b)=>{const x=a.configuration??{},y=b.configuration??{};return Number(x.targetDteFamilyDays)-Number(y.targetDteFamilyDays)||String(x.strikeMethod).localeCompare(String(y.strikeMethod))||Number(x.requestedWidth)-Number(y.requestedWidth)||String(x.structureFamily).localeCompare(String(y.structureFamily))});
 const opportunities=configurations.reduce((n,x)=>n+x.eligibleOpportunities,0),priced=configurations.reduce((n,x)=>n+x.pricedOpportunities,0),eventN=report.independentEventN;
 const medConfig=(pick:(x:(typeof configurations)[number])=>number|null)=>{const values=configurations.map(pick).filter((x):x is number=>x!==null);return values.length?values.sort((a,b)=>a-b)[values.length>>1]!:null};
 const selected=report.matched[dimension],maxDelta=Math.max(1e-12,...selected.map(x=>Math.abs(x.metrics[metric].medianDelta??0))),marginals=(["dte","strike","width"] as const).map(d=>report.marginals.find(x=>x.dimension===d)!);
 const thirdDimension=interaction==="dte_width"?"strike":interaction==="dte_strike"?"width":"dte",thirdValues=[...new Set(report.configurations.map(c=>{const f=c.configuration;return thirdDimension==="strike"?f?.strikeMethod:thirdDimension==="width"?f?.requestedWidth:f?.targetDteFamilyDays}).filter(x=>x!==null))].map(String),held=third==="all"?"all":thirdDimension==="strike"?third:Number(third),matrix=report.interactions.find(x=>x.kind===interaction&&x.heldValue===held)??buildInteractionCells([],interaction,held),xs=[...new Set(matrix.cells.map(x=>x.x))],ys=[...new Set(matrix.cells.map(x=>x.y))];
 const execGroups=report.execution.groups.filter(x=>x.dimension===executionDimension),degradation=report.execution.comparisons,invalid=configurations.filter(x=>x.status==="integrity_error").length,partial=configurations.filter(x=>Object.values(x.usd).some(v=>v.effectiveN<v.requiredN)).length,unavailable=configurations.reduce((n,x)=>n+x.unavailableOpportunities,0),lowN=configurations.filter(x=>x.p10PnlUsd.value===null).length,unpaired=degradation.reduce((n,x)=>n+Math.max(0,x.fromPricedN-x.commonN),0);
 return <section className="workspace-section exit-report research-economics-report" data-testid="research-economic-matrix-report">
  <header className="exit-header"><p className="eyebrow">Full-space position economics</p><h2>Comparative Economics</h2><p className="exit-subtitle">Compare position/configuration economics across the ex-ante research space; account-level deployment remains in Strategy Evaluation.</p><div className="exit-scope"><span>Full configuration space</span><span>Independent-event weighted</span><span>{researchExitPolicy?.replaceAll("_"," ")}</span><span>{TRACKS.find(x=>x.id===track)!.label}</span></div><Toggle label="Analytical execution view" value={track} options={TRACKS} onChange={setTrack}/><details className="exit-methodology"><summary>Methodology &amp; definitions</summary><p>Marginal views are descriptive and composition-sensitive. Controlled comparisons pair the same event while holding every other ex-ante structural dimension fixed. USD values are canonical per observation; unavailable evidence is retained and never replaced with zero. Destination − source does not imply better or worse.</p></details></header>
  <div className="exit-kpis"><ReportKpi label="Independent MR events" value={String(eventN)} context="One vote per event within a cell"/><ReportKpi label="Coherent configurations" value={String(configurations.length)} context="No automatic ranking"/><ReportKpi label="Eligible opportunities" value={String(opportunities)} context="Event × configuration denominator"/><ReportKpi label="Priced coverage" value={opportunities?`${priced}/${opportunities}`:"Not evaluated"} context={TRACKS.find(x=>x.id===track)!.label}/><ReportKpi label="Median configuration PnL" value={<Money usd={medConfig(x=>x.medianPnlUsd)} btc={medConfig(x=>x.medianPnlBtc)}/>} context={`Across ${configurations.length} configurations`}/><ReportKpi label="Median peak IM" value={<Money usd={medConfig(x=>x.medianPeakInitialMarginUsd)}/>} context="Canonical selected-currency evidence only"/></div>

  <ReportPanel primary title="Controlled one-factor comparisons" eyebrow="Primary decision surface" description="Within-event matches vary one parameter only. Chart values are destination − source."><div className="research-economics-controls"><Toggle label="Parameter" value={dimension} options={[{id:"dte",label:"DTE"},{id:"strike",label:"Strike"},{id:"width",label:"Width"}]} onChange={setDimension}/><Toggle label="Metric" value={metric} options={METRICS} onChange={setMetric}/></div><div className="research-economics-deltas" role="img" aria-label={`Zero-centered ${labelMetric(metric).label} destination minus source comparisons`}>{selected.length?selected.map(x=>{const s=category(x.source,dimension),d=category(x.destination,dimension),stat=x.metrics[metric],width=Math.abs(stat.medianDelta??0)/maxDelta*50;return <div className="research-economics-delta-row" key={`${s}-${d}`} tabIndex={0} title={`${s} to ${d}; paired N ${stat.effectivePairedN}; unpaired ${x.unpairedN}; ${Object.entries(x.missingReasons).map(([r,n])=>`${r}: ${n}`).join(", ")||"no identity-level missingness"}`}><strong>{s} → {d}</strong><div className="exit-delta-track"><i className="exit-delta-zero"/>{stat.medianDelta!==null&&<i className="research-economics-delta-fill" style={{width:`${width}%`,left:stat.medianDelta<0?`${50-width}%`:"50%"}}/>}</div><span><MetricValue metric={metric} value={stat.medianDelta}/> · paired N={stat.effectivePairedN}</span></div>}):<p className="metric-unavailable">Not estimable — no coherent matched pairs.</p>}</div><div className="exit-table-scroll"><table className="exit-table"><thead><tr><th>Comparison</th><th>Δ PnL</th><th>Δ fees</th><th>Δ peak IM</th><th>Δ capital-days</th><th>Unpaired</th></tr></thead><tbody>{selected.map(x=><tr key={`${x.source}-${x.destination}`}><th>{category(x.source,dimension)} → {category(x.destination,dimension)}</th>{(["pnlUsd","totalFeesUsd","peakImUsd","capitalDaysUsd"] as const).map(m=><td key={m}><Money usd={x.metrics[m].medianDelta}/><small> paired N={x.metrics[m].effectivePairedN}</small></td>)}<td>{x.unpairedN}</td></tr>)}</tbody></table></div></ReportPanel>

  <div className="research-economics-panel-grid">{marginals.map(group=><ReportPanel key={group.dimension} title={`Economics by ${group.dimension==="dte"?"DTE":group.dimension==="strike"?"Short Strike":"Spread Width"}`} eyebrow="Descriptive / composition-sensitive"><div className="research-economics-bars" aria-label={`${group.dimension} descriptive ${labelMetric(metric).label}`}>{group.cells.map(cell=>{const value=cell[metric==="pnlUsd"?"medianPnlUsd":metric==="totalFeesUsd"?"medianTotalFeesUsd":metric==="peakImUsd"?"medianPeakImUsd":metric==="capitalDaysUsd"?"medianCapitalDaysUsd":metric==="returnOnPeakCapital"?"medianReturnOnPeakCapital":"medianFeeDrag"],max=Math.max(...group.cells.map(c=>Math.abs(c[metric==="pnlUsd"?"medianPnlUsd":metric==="totalFeesUsd"?"medianTotalFeesUsd":metric==="peakImUsd"?"medianPeakImUsd":metric==="capitalDaysUsd"?"medianCapitalDaysUsd":metric==="returnOnPeakCapital"?"medianReturnOnPeakCapital":"medianFeeDrag"]??0)),1e-12);return <div className="research-economics-bar" key={String(cell.category)} tabIndex={0} title={`${cell.configurationCount} configurations; ${cell.unavailableOpportunities} unavailable opportunities`}><strong>{category(cell.category,group.dimension as Dimension)}</strong><i><span style={{width:`${Math.abs(value??0)/max*100}%`}}/></i><span><MetricValue metric={metric} value={value}/> · event N={cell.independentEventN}</span></div>})}</div></ReportPanel>)}</div>

  <ReportPanel title="Interaction matrices" eyebrow="Observed cells only" description={third==="all"?"All third-variable values: descriptive / composition-sensitive.":`Holding ${thirdDimension} fixed at ${third}.`}><div className="research-economics-controls"><Toggle label="View" value={interaction} options={[{id:"dte_width",label:"DTE × Width"},{id:"dte_strike",label:"DTE × Strike"},{id:"strike_width",label:"Strike × Width"}]} onChange={v=>{setInteraction(v);setThird("all")}}/><Toggle label="Metric" value={metric} options={METRICS} onChange={setMetric}/><label className="research-economics-select">Fix {thirdDimension}<select value={third} onChange={e=>setThird(e.target.value)}><option value="all">All · composition-sensitive</option>{thirdValues.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="exit-table-scroll"><table className="research-economics-heatmap" aria-label={`${interaction.replaceAll("_"," by ")} interaction matrix`}><thead><tr><th scope="col">{interaction.split("_")[0]} ↓ / {interaction.split("_")[1]} →</th>{ys.map(y=><th scope="col" key={String(y)}>{String(y)}</th>)}</tr></thead><tbody>{xs.map(x=><tr key={String(x)}><th scope="row">{String(x)}</th>{ys.map(y=>{const cell=matrix.cells.find(c=>c.x===x&&c.y===y);if(!cell)return <td className="is-absent" key={String(y)}>Not observed</td>;const value=cell[metric==="pnlUsd"?"medianPnlUsd":metric==="totalFeesUsd"?"medianTotalFeesUsd":metric==="peakImUsd"?"medianPeakImUsd":metric==="capitalDaysUsd"?"medianCapitalDaysUsd":metric==="returnOnPeakCapital"?"medianReturnOnPeakCapital":"medianFeeDrag"];return <td key={String(y)} tabIndex={0} title={`${String(x)} × ${String(y)}; independent event N ${cell.independentEventN}`}><MetricValue metric={metric} value={value}/><small>N={cell.independentEventN}</small></td>})}</tr>)}</tbody></table></div></ReportPanel>

  <ReportPanel title="Execution survival" eyebrow="Reference → Q50 → Q90" description="Coverage attrition and paired economic degradation are separate evidence."><div className="research-economics-controls"><Toggle label="Dimension" value={executionDimension} options={[{id:"dte",label:"DTE"},{id:"strike",label:"Strike"},{id:"width",label:"Width"}]} onChange={setExecutionDimension}/><Toggle label="Degradation metric" value={executionMetric} options={[{id:"netCreditUsd",label:"Net credit"},{id:"totalFeesUsd",label:"Fees"},{id:"pnlUsd",label:"PnL"},{id:"trackMaximumNetLossUsd",label:"Track max loss"},{id:"returnOnPeakCapital",label:"Return"}]} onChange={setExecutionMetric}/></div><div className="exit-table-scroll"><table className="exit-table"><thead><tr><th>Category</th><th>Reference priced</th><th>Q50 priced</th><th>Q90 priced</th><th>Ref↔Q50 common</th><th>Q50↔Q90 common</th></tr></thead><tbody>{execGroups.map(x=><tr key={String(x.value)}><th>{category(x.value,executionDimension)}</th><td>{x.tracks.reference.pricedN}</td><td>{x.tracks.modeled_expected.pricedN}</td><td>{x.tracks.modeled_conservative.pricedN}</td><td>{x.comparisons[0]!.commonN}</td><td>{x.comparisons[1]!.commonN}</td></tr>)}</tbody></table></div><div className="research-economics-degradation">{degradation.map(x=>{const d=x.deltas[executionMetric as keyof typeof x.deltas];return <span key={`${x.from}-${x.to}`}><b>{TRACKS.find(t=>t.id===x.from)!.label} → {TRACKS.find(t=>t.id===x.to)!.label}</b><Money usd={d?.medianDelta??null}/><small>paired N={d?.effectivePairedN??0} · coverage attrition {x.coverageLoss}</small></span>})}</div></ReportPanel>

  <ReportPanel title="Economics by exit policy" eyebrow="Complete policies · fixed execution track" description="Economic consequences across the configuration universe; detailed chronology remains in Exit Policy."><Toggle label="Metric" value={policyMetric} options={METRICS.filter(x=>["pnlUsd","capitalDaysUsd","totalFeesUsd","returnOnPeakCapital"].includes(x.id))} onChange={setPolicyMetric}/><div className="research-economics-policy-grid">{report.exitPolicies.map((x,i)=>{const value=x[policyMetric==="pnlUsd"?"medianPnlUsd":policyMetric==="capitalDaysUsd"?"medianCapitalDaysUsd":policyMetric==="totalFeesUsd"?"medianTotalFeesUsd":"medianReturnOnPeakCapital"];return <article key={x.policy.id}><span className="exit-policy-chip">{i+1}</span><strong>{x.policy.label}</strong><MetricValue metric={policyMetric} value={value}/><small>priced N={x.coverage.pricedN}/{x.coverage.totalN}</small></article>})}</div><div className="exit-table-scroll"><table className="exit-table"><thead><tr><th>Alternative vs Thesis</th><th>Median Δ</th><th>Metric-specific paired N</th></tr></thead><tbody>{report.exitPolicies.filter(x=>x.policy.id!=="thesis").map(x=>{const d=x.versusThesis.deltas[policyMetric];return <tr key={x.policy.id}><th>{x.policy.label}</th><td><MetricValue metric={policyMetric} value={d.medianDelta}/></td><td>{d.effectivePairedN} / common {x.versusThesis.commonN}</td></tr>})}</tbody></table></div></ReportPanel>

  <details className="exit-panel research-economics-full-matrix"><summary><strong>Full configuration matrix</strong><small>{configurations.length} canonical configurations · deterministic structural order</small></summary><div className="exit-table-scroll"><table className="exit-table exit-table-wide"><thead><tr><th>Configuration</th><th>Coverage</th><th>Median PnL</th><th>Total fees</th><th>Fee drag</th><th>Peak IM</th><th>Return / peak capital</th><th>Capital-days</th><th>P10</th></tr></thead><tbody>{configurations.map(x=><tr key={x.configurationId}><th>{structuralConfigurationLabel(x.configuration)}</th><td>{x.pricedOpportunities}/{x.eligibleOpportunities}<small>{x.explicitNoTradeOpportunities} no-trade · {x.unavailableOpportunities} unavailable</small></td><td><Money usd={x.medianPnlUsd} btc={x.medianPnlBtc}/></td><td><Money usd={x.medianTotalFeesUsd} btc={x.medianTotalFeesBtc}/></td><td>{pct(x.medianFeeDrag)}</td><td><Money usd={x.medianPeakInitialMarginUsd}/></td><td>{pct(x.medianReturnOnPeakCapital)}</td><td><Money usd={x.medianCapitalDaysUsd} btc={x.medianCapitalDaysBtc}/></td><td>{x.p10PnlUsd.value===null?<span className="metric-unavailable">Not estimable · {x.p10PnlUsd.reason}</span>:<Money usd={x.p10PnlUsd.value} btc={x.p10PnlBtc.value}/>}</td></tr>)}</tbody></table></div></details>

  <ReportPanel title="Missingness & attention audit" eyebrow="Evidence first" description="Summary first; expand only when configuration-level reasons are needed."><div className="analytics-audit"><AuditAttentionControls invalid={invalid} partial={partial} unavailable={unavailable} unusual={unpaired} lowN={lowN}/><details className="exit-details"><summary>Configuration evidence details</summary>{configurations.map(x=>{const status=x.status==="integrity_error"?"INVALID":Object.values(x.usd).some(v=>v.effectiveN<v.requiredN)?"PARTIAL":x.unavailableOpportunities?"UNAVAILABLE":"VALID";return <p key={x.configurationId}><ResearchEvidenceBadge assessment={{status,reason:x.reason??(status==="PARTIAL"?"One or more canonical USD statistics have incomplete coverage.":status==="UNAVAILABLE"?`${x.unavailableOpportunities} unavailable opportunities.`:null)}}/> {structuralConfigurationLabel(x.configuration)} · priced {x.pricedOpportunities}/{x.eligibleOpportunities}</p>})}</details></div></ReportPanel>
  {currency==="btc"&&<p className="exit-note">Native BTC display uses only independently canonical BTC fields. USD-only comparative cells show Unavailable without conversion or fallback.</p>}
 </section>
}
