"use client";
import type {StructureAnalyticsReport} from "../lib/structure-policy-economics";
const f=(x:number|null)=>x===null?"unavailable":x.toFixed(6),p=(x:number|null)=>x===null?"unavailable":`${(x*100).toFixed(1)}%`;
export function StructurePolicyEconomicsReport({report:r}:{report:StructureAnalyticsReport}){return <section className="workspace-section" data-testid="structure-policy-economics-report"><div className="section-heading"><div><p className="eyebrow">Research Analytics · causal controls</p><h2>Structure, Exit Policies &amp; Economics</h2></div></div><p className="resolution-banner">Every result shows sample, coverage, pricing track and execution assumption. Unmatched observations are descriptive, not causal.</p>
<div className="card"><h3>Short Strike · matched pairs &amp; tail-loss chart</h3><p>{r.shortStrike.matchedPairCount} matched pairs · {r.shortStrike.excludedCases} excluded. {r.shortStrike.conclusion}</p><div className="table-scroll"><table><caption>Technical versus buffered; event, actual expiry, actual width, execution, track and policy held constant</caption><thead><tr><th>Pair</th><th>Controls</th><th>Δ PnL</th><th>Credit sacrificed</th></tr></thead><tbody>{r.shortStrike.matches.map(x=><tr key={x.leftId+x.rightId}><td>{x.leftId} / {x.rightId}</td><td>{x.controlKey}</td><td>{f(x.deltaPnl)}</td><td>{f(x.creditSacrificed)}</td></tr>)}</tbody></table></div></div>
<div className="card"><h3>Width risk / return frontier</h3><p>{r.width.matchedPairCount} matched pairs · {r.width.excludedCases} excluded.</p><div className="table-scroll"><table><thead><tr><th>Position</th><th>Actual width</th><th>Credit</th><th>Exact maximum economic loss</th><th>Return / max loss</th></tr></thead><tbody>{r.width.frontier.map(x=><tr key={String(x.candidate_id)}><td>{String(x.candidate_id)}</td><td>{f(x.width as number|null)}</td><td>{f(x.credit as number|null)}</td><td>{f(x.maximum_economic_loss as number|null)}</td><td>{p(x.return_on_max_loss as number|null)}</td></tr>)}</tbody></table></div><div className="table-scroll"><table><caption>Long-leg protection counterfactual; separate leg components, same quantity and fees</caption><thead><tr><th>Position</th><th>Spread</th><th>Naked short</th><th>Protection benefit</th><th>Margin warning</th></tr></thead><tbody>{r.width.protection.map(x=><tr key={String(x.candidate_id)}><td>{String(x.candidate_id)}</td><td>{f(x.spread_pnl as number|null)}</td><td>{f(x.naked_short_counterfactual as number|null)}</td><td>{f(x.long_leg_protection as number|null)}</td><td>{String(x.margin_comparability)}</td></tr>)}</tbody></table></div></div>
<div className="card"><h3>Policy comparison &amp; trigger composition</h3><div className="table-scroll"><table><thead><tr><th>Policy / track / execution</th><th>n / coverage</th><th>Mean / median</th><th>P10 / P5 / worst</th><th>MAE / surrendered MFE / avoided</th><th>Hours / capital-days / fees</th><th>Triggers</th></tr></thead><tbody>{r.policies.map(x=><tr key={x.policy+x.track}><td>{x.policy}<br/><small>{x.track} · {x.executionAssumption}</small></td><td>{x.sampleSize} / {p(x.coverage.rate)} ({x.coverage.available}/{x.coverage.total})</td><td>{f(x.expectancy)} / {f(x.median)}</td><td>{f(x.p10)} / {f(x.p5)} / {f(x.worst)}</td><td>{f(x.mae)} / {f(x.surrenderedPostExitMfe)} / {f(x.lossesAvoided)}</td><td>{f(x.holdingHours)} / {f(x.capitalDays)} / {f(x.fees)}</td><td>{Object.entries(x.triggers).map(([k,v])=>`${k}:${v}`).join(", ")||`missing ${x.missingExits}`}</td></tr>)}</tbody></table></div></div>
<div className="card"><h3>Per-position economics ledger</h3><div className="table-scroll"><table><thead><tr><th>Position / track / execution</th><th>Gross / net</th><th>Open / close fees</th><th>Slippage</th><th>Exact max loss</th><th>Occupancy</th><th>Incremental / peak margin</th><th>Account model &amp; provenance</th><th>Policies</th></tr></thead><tbody>{r.economics.map(x=><tr key={x.candidateId+x.track}><td>{x.candidateId}<br/><small>{x.track} · {x.executionAssumption}</small></td><td>{f(x.grossCredit)} / {f(x.netCredit)}</td><td>{f(x.openingFees)} / {f(x.closingFees)}</td><td>{f(x.slippage)}</td><td>{f(x.maximumEconomicLoss)}</td><td>{f(x.capitalOccupancyDays)}d</td><td>{f(x.incrementalOpeningMargin)} / {f(x.peakMargin)}</td><td>{x.marginAccountModel}; {x.marginStatus}; historical {x.historicalMarginStatus}; PM {x.portfolioMarginStatus}</td><td><details><summary>Drill down</summary>{Object.entries(x.pnlByPolicy).map(([k,v])=><div key={k}>{k}: {f(v)} · RoML {p(x.returnOnMaximumLoss[k])}</div>)}</details></td></tr>)}</tbody></table></div></div>
<div className="card"><h3>Methodology</h3>{r.methodology.map(x=><p className="fine-print" key={x}>{x}</p>)}</div></section>}
