import type {VolatilityReport} from "../lib/volatility/volatility-report";
import {RV_HORIZONS} from "../lib/volatility/realized-volatility";
const pct=(v:number|null)=>v===null?"Not evaluated":`${(v*100).toFixed(1)}%`;
const value=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?`${(v*100).toFixed(2)}%`:"Unavailable";
const reasons=(r:Readonly<Record<string,number>>)=>Object.entries(r).map(([k,n])=>`${k}: ${n}`).join(" · ")||"none";
const Coverage=({label,t}:{label:string;t:{available:number;total:number;ratio:number|null;reasons:Readonly<Record<string,number>>}})=><div className="dd-card"><span className="dd-label">{label}</span><strong>{t.available} / {t.total}</strong><small>{pct(t.ratio)} · unavailable: {reasons(t.reasons)}</small></div>;
export function VolatilityReportView({report}:{report:VolatilityReport}){return <section id="volatility-report" className="workspace-section">
 <div className="section-heading"><div><p className="eyebrow">Market-state research layer · execution-independent</p><h2>Volatility</h2></div><em className="report-state available">{report.coverage.eventCount} events · {report.coverage.structureCount} structures</em></div>
 <p className="resolution-banner">A vertical spread has no single implied volatility. The legs and their differentials are analyzed separately. DVOL is broad BTC volatility context only, never the IV of a selected spread.</p>
 <h3>Evidence coverage</h3><div className="dd-grid">{(["7d","14d","30d"] as const).map(t=><Coverage key={t} label={`${t.toUpperCase()} reference IV`} t={report.coverage.referenceIvByTenor[t]}/>)}{RV_HORIZONS.map(h=><Coverage key={h} label={`RV ${h.toUpperCase()}`} t={report.coverage.realizedVolatilityByHorizon[h]}/>)}<Coverage label="Broad volatility / DVOL" t={report.coverage.broadVolatilityIndex}/><Coverage label="Same-expiry reference" t={report.coverage.structureReference}/><Coverage label="Observed short leg" t={report.structureCoverage.short}/><Coverage label="Observed long leg" t={report.structureCoverage.long}/><Coverage label="Both legs observed" t={report.structureCoverage.both}/><Coverage label="Post-entry endpoints" t={report.endpointCoverage}/></div>
 <h3>Volatility environment at MR entry</h3><div className="table-scroll"><table className="dd-table"><thead><tr><th>Event</th><th>Reference IV 7D / 14D / 30D</th><th>Actual DTE</th><th>RV 1D / 3D / 7D / 14D / 30D</th><th>IV percentile (prior N)</th><th>Term slopes raw / actual-day</th><th>Broad context</th></tr></thead><tbody>{report.events.map(e=><tr key={String(e.event_id)}><td>{String(e.event_id)}</td><td>{(e.reference_iv as Record<string,unknown>[]).map(x=>value(x.iv_decimal)).join(" / ")}</td><td>{(e.reference_iv as Record<string,unknown>[]).map(x=>typeof x.actual_dte_days==="number"?`${x.actual_dte_days.toFixed(1)}d`:"—").join(" / ")}</td><td>{(e.realized_volatility as Record<string,unknown>[]).map(x=>value(x.rv_decimal)).join(" / ")}</td><td>{(e.reference_iv_percentile as Record<string,unknown>[]).map(x=>`${value(x.percentile)} (${String(x.prior_observation_count??0)})`).join(" / ")}</td><td>{(e.term_structure as Record<string,unknown>[]).map(x=>`${value(x.value)} / ${value(x.value_per_day)}`).join(" · ")}</td><td>{value((e.broad_volatility_index as Record<string,unknown>)?.value_decimal)}</td></tr>)}</tbody></table></div>
 <h3>Structure volatility and skew</h3><div className="table-scroll"><table className="dd-table"><thead><tr><th>Metric</th><th>N</th><th>P25</th><th>Median</th><th>P75</th></tr></thead><tbody>{Object.entries(report.aggregates).map(([k,q])=><tr key={k}><td>{k.replaceAll("_"," ")}</td><td>{q.n}</td><td>{value(q.p25)}</td><td>{value(q.median)}</td><td>{value(q.p75)}</td></tr>)}</tbody></table></div>
 <details><summary>Structure evidence and provenance</summary><pre className="analytics-inspector">{JSON.stringify(report.structures,null,2)}</pre></details>
 <h3>Observed IV behavior after entry</h3><p>Changes require observed market IV at both endpoints. Outcome endpoints join exactly to the canonical Reference outcome valuation timestamp; gaps are not carried forward.</p><div className="table-scroll"><table className="dd-table"><thead><tr><th>Candidate</th><th>Endpoint</th><th>Canonical timestamp</th><th>Short IV / Δ</th><th>Long IV / Δ</th><th>Status</th></tr></thead><tbody>{report.endpoints.map((e,i)=><tr key={`${e.candidateId}-${e.id}-${i}`}><td>{e.candidateId}</td><td>{e.label}</td><td>{e.timestampUtc??"Unavailable"}</td><td>{value(e.shortIv)} / {value(e.deltaShortIv)}</td><td>{value(e.longIv)} / {value(e.deltaLongIv)}</td><td>{e.status}{e.reason?` · ${e.reason}`:""}</td></tr>)}</tbody></table></div>
 </section>}
