import type {VolatilityReport,Row} from "../lib/volatility/volatility-report";
import {volatilityDiff,volatilityLeg} from "../lib/volatility/volatility-report";
const num=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:null;
const rows=(v:unknown):Row[]=>Array.isArray(v)?v as Row[]:[];
const iv=(v:unknown)=>num(v)===null?"Unavailable":`${(num(v)!*100).toFixed(1)}%`;
const vp=(v:unknown)=>num(v)===null?"Unavailable":`${num(v)!<0?"":"+"}${(num(v)!*100).toFixed(1)} vol pts`;
const ordinal=(v:unknown)=>num(v)===null?"Unavailable":`${Math.round(num(v)!*100)}th`;
const ratio=(a:number,b:number)=>`${a} / ${b} · ${b?`${(a/b*100).toFixed(1)}%`:"Not evaluated"}`;
const why=(r:Readonly<Record<string,number>>)=>Object.entries(r).map(([k,v])=>`${k}: ${v}`).join(" · ")||"none";
const Coverage=({label,a,t,reasons}:{label:string;a:number;t:number;reasons?:Readonly<Record<string,number>>})=><div className="dd-card" title={`Unavailable reasons: ${why(reasons??{})}`}><span className="dd-label">{label}</span><strong>{ratio(a,t)}</strong><small>available N / denominator N</small></div>;
const by=(r:Row,key:string,name:string)=>rows(r[key]).find(x=>x.nominal_tenor===name||x.horizon===name||x.slope===name);

export function EmbeddedVolatilityContext({report,kind}:{report:VolatilityReport;kind:"dte"|"strike"|"width"|"exit"|"economics"}){
 if(kind==="dte")return <section className="dd-block" data-testid="duration-volatility"><h3>Volatility by DTE</h3><p>How much volatility are we selling across different maturities, and what does the term structure look like?</p><div className="table-scroll"><table className="dd-table"><thead><tr><th>Horizon / actual DTE</th><th>N / denominator</th><th>Reference IV</th><th>Short IV</th><th>Long IV</th><th>Trailing RV</th><th>Entry IV − trailing RV</th><th>IV percentile</th><th>Term slope</th></tr></thead><tbody>{["7d","14d","30d"].map((t,i)=>{const er=report.events.filter(e=>by(e,"reference_iv",t)?.status==="available"),sr=report.structures.filter(x=>{const d=num(x.actual_dte_days);return d!==null&&(i===0?d<11:i===1?d<22:d>=22)}),med=(a:(number|null)[])=>{const z=a.filter((x):x is number=>x!==null).sort((a,b)=>a-b);return z.length?z[Math.floor(z.length/2)]!:null};return <tr key={t}><td>{t.toUpperCase()} / {er.length?`${num(by(er[0]!,"reference_iv",t)?.actual_dte_days)?.toFixed(1)}d`:"Unavailable"}</td><td>{ratio(er.length,report.eventDenominator)}</td><td>{iv(med(er.map(x=>num(by(x,"reference_iv",t)?.iv_decimal))))}</td><td>{iv(med(sr.map(x=>num(volatilityLeg(x,"short")?.iv_decimal))))}</td><td>{iv(med(sr.map(x=>num(volatilityLeg(x,"long")?.iv_decimal))))}</td><td>{iv(med(er.map(x=>num(by(x,"realized_volatility",t)?.rv_decimal))))}</td><td>{vp(med(er.map(x=>num(by(x,"iv_minus_rv",t)?.value))))}</td><td>{ordinal(med(er.map(x=>num(by(x,"reference_iv_percentile",t)?.percentile))))}</td><td>{vp(med(er.map(x=>num(by(x,"term_structure",i===0?"slope_7d_14d":"slope_14d_30d")?.value))))}</td></tr>})}</tbody></table></div></section>;
 if(kind==="exit")return <section className="dd-block" data-testid="exit-volatility"><h3>Observed IV at existing exits</h3><p>Did this exit usually occur after the volatility we sold had already compressed? Association only; no PnL attribution.</p><table className="dd-table"><thead><tr><th>Policy / endpoint</th><th>Observed N / denominator</th><th>Entry → exit short IV</th><th>Median Δ short IV</th><th>Entry → exit long IV</th><th>Median Δ long IV</th><th>Short-IV compression / expansion</th></tr></thead><tbody>{report.endpointAggregates.filter(x=>["vpoc","invalidation","credit_capture_50","credit_capture_70","fixed_3d","fixed_5d","fixed_7d","settlement"].includes(x.id)).map(x=><tr key={x.id}><td>{x.label}</td><td>{ratio(x.n,x.denominator)}</td><td>{x.n?"Observed endpoints":"Unavailable"}</td><td>{vp(x.medianDeltaShortIv)}</td><td>{x.n?"Observed endpoints":"Unavailable"}</td><td>{vp(x.medianDeltaLongIv)}</td><td>{x.shortCompressionShare===null?"Not evaluated":`${iv(x.shortCompressionShare)} / ${iv(x.shortExpansionShare)}`}</td></tr>)}</tbody></table></section>;
 const title=kind==="strike"?"Volatility by Short Strike":kind==="width"?"Protection Skew by Spread Width":"Entry volatility context (read-only)";
 return <section className="dd-block" data-testid={`${kind}-volatility`}><h3>{title}</h3><p>{kind==="strike"?"Moving the short strike farther away: skew/IV/credit surrendered versus risk removed; higher IV is not automatically better.":kind==="width"?"What part of skew is purchased as protection, its premium cost, and whether loss distribution improves; skew alone is not proof of value.":"These fields do not affect Q50, Q90, fees, slippage, margin, account size, structural loss, or PnL."}</p><div className="table-scroll"><table className="dd-table"><thead><tr><th>Event / candidate</th><th>DTE</th><th>Short strike / IV</th><th>Long strike / IV</th><th>Same-expiry reference</th><th>Short − reference</th><th>{kind==="width"?"Short − long IV":"IV − trailing RV"}</th><th>Evidence status / age</th></tr></thead><tbody>{report.structures.map(r=>{const a=volatilityLeg(r,"short"),b=volatilityLeg(r,"long"),ref=r.same_expiry_reference as Row|undefined;return <tr key={String(r.candidate_id)}><td>{String(r.event_id)}<br/><small>{String(r.candidate_id)}</small></td><td>{num(r.actual_dte_days)?.toFixed(1)??"Unavailable"}d</td><td>{num(r.short_strike)??"Unavailable"} / {iv(a?.iv_decimal)}</td><td>{num(r.long_strike)??"Unavailable"} / {iv(b?.iv_decimal)}</td><td>{iv(ref?.iv_decimal)}</td><td>{vp(volatilityDiff(r,"short_minus_reference_iv")?.value)}</td><td>{kind==="width"?vp(volatilityDiff(r,"short_minus_long_iv")?.value):"See matching event tenor"}</td><td>{String(a?.status??"unavailable")} / {num(a?.age_minutes)?.toFixed(1)??"—"} min</td></tr>})}</tbody></table></div></section>;
}

export function VolatilityReportView({report}:{report:VolatilityReport}){return <section id="volatility-report" className="workspace-section" data-testid="volatility-report"><div className="section-heading"><div><p className="eyebrow">Market-state research layer · execution-independent</p><h2>Volatility</h2></div></div><p className="resolution-banner">A vertical spread has no single implied volatility. Short- and long-leg IV are analyzed separately. DVOL is broad context only.</p>
 <h3>Evidence coverage</h3><div className="dd-grid"><Coverage label="MR events with volatility state" a={report.coverage.eventCount} t={report.eventDenominator}/><Coverage label="Selected structures with volatility state" a={report.coverage.structureCount} t={report.structureDenominator}/>{(["7d","14d","30d"] as const).map(t=><Coverage key={t} label={`${t.toUpperCase()} reference-IV`} a={report.coverage.referenceIvByTenor[t].available} t={report.coverage.referenceIvByTenor[t].total} reasons={report.coverage.referenceIvByTenor[t].reasons}/>)}<Coverage label="RV coverage (7D)" {...{a:report.coverage.realizedVolatilityByHorizon["7d"].available,t:report.coverage.realizedVolatilityByHorizon["7d"].total,reasons:report.coverage.realizedVolatilityByHorizon["7d"].reasons}}/><Coverage label="IV-percentile coverage (7D)" a={report.coverage.percentileByTenor["7d"].available} t={report.coverage.percentileByTenor["7d"].total} reasons={report.coverage.percentileByTenor["7d"].reasons}/><Coverage label="Same-expiry structure reference" a={report.coverage.structureReference.available} t={report.coverage.structureReference.total} reasons={report.coverage.structureReference.reasons}/><Coverage label="Short-leg observed IV" {...{a:report.structureCoverage.short.available,t:report.structureCoverage.short.total,reasons:report.structureCoverage.short.reasons}}/><Coverage label="Long-leg observed IV" {...{a:report.structureCoverage.long.available,t:report.structureCoverage.long.total,reasons:report.structureCoverage.long.reasons}}/><Coverage label="Both-leg observed IV" {...{a:report.structureCoverage.both.available,t:report.structureCoverage.both.total,reasons:report.structureCoverage.both.reasons}}/><Coverage label="Post-entry observed IV" {...{a:report.endpointCoverage.available,t:report.endpointCoverage.total,reasons:report.endpointCoverage.reasons}}/></div>
 <h3>Aggregate entry volatility environment</h3><table className="dd-table"><thead><tr><th>Tenor</th><th>N</th><th>Median / P25 / P75 entry IV</th><th>Median trailing RV</th><th>Median Entry IV − trailing RV</th><th>Median percentile</th><th>Term structure</th></tr></thead><tbody>{["7d","14d","30d"].map((t,i)=>{const es=report.events,vals=es.flatMap(e=>{const x=by(e,"reference_iv",t);return num(x?.iv_decimal)===null?[]:[num(x?.iv_decimal)!]}).sort((a,b)=>a-b),q=(p:number)=>vals.length?vals[Math.floor((vals.length-1)*p)]!:null;return <tr key={t}><td>{t.toUpperCase()}</td><td>{vals.length} / {report.eventDenominator}</td><td>{iv(q(.5))} / {iv(q(.25))} / {iv(q(.75))}</td><td>{iv(num(by(es[0]??{},"realized_volatility",t)?.rv_decimal))}</td><td>{vp(num(by(es[0]??{},"iv_minus_rv",t)?.value))}</td><td>{ordinal(num(by(es[0]??{},"reference_iv_percentile",t)?.percentile))}</td><td>{i<2?vp(num(by(es[0]??{},"term_structure",i?"slope_14d_30d":"slope_7d_14d")?.value)):"—"}</td></tr>})}</tbody></table>
 <h3>Entry volatility environment</h3><div className="table-scroll"><table className="dd-table"><thead><tr><th>Event / entry UTC</th><th>~7D IV / actual DTE</th><th>~14D IV / actual DTE</th><th>~30D IV / actual DTE</th><th>RV 1D / 3D / 7D / 14D / 30D</th><th>Entry IV − trailing RV 7/14/30</th><th>IV percentile 7/14/30</th><th>7→14 / 14→30 slope</th><th>DVOL / evidence</th></tr></thead><tbody>{report.events.map(e=><tr key={String(e.event_id)}><td>{String(e.event_id)}<br/><small>{String(e.entry_timestamp_utc)} UTC</small></td>{["7d","14d","30d"].map(t=>{const x=by(e,"reference_iv",t);return <td key={t}>{iv(x?.iv_decimal)} / {num(x?.actual_dte_days)?.toFixed(1)??"Unavailable"}d</td>})}<td>{["1d","3d","7d","14d","30d"].map(t=>iv(by(e,"realized_volatility",t)?.rv_decimal)).join(" / ")}</td><td>{["7d","14d","30d"].map(t=>vp(by(e,"iv_minus_rv",t)?.value)).join(" / ")}</td><td>{["7d","14d","30d"].map(t=>ordinal(by(e,"reference_iv_percentile",t)?.percentile)).join(" / ")}</td><td>{["slope_7d_14d","slope_14d_30d"].map(t=>vp(by(e,"term_structure",t)?.value)).join(" / ")}</td><td>{iv((e.broad_volatility_index as Row|undefined)?.value_decimal)} / {rows(e.reference_iv).some(x=>x.status==="available")?"market evidence available":"Unavailable"}</td></tr>)}</tbody></table></div>
 <h3>Structure IV / skew</h3><EmbeddedVolatilityContext report={report} kind="width"/><table className="dd-table"><thead><tr><th>Metric</th><th>Coverage N</th><th>P25</th><th>Median</th><th>P75</th></tr></thead><tbody>{Object.entries(report.aggregates).map(([k,q])=><tr key={k}><td>{k.replaceAll("_"," ")}</td><td>{q.n} / {report.structureDenominator}</td><td>{k.includes("minus")?vp(q.p25):iv(q.p25)}</td><td>{k.includes("minus")?vp(q.median):iv(q.median)}</td><td>{k.includes("minus")?vp(q.p75):iv(q.p75)}</td></tr>)}</tbody></table>
 <h3>Post-entry observed IV behavior</h3><p>Outcome endpoints exact-match <code>outcomes.jsonl.valuation_timestamp_utc</code> on canonical Reference; no nearby search or reconstructed IV.</p><EmbeddedVolatilityContext report={report} kind="exit"/><div className="table-scroll"><table className="dd-table"><thead><tr><th>Candidate</th><th>Endpoint / exact UTC</th><th>Entry → endpoint short IV / Δ</th><th>Entry → endpoint long IV / Δ</th><th>Status</th></tr></thead><tbody>{report.endpoints.map((e,i)=><tr key={`${e.candidateId}-${e.id}-${i}`}><td>{e.candidateId}</td><td>{e.label}<br/><small>{e.timestampUtc??"Unavailable"}</small></td><td>{iv(e.entryShortIv)} → {iv(e.shortIv)} / {vp(e.deltaShortIv)}</td><td>{iv(e.entryLongIv)} → {iv(e.longIv)} / {vp(e.deltaLongIv)}</td><td>{e.status}{e.reason?` · ${e.reason}`:""}</td></tr>)}</tbody></table></div>
 <h3>Observed IV path diagnostics</h3><p>No interpolation and no constant-IV inference during gaps.</p><table className="dd-table"><thead><tr><th>Candidate</th><th>Short points</th><th>Short min / max / range</th><th>Long points</th><th>Long min / max / range</th></tr></thead><tbody>{report.paths.map(x=><tr key={x.candidateId}><td>{x.candidateId}</td><td>{x.shortPoints}</td><td>{iv(x.shortMin)} / {iv(x.shortMax)} / {vp(x.shortRange)}</td><td>{x.longPoints}</td><td>{iv(x.longMin)} / {iv(x.longMax)} / {vp(x.longRange)}</td></tr>)}</tbody></table></section>}
