import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {assessEconomicPositions,matchesAttentionFilter,summarizeAttention,ECONOMICS_TAIL_ATTENTION_MIN_N} from "../app/lib/analytics-attention.ts";
import type {PositionEconomics} from "../app/lib/economics/position.ts";

const position=(id:string,pnl:number|null,status:PositionEconomics["status"]="priced",reason:string|null=null)=>({candidateId:id,eventId:`event-${id}`,structureExecutionId:id,exitPolicy:"thesis",status,pnlBtc:pnl,missingReason:reason,trackMaximumNetLossBtc:{value:.1,reason:null},incrementalInitialMarginBtc:{value:.1,reason:null},peakInitialMarginBtc:{value:.1,reason:null},capitalDaysBtc:{value:.1,reason:null}} as PositionEconomics);

test("PRESENTATION: a losing valid observation is adverse economics, never invalid evidence",()=>{const rows=Array.from({length:ECONOMICS_TAIL_ATTENTION_MIN_N},(_,i)=>position(String(i),i-10)),map=assessEconomicPositions(rows),loss=map.get("0|thesis")!;assert.equal(loss.evidence,"VALID");assert.ok(loss.attention.some(x=>x.kind==="ADVERSE"));assert.ok(!loss.attention.some(x=>x.kind as string==="INVALID"))});
test("PRESENTATION: canonical invalidity and unavailable evidence stay distinct",()=>{const map=assessEconomicPositions([position("bad",1,"priced","Causal violation: pre-entry mark."),position("missing",null,"unavailable","Exit valuation unavailable.")]);assert.equal(map.get("bad|thesis")!.evidence,"INVALID");assert.equal(map.get("missing|thesis")!.evidence,"UNAVAILABLE")});
test("PRESENTATION: attention summary exactly counts detailed assessments",()=>{const rows=Array.from({length:20},(_,i)=>position(String(i),i)),map=assessEconomicPositions(rows),summary=summarizeAttention(map.values());assert.equal(summary.unusualAdverse,[...map.values()].filter(x=>x.attention.some(a=>a.kind==="UNUSUAL")&&x.attention.some(a=>a.kind==="ADVERSE")).length);assert.equal(summary.unusualFavorable,[...map.values()].filter(x=>x.attention.some(a=>a.kind==="UNUSUAL")&&x.attention.some(a=>a.kind==="FAVORABLE")).length);assert.ok(matchesAttentionFilter(map.get("0|thesis")!,"attention"));assert.ok(!matchesAttentionFilter(map.get("10|thesis")!,"attention"))});
test("PRESENTATION: Economics is summary-first and raw rows are a closed audit",()=>{const source=readFileSync(new URL("../app/components/economic-analysis-report.tsx",import.meta.url),"utf8");assert.ok(source.indexOf("economics-primary-kpis")<source.indexOf('title="Per-position details"'));assert.match(source,/<details className="exit-details economics-audit"/);assert.match(source,/Attention only/);assert.match(source,/aria-pressed/);assert.match(source,/x===null\?UNAVAILABLE/);assert.doesNotMatch(source,/[-−]\$0(?:\.0+)?/)});
test("PRESENTATION: shared badges expose textual accessibility labels",()=>{const source=readFileSync(new URL("../app/components/research-evidence-status.tsx",import.meta.url),"utf8");assert.match(source,/aria-label={`Evidence:/);assert.match(source,/aria-label={`Attention:/)});
test("PRESENTATION: large report audit datasets default collapsed while Exit Policy keeps its primary surface",()=>{for(const file of ["underlying-resolution-report.tsx","duration-dte-report.tsx","short-strike-report.tsx","spread-width-report.tsx","futures-comparison-report.tsx"]){const source=readFileSync(new URL(`../app/components/${file}`,import.meta.url),"utf8");assert.match(source,/<details[^>]*(?:exit-details|ur-block|dd-event-block)/,file)}const exit=readFileSync(new URL("../app/components/exit-policy-report.tsx",import.meta.url),"utf8");assert.match(exit,/Primary decision surface/);assert.match(exit,/Candidate and missing-data audit/)});
