import test from "node:test";
import assert from "node:assert/strict";
import { analyzeDelayedExecution, createEntryTimingPolicy } from "../app/lib/delayed-execution.ts";
import { executeHistoricalSpread, type BacktestEvent, type ContractSeries, type ContractTrade, type RetrievedSpread } from "../app/lib/backtester.ts";

const H=3_600_000,T=Date.UTC(2025,0,6),expiry=T+40*H;
const trade=(instrumentName:string,h:number,direction:"buy"|"sell",price:number,amount=1,id=`${instrumentName}-${h}-${direction}`):ContractTrade=>({instrumentName,timestamp:T+h*H,direction,price,amount,indexPrice:100_000+h*100,tradeId:id});
const series=(instrumentName:string,strike:number,trades:ContractTrade[],metadata=false):ContractSeries=>({instrumentName,strike,trades,optionType:"P",expiryTimestamp:expiry,expiryLabel:"fixture",firstTradeTimestamp:T,lastTradeTimestamp:expiry,sourceFiles:["fixture"],amountMetadata:metadata?{minimumTradeAmount:.1,amountStep:.1,amountPrecision:1,source:"deribit-instrument-metadata"}:undefined});
function fixture(shortTrades:ContractTrade[],longTrades:ContractTrade[],metadata=false){const soldContract=series("BTC-SHORT",100_000,shortTrades,metadata),boughtContract=series("BTC-LONG",90_000,longTrades,metadata);const spread={id:"s",targetDte:2,targetWidth:10_000,anchorStrike:100_000,soldStrike:100_000,boughtStrike:90_000,optionType:"P",spreadKind:"credit",structure:"put-credit",buffered:false,venue:"deribit",expiryTimestamp:expiry,soldContract,boughtContract,soldExistedAtEntry:true,boughtExistedAtEntry:true,retrievalStatus:"ready",retrievalNote:"fixture"} satisfies RetrievedSpread;const event={id:"e",label:"fixture",direction:"long",entryDate:"2025-01-06",entryPrice:100_000,entryTimestamp:T} satisfies BacktestEvent;return{spread,event}}
const run=(f:ReturnType<typeof fixture>,extra:Record<string,unknown>={})=>analyzeDelayedExecution({spread:f.spread,event:f.event,signalTimestamp:T,underlyingCandles:[{openTime:T+3*H,closeTime:T+4*H,open:100_200,high:101_000,low:99_000,close:100_400,volume:1}],primarySize:1,policy:createEntryTimingPolicy({maximumLegSynchronizationMs:H}),...extra});

test("no immediate evidence becomes executable causally in 2-4h and later leg sets entry",()=>{const a=run(fixture([trade("BTC-SHORT",2.5,"sell",.08)],[trade("BTC-LONG",3,"buy",.02)]));const o=a.results[0].taker[1];assert.equal(o.status,"delayed taker execution proxy");assert.equal(o.entryTimestamp,T+3*H);assert.equal(o.shortLeg!.completionTimestamp,T+2.5*H);assert.equal(o.synchronizationGapMs,.5*H);assert.equal(a.results[0].taker[0].status,"unavailable")});
test("predetermined sizes do not opportunistically resize the primary population",()=>{const a=run(fixture([trade("BTC-SHORT",3,"sell",.08,.5)],[trade("BTC-LONG",3,"buy",.02,.5)],true),{sizeGrid:[.5]});assert.equal(a.results[0].size,1);assert.equal(a.results[0].taker[1].reasonCode,"insufficient-short-amount");assert.equal(a.results[1].isPrimary,false);assert.equal(a.results[1].taker[1].status,"delayed taker execution proxy")});
test("classifies VPOC, invalidation and expiry before completion as missed entries",()=>{for(const [field,expected] of [["vpocTimestamp","vpoc-occurred-before-entry"],["exitTimestamp","invalidation-occurred-before-entry"]] as const){const f=fixture([trade("BTC-SHORT",3,"sell",.08)],[trade("BTC-LONG",3,"buy",.02)]);f.event[field]=T+2*H;const o=run(f).results[0].taker[1];assert.equal(o.status,"missed-entry");assert.equal(o.preEntryResolution,expected);assert.deepEqual(o.postEntryPath,[])}const f=fixture([trade("BTC-SHORT",41,"sell",.08)],[trade("BTC-LONG",41,"buy",.02)]);assert.equal(run(f).results[0].taker.at(-1)!.preEntryResolution,"expired-before-entry")});
test("recomputes delayed deterioration and improvement without signal economics",()=>{const bad=run(fixture([trade("BTC-SHORT",3,"sell",.01)],[trade("BTC-LONG",3,"buy",.02)])).results[0].taker[1],good=run(fixture([trade("BTC-SHORT",3,"sell",.12)],[trade("BTC-LONG",3,"buy",.01)])).results[0].taker[1];assert.equal(bad.reasonCode,"debit-at-delayed-entry");assert.equal(bad.status,"observed-but-policy-rejected");assert.ok(good.economics!.netCreditBtc>0);assert.equal(good.economics!.underlyingIndex,100_300);assert.equal(good.economics!.remainingDte,37/24)});
test("synchronization failure is typed",()=>{const o=run(fixture([trade("BTC-SHORT",2.1,"sell",.08)],[trade("BTC-LONG",3.5,"buy",.02)])).results[0].taker[1];assert.equal(o.reasonCode,"synchronization-failure")});
test("maker and taker use independent direction evidence",()=>{const maker=run(fixture([trade("BTC-SHORT",3,"buy",.08)],[trade("BTC-LONG",3,"sell",.02)])).results[0];assert.equal(maker.maker[1].status,"delayed observed opportunity");assert.equal(maker.taker[1].status,"unavailable");const taker=run(fixture([trade("BTC-SHORT",3,"sell",.08)],[trade("BTC-LONG",3,"buy",.02)])).results[0];assert.equal(taker.taker[1].status,"delayed taker execution proxy");assert.equal(taker.maker[1].status,"unavailable")});
test("deduplicates trade IDs and never consumes future evidence in an earlier bucket",()=>{const s=trade("BTC-SHORT",3,"sell",.08,.6,"duplicate"),l=trade("BTC-LONG",3,"buy",.02,1);const a=run(fixture([s,{...s}],[l]));assert.equal(a.results[0].taker[1].reasonCode,"insufficient-short-amount");assert.equal(a.results[0].taker[0].shortLeg,undefined)});
test("actual entry anchors spot, DTE, path, holding and capital-days",()=>{const o=run(fixture([trade("BTC-SHORT",3,"sell",.08)],[trade("BTC-LONG",3,"buy",.02)])).results[0].taker[1];assert.equal(o.entryTimestamp,T+3*H);assert.ok(o.postEntryPath.every(p=>p.timestamp>o.entryTimestamp!));assert.equal(o.postEntryPath[0].hoursFromEntry,1);assert.equal(o.operationalHoldingHours,1);assert.notEqual(o.economics!.underlyingIndex,100_000)});
test("analysis survives exact JSON export/import equality and reports buckets",()=>{const a=run(fixture([trade("BTC-SHORT",3,"sell",.08)],[trade("BTC-LONG",3,"buy",.02)]));assert.deepEqual(JSON.parse(JSON.stringify(a)),a);assert.equal(a.coverageByDelayBucket["2-4h"].taker,1);assert.equal(a.policy.version,"causal-progressive-entry/1.0.0")});
test("immediate execution primitive remains unchanged and separate",()=>{const f=fixture([trade("BTC-SHORT",.5,"sell",.08)],[trade("BTC-LONG",.5,"buy",.02)]),before=executeHistoricalSpread({spread:f.spread,intent:"open",executionMode:"taker",decisionTimestamp:T,orderSubmissionTimestamp:T,fillWindowMs:H,amount:1,maxLegSyncMs:H,slippageBps:0});run(f);const after=executeHistoricalSpread({spread:f.spread,intent:"open",executionMode:"taker",decisionTimestamp:T,orderSubmissionTimestamp:T,fillWindowMs:H,amount:1,maxLegSyncMs:H,slippageBps:0});assert.deepEqual(after,before);assert.equal(after.completionTimestamp,T+.5*H)});
