import test from "node:test";import assert from "node:assert/strict";
import {DEFAULT_ANALYSIS_CONFIGURATION,validateEconomicPolicy} from "../app/lib/analysis-configuration.ts";
import {reconstructPortfolio} from "../app/lib/economics/portfolio.ts";
import type {PositionEconomics} from "../app/lib/economics/position.ts";
const a=(value:number)=>({value,reason:null}),u=()=>({value:null,reason:"canonical margin unavailable"});
function position(id:string,entry:string,exit:string,direction:"long"|"short",loss:number,pnl:number,im:number|null):PositionEconomics{return {sourceRun:"run",eventId:id,candidateId:id,structureExecutionId:`${id}~maker`,executionScenario:"maker",pricingTrack:"raw_vwap",exitPolicy:"thesis",status:"priced",missingReason:null,direction,optionType:direction==="long"?"P":"C",instruments:null,expiryTimestamp:exit,entryTimestamp:entry,exitTimestamp:exit,actualDteDays:2,shortStrike:100,longStrike:90,actualWidth:10,quantity:1,shortPremiumBtc:.02,longPremiumBtc:.01,grossOpeningCreditBtc:.01,openingFeesBtc:.0001,netOpeningCashFlowBtc:.0099,executionAdjustmentBtc:null,entryIndex:50_000,winningTrigger:"settlement",exitIndex:51_000,closingCashFlowBtc:0,closingFeesBtc:.0001,deliveryFeesBtc:.0001,totalRealizedFeesBtc:.0002,pnlBtc:pnl,pnlUsd:pnl*51_000,maximumStructuralLossBtc:a(loss),maximumStructuralLossUsd:a(loss*51_000),incrementalInitialMarginBtc:im===null?u():a(im),incrementalMaintenanceMarginBtc:im===null?u():a(im/2),peakInitialMarginBtc:im===null?u():a(im),peakMaintenanceMarginBtc:im===null?u():a(im/2),peakMarginTimestamp:im===null?null:entry,holdingDays:2,capitalDaysBtc:im===null?u():a(im*2),returnOnStructuralLoss:a(pnl/loss),returnOnOpeningMargin:im===null?u():a(pnl/im),returnOnPeakCapital:im===null?u():a(pnl/im),riskMinimumEquityBtc:a(loss/.01),marginMinimumEquityBtc:im===null?u():a(im/.25),minimumEquityBtc:im===null?u():a(Math.max(loss/.01,im/.25)),bindingConstraint:im===null?null:"risk"};}
const config={...DEFAULT_ANALYSIS_CONFIGURATION,executionAssumption:"maker" as const,pricingTrack:"raw_vwap" as const,exitPolicy:"thesis" as const,maximumRiskFraction:.01,maximumMarginUtilization:.25,accountEquity:1};
test("overlap sums gross loss without directional netting and produces complete account minimum",()=>{const r=reconstructPortfolio([position("bull","2026-01-01T00:00:00Z","2026-01-03T00:00:00Z","long",.1,.01,.05),position("bear","2026-01-02T00:00:00Z","2026-01-04T00:00:00Z","short",.2,-.02,.08)],config);assert.equal(r.maximumConcurrentPositions,2);assert.ok(Math.abs(r.peakAggregateStructuralLossBtc.value!-.3)<1e-12);assert.equal(r.maximumMixedDirectionPositions,2);assert.ok(Math.abs(r.minimumRequiredAccountSizeBtc.value!-30)<1e-12);});
test("exact ties close before open and candidate ordering is deterministic",()=>{const r=reconstructPortfolio([position("a","2026-01-01T00:00:00Z","2026-01-02T00:00:00Z","long",.1,.01,.05),position("b","2026-01-02T00:00:00Z","2026-01-03T00:00:00Z","short",.2,0,.05)],config);const tie=r.timeline[1]!;assert.deepEqual(tie.closed,["a"]);assert.deepEqual(tie.opened,["b"]);assert.equal(tie.concurrentPositions,1);});
test("missing margin stays partial and never becomes zero or opening-margin fallback",()=>{const r=reconstructPortfolio([position("a","2026-01-01T00:00:00Z","2026-01-02T00:00:00Z","long",.1,.01,null)],config);assert.equal(r.peakAggregateInitialMarginBtc.value,null);assert.equal(r.minimumRequiredAccountSizeBtc.value,null);assert.equal(r.timeline[0]!.riskRequiredEquityBtc.value,10);});
test("risk policy fractions reject zero, negative and 100 percent",()=>{assert.equal(validateEconomicPolicy({maximumRiskFraction:0,maximumMarginUtilization:1}).length,2);assert.equal(validateEconomicPolicy({maximumRiskFraction:-.1,maximumMarginUtilization:.25}).length,1);assert.deepEqual(validateEconomicPolicy({maximumRiskFraction:.005,maximumMarginUtilization:.25}),[]);});
