import test from "node:test";import assert from "node:assert/strict";
import {DEFAULT_ANALYSIS_CONFIGURATION,validateEconomicPolicy} from "../app/lib/analysis-configuration.ts";
import {reconstructPortfolio} from "../app/lib/economics/portfolio.ts";
import {validatePortfolioCohort} from "../app/lib/economics/report.ts";
import {buildEconomicReport} from "../app/lib/economics/report.ts";
import {normalizePositionEconomics} from "../app/lib/economics/position.ts";
import {canonicalStructuralLoss} from "../app/lib/maximum-economic-loss.ts";
import type {AnalysisDataset} from "../app/lib/research-analysis.ts";
import {buildConfigurationEconomics,selectedConfigurationPortfolio} from "../app/lib/economics/configuration.ts";
import {structuralConfigurationIdentity} from "../app/lib/economics/strategy-configuration.ts";
import type {PositionEconomics} from "../app/lib/economics/position.ts";
const a=(value:number)=>({value,reason:null}),u=()=>({value:null,reason:"canonical margin unavailable"});
function position(id:string,entry:string,exit:string,direction:"long"|"short",loss:number,pnl:number,im:number|null):PositionEconomics{return {sourceRun:"run",eventId:id,candidateId:id,structureExecutionId:`${id}~maker`,structuralConfigurationId:"cfg",structuralConfiguration:{targetDteFamilyDays:2,strikeMethod:"anchor",requestedWidth:10,structureType:"vertical",quantity:1},executionScenario:"maker",pricingTrack:"raw_vwap",exitPolicy:"thesis",status:"priced",missingReason:null,direction,optionType:direction==="long"?"P":"C",instruments:null,expiryTimestamp:exit,entryTimestamp:entry,exitTimestamp:exit,actualDteDays:2,shortStrike:100,longStrike:90,actualWidth:10,quantity:1,shortPremiumBtc:.02,longPremiumBtc:.01,grossOpeningCreditBtc:.01,openingFeesBtc:.0001,netOpeningCashFlowBtc:.0099,executionAdjustmentBtc:null,entryIndex:50_000,winningTrigger:"settlement",exitIndex:51_000,closingCashFlowBtc:0,closingFeesBtc:.0001,deliveryFeesBtc:.0001,totalRealizedFeesBtc:.0002,pnlBtc:pnl,pnlUsd:pnl*51_000,maximumStructuralLossBtc:a(loss),maximumStructuralLossUsd:a(loss*51_000),trackMaximumNetLossBtc:a(loss),trackMaximumNetLossUsd:a(loss*51_000),incrementalInitialMarginBtc:im===null?u():a(im),incrementalMaintenanceMarginBtc:im===null?u():a(im/2),peakInitialMarginBtc:im===null?u():a(im),peakMaintenanceMarginBtc:im===null?u():a(im/2),peakMarginTimestamp:im===null?null:entry,peakInitialMarginTimestamp:im===null?null:entry,peakMaintenanceMarginTimestamp:im===null?null:entry,holdingDays:2,capitalDaysBtc:im===null?u():a(im*2),returnOnStructuralLoss:a(pnl/loss),returnOnTrackMaximumNetLoss:a(pnl/loss),returnOnOpeningMargin:im===null?u():a(pnl/im),returnOnPeakCapital:im===null?u():a(pnl/im),riskMinimumEquityBtc:a(loss/.01),marginMinimumEquityBtc:im===null?u():a(im/.25),minimumEquityBtc:im===null?u():a(Math.max(loss/.01,im/.25)),bindingConstraint:im===null?null:"risk"};}
const config={...DEFAULT_ANALYSIS_CONFIGURATION,executionAssumption:"maker" as const,pricingTrack:"raw_vwap" as const,exitPolicy:"thesis" as const,maximumRiskFraction:.01,maximumMarginUtilization:.25,accountEquity:1};
test("overlap sums gross loss without directional netting and produces complete account minimum",()=>{const r=reconstructPortfolio([position("bull","2026-01-01T00:00:00Z","2026-01-03T00:00:00Z","long",.1,.01,.05),position("bear","2026-01-02T00:00:00Z","2026-01-04T00:00:00Z","short",.2,-.02,.08)],config);assert.equal(r.maximumConcurrentPositions,2);assert.ok(Math.abs(r.peakAggregateStructuralLossBtc.value!-.3)<1e-12);assert.equal(r.maximumMixedDirectionPositions,2);assert.ok(Math.abs(r.minimumRequiredAccountSizeBtc.value!-30)<1e-12);});
test("exact ties close before open and candidate ordering is deterministic",()=>{const r=reconstructPortfolio([position("a","2026-01-01T00:00:00Z","2026-01-02T00:00:00Z","long",.1,.01,.05),position("b","2026-01-02T00:00:00Z","2026-01-03T00:00:00Z","short",.2,0,.05)],config);const tie=r.timeline[1]!;assert.deepEqual(tie.closed,["a"]);assert.deepEqual(tie.opened,["b"]);assert.equal(tie.concurrentPositions,1);});
test("missing margin stays partial and never becomes zero or opening-margin fallback",()=>{const r=reconstructPortfolio([position("a","2026-01-01T00:00:00Z","2026-01-02T00:00:00Z","long",.1,.01,null)],config);assert.equal(r.peakAggregateInitialMarginBtc.value,null);assert.equal(r.minimumRequiredAccountSizeBtc.value,null);assert.equal(r.timeline[0]!.riskRequiredEquityBtc.value,10);});
test("risk policy fractions reject zero, negative and 100 percent",()=>{assert.equal(validateEconomicPolicy({maximumRiskFraction:0,maximumMarginUtilization:1}).length,2);assert.equal(validateEconomicPolicy({maximumRiskFraction:-.1,maximumMarginUtilization:.25}).length,1);assert.deepEqual(validateEconomicPolicy({maximumRiskFraction:.005,maximumMarginUtilization:.25}),[]);});
test("research width alternatives for one event capability-gate the portfolio",()=>{const x=position("event","2026-01-01T00:00:00Z","2026-01-02T00:00:00Z","long",.1,.01,.05),y={...position("other-id","2026-01-01T00:00:00Z","2026-01-02T00:00:00Z","long",.2,.01,.06),eventId:"event",actualWidth:20};const cohort=validatePortfolioCohort([x,y]);assert.equal(cohort.status,"not_estimable");assert.deepEqual(cohort.ambiguousEventIds,["event"]);assert.equal(cohort.positions.length,0);});
test("portfolio drawdown uses exact open-position marks and overlap is time weighted",()=>{const x={...position("a","2026-01-01T00:00:00Z","2026-01-03T00:00:00Z","long",.1,-.01,.05),path:[{timestamp:"2026-01-01T00:00:00Z",pnlBtc:a(0),index:50_000,initialMarginBtc:a(.05),maintenanceMarginBtc:a(.02)},{timestamp:"2026-01-02T00:00:00Z",pnlBtc:a(-.2),index:40_000,initialMarginBtc:a(.06),maintenanceMarginBtc:a(.03)}]},r=reconstructPortfolio([x],config);assert.ok(Math.abs(r.maximumTradingDrawdownBtc.value!-.2)<1e-12);assert.ok(Math.abs(r.totalPortfolioCapitalDaysBtc.value!-.11)<1e-12);});
test("missing one constituent mark invalidates complete MTM rather than carrying it",()=>{const x={...position("a","2026-01-01T00:00:00Z","2026-01-03T00:00:00Z","long",.1,-.01,.05),path:[]},r=reconstructPortfolio([x],config);assert.equal(r.timeline[0]!.unrealizedPnlBtc.value,null);assert.equal(r.maximumTradingDrawdownBtc.value,null);});

const day=(d:number)=>new Date(Date.UTC(2026,0,d)).toISOString(),ms=(d:number)=>Date.parse(day(d));
function phaseOneDataset():AnalysisDataset{const reference=canonicalStructuralLoss({optionType:"P",shortStrike:40000,longStrike:38000,shortEntryPremiumBtc:.01,longEntryPremiumBtc:.002,entryIndex:42000,amount:1,openingFeesBtc:.0004,expiryTimestamp:ms(15)}),candidate={event_id:"event",candidate_id:"candidate",strategy_variant_id:"selected",structural_configuration_id:"cfg-phase",structural_configuration:{targetDteFamilyDays:14,strikeMethod:"anchor",requestedWidth:2000,structureType:"bull_put_credit",quantity:1},structure_execution_id:"candidate~modeled_expected",is_selected:true,research_role:null,analytics_track:"modeled_expected",execution_scenario:null,execution_scenario_status:"evaluated",direction:"long",option_type:"P",structure_type:"bull_put_credit",strike_method:"anchor",actual_strikes:{short:40000,long:38000,width:2000},requested_width:2000,expiry_timestamp_utc:day(15),actual_dte_days:14,structure_entry_timestamp_utc:day(1),entry_index_price:42000,quantity:1,entry_legs:{short:{price_native:.008,unslipped_price_native:.01},long:{price_native:.002,unslipped_price_native:.002}},gross_credit_debit_native:.006,opening_fees_native:.0004,net_opening_cash_flow_native:.0056},outcome={candidate_id:"candidate",event_id:"event",analytics_track:"modeled_expected",execution_scenario:null,outcome_type:"settlement",status:"priced",trigger_status:"reached",decision_available_timestamp_utc:day(4),valuation_timestamp_utc:day(4),holding_hours:72,closing_fees_native:.0002,net_pnl_native:.003,net_pnl_usd:126},economics={candidate_id:"candidate",event_id:"event",maximum_structural_loss_status:"available",maximum_structural_loss_native:reference.btcAtReferenceIndex,maximum_structural_loss_usd:reference.usd,maximum_structural_loss_reference_index:reference.referenceIndex,maximum_structural_loss_method_version:reference.methodVersion},margin={candidate_id:"candidate",event_id:"event",margin_status:"available",margin_model:"segregated_sm",margin_inputs:{path:[{timestamp:ms(1),initialMarginBtc:.1,maintenanceMarginBtc:.05,indexPrice:42000},{timestamp:ms(2),initialMarginBtc:.2,maintenanceMarginBtc:.1,indexPrice:41000},{timestamp:ms(8),initialMarginBtc:.9,maintenanceMarginBtc:.45,indexPrice:39000}]}};return{filename:"phase-one",schemaVersion:"4.1.0",migratedFrom:null,run:{},tables:{candidates:[candidate],outcomes:[outcome],valuations:[],structure_economics:[economics],margin_scenarios:[margin],availability:[{event_id:"event",candidate_id:"candidate",strategy_variant_id:"selected"}]},counts:{},venues:[],sourceRuns:[],eventUniverseComplete:true,capabilities:[]}}
const phaseConfig={...DEFAULT_ANALYSIS_CONFIGURATION,exitPolicy:"settlement_benchmark" as const,maximumRiskFraction:.01,maximumMarginUtilization:.25};
test("null complete exit policy blocks all Economics rows and portfolio evaluation",()=>{const r=buildEconomicReport(phaseOneDataset(),DEFAULT_ANALYSIS_CONFIGURATION);assert.equal(r.status,"not_configured");assert.equal(r.positions.length,0);assert.equal(r.portfolio,null);assert.match(r.statusReason!,/select one Complete Exit Policy/);});
test("selected Economics denominator excludes controlled Short-Strike research",()=>{const d=phaseOneDataset(),controlled={...(d.tables.candidates[0] as Record<string,unknown>),candidate_id:"controlled",strategy_variant_id:"controlled",structure_execution_id:"controlled~modeled_expected",is_selected:false,research_role:"short_strike_buffered"};(d.tables as Record<string,unknown>).candidates=[...d.tables.candidates,controlled];(d.tables as Record<string,unknown>).availability=[...d.tables.availability,{event_id:"event",candidate_id:"controlled",strategy_variant_id:"controlled"}];const r=buildEconomicReport(d,phaseConfig);assert.equal(r.modeledMethodology.centralCoverage.total,1);assert.equal(r.modeledMethodology.centralCoverage.available,1);});
test("track loss uses worse Q50 credit while canonical Reference loss remains unchanged",()=>{const p=normalizePositionEconomics(phaseOneDataset(),phaseConfig)[0]!,reference=p.maximumStructuralLossBtc.value!,track=p.trackMaximumNetLossBtc.value!;assert.ok(track>reference);assert.notEqual(p.returnOnTrackMaximumNetLoss.value,p.returnOnStructuralLoss.value);assert.ok(Math.abs(p.riskMinimumEquityBtc.value!-track/.01)<1e-12);assert.ok(Math.abs(p.trackMaximumNetLossUsd.value!-track*42000)<1e-9);assert.ok(Math.abs(p.totalRealizedFeesBtc!-.0006)<1e-12);assert.equal(p.pnlUsd,126);});
test("policy-window margin excludes a later expiry-window peak and integrates only to exit",()=>{const p=normalizePositionEconomics(phaseOneDataset(),phaseConfig)[0]!;assert.equal(p.incrementalInitialMarginBtc.value,.1);assert.equal(p.peakInitialMarginBtc.value,.2);assert.equal(p.peakInitialMarginTimestamp,day(2));assert.ok(Math.abs(p.capitalDaysBtc.value!-(.1+.2*2))<1e-12);});
test("missing margin path, Cross SM, and PM never expose segregated margin values or zero",()=>{const d=phaseOneDataset(),missing={...d,tables:{...d.tables,margin_scenarios:[{...d.tables.margin_scenarios[0],margin_inputs:{path:null}}]}} as AnalysisDataset;for(const [data,cfg,why] of [[missing,phaseConfig,/path/],[d,{...phaseConfig,collateralMode:"cross" as const},/cross-account/],[d,{...phaseConfig,marginModel:"portfolio" as const},/Portfolio Margin/]] as const){const p=normalizePositionEconomics(data,cfg)[0]!;assert.equal(p.peakInitialMarginBtc.value,null);assert.equal(p.capitalDaysBtc.value,null);assert.match(p.peakInitialMarginBtc.reason!,why);assert.equal(p.returnOnOpeningMargin.value,null);assert.equal(p.marginMinimumEquityBtc.value,null);assert.notEqual(p.maximumStructuralLossBtc.value,null)}});
test("structural configuration identity uses ex-ante rules, not realized geometry",()=>{const a=structuralConfigurationIdentity({target_horizon_days:14,strike_method:"buffered",requested_width:2000,structure_type:"vertical",quantity:1,actual_dte:12,actual_strikes:{width:1900}}),b=structuralConfigurationIdentity({target_horizon_days:14,strike_method:"buffered",requested_width:2000,structure_type:"vertical",quantity:1,actual_dte:13,actual_strikes:{width:1800}});assert.equal(a.id,b.id);assert.notEqual(a.id,structuralConfigurationIdentity({target_horizon_days:14,strike_method:"buffered",requested_width:3000,structure_type:"vertical",quantity:1}).id)});
test("three widths are separate configurations and never three positions in one event portfolio",()=>{const rows=[1000,2000,3000].map((width,i)=>({...position(`c${i}`,day(1),day(4),"long",.1,.01,.05),eventId:"event",structuralConfigurationId:`width-${width}`,structuralConfiguration:{requestedWidth:width}})),summaries=buildConfigurationEconomics(rows,config);assert.equal(summaries.length,3);assert.ok(summaries.every(x=>x.positions.length===1));assert.ok(summaries.every(x=>reconstructPortfolio(x.positions,config).maximumConcurrentPositions===1))});
test("duplicate configuration/event is an integrity error with candidate identities",()=>{const rows=[position("a",day(1),day(4),"long",.1,.01,.05),{...position("b",day(1),day(4),"long",.1,.01,.05),eventId:"a"}],summary=buildConfigurationEconomics(rows,config)[0]!;assert.equal(summary.status,"integrity_error");assert.deepEqual(summary.conflictingCandidates[0]!.candidateIds,["a","b"]);assert.equal(summary.positions.length,0)});
test("different configurations reconstruct only after explicit selection",()=>{const rows=[position("a",day(1),day(4),"long",.1,.01,.05),{...position("b",day(2),day(5),"short",.2,.02,.08),structuralConfigurationId:"cfg-2"}],summaries=buildConfigurationEconomics(rows,config);assert.equal(selectedConfigurationPortfolio(summaries,{...config,selectedStructuralConfigurationId:null}).status,"not_selected");const chosen=selectedConfigurationPortfolio(summaries,{...config,selectedStructuralConfigurationId:"cfg-2"});assert.equal(chosen.portfolio!.maximumConcurrentPositions,1);assert.equal(chosen.portfolio!.timeline.some(x=>x.openCandidateIds.includes("a")),false)});
test("time-indexed aggregate margin captures intrahold peak rather than summing openings",()=>{const path=(entry:string,peak:string,opening:number,later:number)=>[{timestamp:entry,pnlBtc:a(0),index:50000,initialMarginBtc:a(opening),maintenanceMarginBtc:a(opening/2)},{timestamp:peak,pnlBtc:a(-.01),index:49000,initialMarginBtc:a(later),maintenanceMarginBtc:a(later/2)}],x={...position("a",day(1),day(5),"long",.1,.01,.1),path:path(day(1),day(3),.1,.4)},y={...position("b",day(1),day(5),"short",.1,.01,.05),path:path(day(1),day(3),.05,.2)},r=reconstructPortfolio([x,y],config);assert.ok(Math.abs(r.peakAggregateInitialMarginBtc.value!-.6)<1e-12);assert.notEqual(r.peakAggregateInitialMarginBtc.value,.15)});
test("MTM loss precedes recovery, realized drawdown stays distinct, and closing PnL is counted once",()=>{const x={...position("a",day(1),day(4),"long",.1,.05,.05),path:[{timestamp:day(1),pnlBtc:a(0),index:50000,initialMarginBtc:a(.05),maintenanceMarginBtc:a(.02)},{timestamp:day(2),pnlBtc:a(-.2),index:45000,initialMarginBtc:a(.05),maintenanceMarginBtc:a(.02)},{timestamp:day(3),pnlBtc:a(.04),index:51000,initialMarginBtc:a(.05),maintenanceMarginBtc:a(.02)}]},r=reconstructPortfolio([x],config),last=r.timeline.at(-1)!;assert.ok(Math.abs(r.maximumModeledEquityDrawdownBtc.value!-.2)<1e-12);assert.equal(r.realizedEquityDrawdownBtc.value,0);assert.ok(Math.abs(last.modeledEquityBtc.value!-1.05)<1e-12)});
test("missing synchronized mark is incomplete and is never forward-filled",()=>{const x={...position("a",day(1),day(4),"long",.1,.01,.05),path:[{timestamp:day(1),pnlBtc:a(0),index:50000,initialMarginBtc:a(.05),maintenanceMarginBtc:a(.02)}]},y={...position("b",day(2),day(4),"short",.1,.01,.05),path:[{timestamp:day(2),pnlBtc:a(0),index:50000,initialMarginBtc:a(.05),maintenanceMarginBtc:a(.02)}]},r=reconstructPortfolio([x,y],config),state=r.timeline.find(p=>p.timestamp===day(2))!;assert.equal(state.unrealizedPnlBtc.value,null);assert.match(state.unrealizedPnlBtc.reason!,/mark is unavailable/)});
test("risk and margin requirements remain separate and binding switches by state",()=>{const x={...position("a",day(1),day(3),"long",.01,.01,.01),path:[{timestamp:day(1),pnlBtc:a(0),index:50000,initialMarginBtc:a(.01),maintenanceMarginBtc:a(.005)},{timestamp:day(2),pnlBtc:a(0),index:50000,initialMarginBtc:a(1),maintenanceMarginBtc:a(.5)}]},r=reconstructPortfolio([x],config);assert.equal(r.timeline[0]!.bindingConstraint,"risk");assert.equal(r.timeline[1]!.bindingConstraint,"margin");assert.notEqual(r.timeline[1]!.riskRequiredEquityBtc.value,r.timeline[1]!.marginRequiredEquityBtc.value)});
test("opportunity expectancy counts explicit no-trade as zero but refuses unavailable",()=>{const priced=position("p",day(1),day(3),"long",.1,.1,.05),noTrade={...position("n",day(1),day(3),"long",.1,0,.05),status:"not_evaluated" as const,pnlBtc:null,pnlUsd:null},summary=buildConfigurationEconomics([priced,noTrade],config)[0]!;assert.equal(summary.opportunityExpectancyBtc.value,.05);assert.equal(summary.priced,1);assert.equal(summary.explicitNoTrade,1);const unavailable={...noTrade,candidateId:"u",eventId:"u",status:"unavailable" as const};const incomplete=buildConfigurationEconomics([priced,noTrade,unavailable],config)[0]!;assert.equal(incomplete.opportunityExpectancyBtc.value,null);assert.equal(incomplete.unavailable,1)});
