import test from "node:test";
import assert from "node:assert/strict";
import {priceInverseOption,impliedVolatilityFromInversePrice} from "../app/lib/inverse-option-pricing.ts";
import {performance} from "node:perf_hooks";
import {amountBand,compileCalibrationRows,dteBand,ExecutionCalibrationIndex,quantileR7,type EmpiricalCalibrationRow,type ExecutionEstimatorArtifact} from "../app/lib/empirical-taker-execution.ts";
import type {ExecutionCalibrationObservation} from "../app/lib/execution-calibration.ts";
const DAY=864e5,ts=1_700_000_000_000,expiry=ts+10*DAY,index=40000,forward=40200,strike=40000;
const mark=priceInverseOption({optionType:"call",indexPrice:index,strike,valuationTimestamp:ts,expiryTimestamp:expiry,forwardPrice:forward,ivDecimal:.6});if(mark.status!=="priced")throw Error("fixture");
const row=(id:string,direction="buy",tradeIv=.61,time=ts)=>({method_version:"execution-calibration-observations-v4",taker_concession_eligible:true,trade_id:id,trade_timestamp_ms:time,direction,trade_iv_decimal:tradeIv,primary_fair_iv_decimal:.58,mark_price_btc:mark.priceBtc,index_price:index,forward_price:forward,strike,option_type:"C",expiry_timestamp_ms:expiry,actual_dte_days:10,amount:1,forward_moneyness:Math.log(strike/forward),features:{calendar_date:new Date(time).toISOString().slice(0,10),expiry_date_group_id:`g-${id}`}}) as unknown as ExecutionCalibrationObservation;
test("authoritative inverse IV inversion and mark decomposition retain signed concessions",()=>{const iv=impliedVolatilityFromInversePrice({optionType:"call",indexPrice:index,strike,valuationTimestamp:ts,expiryTimestamp:expiry,forwardPrice:forward,priceBtc:mark.priceBtc});assert.ok(Math.abs(iv!-.6)<1e-9);const values=compileCalibrationRows([row("b"),row("s","sell",.59),row("f","buy",.59)]),buy=values.find(r=>r.tradeId==="b")!,sell=values.find(r=>r.tradeId==="s")!,favorable=values.find(r=>r.tradeId==="f")!;assert.ok(Math.abs(buy!.concessionVolPoints-1)<1e-8);assert.ok(Math.abs(sell!.concessionVolPoints-1)<1e-8);assert.ok(favorable!.concessionVolPoints<0);assert.ok(Math.abs(buy!.referenceErrorVolPoints-2)<1e-8)});
test("trade_id dedupe is authoritative while observation ids are irrelevant",()=>{const a=row("a"),b={...row("b"),observation_id:"same"},c={...a,observation_id:"same"};assert.equal(compileCalibrationRows([a,b,c]).length,2);assert.throws(()=>compileCalibrationRows([a,{...a,trade_iv_decimal:.9}]),/Conflicting economic fields/)});
test("bucket boundaries, amount policy, exact causal cutoff and fallback support",()=>{assert.deepEqual([1,2.999,3,7,14,30,46,46.1].map(dteBand),["1-3","1-3","3-7","7-14","14-30","30-46","30-46",null]);assert.equal(amountBand(1),"small");assert.equal(amountBand(1.01),"larger");const rows=Array.from({length:5000},(_,i)=>row(`t${i}`,i%2?"buy":"sell",.61,ts-(i%30+1)*DAY));const indexer=new ExecutionCalibrationIndex(rows);assert.equal(indexer.execution({action:"buy",dteDays:10,amount:1,forwardMoneyness:0,cutoffMs:ts})?.fallbackLevel,"action_dte_amount");assert.equal(indexer.execution({action:"buy",dteDays:10,amount:1,forwardMoneyness:0,cutoffMs:ts-31*DAY}),null);assert.equal(indexer.execution({action:"buy",dteDays:10,amount:1,forwardMoneyness:.36,cutoffMs:ts}),null);assert.equal(quantileR7([-1,0,1],.5),0)});

const syntheticArtifact=()=>{const rows:EmpiricalCalibrationRow[]=[];const add=(count:number,action:"buy"|"sell",dteDays:number,amount:number)=>{for(let i=0;i<count;i++){const n=rows.length;rows.push({tradeId:`synthetic-${n}`,timestampMs:ts-(40-n%40)*DAY+n,action,dteDays,dteBand:dteBand(dteDays)!,amount,amountBand:amountBand(amount),expiryDayGroup:`expiry-${n%25}`,calendarDate:new Date(ts-(n%40+1)*DAY).toISOString().slice(0,10),concessionVolPoints:(n%29-14)/7,referenceErrorVolPoints:(n%23)/11})}};add(250,"buy",10,1);add(250,"buy",10,2);add(100,"buy",20,1);add(4_600,"buy",35,1);add(100,"sell",20,1);rows.sort((a,b)=>a.timestampMs-b.timestampMs||a.tradeId.localeCompare(b.tradeId));return{datasetId:"execution-calibration-observations-v4",methodVersion:"execution-calibration-observations-v4",sourceDatasetFingerprint:"synthetic",coverageStartMs:rows[0]!.timestampMs,coverageEndMs:rows.at(-1)!.timestampMs,estimatorVersion:"empirical-taker-execution-v1",bucketPolicyVersion:"taker-action-dte-amount-v1",tradeCount:rows.length,uniqueDays:40,uniqueExpiryDayGroups:25,quantileMethod:"linear-interpolation-r7",rows,artifactHash:"synthetic"} satisfies ExecutionEstimatorArtifact};
const counts=(rows:readonly EmpiricalCalibrationRow[])=>({tradeCount:rows.length,calendarDayCount:new Set(rows.map(r=>r.calendarDate)).size,expiryDayGroupCount:new Set(rows.map(r=>r.expiryDayGroup)).size});
const sufficient=(value:ReturnType<typeof counts>,global=false)=>value.tradeCount>=(global?5000:500)&&value.calendarDayCount>=10&&value.expiryDayGroupCount>=20;
function simpleExecution(rows:readonly EmpiricalCalibrationRow[],target:{action:"buy"|"sell";dteDays:number;amount:number;forwardMoneyness:number;cutoffMs:number}){const band=dteBand(target.dteDays);if(!band||Math.abs(target.forwardMoneyness)>.35)return null;const causal=rows.filter(r=>r.timestampMs<target.cutoffMs),ab=amountBand(target.amount),levels=[{name:"action_dte_amount" as const,rows:causal.filter(r=>r.action===target.action&&r.dteBand===band&&r.amountBand===ab)},{name:"action_dte" as const,rows:causal.filter(r=>r.action===target.action&&r.dteBand===band)},{name:"action" as const,rows:causal.filter(r=>r.action===target.action)},{name:"global" as const,rows:causal}];for(const level of levels){const support=counts(level.rows);if(sufficient(support,level.name==="global"))return{fallbackLevel:level.name,...support,q50VolPoints:quantileR7(level.rows.map(r=>r.concessionVolPoints),.5)!,q90VolPoints:quantileR7(level.rows.map(r=>r.concessionVolPoints),.9)!,dteBand:band,amountBand:ab}}return null}
function simpleReference(rows:readonly EmpiricalCalibrationRow[],target:{dteDays:number;cutoffMs:number}){const band=dteBand(target.dteDays);if(!band)return null;const causal=rows.filter(r=>r.timestampMs<target.cutoffMs),levels=[{name:"dte" as const,rows:causal.filter(r=>r.dteBand===band)},{name:"global" as const,rows:causal}];for(const level of levels){const support=counts(level.rows);if(sufficient(support,level.name==="global"))return{fallbackLevel:level.name,...support,q90VolPoints:quantileR7(level.rows.map(r=>r.referenceErrorVolPoints),.9)!,dteBand:band}}return null}
test("pre-indexed causal queries exactly match the simple full-scan implementation",()=>{const artifact=syntheticArtifact(),index=new ExecutionCalibrationIndex(artifact),cutoffs=[ts-41*DAY,ts-20*DAY,ts,ts+1],queries=[{action:"buy" as const,dteDays:10,amount:1,forwardMoneyness:0},{action:"buy" as const,dteDays:20,amount:1,forwardMoneyness:0},{action:"sell" as const,dteDays:20,amount:1,forwardMoneyness:0},{action:"buy" as const,dteDays:35,amount:1,forwardMoneyness:0},{action:"buy" as const,dteDays:35,amount:2,forwardMoneyness:0}];for(const cutoffMs of cutoffs){for(const query of queries)assert.deepEqual(index.execution({...query,cutoffMs}),simpleExecution(artifact.rows,{...query,cutoffMs}));for(const dteDays of [2,10,20,35])assert.deepEqual(index.reference({dteDays,cutoffMs}),simpleReference(artifact.rows,{dteDays,cutoffMs}))}});
test("synthetic repeated-query benchmark avoids inspecting unrelated calibration rows",()=>{const artifact=syntheticArtifact(),index=new ExecutionCalibrationIndex(artifact),query={action:"buy" as const,dteDays:10,amount:1,forwardMoneyness:0,cutoffMs:ts+1},repetitions=50;let started=performance.now();for(let i=0;i<repetitions;i++)simpleExecution(artifact.rows,query);const simpleMs=performance.now()-started;started=performance.now();for(let i=0;i<repetitions;i++)index.execution(query);const indexedMs=performance.now()-started;const fullScanRows=artifact.rows.length*repetitions,indexedCandidateRows=(250+500)*repetitions;assert.ok(indexedCandidateRows<fullScanRows/5);assert.deepEqual(index.execution(query),simpleExecution(artifact.rows,query));assert.ok(Number.isFinite(indexedMs));console.log(`execution-index benchmark: full-scan candidates=${fullScanRows}, indexed candidates=${indexedCandidateRows}, simple=${simpleMs.toFixed(1)}ms, indexed=${indexedMs.toFixed(1)}ms`) });
