import test from "node:test";import assert from "node:assert/strict";import {readFileSync} from "node:fs";
import {buildCalibrationObservation,calibrationContentHash,calibrationRawShardId,calibrationTargets,causalFeatures,adverseConcession,relativeConcessionBps,DIRECTION_SEMANTICS_VERSION} from "../app/lib/execution-calibration.ts";
import type {RawOptionPrint} from "../app/lib/volatility/cross-section.ts";
import {REFERENCE_GEOMETRY_RULE,REFERENCE_VALUATION_METHOD_VERSION} from "../app/lib/volatility/reference-hybrid.ts";
import {RESEARCH_BUNDLE_SCHEMA_VERSION} from "../app/lib/research-bundle.ts";import {RESEARCH_SELECTION_SCHEMA_VERSION} from "../app/lib/research-selections.ts";import {MODELED_EXECUTION_VERSION} from "../app/lib/modeled-execution.ts";
const T=Date.UTC(2024,0,2,12),E=T+7*864e5,S=40000;
const p=(strike:number,ts=T-60000,over:Partial<RawOptionPrint>={}):RawOptionPrint=>({instrumentName:`BTC-X-${strike}-C`,tradeId:`${strike}-${ts}`,tradeSeq:ts,strike,optionType:"C",expiryTimestampMs:E,contractCreatedAtMs:T-10*864e5,settlementPeriod:"week",timestampMs:ts,ivApiPercent:50+Math.abs(strike-S)/10000,indexPrice:S,price:.02,markPrice:.021,amount:1,direction:"buy",...over});
const target=p(S,T,{tradeId:"target",price:.025,ivApiPercent:55});const evidence=[p(36000),p(38000),p(39000),p(41000),p(42000),p(44000)];
const build=(over:Partial<Parameters<typeof buildCalibrationObservation>[0]>={})=>buildCalibrationObservation({target,tape:[...evidence,target],sourceHost:"history.deribit.com",retrievalShardId:"2024-01",retrievalContentHash:"abc",sourceWindowComplete:true,...over});
test("script typecheck explicitly includes the calibration builder",()=>{const config=JSON.parse(readFileSync(new URL("../tsconfig.scripts.json",import.meta.url),"utf8")) as {include:string[]};assert.ok(config.include.includes("scripts/build-execution-calibration.ts"));assert.ok(config.include.includes("app/lib/execution-calibration.ts"));});
test("independent primary excludes the target instrument and requires strictly prior evidence",()=>{const row=build();assert.equal(row.status,"eligible_primary_calibration");assert.equal(row.fair_reference_observation_count,6);assert.equal(row.geometry_rule,REFERENCE_GEOMETRY_RULE);assert.equal(row.primary_fair_source,"independent_same_expiry_rule_c_interpolation");assert.notEqual(row.primary_fair_method_version,row.production_hybrid_method_version);assert.ok(row.primary_fair_iv_decimal);const contaminated=build({tape:[...evidence,p(40000,T-1,{instrumentName:target.instrumentName,ivApiPercent:500}),target]});assert.equal(contaminated.primary_fair_iv_decimal,row.primary_fair_iv_decimal);});
test("future and same-millisecond evidence cannot leak; primary never extrapolates",()=>{const future=evidence.map(x=>({...x,timestampMs:T+1,tradeId:`f${x.tradeId}`}));assert.equal(build({tape:[...future,target]}).status,"fair_reference_unavailable");const same=evidence.map(x=>({...x,timestampMs:T,tradeId:`s${x.tradeId}`}));assert.equal(build({tape:[...same,target]}).status,"fair_reference_unavailable");assert.equal(build({target:p(50000,T,{tradeId:"wing"})}).status,"independent_reference_not_bracketed");});

test("authoritative Rule C covers exact strike, sparse, outside, and unavailable evidence",()=>{const exact=p(S,T-30000,{instrumentName:"BTC-X-40000-P",optionType:"P",tradeId:"other-exact",ivApiPercent:47});const exactRow=build({tape:[...evidence,exact,target]});assert.equal(exactRow.primary_fair_eligible,true);assert.equal(exactRow.primary_fair_source,"independent_same_expiry_rule_c_interpolation");assert.ok(Math.abs(exactRow.primary_fair_iv_decimal!-.47)<1e-12);assert.equal(build({tape:[...evidence.slice(0,4),target]}).status,"independent_reference_too_sparse");assert.equal(build({target:p(50000,T,{tradeId:"outside"})}).status,"independent_reference_not_bracketed");assert.equal(build({tape:[target]}).status,"fair_reference_unavailable");});

test("monthly boundaries use prior context without duplicating targets",()=>{const boundary=Date.UTC(2024,1,1),expiry=boundary+7*864e5,early={...target,timestampMs:boundary+30000,expiryTimestampMs:expiry,tradeId:"feb-target"},prior=evidence.map((x,i)=>({...x,expiryTimestampMs:expiry,timestampMs:boundary-30000-i,tradeId:`jan-${i}`}));const feb=calibrationTargets([...prior,early],boundary,Date.UTC(2024,2,1));const jan=calibrationTargets([...prior,early],Date.UTC(2024,0,1),boundary);assert.deepEqual(feb.map(x=>x.tradeId),["feb-target"]);assert.ok(!jan.some(x=>x.tradeId==="feb-target"));const separate=buildCalibrationObservation({target:early,tape:[...prior,early],sourceHost:"history.deribit.com",retrievalShardId:"feb",retrievalContentHash:"x",sourceWindowComplete:true});assert.equal(separate.primary_fair_eligible,true);assert.equal(separate.primary_fair_iv_decimal,buildCalibrationObservation({target:early,tape:[...prior,early,{...prior[0]!,timestampMs:boundary+60000,tradeId:"future"}],sourceHost:"history.deribit.com",retrievalShardId:"feb",retrievalContentHash:"x",sourceWindowComplete:true}).primary_fair_iv_decimal);});

test("raw cache identity covers exact target and evidence intervals",()=>{const a=calibrationRawShardId(T,T+864e5,T-720*60000),b=calibrationRawShardId(T,T+2*864e5,T-720*60000),c=calibrationRawShardId(T,T+864e5,T-60*60000);assert.equal(a,calibrationRawShardId(T,T+864e5,T-720*60000));assert.notEqual(a,b);assert.notEqual(a,c);});

test("instrument size metadata and minimum-amount ratio propagate without fabrication",()=>{const row=build({contractSize:10,minimumTradeAmount:.1,target:{...target,amount:.35}});assert.equal(row.contract_size,10);assert.equal(row.minimum_trade_amount,.1);assert.ok(Math.abs(row.amount_to_minimum_trade_amount!-3.5)<1e-12);const absent=build();assert.equal(absent.contract_size,null);assert.equal(absent.minimum_trade_amount,null);assert.equal(absent.amount_to_minimum_trade_amount,null);});

test("unknown direction keeps signed fair diagnostics but is not taker calibration",()=>{const row=build({target:{...target,direction:"unknown"}});assert.equal(row.status,"eligible_primary_calibration");assert.equal(row.primary_fair_eligible,true);assert.equal(row.taker_concession_eligible,false);assert.equal(row.taker_concession_unavailable_reason,"direction_semantics_unavailable");assert.ok(row.signed_iv_residual_decimal!==null);assert.equal(row.adverse_iv_concession_decimal,null);assert.equal(row.adverse_price_concession_btc,null);});
test("listing and incomplete source gates are hard eligibility failures",()=>{assert.equal(build({target:{...target,contractCreatedAtMs:T+1}}).status,"contract_not_listed");assert.equal(build({sourceWindowComplete:false}).status,"source_window_incomplete");});
test("Deribit aggressor direction signs concessions and retains favorable negatives",()=>{assert.match(DIRECTION_SEMANTICS_VERSION,/aggressor/);assert.ok(Math.abs(adverseConcession("buy",.6,.5)!-.1)<1e-12);assert.ok(Math.abs(adverseConcession("sell",.4,.5)!-.1)<1e-12);assert.ok(Math.abs(adverseConcession("buy",.4,.5)!+.1)<1e-12);assert.ok(Math.abs(adverseConcession("sell",.6,.5)!+.1)<1e-12);const favorable=build({target:{...target,ivApiPercent:40,price:.001}});assert.ok(favorable.adverse_iv_concession_vol_points!<0);assert.ok(favorable.adverse_price_concession_btc!<0);});
test("relative premium denominator refuses near zero and never truncates negative bps",()=>{assert.ok(Math.abs(relativeConcessionBps(-.01,.1)!+1000)<1e-9);assert.equal(relativeConcessionBps(.01,1e-9),null);});
test("identity, hashes, groups, and activity features are deterministic and causal",()=>{const a=build(),b=build();assert.equal(a.observation_id,b.observation_id);assert.equal(calibrationContentHash([a]),calibrationContentHash([b]));assert.deepEqual(a.features,b.features);const withFuture=causalFeatures(target,[...evidence,p(S,T+1,{tradeId:"future"})]);assert.equal(withFuture.same_instrument_count_5m,0);assert.match(a.features.expiry_date_group_id,/~/);});
test("frozen runtime and persistence identities remain unchanged",()=>{assert.equal(MODELED_EXECUTION_VERSION,"modeled-execution-v2");assert.equal(REFERENCE_VALUATION_METHOD_VERSION,"causal-reference-v2-hybrid-interpolation");assert.equal(RESEARCH_BUNDLE_SCHEMA_VERSION,"3.7.0");assert.equal(RESEARCH_SELECTION_SCHEMA_VERSION,"1.8.0");});

// v3 engineering regressions
import {mkdtemp,readFile,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {CausalFeatureIndex,EXECUTION_CALIBRATION_METHOD_VERSION} from "../app/lib/execution-calibration.ts";
import {IncompleteCalibrationSourceError,loadOrRetrieveRawCalibrationShard,rawCalibrationContentIdentity} from "../scripts/execution-calibration-cache.ts";
import {calibrationDayRanges} from "../scripts/build-execution-calibration-range.ts";
import {aggregateExecutionCalibration} from "../scripts/aggregate-execution-calibration.ts";
import type {InstrumentMeta} from "../scripts/cross-section-cache.ts";
const meta=(name:string,strike=40000):InstrumentMeta=>({instrumentName:name,strike,optionType:"C",expiryTimestampMs:E,createdAtMs:T-864e5,settlementPeriod:"week",contractSize:1,minimumTradeAmount:.1});

test("v3 identity is stable across irrelevant manifest and input ordering",()=>{assert.equal(EXECUTION_CALIBRATION_METHOD_VERSION,"execution-calibration-observations-v3");const prints=[p(39000),p(41000)],manifest=[meta(prints[0]!.instrumentName,39000),meta(prints[1]!.instrumentName,41000)],a=rawCalibrationContentIdentity(prints,manifest);assert.equal(a.contentHash,rawCalibrationContentIdentity([...prints].reverse(),[...manifest].reverse()).contentHash);assert.equal(a.contentHash,rawCalibrationContentIdentity(prints,[...manifest,meta("BTC-FUTURE-UNRELATED",99999)]).contentHash);assert.notEqual(a.contentHash,rawCalibrationContentIdentity(prints,[{...manifest[0]!,contractSize:2},manifest[1]!]).contentHash);assert.notEqual(a.contentHash,rawCalibrationContentIdentity([{...prints[0]!,price:.123},prints[1]!],manifest).contentHash);});

test("incomplete cache self-heals on the next retrieval",async()=>{const root=await mkdtemp(join(tmpdir(),"cal-cache-")),path=join(root,"raw.json"),prints=[p(39000)],instruments=[meta(prints[0]!.instrumentName,39000)];let calls=0;const input={path,rawSourceId:"r",targetStartMs:T,targetEndExclusiveMs:T+864e5,evidenceStartMs:T-720*60000,sourceHost:"history",retrievedAtUtc:()=>"2026-01-01T00:00:00.000Z",retrieve:async()=>{calls++;return{prints,instruments,complete:calls>1,incompleteLeafWindows:calls>1?[]:[{from:T,to:T+1}]}}};await assert.rejects(loadOrRetrieveRawCalibrationShard(input),IncompleteCalibrationSourceError);assert.equal((JSON.parse(await readFile(path,"utf8")) as {complete:boolean}).complete,false);const healed=await loadOrRetrieveRawCalibrationShard(input);assert.equal(calls,2);assert.equal(healed.shard.complete,true);assert.equal(healed.cacheReused,false);assert.equal(healed.shard.content_hash,rawCalibrationContentIdentity(prints,instruments).contentHash);const recoveredTargets=calibrationTargets(healed.shard.prints,T-60000,T+1);assert.equal(recoveredTargets.length,1);assert.equal(buildCalibrationObservation({target:recoveredTargets[0]!,tape:healed.shard.prints,sourceHost:"history",retrievalShardId:"r",retrievalContentHash:healed.shard.content_hash,sourceWindowComplete:healed.shard.complete}).source_window_complete,true);});

test("repeated incomplete retrieval never emits a complete shard",async()=>{const root=await mkdtemp(join(tmpdir(),"cal-cache-")),path=join(root,"raw.json");let calls=0;const input={path,rawSourceId:"r",targetStartMs:T,targetEndExclusiveMs:T+1,evidenceStartMs:T-1,sourceHost:"history",retrieve:async()=>{calls++;return{prints:[p(39000)],instruments:[meta(p(39000).instrumentName,39000)],complete:false,incompleteLeafWindows:[{}]}}};await assert.rejects(loadOrRetrieveRawCalibrationShard(input),IncompleteCalibrationSourceError);await assert.rejects(loadOrRetrieveRawCalibrationShard(input),IncompleteCalibrationSourceError);assert.equal(calls,2);assert.equal((JSON.parse(await readFile(path,"utf8")) as {complete:boolean}).complete,false);});

test("indexed causal features exactly equal the simple reference windows",()=>{const rows=[p(S,T-61*60000,{tradeId:"old"}),p(S,T-60*60000,{tradeId:"edge60",amount:2}),p(S,T-15*60000,{tradeId:"edge15",amount:3}),p(S,T-5*60000,{tradeId:"edge5",amount:4}),p(41000,T-1,{tradeId:"expiry-other",amount:5}),target,p(S,T,{tradeId:"same-ms"}),p(S,T+1,{tradeId:"future"})];const index=new CausalFeatureIndex(rows);assert.deepEqual(index.features(target),causalFeatures(target,rows));assert.equal(index.features(target).same_instrument_count_5m,1);assert.equal(index.features(target).same_instrument_count_15m,2);assert.equal(index.features(target).same_instrument_count_60m,3);});

test("day range driver and read-only v3 aggregator are deterministic",async()=>{assert.deepEqual(calibrationDayRanges(T,T+2*864e5),[{start:"2024-01-02",end:"2024-01-03"},{start:"2024-01-03",end:"2024-01-04"}]);const root=await mkdtemp(join(tmpdir(),"cal-aggregate-")),row=build(),obs=join(root,"one.jsonl");await writeFile(obs,JSON.stringify({...row,method_version:EXECUTION_CALIBRATION_METHOD_VERSION})+"\n");const manifest={method_version:EXECUTION_CALIBRATION_METHOD_VERSION,dataset_content_hash:"dh",raw_source:{id:"day1",target_start_utc:"2024-01-02T00:00:00.000Z",target_end_exclusive_utc:"2024-01-03T00:00:00.000Z"},shards:[{file:obs,observation_content_hash:"oh"}]};await writeFile(join(root,"manifest.day1.json"),JSON.stringify(manifest));const summary=await aggregateExecutionCalibration(root);assert.equal(summary.completed_shard_count,1);assert.equal(summary.total_observations,1);assert.equal(summary.primary_fair_eligible,1);assert.equal(summary.taker_concession_eligible,1);assert.ok(summary.dataset_content_hash);});
