import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import type {AnalysisDataset} from "../app/lib/research-analysis.ts";
import {datasetForAnalyticsTrack} from "../app/lib/research-analytics-model.ts";
import {normalizeExitPolicies} from "../app/lib/exit-policy/normalize.ts";
import {buildExitPolicyReport} from "../app/lib/exit-policy/report.ts";
import {nearFullLoss} from "../app/lib/exit-policy/report.ts";
import {pairedComparison,policyStatistics} from "../app/lib/exit-policy/statistics.ts";
import {buildVolatilityReport,volatilityEndpointsForCandidates,winningExitVolatility} from "../app/lib/volatility/volatility-report.ts";
import {DEFAULT_ANALYSIS_CONFIGURATION} from "../app/lib/analysis-configuration.ts";

const D=(day:number)=>new Date(Date.UTC(2026,0,day)).toISOString();
const dataset=(outcomes:Readonly<Record<string,unknown>>[],candidates:Readonly<Record<string,unknown>>[]=[candidate()]):AnalysisDataset=>({filename:"fixture",schemaVersion:"4.1.0",migratedFrom:null,run:{},tables:{candidates,outcomes,valuations:[],margin_scenarios:[]},counts:{},venues:["deribit"],sourceRuns:["run"],eventUniverseComplete:true,capabilities:[]});
function candidate(over:Record<string,unknown>={}){return{source_run_id:"run",event_id:"event",candidate_id:"candidate",strategy_variant_id:"candidate",structure_execution_id:"candidate~reference",analytics_track:"reference",execution_scenario:null,execution_scenario_status:"evaluated",structure_entry_timestamp_utc:D(2),expiry_timestamp_utc:D(10),quantity:1,...over}}
const outcome=(type:string,day:number,over:Record<string,unknown>={})=>({candidate_id:"candidate",analytics_track:"reference",execution_scenario:null,outcome_type:type,trigger_status:"reached",source_status:"estimated",status:"priced",decision_available_timestamp_utc:D(day),valuation_timestamp_utc:D(day),net_pnl_native:.01,net_pnl_usd:400,...over});
const thesis=(d:AnalysisDataset)=>normalizeExitPolicies(d).find(x=>x.policyId==="thesis")!;

test("chronology freezes an earlier reached-but-unpriced winner",()=>{const row=thesis(dataset([outcome("vpoc",3,{status:"unavailable",net_pnl_native:null,evidence_reason:"reference mark absent"}),outcome("settlement",9)]));assert.equal(row.winningTrigger,"vpoc");assert.equal(row.status,"triggered_unpriced");assert.equal(row.diagnosticCode,"outcome_reached_unpriced");assert.match(row.missingDataReason!,/reference mark absent/)});

test("exact decision ties use declared policy priority and disclose the tie",()=>{const row=thesis(dataset([outcome("invalidation",4),outcome("vpoc",4),outcome("settlement",9)]));assert.equal(row.winningTrigger,"vpoc");assert.match(row.tieResolution!,/policy priority at the same decision timestamp/)});

test("fixed identities resolve, an after-expiry cap cannot win, and settlement survives",()=>{const rows=normalizeExitPolicies(dataset([outcome("fixed_3d",5),outcome("fixed_5d",7),outcome("fixed_7d",11,{trigger_status:"after_expiry"}),outcome("settlement",10)]));assert.equal(rows.find(x=>x.policyId==="time_cap_3d")!.winningTrigger,"fixed_3d");assert.equal(rows.find(x=>x.policyId==="time_cap_5d")!.winningTrigger,"fixed_5d");assert.equal(rows.find(x=>x.policyId==="time_cap_7d")!.winningTrigger,"settlement");assert.equal(rows.find(x=>x.policyId==="settlement_benchmark")!.winningTrigger,"settlement")});

test("a pre-entry VPOC cannot close a delayed-entry structure",()=>{const row=thesis(dataset([outcome("vpoc",1),outcome("settlement",9)]));assert.equal(row.winningTrigger,"settlement");assert.equal(row.status,"priced")});

test("one projected analytical track does not double count pricing representations",()=>{const candidates=[candidate(),candidate({structure_execution_id:"alternate-representation"})],rows=normalizeExitPolicies(dataset([outcome("settlement",9)],candidates));assert.equal(rows.filter(x=>x.policyId==="thesis").length,1);assert.equal(rows[0]!.pricingTrack,null)});

test("Reference report routing is execution-independent while strict tracks are projected separately",()=>{const base=candidate({analytics_track:undefined,execution_scenario:"maker",structure_execution_id:"candidate~maker",reference_valuation:{status:"valued",entrySnapshot:{status:"priced",targetTimestamp:Date.parse(D(2)),grossSpreadBtc:.02,openingFeesBtc:.001,netOpeningCashFlowBtc:.019},valuationPathSnapshot:[],outcomeSnapshots:[{label:"settlement",status:"estimated",decisionTimestamp:Date.parse(D(10)),valuationTimestamp:Date.parse(D(10)),estimatedNetPnlBtc:.01,estimatedNetPnlUsd:400,feesBtc:.002,evidenceReason:"official delivery"}]}}),report=buildExitPolicyReport(dataset([], [base]),DEFAULT_ANALYSIS_CONFIGURATION);assert.equal(report.scope.analyticsTrack,"reference");assert.equal(report.scope.executionScenario,null);assert.equal(report.scope.pricingTrack,null);assert.equal(report.reference.policies.find(x=>x.policy.id==="thesis")!.observations.length,1);assert.equal(report.reference.policies.find(x=>x.policy.id==="thesis")!.observations[0]!.pricingTrack,null);assert.equal(report.observed.maker.scope.analyticsTrack,"immediate_maker");assert.equal(report.observed.taker.scope.analyticsTrack,"immediate_taker");const settlement=report.policies.find(x=>x.policy.id==="thesis")!.observations[0]!;assert.equal(settlement.closingFeesBtc,.002);assert.equal(settlement.deliveryFeesBtc,.002);assert.equal(settlement.totalFeesBtc,.003);assert.equal(settlement.missingDataReason,null);assert.equal(settlement.sourceEvidenceReason,"official delivery")});

test("explicit denominators and conditional PnL retain incomplete coverage",()=>{const priced=thesis(dataset([outcome("settlement",9,{net_pnl_native:-.02})])),unpriced=thesis(dataset([outcome("vpoc",3,{status:"unavailable",net_pnl_native:null}),outcome("settlement",9)])),stats=policyStatistics([priced,unpriced]);assert.deepEqual(stats.denominators,{selectedEligible:{n:2},trackAvailable:{n:2},trackUnavailable:{n:0},triggerDeterminate:{n:2},pricedWinningExits:{n:1},triggeredUnpriced:{n:1},unavailable:{n:0},notEvaluated:{n:0}});assert.equal(stats.pricingCoverage.value,.5);assert.equal(stats.selectedCohortCoverage.value,.5);assert.equal(stats.pnlAmongPricedExits.btc.mean.value,-.02);assert.equal(stats.pnlAmongPricedExits.btc.worst.value,-.02);assert.match(stats.pnlAmongPricedExits.btc.p10.reason!,/insufficient sample/)});

test("fees, MAE and policy-specific piecewise capital-days use canonical rows",()=>{const d=dataset([outcome("settlement",6,{closing_fees_native:.002})]);(d.tables as Record<string,unknown>).candidates=[candidate({opening_fees_native:.001})];(d.tables as Record<string,unknown>).valuations=[{candidate_id:"candidate",analytics_track:"reference",execution_scenario:null,pricing_track:"reference",valuation_status:"priced",timestamp_utc:D(3),net_pnl_native:-.004},{candidate_id:"candidate",analytics_track:"reference",execution_scenario:null,pricing_track:"reference",valuation_status:"priced",timestamp_utc:D(5),net_pnl_native:.01}];(d.tables as Record<string,unknown>).margin_scenarios=[{candidate_id:"candidate",margin_status:"available",margin_inputs:{path:[{timestamp:Date.parse(D(2)),initialMarginBtc:.1},{timestamp:Date.parse(D(4)),initialMarginBtc:.2}]}}];const row=normalizeExitPolicies(d,{capitalBasis:"peak_required_capital"}).find(x=>x.policyId==="thesis")!;assert.equal(row.deliveryFeesBtc,.002);assert.equal(row.totalFeesBtc,.003);assert.equal(row.maeBtc,-.004);assert.ok(Math.abs(row.capitalDaysBtc!-(.1*2+.2*2))<1e-12);assert.notEqual(row.capitalDaysBtc,.2*4,"peak IM is not multiplied over the whole holding period")});

test("capital-days stays unavailable when the canonical causal path is absent",()=>{const row=normalizeExitPolicies(dataset([outcome("settlement",6)]),{capitalBasis:"peak_required_capital"}).find(x=>x.policyId==="thesis")!;assert.equal(row.capitalDaysBtc,null);assert.match(row.capitalDaysReason!,/margin path unavailable/)});

test("paired post-exit diagnostics use only causal Reference marks through Thesis",()=>{const d=dataset([outcome("credit_capture_50",4,{net_pnl_native:.01}),outcome("vpoc",8,{net_pnl_native:.02}),outcome("settlement",10)]);(d.tables as Record<string,unknown>).valuations=[{candidate_id:"candidate",analytics_track:"reference",execution_scenario:null,pricing_track:"reference",valuation_status:"priced",timestamp_utc:D(5),net_pnl_native:.03},{candidate_id:"candidate",analytics_track:"reference",execution_scenario:null,pricing_track:"reference",valuation_status:"unavailable",timestamp_utc:D(6),net_pnl_native:-9},{candidate_id:"candidate",analytics_track:"reference",execution_scenario:null,pricing_track:"reference",valuation_status:"priced",timestamp_utc:D(7),net_pnl_native:-.02},{candidate_id:"candidate",analytics_track:"reference",execution_scenario:null,pricing_track:"reference",valuation_status:"priced",timestamp_utc:D(8),net_pnl_native:99},{candidate_id:"candidate",analytics_track:"reference",execution_scenario:null,pricing_track:"reference",valuation_status:"priced",timestamp_utc:D(9),net_pnl_native:5}];const rows=normalizeExitPolicies(d),comparison=pairedComparison(rows.filter(x=>x.policyId==="capture_50"),rows.filter(x=>x.policyId==="thesis"));assert.equal(comparison.matchedN,1);assert.equal(comparison.pnlDifferenceBtc.mean.value,-.01);assert.ok(Math.abs(comparison.postExitOpportunitySurrendered.mean.value!-.02)<1e-12);assert.ok(Math.abs(comparison.postExitDownsideAvoided.mean.value!-.03)<1e-12);assert.equal(comparison.postExitOpportunitySurrendered.mean.n,1);assert.equal(comparison.postExitEvidenceCounts[0],3,"duplicate Thesis timestamp is replaced by the exact endpoint and post-Thesis marks are excluded")});

test("missing post-exit marks and legacy provenance never become zero or a pair",()=>{const rows=normalizeExitPolicies(dataset([outcome("credit_capture_50",4),outcome("vpoc",8),outcome("settlement",10)])),capture=rows.find(x=>x.policyId==="capture_50")!,thesisRow=rows.find(x=>x.policyId==="thesis")!,missing=pairedComparison([capture],[thesisRow]);assert.equal(missing.postExitOpportunitySurrendered.mean.value,0,"the exact Thesis endpoint is sufficient evidence");assert.equal(missing.postExitEvidenceCounts[0],1);const late=pairedComparison([{...capture,valuationTimestamp:thesisRow.valuationTimestamp}],[thesisRow]);assert.equal(late.postExitOpportunitySurrendered.mean.value,null);assert.match(late.postExitUnavailableReasons[0]!,/does not exit before Thesis/);const legacy={...capture,legacyUndifferentiated:true},excluded=pairedComparison([legacy],[thesisRow]);assert.equal(excluded.matchedN,0);assert.ok(excluded.unmatched.reasons.includes("legacy provenance excluded"))});

test("near-full-loss is configuration-gated and uses structural loss rather than margin",()=>{const base=thesis(dataset([outcome("settlement",9,{net_pnl_native:-.08})])),row={...base,maximumStructuralLossBtc:.1,requiredCapitalBtc:.01};assert.equal(nearFullLoss([row],null).status,"not_configured");const configured=nearFullLoss([row],.7);assert.equal(configured.eligibleN,1);assert.equal(configured.nearFullLossN,1);assert.equal(configured.frequency,1);assert.deepEqual(configured.candidateIds,["candidate"])});

test("exact structural identity prevents same-event cross-candidate pairing",()=>{const base=thesis(dataset([outcome("settlement",9)])),other={...base,candidateId:"other",matchKey:base.matchKey.replace("candidate","other")};assert.equal(pairedComparison([other],[base]).matchedN,0)});

test("equal-event summaries do not treat several structures from one MR event as independent",()=>{const a=thesis(dataset([outcome("settlement",9,{net_pnl_native:.01})])),pairs=[{...a,policyId:"capture_50" as const,pnlBtc:.02},{...a,policyId:"capture_50" as const,candidateId:"c2",matchKey:"c2",pnlBtc:.04},{...a,policyId:"capture_50" as const,eventId:"e2",candidateId:"c3",matchKey:"c3",pnlBtc:.11}],bases=[a,{...a,candidateId:"c2",matchKey:"c2",pnlBtc:.02},{...a,eventId:"e2",candidateId:"c3",matchKey:"c3",pnlBtc:.01}],x=pairedComparison(pairs,bases);assert.equal(x.matchedStructuresN,3);assert.equal(x.matchedEventN,2);assert.equal(x.equalEvent.pnlBtc.mean.value,.0575);assert.equal(x.equalEvent.pnlBtc.eventN,2)});


test("Exit volatility scopes controlled research out and winning joins are exact",()=>{const evidence=(iv:number,source="deribit_trade_iv")=>({status:"available",observation:"observed",source,iv_decimal:iv}),structures=[{candidate_id:"selected",legs:[{leg:"short",...evidence(.5)},{leg:"long",...evidence(.6)}],same_expiry_reference:{status:"unavailable"},differentials:[],post_entry_market_iv:[{endpoint_id:"vpoc",target_timestamp_utc:D(4),short:evidence(.4),long:evidence(.55)},{endpoint_id:"settlement",target_timestamp_utc:D(10),short:{status:"unavailable"},long:{status:"unavailable"}}],market_iv_path:[]},{candidate_id:"controlled",legs:[{leg:"short",...evidence(.7)}],same_expiry_reference:{status:"unavailable"},differentials:[],post_entry_market_iv:[{endpoint_id:"vpoc",target_timestamp_utc:D(4),short:evidence(.6),long:{status:"unavailable"}}],market_iv_path:[]}],d={...dataset([],[candidate({candidate_id:"selected",strategy_variant_id:"selected",is_selected:true}),candidate({candidate_id:"controlled",strategy_variant_id:"controlled",is_selected:false,research_role:"short_strike_buffered"})]),tables:{...dataset([]).tables,structure_volatility_state:structures,candidates:[candidate({candidate_id:"selected",strategy_variant_id:"selected",is_selected:true}),candidate({candidate_id:"controlled",strategy_variant_id:"controlled",is_selected:false,research_role:"short_strike_buffered"})]}} as AnalysisDataset,vol=buildVolatilityReport(d),scoped=volatilityEndpointsForCandidates(vol,new Set(["selected"]));assert.equal(scoped.aggregates.find(x=>x.id==="vpoc")!.denominator,1);const policy={...thesis(dataset([outcome("vpoc",4)])),candidateId:"selected",winningTrigger:"vpoc" as const,valuationTimestamp:D(4)},winner=winningExitVolatility(vol,[{policyId:"thesis",observations:[policy]}],new Set(["selected"]))[0]!;assert.equal(winner.shortObservedN,1);assert.equal(winner.bothObservedN,1);assert.ok(Math.abs(winner.medianDeltaShortIv!+.1)<1e-12);const wrong={...policy,valuationTimestamp:D(5)};assert.equal(winningExitVolatility(vol,[{policyId:"thesis",observations:[wrong]}],new Set(["selected"]))[0]!.completelyUnavailableN,1);const settlement={...policy,winningTrigger:"settlement" as const,valuationTimestamp:D(10)};assert.equal(winningExitVolatility(vol,[{policyId:"thesis",observations:[settlement]}],new Set(["selected"]))[0]!.settlementNotApplicableN,1)});

test("MAE includes the authoritative exact winning endpoint and deduplicates its timestamp",()=>{const d=dataset([outcome("invalidation",5,{net_pnl_native:-.02}),outcome("settlement",10)]);(d.tables as Record<string,unknown>).valuations=[{candidate_id:"candidate",analytics_track:"reference",execution_scenario:null,pricing_track:"reference",valuation_status:"priced",timestamp_utc:D(3),net_pnl_native:-.004},{candidate_id:"candidate",analytics_track:"reference",execution_scenario:null,pricing_track:"reference",valuation_status:"priced",timestamp_utc:D(5),net_pnl_native:-.001},{candidate_id:"candidate",analytics_track:"reference",execution_scenario:null,pricing_track:"reference",valuation_status:"priced",timestamp_utc:D(6),net_pnl_native:-.5}];const row=thesis(d);assert.equal(row.winningTrigger,"invalidation");assert.equal(row.maeBtc,-.02)});

test("canonical snapshot economics keeps tabular closing fee authority",()=>{const base=candidate({analytics_track:undefined,execution_scenario:"maker",reference_valuation:{status:"valued",entrySnapshot:{status:"priced",targetTimestamp:Date.parse(D(2)),grossSpreadBtc:.02,openingFeesBtc:.001,netOpeningCashFlowBtc:.019},valuationPathSnapshot:[],outcomeSnapshots:[{label:"settlement",status:"estimated",decisionTimestamp:Date.parse(D(10)),valuationTimestamp:Date.parse(D(10)),estimatedNetPnlBtc:.01,closing_fees_native:.003}]}}),projected=datasetForAnalyticsTrack(dataset([],[base]),"reference"),row=projected.tables.outcomes!.find(x=>x.outcome_type==="settlement")!;assert.equal(row.closing_fees_native,.003)});

test("exact but IV-empty winning endpoint is completely unavailable and settlement needs no endpoint row",()=>{const evidence=(iv:number)=>({status:"available",observation:"observed",source:"deribit_trade_iv",iv_decimal:iv}),d={...dataset([]),tables:{...dataset([]).tables,candidates:[candidate({candidate_id:"c"})],structure_volatility_state:[{candidate_id:"c",legs:[{leg:"short",...evidence(.5)}],same_expiry_reference:{status:"unavailable"},differentials:[],post_entry_market_iv:[{endpoint_id:"vpoc",target_timestamp_utc:D(4),short:{status:"unavailable"},long:{status:"unavailable"}}],market_iv_path:[]}]}} as AnalysisDataset,vol=buildVolatilityReport(d),base={...thesis(dataset([outcome("vpoc",4)])),candidateId:"c",winningTrigger:"vpoc" as const,valuationTimestamp:D(4)},empty=winningExitVolatility(vol,[{policyId:"thesis",observations:[base]}],new Set(["c"]))[0]!;assert.equal(empty.exactEndpointN,1);assert.equal(empty.anyLegObservedN,0);assert.equal(empty.completelyUnavailableN,1);const settlement={...base,winningTrigger:"settlement" as const,valuationTimestamp:D(10)},terminal=winningExitVolatility(vol,[{policyId:"thesis",observations:[settlement]}],new Set(["c"]))[0]!;assert.equal(terminal.ivApplicableN,0);assert.equal(terminal.settlementNotApplicableN,1);assert.equal(terminal.completelyUnavailableN,0)});

test("strict-track availability denominators remain distinct",()=>{const rows=[thesis(dataset([outcome("settlement",9)])),thesis(dataset([], [candidate({candidate_id:"u1",execution_scenario_status:"unavailable"})])),thesis(dataset([], [candidate({candidate_id:"u2",execution_scenario_status:"unavailable"})]))],stats=policyStatistics(rows);assert.equal(stats.denominators.selectedEligible.n,3);assert.equal(stats.denominators.trackAvailable.n,1);assert.equal(stats.denominators.trackUnavailable.n,2);assert.equal(stats.denominators.notEvaluated.n,0)});

test("missing capital evidence is unavailable, not mathematically not estimable",()=>{const row=normalizeExitPolicies(dataset([outcome("settlement",6)]),{capitalBasis:"peak_required_capital"}).find(x=>x.policyId==="thesis")!,stats=policyStatistics([row]);assert.equal(stats.capitalDaysAmongPricedExits.status,"unavailable");assert.equal(stats.capitalDaysAmongPricedExits.n,0)});

test("winning-exit IV separates observed endpoints from usable delta pairs",()=>{
 const observed=(iv:number)=>({status:"available",observation:"observed",source:"deribit_trade_iv",iv_decimal:iv});
 const structures=Array.from({length:5},(_,i)=>({candidate_id:`iv-${i}`,legs:[{leg:"short",...(i<2?observed(.5):{status:"unavailable"})}],same_expiry_reference:{status:"unavailable"},differentials:[],post_entry_market_iv:[{endpoint_id:"vpoc",target_timestamp_utc:D(4),short:i<3?observed(i<2?.45:.4):{status:"unavailable"},long:{status:"unavailable"}}],market_iv_path:[]}));
 const d={...dataset([]),tables:{...dataset([]).tables,structure_volatility_state:structures}} as AnalysisDataset;
 const vol=buildVolatilityReport(d),base=thesis(dataset([outcome("vpoc",4)]));
 const observations=structures.map((_,i)=>({...base,candidateId:`iv-${i}`,matchKey:`iv-${i}`,winningTrigger:"vpoc" as const,valuationTimestamp:D(4)}));
 const result=winningExitVolatility(vol,[{policyId:"thesis",observations}],new Set(observations.map(x=>x.candidateId)))[0]!;
 assert.equal(result.exactEndpointN,5);
 assert.equal(result.shortObservedN,3);
 assert.equal(result.shortDeltaN,2);
 assert.equal(result.longDeltaN,0);
 assert.equal(result.bothDeltaN,0);
 assert.equal(result.medianEntryShortIv,.5);
 assert.equal(result.medianExitShortIv,.45);
 assert.ok(Math.abs(result.medianDeltaShortIv!+.05)<1e-12);
});

test("winning-exit paired IV arrows exclude exit-only endpoint observations",()=>{
 const observed=(iv:number)=>({status:"available",observation:"observed",source:"deribit_trade_iv",iv_decimal:iv});
 const structures=[
  {candidate_id:"paired-a",legs:[{leg:"short",...observed(.5)}],same_expiry_reference:{status:"unavailable"},differentials:[],post_entry_market_iv:[{endpoint_id:"vpoc",target_timestamp_utc:D(4),short:observed(.45),long:{status:"unavailable"}}],market_iv_path:[]},
  {candidate_id:"paired-b",legs:[{leg:"short",...observed(.6)}],same_expiry_reference:{status:"unavailable"},differentials:[],post_entry_market_iv:[{endpoint_id:"vpoc",target_timestamp_utc:D(4),short:observed(.55),long:{status:"unavailable"}}],market_iv_path:[]},
  {candidate_id:"exit-only",legs:[{leg:"short",status:"unavailable"}],same_expiry_reference:{status:"unavailable"},differentials:[],post_entry_market_iv:[{endpoint_id:"vpoc",target_timestamp_utc:D(4),short:observed(.1),long:{status:"unavailable"}}],market_iv_path:[]}
 ];
 const vol=buildVolatilityReport({...dataset([]),tables:{...dataset([]).tables,structure_volatility_state:structures}} as AnalysisDataset),base=thesis(dataset([outcome("vpoc",4)]));
 const observations=structures.map(x=>({...base,candidateId:x.candidate_id,matchKey:x.candidate_id,winningTrigger:"vpoc" as const,valuationTimestamp:D(4)}));
 const result=winningExitVolatility(vol,[{policyId:"thesis",observations}],new Set(observations.map(x=>x.candidateId)))[0]!;
 assert.equal(result.shortObservedN,3);
 assert.equal(result.shortDeltaN,2);
 assert.equal(result.medianEntryShortIv,.55);
 assert.equal(result.medianExitShortIv,.5);
 assert.ok(Math.abs(result.medianDeltaShortIv!+.05)<1e-12);
});

test("winning-exit IV absence is unavailable evidence while measured zero remains numeric",()=>{
 const observed=(iv:number)=>({status:"available",observation:"observed",source:"deribit_trade_iv",iv_decimal:iv});
 const structures=[{candidate_id:"no-entry",legs:[{leg:"short",status:"unavailable"}],same_expiry_reference:{status:"unavailable"},differentials:[],post_entry_market_iv:[{endpoint_id:"vpoc",target_timestamp_utc:D(4),short:observed(.45),long:{status:"unavailable"}}],market_iv_path:[]},{candidate_id:"zero",legs:[{leg:"short",...observed(.5)}],same_expiry_reference:{status:"unavailable"},differentials:[],post_entry_market_iv:[{endpoint_id:"vpoc",target_timestamp_utc:D(4),short:observed(.5),long:{status:"unavailable"}}],market_iv_path:[]}];
 const vol=buildVolatilityReport({...dataset([]),tables:{...dataset([]).tables,structure_volatility_state:structures}} as AnalysisDataset),base=thesis(dataset([outcome("vpoc",4)]));
 const rows=structures.map((x,i)=>({...base,candidateId:x.candidate_id,matchKey:x.candidate_id,winningTrigger:"vpoc" as const,valuationTimestamp:D(4),policyId:i?"capture_50" as const:"thesis" as const}));
 const results=winningExitVolatility(vol,rows.map(x=>({policyId:x.policyId,observations:[x]})),new Set(rows.map(x=>x.candidateId)));
 assert.equal(results[0]!.shortDeltaN,0); assert.equal(results[0]!.medianDeltaShortIv,null);
 assert.equal(results[1]!.shortDeltaN,1); assert.equal(results[1]!.shortCompressionShare,0); assert.equal(results[1]!.shortExpansionShare,0);
});

test("Exit presentation scopes overflow, fixed cards, identities, IV units and null language",()=>{
 const view=readFileSync(new URL("../app/components/exit-policy-report.tsx",import.meta.url),"utf8"),volatilityView=readFileSync(new URL("../app/components/volatility-report.tsx",import.meta.url),"utf8"),css=readFileSync(new URL("../app/globals.css",import.meta.url),"utf8");
 assert.match(view,/className="exit-table-scroll"/);
 assert.doesNotMatch(view,/className="count-grid"/);
 assert.match(view,/report\.policies\.map/);
 assert.match(view,/\(x\*100\)\.toFixed\(1\).*vol pts/);
 assert.match(view,/shortDeltaN/); assert.match(view,/longDeltaN/); assert.match(view,/bothDeltaN/);
 assert.match(view,/Not evaluated/); assert.match(view,/Completely unavailable/); assert.match(view,/Partial endpoint evidence/); assert.match(view,/Endpoint observed/); assert.match(view,/Not applicable/);
 assert.match(view,/Showing first 200 of/);
 assert.match(volatilityView,/<tr><td>Settlement<\/td><td colSpan=\{6\}>Not applicable/);
 assert.match(volatilityView,/className="exit-table-scroll"/);
 assert.match(css,/\.exit-table-scroll \{ width: 100%; max-width: 100%; min-width: 0; overflow-x: auto/);
 assert.match(css,/\.exit-fixed-grid \{ display: grid; grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/);
 assert.match(css,/\.exit-capture-grid \{ display: grid; gap: 10px; min-width: 0; \}/);
 assert.match(view,/Policies with determinate exits/);
 assert.match(view,/policiesWithDeterminateExits=report\.policies\.filter\(x=>x\.stats\.denominators\.triggerDeterminate\.n>0\)\.length/);
 assert.doesNotMatch(view,/Policies evaluated/);
 assert.match(view,/value!==null&&value!==0&&<i className=\{`exit-delta-fill/,"numeric zero has no directional fill");
 assert.match(view,/value<0\?"is-negative":"is-positive"/,"only strictly positive values receive the positive fill");
});
