import test from "node:test";import assert from "node:assert/strict";import {mkdtemp,mkdir,writeFile} from "node:fs/promises";import {tmpdir} from "node:os";import {join} from "node:path";
import {parseLocalContractRow,LOCAL_ARCHIVE_MANIFEST,LOCAL_ARCHIVE_SOURCE} from "../scripts/local-contract-archive.ts";
import {LOCAL_AUX_DIRECTORY,LOCAL_INSTRUMENT_MANIFEST,LOCAL_OPTION_TAPE_DIRECTORY,LOCAL_SOURCE_MANIFEST,LocalVolatilityRetrieval,localPrintToIvTrade} from "../scripts/local-volatility-retrieval.ts";

const midnight=Date.parse("2024-01-02T00:00:00Z"),expiry=Date.parse("2024-01-26T08:00:00Z");
const raw=(id:string,timestamp:number,name="BTC-26JAN24-40000-C")=>({trade_seq:Number(id.replace(/\D/g,""))||1,trade_id:id,timestamp,price:.02,mark_price:.021,iv:55.5,instrument_name:name,index_price:40_100,direction:"buy",amount:1});
async function fixture(){const root=await mkdtemp(join(tmpdir(),"local-volatility-")),tape=join(root,LOCAL_OPTION_TAPE_DIRECTORY),aux=join(root,LOCAL_AUX_DIRECTORY);await mkdir(tape,{recursive:true});await mkdir(aux,{recursive:true});await writeFile(join(tape,LOCAL_ARCHIVE_MANIFEST),JSON.stringify({source:LOCAL_ARCHIVE_SOURCE,data_content_fingerprint:"f".repeat(64),coverage_start:"2024-01-01T00:00:00.000Z",coverage_end:"2024-01-02T23:59:59.999Z"}));const before=parseLocalContractRow(raw("b",midnight-1))!,after=parseLocalContractRow(raw("a",midnight+1))!,future=parseLocalContractRow(raw("z",midnight+10_000))!,put=parseLocalContractRow(raw("p",midnight+1,"BTC-26JAN24-39000-P"))!;await writeFile(join(tape,"2024-01-01.jsonl"),JSON.stringify(before)+"\n");await writeFile(join(tape,"2024-01-02.jsonl"),[future,put,after].map(JSON.stringify).join("\n")+"\n");const manifest=[{instrumentName:"BTC-26JAN24-40000-C",strike:40_000,optionType:"C",expiryTimestampMs:expiry,createdAtMs:Date.parse("2023-06-01T08:00:00Z"),settlementPeriod:"month"},{instrumentName:"BTC-26JAN24-39000-P",strike:39_000,optionType:"P",expiryTimestampMs:expiry,createdAtMs:Date.parse("2023-06-01T08:00:00Z"),settlementPeriod:"month"}] as const;await writeFile(join(aux,LOCAL_INSTRUMENT_MANIFEST),JSON.stringify(manifest));return{root,before,after,future,put,manifest}}

test("one-day intervals filter exactly, exclude future rows, sort deterministically, and reuse a day shard",async()=>{const f=await fixture(),local=new LocalVolatilityRetrieval(f.root);const first=await local.ivTradesByCurrency(midnight,midnight+1);assert.deepEqual(first.map(x=>x.tradeId),["p","a"]);assert.equal(local.localDayShardReads,1);assert.equal(local.localRowsScanned,3);assert.deepEqual((await local.ivTradesByCurrency(midnight+1,midnight+1)).map(x=>x.tradeId),["p","a"]);assert.equal(local.localDayShardReads,1);assert.equal(local.localRowsScanned,6)});
test("cross-midnight reads intersecting UTC shards and exact instrument filtering",async()=>{const f=await fixture(),local=new LocalVolatilityRetrieval(f.root),rows=await local.ivTrades("BTC-26JAN24-40000-C",midnight-1,midnight+1);assert.deepEqual(rows.map(x=>x.tradeId),["b","a"]);assert.equal(local.localDayShardReads,2);assert.equal(local.localRowsScanned,4);assert.ok(rows.every(x=>x.instrumentName==="BTC-26JAN24-40000-C"))});
test("batched exact retrieval is field-equivalent, opens each union day once, and retains no day archive",async()=>{const f=await fixture(),windows=new Map([["BTC-26JAN24-40000-C",{start:midnight-1,end:midnight+1}],["BTC-26JAN24-39000-P",{start:midnight,end:midnight+1}]]),individual=new LocalVolatilityRetrieval(f.root),expected=new Map(await Promise.all([...windows].map(async([name,w])=>[name,await individual.ivTrades(name,w.start,w.end)] as const))),batched=new LocalVolatilityRetrieval(f.root),actual=await batched.ivTradesMany(windows);assert.deepEqual(actual,expected);assert.equal(batched.exactBatchDayShardsRead,2);assert.equal(batched.localDayShardReads,2);assert.equal(batched.localRowsScanned,4);assert.equal(batched.peakBatchDayShardsRetained,1);assert.equal((batched as unknown as {days:Map<string,unknown>}).days.size,0,"batch shards are released rather than retained")});
test("saved instrument manifest supplies genuine creation timestamps without HTTP",async()=>{const f=await fixture(),prior=globalThis.fetch,calls:{count:number}={count:0};globalThis.fetch=(async()=>{calls.count++;throw new Error("network forbidden")}) as typeof fetch;try{const local=new LocalVolatilityRetrieval(f.root);assert.deepEqual(await local.instrumentManifest(),f.manifest);await local.ivTradesByCurrency(midnight,midnight+1);assert.equal(local.requestCount,0);assert.equal(calls.count,0)}finally{globalThis.fetch=prior}});
test("missing or non-genuine instrument manifests fail with preparation guidance",async()=>{const f=await fixture(),missing=new LocalVolatilityRetrieval(join(f.root,"missing"));await assert.rejects(missing.instrumentManifest(),/instrument manifest is missing.*volatility:prepare-local-data/);await writeFile(join(f.root,LOCAL_AUX_DIRECTORY,LOCAL_INSTRUMENT_MANIFEST),JSON.stringify([{...f.manifest[0],createdAtMs:null}]));await assert.rejects(new LocalVolatilityRetrieval(f.root).instrumentManifest(),/genuine creation timestamps/)});
test("archive fingerprint is exposed, cross-checked, and invalid manifests fail loudly",async()=>{const f=await fixture(),local=new LocalVolatilityRetrieval(f.root);assert.equal((await local.archiveManifest()).data_content_fingerprint,"f".repeat(64));await writeFile(join(f.root,LOCAL_AUX_DIRECTORY,LOCAL_SOURCE_MANIFEST),JSON.stringify({generatedAtUtc:new Date(0).toISOString(),archive:{fingerprint:"wrong"},optionTradeNetworkRequests:0}));await assert.rejects(local.sourceManifest(),/fingerprint does not match/);await writeFile(join(f.root,LOCAL_OPTION_TAPE_DIRECTORY,LOCAL_ARCHIVE_MANIFEST),JSON.stringify({source:LOCAL_ARCHIVE_SOURCE}));await assert.rejects(new LocalVolatilityRetrieval(f.root).ivTradesByCurrency(midnight,midnight+1),/manifest is invalid/)});
test("local archive and canonical HTTP field representation produce equivalent evidence",async()=>{const api=raw("77",midnight+1),canonical={instrumentName:api.instrument_name,tradeId:api.trade_id,tradeSeq:api.trade_seq,timestampMs:api.timestamp,ivApiPercent:api.iv,price:api.price,markPrice:api.mark_price,indexPrice:api.index_price,direction:api.direction,amount:api.amount},print=parseLocalContractRow(api)!;assert.deepEqual(localPrintToIvTrade(print),canonical);assert.deepEqual({instrumentName:print.instrumentName,iv:print.ivApiPercent,indexPrice:print.indexPrice,timestamp:print.timestampMs,optionType:print.optionType,strike:print.strike,expiry:print.expiryTimestampMs},{instrumentName:canonical.instrumentName,iv:canonical.ivApiPercent,indexPrice:canonical.indexPrice,timestamp:canonical.timestampMs,optionType:"C",strike:40_000,expiry})});
