import test from "node:test";
import assert from "node:assert/strict";
import {mkdtemp,mkdir,readFile,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {DERIBIT_OPTION_INDEX_UNDERLYING,buildReferenceSeriesRows,type ListedExpiry} from "../app/lib/volatility/reference-series.ts";
import {LOCAL_ARCHIVE_MANIFEST,LOCAL_ARCHIVE_SOURCE} from "../scripts/local-contract-archive.ts";
import {LOCAL_AUX_DIRECTORY,LOCAL_INSTRUMENT_MANIFEST,LOCAL_OPTION_TAPE_DIRECTORY,LOCAL_SOURCE_MANIFEST} from "../scripts/local-volatility-retrieval.ts";
import {LOCAL_PRECOMPUTE_MANIFEST,buildStreamingReferenceRows,precomputeLocalVolatility} from "../scripts/precompute-local-volatility.ts";
import type {DeribitIvTradeRow,DeribitOptionInstrument} from "../scripts/volatility-reference-cache.ts";
import {REFERENCE_SERIES_ID} from "../app/lib/volatility/reference-series.ts";

const HOUR=3_600_000,T0=Date.parse("2024-01-02T00:00:00Z"),tenors=["7d","14d","30d"] as const;
const instruments:DeribitOptionInstrument[]=tenors.flatMap((tenor,i)=>{const days=[7,14,30][i]!,expiry=T0+days*86_400_000;return [39_000,40_000,41_000].map((strike,j)=>({instrumentName:`BTC-${tenor}-${strike}-${j%2?"P":"C"}`,strike,optionType:j%2?"P":"C",expiryTimestampMs:expiry,createdAtMs:T0-86_400_000,settlementPeriod:"week"}))});
const trades:DeribitIvTradeRow[]=Array.from({length:3},(_,h)=>instruments.map((m,i)=>({instrumentName:m.instrumentName,tradeId:`${h}-${i}`,tradeSeq:h*100+i,timestampMs:T0+h*HOUR-10*60_000,ivApiPercent:50+i+h,price:.02,markPrice:.02,indexPrice:40_000,direction:"buy",amount:1}))).flat();
const listed=(target:number):ListedExpiry[]=>[...new Set(instruments.map(x=>x.expiryTimestampMs))].filter(x=>x>target).map(expiryTimestampMs=>({expiryTimestampMs,createdAtMs:T0-86_400_000,settlementPeriod:"week",strikes:instruments.filter(x=>x.expiryTimestampMs===expiryTimestampMs).map(x=>x.strike)}));
const raw=(target:number)=>trades.filter(x=>x.timestampMs<=target&&x.timestampMs>=target-HOUR).map(t=>{const m=instruments.find(x=>x.instrumentName===t.instrumentName)!;return{instrumentName:m.instrumentName,tradeId:t.tradeId,tradeSeq:t.tradeSeq,strike:m.strike,optionType:m.optionType,expiryTimestampMs:m.expiryTimestampMs,settlementPeriod:m.settlementPeriod,contractCreatedAtMs:m.createdAtMs,timestampMs:t.timestampMs,ivApiPercent:t.ivApiPercent,indexPrice:t.indexPrice}});

test("streaming/sliding-window rows are field-equivalent to target-by-target canonical construction",()=>{const targets=[T0,T0+HOUR,T0+2*HOUR],diagnostics={dayShardsOpened:0,rowsStreamed:0,hourlyTargetsProduced:0},actual=buildStreamingReferenceRows({targets,trades,instruments,diagnostics}),expected=targets.flatMap(timestampMs=>buildReferenceSeriesRows({timestampMs,underlyingInstrument:DERIBIT_OPTION_INDEX_UNDERLYING,underlyingPrice:40_000,listedExpiries:listed(timestampMs),candidates:raw(timestampMs),tenors}).rows);const fields=["observation_class","reference_iv_decimal","reference_expiry_timestamp_utc","actual_dte_days","underlying_price","observation_timestamp_utc","age_minutes","tenor_tolerance_passed","unavailable_reason_code"] as const;assert.deepEqual(actual.map(row=>fields.map(k=>row[k])),expected.map(row=>fields.map(k=>row[k])));assert.equal(diagnostics.rowsStreamed,trades.length);assert.equal(diagnostics.hourlyTargetsProduced,targets.length)});

async function fixture(){const root=await mkdtemp(join(tmpdir(),"vol-precompute-")),cache=join(root,"cache"),tape=join(root,LOCAL_OPTION_TAPE_DIRECTORY),aux=join(root,LOCAL_AUX_DIRECTORY);await mkdir(tape,{recursive:true});await mkdir(aux,{recursive:true});const fingerprint="a".repeat(64);await writeFile(join(tape,LOCAL_ARCHIVE_MANIFEST),JSON.stringify({source:LOCAL_ARCHIVE_SOURCE,data_content_fingerprint:fingerprint,coverage_start:new Date(T0).toISOString(),coverage_end:new Date(T0+2*HOUR).toISOString()}));await writeFile(join(aux,LOCAL_SOURCE_MANIFEST),JSON.stringify({generatedAtUtc:new Date(0).toISOString(),archive:{fingerprint},optionTradeNetworkRequests:0}));await writeFile(join(aux,LOCAL_INSTRUMENT_MANIFEST),JSON.stringify(instruments));await writeFile(join(tape,"2024-01-02.jsonl"),trades.map(t=>JSON.stringify({...t,strike:instruments.find(x=>x.instrumentName===t.instrumentName)!.strike,optionType:instruments.find(x=>x.instrumentName===t.instrumentName)!.optionType,expiryTimestampMs:instruments.find(x=>x.instrumentName===t.instrumentName)!.expiryTimestampMs,contractCreatedAtMs:T0-86_400_000,settlementPeriod:"week"})).join("\n")+"\n");return{root,cache}}

test("local precompute opens a shard once, checkpoints canonical rows, and unchanged rerun streams no tape",async()=>{const f=await fixture(),first=await precomputeLocalVolatility({dataRoot:f.root,cacheRoot:f.cache,generatedAtUtc:"2024-02-01T00:00:00.000Z"});assert.deepEqual({processed:first.targetsProcessed,reused:first.targetsReused,rows:first.rowsWritten,opened:first.diagnostics.dayShardsOpened,streamed:first.diagnostics.rowsStreamed,produced:first.diagnostics.hourlyTargetsProduced},{processed:3,reused:0,rows:9,opened:2,streamed:trades.length,produced:3});const second=await precomputeLocalVolatility({dataRoot:f.root,cacheRoot:f.cache,generatedAtUtc:"2024-02-01T00:00:00.000Z"});assert.equal(second.targetsProcessed,0);assert.equal(second.targetsReused,3);assert.deepEqual(second.diagnostics,{dayShardsOpened:0,rowsStreamed:0,hourlyTargetsProduced:0});const manifest=JSON.parse(await readFile(join(f.cache,REFERENCE_SERIES_ID,LOCAL_PRECOMPUTE_MANIFEST),"utf8"));assert.equal(manifest.archiveFingerprint,"a".repeat(64));assert.equal(manifest.hourlyTargetsAttempted,3)});

test("non-append fingerprint changes are rejected explicitly",async()=>{const f=await fixture();await precomputeLocalVolatility({dataRoot:f.root,cacheRoot:f.cache});const path=join(f.root,LOCAL_OPTION_TAPE_DIRECTORY,LOCAL_ARCHIVE_MANIFEST),archive=JSON.parse(await readFile(path,"utf8"));archive.data_content_fingerprint="b".repeat(64);archive.coverage_start=new Date(T0+HOUR).toISOString();await writeFile(path,JSON.stringify(archive));const sourcePath=join(f.root,LOCAL_AUX_DIRECTORY,LOCAL_SOURCE_MANIFEST),source=JSON.parse(await readFile(sourcePath,"utf8"));source.archive.fingerprint=archive.data_content_fingerprint;await writeFile(sourcePath,JSON.stringify(source));await assert.rejects(precomputeLocalVolatility({dataRoot:f.root,cacheRoot:f.cache}),/fingerprint changed non-append-only/)});
