import test from "node:test";import assert from "node:assert/strict";import {mkdtemp,mkdir,readFile,writeFile} from "node:fs/promises";import {tmpdir} from "node:os";import {join} from "node:path";
import {buildCalibrationObservation,CALIBRATION_EVIDENCE_CONTEXT_MINUTES,CausalFeatureIndex} from "../app/lib/execution-calibration.ts";
import {buildLocalCalibrationRange} from "../scripts/build-execution-calibration-local-range.ts";
import {indexLocalContractArchive,LOCAL_ARCHIVE_MANIFEST,LOCAL_ARCHIVE_SOURCE,parseLocalContractRow,readLocalDay} from "../scripts/local-contract-archive.ts";
const supplied={trade_seq:6,trade_id:"70764236",timestamp:1585710393658,tick_direction:0,price:.017,mark_price:.0167255,iv:89.69,instrument_name:"BTC-1APR20-6250-C",index_price:6339.13,direction:"buy",amount:1.4};
test("maps supplied fields and Deribit call/put identity at 08:00 UTC",()=>{const call=parseLocalContractRow(supplied)!;assert.deepEqual({id:call.tradeId,seq:call.tradeSeq,ts:call.timestampMs,strike:call.strike,type:call.optionType,expiry:call.expiryTimestampMs,created:call.contractCreatedAtMs},{id:"70764236",seq:6,ts:1585710393658,strike:6250,type:"C",expiry:Date.parse("2020-04-01T08:00:00Z"),created:null});assert.equal(call.ivApiPercent,89.69);assert.equal(call.markPrice,.0167255);assert.equal(parseLocalContractRow({...supplied,instrument_name:"BTC-25DEC20-5000-P"})!.optionType,"P")});
test("indexes sorted day shards, malformed rows, and duplicates",async()=>{const root=await mkdtemp(join(tmpdir(),"contracts-")),out=await mkdtemp(join(tmpdir(),"tape-"));await mkdir(join(root,"nested"));const later={...supplied,trade_id:"b",timestamp:1585710493658,direction:"sell"},earlier={...supplied,trade_id:"a",timestamp:1585710293658};await writeFile(join(root,"nested","one.jsonl"),[JSON.stringify(later),"bad json",JSON.stringify(earlier),JSON.stringify(earlier)].join("\n"));const manifest=await indexLocalContractArchive(root,out),rows=await readLocalDay(out,"2020-04-01");assert.equal(manifest.raw_trade_rows,4);assert.equal(manifest.malformed_rows,1);assert.equal(manifest.malformed_files,1);assert.equal(manifest.duplicate_rows,1);assert.equal(manifest.accepted_rows,2);assert.deepEqual(rows.map(r=>r.tradeId),["a","b"]);assert.match(manifest.data_content_fingerprint,/^[a-f0-9]{64}$/);assert.equal(JSON.parse(await readFile(join(out,LOCAL_ARCHIVE_MANIFEST),"utf8")).source,LOCAL_ARCHIVE_SOURCE)});
test("conflicting duplicate IDs fail loudly after audit",async()=>{const root=await mkdtemp(join(tmpdir(),"contracts-conflict-")),out=await mkdtemp(join(tmpdir(),"tape-conflict-"));await writeFile(join(root,"x.jsonl"),JSON.stringify(supplied)+"\n"+JSON.stringify({...supplied,price:.02})+"\n");await assert.rejects(indexLocalContractArchive(root,out),/conflicting duplicate/);assert.equal(JSON.parse(await readFile(join(out,LOCAL_ARCHIVE_MANIFEST),"utf8")).conflicting_duplicates,1)});
test("local range supplies prior-day context and delegates observation construction",async()=>{const tape=await mkdtemp(join(tmpdir(),"local-range-")),output=await mkdtemp(join(tmpdir(),"local-output-")),targetTs=Date.parse("2024-01-02T00:01:00Z"),expiry=Date.parse("2024-01-12T08:00:00Z"),base={timestampMs:targetTs-60_000,expiryTimestampMs:expiry,contractCreatedAtMs:null,settlementPeriod:null,optionType:"C" as const,indexPrice:40_000,price:.02,markPrice:.02,amount:1,direction:"buy",tickDirection:0,ivApiPercent:50};const evidence=[38_000,39_000,40_000,41_000,42_000].map((strike,i)=>({...base,instrumentName:`BTC-12JAN24-${strike}-C`,strike,tradeId:`e${i}`,timestampMs:targetTs-120_000-i})),target={...base,instrumentName:"BTC-12JAN24-40500-C",strike:40_500,tradeId:"target",timestampMs:targetTs};await writeFile(join(tape,"2024-01-01.jsonl"),evidence.map(x=>JSON.stringify(x)).join("\n")+"\n");await writeFile(join(tape,"2024-01-02.jsonl"),JSON.stringify(target)+"\n");await writeFile(join(tape,LOCAL_ARCHIVE_MANIFEST),JSON.stringify({data_content_fingerprint:"abc",coverage_start:"2024-01-01T00:00:00.000Z"}));const manifest=await buildLocalCalibrationRange(tape,"2024-01-02","2024-01-03",output),rows=(await readFile(manifest.shards[0]!.file,"utf8")).trim().split("\n").map(JSON.parse),all=[...evidence,target],expected=buildCalibrationObservation({target,tape:all,features:new CausalFeatureIndex(all).features(target),sourceHost:LOCAL_ARCHIVE_SOURCE,retrievalShardId:manifest.shards[0]!.id,retrievalContentHash:"abc",sourceWindowComplete:true,directionSemanticsVerified:true});assert.equal(CALIBRATION_EVIDENCE_CONTEXT_MINUTES,720);assert.deepEqual(rows,[expected]);assert.equal(rows[0].features.same_expiry_count_60m,5)});
