import test from "node:test";
import assert from "node:assert/strict";
import { buildExecutionCalibrationRecords, buildModeledExecution, MODELED_EXECUTION_VERSION } from "../app/lib/modeled-execution.ts";
import type { ResearchSelectionStore } from "../app/lib/research-selections.ts";
const rec=(v:unknown)=>v as Record<string,unknown>;
const entry=(time:number,gross=.1)=>({targetTimestamp:time,valuationTimestamp:time,amount:1,sold:{priceBtcPerContract:.12},bought:{priceBtcPerContract:.02},grossSpreadBtcPerContract:gross,grossSpreadBtc:gross,openingFeesBtc:.0006,netOpeningCashFlowBtc:gross-.0006});
const reference=(time:number)=>({status:"valued",source:"same-expiry-interpolation",entrySnapshot:entry(time),valuationPathSnapshot:[{timestamp:time+1,valuationTimestamp:time+1,closingSpreadValueBtc:-.04,closingFeesBtc:.0004,estimatedNetPnlBtc:.059}],outcomeSnapshots:[{label:"50% credit",valuationTimestamp:time+1,estimatedNetPnlBtc:.059}],provenance:{quality:"B",expiryTimestamp:time+10}});
test("under-calibrated canonical model keeps expected unavailable and exposes action-aware 0/50/100/250/500 grid",()=>{const x=rec(buildModeledExecution(reference(1000)));assert.equal(rec(x.expected).status,"unavailable");assert.equal(rec(x.expected).modelVersion,MODELED_EXECUTION_VERSION);assert.equal(rec(x.conservative).status,"unavailable");assert.deepEqual((rec(x.penaltySensitivity).grid as Array<Record<string,unknown>>).map(r=>r.penaltyBps),[0,50,100,250,500]);assert.match(String(rec(x.conservative).reason),/no 500 bp substitution/)});
test("legacy selected-structure rows never promote empirical tracks",()=>{const x=rec(buildModeledExecution(reference(1000)));assert.equal(rec(x.expected).status,"unavailable");assert.equal(rec(x.conservative).status,"unavailable")});
test("calibration is scenario-separated, timestamp-matched and deduplicated per completed execution",()=>{const t=200;const structure={candidateId:"c",eventId:"e",quantity:1,candidateSnapshot:{optionType:"P",actualWidth:10},referenceValuation:{...reference(100),valuationPathSnapshot:[{timestamp:t,valuationTimestamp:t,grossSpreadBtc:.08}]},executionScenarios:{maker:{status:"evaluated",entrySnapshot:{...entry(t,.07),evidenceCompletionTimestamp:t}},taker:{status:"unavailable"}},delayedExecution:{maker:{status:"evaluated",entrySnapshot:{...entry(t,.07),evidenceCompletionTimestamp:t,rawPrintIds:["a","b"]}},taker:{status:"evaluated",entrySnapshot:{...entry(t,.06),evidenceCompletionTimestamp:t}}}};const store={events:[{eventId:"e",selectedStructures:[structure]}]} as unknown as ResearchSelectionStore;const rows=buildExecutionCalibrationRecords(store);assert.equal(rows.length,3);assert.equal(rows.filter(r=>r.scenario==="maker").length,2);assert.ok(rows.every(r=>r.referenceTimestamp===r.observedTimestamp));assert.ok(rows.every(r=>r.fairCredit===.08));});
test("missing reference and non-economic credits are explicitly unavailable, never observed",()=>{const missing=rec(buildModeledExecution({status:"unavailable"}));assert.equal(rec(missing.conservative).status,"unavailable");const tiny=rec(buildModeledExecution({...reference(1),entrySnapshot:entry(1,.00001)}));assert.equal(tiny.conservative.source,"modeled_execution");assert.notEqual(tiny.conservative.status,"observed")});
test("valued Reference provenance drives expected and conservative empirical BUY/SELL execution",()=>{
 const time=1_700_000_000_000,expiry=time+10*864e5,index=40_000,forward=40_200;
 const model=(strike:number,iv:number)=>({instrument:`BTC-${strike}-C`,strike,optionType:"C",expiryTimestamp:expiry,anchorTimestamp:time-60_000,anchorTradeId:null,anchorDirection:"model-reconstructed",anchorAgeMinutes:1,anchorIvApiPercent:iv*100,anchorIvDecimal:iv,anchorIndex:index,targetIndex:index,dte:10,forwardPrice:forward,forwardMethodVersion:"option-trade-implied-forward-v1",forwardEvidenceTimestamp:time-60_000,rate:0,forwardRateAssumption:"causal",modelPriceBtc:.1,modelName:"fixture"});
 const valued={...reference(time),provenance:{quality:"B",expiryTimestamp:expiry},entrySnapshot:{...entry(time),sold:{priceBtcPerContract:.12,model:model(39_000,.6)},bought:{priceBtcPerContract:.02,model:model(41_000,.58)}}};
 const actions:string[]=[];const provider=(referenceQ90:number,executionQ90=2)=>({execution:(q:{action:string})=>{actions.push(q.action);return{dteBand:"7-14",amountBand:"small",fallbackLevel:"action_dte_amount",tradeCount:500,calendarDayCount:20,expiryDayGroupCount:20,q50VolPoints:1,q90VolPoints:executionQ90}},reference:()=>({dteBand:"7-14",fallbackLevel:"dte",tradeCount:500,calendarDayCount:20,expiryDayGroupCount:20,q90VolPoints:referenceQ90}),artifact:{tradeCount:7_705_061,sourceDatasetFingerprint:"fixture",artifactHash:"fixture",coverageStartMs:1,coverageEndMs:time-1}});
 const result=rec(buildModeledExecution(valued,provider(50) as never));
 assert.equal(rec(result.expected).status,"evaluated");assert.equal(rec(result.conservative).status,"evaluated");
 assert.deepEqual(actions,["sell","buy","sell","buy"],"sold remains SELL and bought remains BUY in both tracks");
 const expected=rec(rec(result.expected).entrySnapshot),sold=rec(expected.sold),bought=rec(expected.bought);
 assert.ok(Number(sold.priceBtcPerContract)<.12);assert.ok(Number(bought.priceBtcPerContract)>.02);
 const expectedLegs=rec(result.expected).provenance as Record<string,unknown>,conservativeLegs=rec(result.conservative).provenance as Record<string,unknown>;
 assert.deepEqual((expectedLegs.legs as Array<Record<string,unknown>>).map(x=>x.appliedAdjustmentVolPoints),[1,1],"expected applies Q50 execution only");
 assert.deepEqual((conservativeLegs.legs as Array<Record<string,unknown>>).map(x=>x.appliedAdjustmentVolPoints),[2,2],"conservative applies Q90 execution only");
 assert.deepEqual((conservativeLegs.legs as Array<Record<string,unknown>>).map(x=>x.q90ReferenceUncertaintyVolPoints),[50,50],"Reference Q90 remains a separate diagnostic");
 assert.match(String(conservativeLegs.description),/not a joint spread P90/);
 const lowReference=rec(buildModeledExecution(valued,provider(0) as never));
 assert.deepEqual(rec(rec(lowReference.expected).entrySnapshot),rec(rec(result.expected).entrySnapshot),"Reference Q90 cannot alter expected prices");
 assert.deepEqual(rec(rec(lowReference.conservative).entrySnapshot),rec(rec(result.conservative).entrySnapshot),"Reference Q90 cannot alter conservative prices");
 assert.equal(rec(result.conservative).status,"evaluated","the old 2 + 50 vol-point construction destroyed this credit, while execution Q90 alone is economic");
 const uneconomic=rec(buildModeledExecution(valued,provider(0,50) as never));
 assert.equal(rec(uneconomic.conservative).status,"unavailable");
 assert.match(String(rec(uneconomic.conservative).reason),/nonpositive credit after authoritative fees/);
});
