import test from "node:test";import assert from "node:assert/strict";
import {analyzePortfolioAndSelectStrategy,DEFAULT_ANALYSIS_CONFIGURATION,type AnalysisConfiguration} from "../app/lib/portfolio-strategy-analysis.ts";
const T=Date.parse("2026-01-01T00:00:00Z"),iso=(h:number)=>new Date(T+h*36e5).toISOString();
const candidate=(id:string,event:string,entry:number)=>({candidate_id:id,event_id:event,valuation_timestamp_utc:iso(entry),expiry_timestamp_utc:iso(240),actual_expiry_timestamp_utc:iso(240),actual_dte_hours:240,actual_width:1000,actual_strikes:{short:100000,long:101000,width:1000},strike_method:"technical",structure_type:"call_credit_spread",option_type:"C",quantity:1,entry_index_price:90000,opening_fees_native:.0002,gross_credit_debit_native:.01,net_opening_cash_flow_native:.0098,entry_legs:{short:{price_native:.02},long:{price_native:.01}},execution_mode:"taker",quality_level:"green"});
const config:AnalysisConfiguration={...DEFAULT_ANALYSIS_CONFIGURATION,pricingTrack:"raw_vwap",executionAssumption:"taker",includedQualityLevels:["green"],exitPolicy:"thesis",trainingEndTimestampUtc:iso(5),accountEquity:100,maximumRiskPerTrade:.01,maximumMarginUtilization:.5,dteMinimumDays:1,dteMaximumDays:30,maximumTailLossRiskUnits:10,maximumDrawdown:1,minimumCellEvents:1};
function data(withMargin=true){const cs=[candidate("a","e1",1),candidate("b","e2",2),candidate("c","e3",8)];return{run:{valuation_methodology_version:"v1"},eventUniverseComplete:true,tables:{candidates:cs,events:[{event_id:"e1",direction:"short"},{event_id:"e2",direction:"long"},{event_id:"e3",direction:"short"},{event_id:"e4",direction:"short"}],availability:[...cs.map(c=>({event_id:c.event_id,candidate_id:c.candidate_id})),{event_id:"e4",candidate_id:"none"}],underlying_path:[],valuations:[],outcomes:cs.map((c,i)=>({candidate_id:c.candidate_id,outcome_type:"vpoc",decision_available_timestamp_utc:iso(i<2?6:10),valuation_timestamp_utc:iso(i<2?6:10),pricing_track:"raw_vwap",outcome_status:"priced",net_pnl_native:i===1?-.001:.002})),margin_scenarios:withMargin?cs.map(c=>({candidate_id:c.candidate_id,margin_status:"available",incremental_initial_margin:.01})):[]}}}
test("configuration blocks ranking and is embedded in PDF metadata",()=>{const r=analyzePortfolioAndSelectStrategy(data(),DEFAULT_ANALYSIS_CONFIGURATION);assert.equal(r.configured,false);assert.equal(r.selection.bestStrategy,null);assert.deepEqual(r.pdfMetadata.analysisConfiguration,r.configuration)});
test("reconstruction preserves overlaps, no-trade zeros, sizing, and chronology",()=>{const r=analyzePortfolioAndSelectStrategy(data(),config);assert.equal(r.portfolio.positions.length,3);assert.equal(r.portfolio.timeline[1].concurrentPositions,2);assert.equal(r.portfolio.noTradeOpportunities,1);assert.ok(r.portfolio.positions.every(x=>x.quantity>0));assert.deepEqual(r.portfolio.positions.map(x=>x.cohort),["training","training","validation"])});
test("margin and futures unavailability are explicit",()=>{const r=analyzePortfolioAndSelectStrategy(data(false),config);assert.equal(r.portfolio.marginUtilizationAvailable,false);assert.equal(r.portfolio.timeline[0].openingMargin,null);assert.equal(r.futures.status,"blocked");assert.match(r.futures.explanation,/Spot\/index candles/)});
test("six matrices use event counts and sparse suppression",()=>{const r=analyzePortfolioAndSelectStrategy(data(),{...config,minimumCellEvents:4});assert.equal(r.matrices.length,6);const cell=r.matrices[0].cells[0];assert.equal(cell.eventN,3);assert.equal(cell.candidateN,3);assert.equal(cell.status,"sparse");assert.ok(cell.confidenceInterval)});
test("failed constraint prevents best-strategy output",()=>{const r=analyzePortfolioAndSelectStrategy(data(),{...config,maximumDrawdown:0});assert.equal(r.selection.bestStrategy,null);assert.ok(r.selection.failedConstraints.includes("Maximum portfolio drawdown"))});
