/* eslint-disable @typescript-eslint/no-explicit-any -- adversarial mutation harness intentionally edits decoded JSON */
import test from "node:test";import assert from "node:assert/strict";
import {mkdtemp,writeFile} from "node:fs/promises";import {tmpdir} from "node:os";import {join} from "node:path";
import type {ResearchSelectionStore} from "../app/lib/research-selections.ts";
import {buildResearchBundle,RESEARCH_BUNDLE_FILES,REQUIRED_OUTCOMES,validateResearchBundle} from "../app/lib/research-bundle.ts";
import {ResearchSelectionService} from "../scripts/research-selection-service.ts";import {createResearchBundleZip} from "../scripts/research-bundle-service.ts";
const now="2026-08-16T00:00:00.000Z",ts=Date.parse(now),config={applicationBuild:"120adbb",pricingEngineVersion:"v1",qualityRulesVersion:"q1",feeScheduleVersion:"f1",dteWindows:{},expirySelectionMode:"all",executionMode:"taker",pricingAssumption:"research-estimate",pricingTracks:["vwap","iv"],historicalEvidenceWindows:{},synchronizationThresholds:{},qualityThresholds:{},feeAssumptions:{},settlementRules:{},valuationInterval:"4h",modelAssumptions:{},generatedAtUtc:now};
const cand=(id:string,status="priced")=>({candidateId:`deribit~${id}`,venue:"deribit" as const,selected:id<"d",status:status as "priced"|"unavailable",availabilityReasons:status==="priced"?[]:["missing"],targetHorizon:id==="red"||id==="u2"?14:7,eligibleDteRange:{min:5,max:10},actualExpiryTimestamp:ts+7*864e5,actualDte:7,requestedStrikes:{short:100,long:id==="red"||id==="u2"?80:90,width:id==="red"||id==="u2"?20:10},actualStrikes:{short:100,long:id==="red"||id==="u2"?80:90,width:id==="red"||id==="u2"?20:10},structure:"credit",optionType:"P",strikeMethod:"anchor",entryQuality:status==="priced"?"red" as const:null});
const sel=(eventId:string,id:string)=>({selectionId:`selection~${id}`,eventId,candidateId:`deribit~${id}`,venue:"deribit" as const,selectedAtUtc:now,quantity:1,candidateSnapshot:{structure:"credit",optionType:"P",expiryTimestamp:ts+7*864e5,shortStrike:100,longStrike:90,actualWidth:10,targetDte:id==="red"?14:7,actualDte:7,strikeMethod:"anchor"},entrySnapshot:{status:"priced",targetTimestamp:ts,entryTargetIndex:100,estimateQuality:"red",priceSource:"direct-vwap",sold:{priceBtcPerContract:.02},bought:{priceBtcPerContract:.01},openingFeesBtc:.001,netOpeningCashFlowBtc:.009},valuationPathSnapshot:[{timestamp:ts,status:"priced",targetIndex:100,rawEstimate:{sold:{priceBtcPerContract:.02},bought:{priceBtcPerContract:.01}},modelEstimate:{sold:{priceBtcPerContract:.02},bought:{priceBtcPerContract:.01}},closingFeesBtc:.001,estimatedNetPnlBtc:.008,estimateQuality:"red"},{timestamp:ts+144e5,status:"missing",unavailableReason:"missing-target-index",missingField:"targetIndex",estimateQuality:"unavailable"}],outcomeSnapshots:[{label:"VPOC",status:"estimated",decisionTimestamp:ts+864e5,valuationTimestamp:ts+864e5,estimatedNetPnlBtc:.004,conversionIndex:101},{label:"Settlement",status:"estimated",decisionTimestamp:ts+7*864e5,valuationTimestamp:ts+7*864e5,estimatedNetPnlBtc:.006,conversionIndex:102}],marginSnapshot:{},evidenceTradeSnapshots:[{instrumentName:"BTC-X",tradeId:"t1",timestamp:ts,price:.02,amount:1,indexPrice:100}]});
const store:ResearchSelectionStore={schemaVersion:"1.0.0",datasetId:"acceptance",updatedAtUtc:now,events:[{eventId:"e1",sourceRun:{event:{id:"e1",direction:"long",entryDate:"2026-08-16",entryTimestamp:ts,entryPrice:100}},generationSnapshot:{generatedAtUtc:now,configuration:config,candidates:[cand("a"),cand("b"),cand("u"),cand("z","unavailable")],underlyingHourlyPath:[{openTime:ts,closeTime:ts+36e5,open:100,high:101,low:99,close:100,volume:1}]},selectedStructures:[sel("e1","a"),sel("e1","b")]},{eventId:"e2",sourceRun:{event:{id:"e2",direction:"short",entryDate:"2026-08-16",entryTimestamp:ts,entryPrice:100}},generationSnapshot:{generatedAtUtc:now,configuration:{...config,pricingEngineVersion:"v2"},candidates:[cand("c"),cand("red"),cand("u2")],underlyingHourlyPath:[]},selectedStructures:[sel("e2","c"),sel("e2","red")]}]};
test("canonical persisted bundle semantics",()=>{const b=buildResearchBundle(structuredClone(store),now);assert.deepEqual(Object.keys(b.files),RESEARCH_BUNDLE_FILES);for(const [n,text] of Object.entries(b.files))if(n.endsWith("jsonl"))for(const line of text.trim().split("\n").filter(Boolean))assert.doesNotThrow(()=>JSON.parse(line));const c=b.files["candidates.jsonl"].trim().split("\n").map(JSON.parse),a=b.files["availability.jsonl"].trim().split("\n").map(JSON.parse),v=b.files["valuations.jsonl"].trim().split("\n").map(JSON.parse),o=b.files["outcomes.jsonl"].trim().split("\n").map(JSON.parse);assert.equal(c.length,4);assert.equal(a.length,7);assert.ok(!c.some(x=>x.candidate_id.includes("~u")));assert.ok(a.some(x=>x.status==="unavailable"));assert.ok(c.every(x=>x.venue==="deribit"&&x.native_currency==="BTC"));assert.equal(new Set(o.map(x=>x.outcome_type)).size,REQUIRED_OUTCOMES.length);assert.deepEqual(new Set(v.map(x=>x.pricing_track)),new Set(["raw_vwap","iv_normalized"]));assert.ok(v.some(x=>x.valuation_status==="unavailable"&&x.net_pnl_native===null));assert.equal(b.run.selected_structure_count,4);assert.equal(b.run.generated_denominator_count,7);assert.equal(validateResearchBundle(b.files).ok,true);assert.match(b.files["margin_scenarios.jsonl"],/verified_historical_margin_model_unavailable/);assert.match(b.files["futures_comparisons.jsonl"],/verified_futures_series_unavailable/);assert.match(b.files["evidence_trades.jsonl"],/"trade_id":"t1"/)});
test("validator rejects broken joins and versions",()=>{const b=buildResearchBundle(store,now);assert.equal(validateResearchBundle({...b.files,"candidates.jsonl":b.files["candidates.jsonl"].replace('"event_id":"e1"','"event_id":"gone"')}).ok,false);assert.equal(validateResearchBundle({...b.files,"run.json":b.files["run.json"].replace('"1.0.0"','"9.0.0"')}).ok,false)});
test("validator adversarial rejection matrix",()=>{const base=buildResearchBundle(store,now).files,mutate=(file:string,fn:(rows:any[])=>void)=>{const copy={...base},rows=file==="run.json"?[JSON.parse(copy[file])]:copy[file].trim().split("\n").map(JSON.parse);fn(rows);copy[file]=file==="run.json"?JSON.stringify(rows[0])+"\n":rows.map(JSON.stringify).join("\n")+"\n";return validateResearchBundle(copy)};
 const cases:[string,ReturnType<typeof validateResearchBundle>][]=[
  ["duplicate primary ID",mutate("candidates.jsonl",r=>r.push(structuredClone(r[0])))],
  ["broken foreign key",mutate("valuations.jsonl",r=>r[0].candidate_id="gone")],
  ["candidate absent from saved selections",mutate("availability.jsonl",r=>r.find(x=>x.is_selected).is_selected=false)],
  ["selected absent from availability",mutate("availability.jsonl",r=>r.splice(r.findIndex(x=>x.is_selected),1))],
  ["missing venue",mutate("events.jsonl",r=>delete r[0].venue)],
  ["venue currency contradiction",mutate("candidates.jsonl",r=>r[0].premium_currency="USDC")],
  ["nonfinite JSON",validateResearchBundle({...base,"valuations.jsonl":base["valuations.jsonl"].replace('"elapsed_hours":0','"elapsed_hours":NaN')})],
  ["timestamp out of bounds",mutate("valuations.jsonl",r=>r[0].timestamp_utc="2099-01-01T00:00:00.000Z")],
  ["missing outcome",mutate("outcomes.jsonl",r=>r.splice(r.findIndex(x=>x.outcome_type==="settlement"),1))],
  ["unknown status",mutate("valuations.jsonl",r=>r[0].valuation_status="invented")],
  ["unknown reason",mutate("valuations.jsonl",r=>r[0].reason_codes=["NOT_A_CODE"])],
  ["missing pricing track",mutate("valuations.jsonl",r=>{for(let i=r.length-1;i>=0;i--)if(r[i].candidate_id===r[0].candidate_id&&r[i].pricing_track==="raw_vwap")r.splice(i,1)})],
  ["unreconciled total",mutate("valuations.jsonl",r=>{const x=r.find(x=>x.net_pnl_usd!==null);x.net_pnl_usd+=1})],
  ["flattened source run",mutate("events.jsonl",r=>r[0].source_run_id="deribit~source~invented")],
  ["unknown version",mutate("run.json",r=>r[0].schema_version="2.0.0")],
 ];for(const [label,result] of cases)assert.equal(result.ok,false,label);
});
test("schema represents a hypothetical Bybit linear-USDC option without BTC premiums",()=>{const files=structuredClone(buildResearchBundle(store,now).files);for(const name of RESEARCH_BUNDLE_FILES.filter(n=>n.endsWith(".jsonl"))){const rows=files[name].trim().split("\n").filter(Boolean).map(JSON.parse);for(const r of rows)if(r.candidate_id==="deribit~a"||r.event_id==="e1"){r.venue="bybit";if(r.candidate_id==="deribit~a"){r.contract_style="linear";r.native_currency="USDC";r.premium_currency="USDC";r.settlement_currency="USDC";r.quote_currency="USD";r.contract_multiplier=1}}files[name]=rows.map(JSON.stringify).join("\n")+(rows.length?"\n":"")}const run=JSON.parse(files["run.json"]);run.venues=["bybit","deribit"];run.source_runs.filter((x:any)=>x.event_id==="e1").forEach((x:any)=>x.venue="bybit");files["run.json"]=JSON.stringify(run)+"\n";assert.doesNotMatch(files["candidates.jsonl"].split("\n").find(x=>x.includes('"candidate_id":"deribit~a"'))!,/"premium_currency":"BTC"/);assert.equal(validateResearchBundle(files).ok,true)});
test("live acceptance: persistence restart, selected-only ZIP, inspection, and reconciliation",async()=>{const dir=await mkdtemp(join(tmpdir(),"bundle-live-"));let service=new ResearchSelectionService(dir);await service.save(store.datasetId,store);service=new ResearchSelectionService(dir);const restored=await service.read(store.datasetId);assert.deepEqual(restored.events.map(e=>e.selectedStructures.length),[2,2]);const bundle=buildResearchBundle(restored,now),zip=createResearchBundleZip(bundle.files),artifact=join(dir,"acceptance-research-bundle.zip");await writeFile(artifact,zip);assert.equal(zip.subarray(0,4).toString("hex"),"504b0304");assert.equal(validateResearchBundle(bundle.files).ok,true);const count=(name:string)=>bundle.files[name].trim().split("\n").filter(Boolean).length;assert.deepEqual({events:count("events.jsonl"),candidates:count("candidates.jsonl"),availability:count("availability.jsonl"),valuations:count("valuations.jsonl"),outcomes:count("outcomes.jsonl"),margins:count("margin_scenarios.jsonl"),evidence:count("evidence_trades.jsonl")},{events:2,candidates:4,availability:7,valuations:16,outcomes:40,margins:4,evidence:4});assert.equal(bundle.run.selected_structure_count,count("candidates.jsonl"));assert.equal(bundle.run.generated_denominator_count,count("availability.jsonl"));});
