import test from "node:test";
import assert from "node:assert/strict";
import type {PositionEconomics} from "../app/lib/economics/position.ts";
import {buildMatchedComparisons,type ResearchEconomicOpportunity} from "../app/lib/research-economics/matched-comparisons.ts";
import {eventValues,median,statistic} from "../app/lib/research-economics/statistics.ts";
const avail=(value:number|null)=>({value,reason:value===null?"missing":null});
const p=(eventId:string,id:string,pnl:number|null,fees:number|null=pnl):PositionEconomics=>({eventId,structuralConfigurationId:id,status:"priced",pnlBtc:pnl,pnlUsd:pnl===null?null:pnl*100,grossOpeningCreditBtc:.1,grossOpeningCreditUsd:avail(10),netOpeningCashFlowBtc:.09,netOpeningCashFlowUsd:avail(9),openingFeesBtc:.01,openingFeesUsd:avail(1),totalRealizedFeesBtc:fees,totalRealizedFeesUsd:avail(fees===null?null:fees*100),incrementalInitialMarginBtc:avail(1),incrementalInitialMarginUsd:avail(100),peakInitialMarginBtc:avail(2),peakInitialMarginUsd:avail(200),maximumStructuralLossBtc:avail(3),maximumStructuralLossUsd:avail(300),trackMaximumNetLossBtc:avail(3),trackMaximumNetLossUsd:avail(300),capitalDaysBtc:avail(4),capitalDaysUsd:avail(400),holdingDays:2,returnOnPeakCapital:avail(pnl===null?null:pnl/2),returnOnTrackMaximumNetLoss:avail(pnl===null?null:pnl/3)} as PositionEconomics);
const o=(eventId:string,id:string,dte:number,width:number,strike="anchor"):ResearchEconomicOpportunity=>({eventId,structuralConfigurationId:id,structuralConfiguration:{targetDteFamilyDays:dte,requestedWidth:width,strikeMethod:strike,structureFamily:"credit_vertical"},candidateId:id,q50GenerationStatus:"trade",q50ReasonCode:null,q50Reason:null,integrityReason:null});
test("mathematical median averages the even middle pair",()=>assert.equal(median([1,3,10,20]),6.5));
test("event aggregation gives multiple variants one event vote",()=>{const values=eventValues([p("one","a",0),p("one","b",1),p("two","c",1)],"pnl","btc");assert.equal(values.size,2);assert.equal(median([...values.values()]),.75)});
test("descriptive statistics retain metric-specific eligible, effective and missing event N",()=>{const rows=[p("a","a",1,1),p("b","b",2,2),p("c","c",3,null)],events=new Set(["a","b","c","d"]);assert.deepEqual(statistic(events,rows,"pnl","btc"),{value:2,effectiveEventN:3,eligibleEventN:4,missingEventN:1,status:"partial",reason:"Partial · metric events 3 / eligible events 4."});assert.equal(statistic(events,rows,"totalFees","btc").effectiveEventN,2)});
test("controlled pair universe starts from opportunities and metric N starts from both-valued evidence",()=>{const opportunities=[o("e1","7",7,1000),o("e1","14",14,1000),o("e2","7b",7,1000),o("e2","14b",14,1000)],positions=[p("e1","7",1),p("e1","14",5),p("e2","7b",2)];const result=buildMatchedComparisons(opportunities,positions,"dte")[0]!;assert.equal(result.eligiblePairUniverseN,2);assert.equal(result.pricedBothN,1);assert.equal(result.sourceOnlyEvidenceN,1);assert.equal(result.metrics.pnl.btc.effectivePairedN,1);assert.equal(result.metrics.pnl.btc.missingPairedN,1);assert.equal(result.metrics.pnl.btc.medianDelta,4)});
test("matching holds non-varied dimensions and diagnoses duplicate identities",()=>{const opportunities=[o("e","a",7,1000),o("e","b",14,1000),o("e","c",14,2000),o("e","dup",14,1000)],result=buildMatchedComparisons(opportunities,[],"dte").find(x=>x.source===7&&x.destination===14)!;assert.equal(result.eligiblePairUniverseN,0);assert.equal(result.missingReasons["duplicate canonical opportunity identity"],1)});

test("grouped execution reports directional coverage changes and category-specific degradation",async()=>{const {buildExecutionSurvival}=await import("../app/lib/research-economics/report.ts"),opportunities=[o("a","a7",7,1000),o("b","b7",7,1000),o("c","c30",30,2000),o("d","d30",30,2000)],reference=[p("a","a7",1),p("c","c30",10)],q50=[p("b","b7",2),p("c","c30",20),p("d","d30",30)],q90=[p("b","b7",3),p("c","c30",25),p("d","d30",50)],report=buildExecutionSurvival(opportunities,{reference,modeled_expected:q50,modeled_conservative:q90}),dte7=report.groups.find(x=>x.dimension==="dte"&&x.category===7)!,dte30=report.groups.find(x=>x.dimension==="dte"&&x.category===30)!,rq7=dte7.comparisons[0]!,qq30=dte30.comparisons[1]!;assert.equal(rq7.sourceOnlyN,1);assert.equal(rq7.destinationOnlyN,1);assert.equal(rq7.netCoverageChange,0);assert.equal(rq7.commonPricedN,0);assert.equal(qq30.commonPricedN,2);assert.equal(qq30.metrics.pnl.btc.medianDelta,12.5);const width=report.groups.find(x=>x.dimension==="width"&&x.category===2000)!;assert.equal(width.comparisons[1]!.metrics.pnl.btc.medianDelta,12.5)});

test("BTC and USD controlled deltas are independent and never synthesized",()=>{const opportunities=[o("e","a",7,1000),o("e","b",14,1000)],a=p("e","a",1),b=p("e","b",3);a.pnlUsd=null;b.pnlUsd=null;const result=buildMatchedComparisons(opportunities,[a,b],"dte")[0]!;assert.equal(result.metrics.pnl.btc.medianDelta,2);assert.equal(result.metrics.pnl.btc.effectivePairedN,1);assert.equal(result.metrics.pnl.usd.medianDelta,null);assert.equal(result.metrics.pnl.usd.effectivePairedN,0)});
