import test from "node:test";
import assert from "node:assert/strict";
import type {PositionEconomics} from "../app/lib/economics/position.ts";
import {buildMatchedComparisons} from "../app/lib/research-economics/matched-comparisons.ts";
import {buildInteractionCells} from "../app/lib/research-economics/report.ts";
import {eventWeightedValues,median} from "../app/lib/research-economics/statistics.ts";

const a=(eventId:string,dte:number,width:number,strike:string,pnl:number|null,fees:number|null=pnl):PositionEconomics=>({eventId,exitPolicy:"thesis",analyticsTrack:"modeled_expected",structuralConfigurationId:`${dte}-${width}-${strike}`,structuralConfiguration:{targetDteFamilyDays:dte,requestedWidth:width,strikeMethod:strike,structureFamily:"credit_vertical"},status:"priced",pnlUsd:pnl,totalRealizedFeesUsd:{value:fees,reason:fees===null?"missing":null},grossOpeningCreditUsd:{value:10,reason:null},netOpeningCashFlowUsd:{value:9,reason:null},openingFeesUsd:{value:1,reason:null},peakInitialMarginUsd:{value:100,reason:null},incrementalInitialMarginUsd:{value:80,reason:null},trackMaximumNetLossUsd:{value:90,reason:null},capitalDaysUsd:{value:200,reason:null},holdingDays:2,returnOnPeakCapital:{value:pnl===null?null:pnl/100,reason:null}} as PositionEconomics);

test("event weighting collapses variants before aggregation",()=>{const values=eventWeightedValues([a("one",7,1000,"delta",0),a("one",7,2000,"delta",100),a("two",7,1000,"delta",100)],"pnlUsd");assert.equal(median(values),75)});
test("one-factor matching holds every other structural field fixed and pairs before aggregation",()=>{const rows=[a("e1",7,1000,"delta",1),a("e1",14,1000,"delta",5),a("e1",14,2000,"delta",100),a("e2",7,1000,"delta",10),a("e2",14,1000,"delta",12),a("e2",14,1000,"otm",500)];const dte=buildMatchedComparisons(rows,"dte").find(x=>x.source===7&&x.destination===14)!;assert.equal(dte.commonPairUniverseN,2);assert.equal(dte.metrics.pnlUsd.medianDelta,3);const width=buildMatchedComparisons(rows,"width").find(x=>x.source===1000&&x.destination===2000)!;assert.equal(width.commonPairUniverseN,1);const strike=buildMatchedComparisons(rows,"strike").find(x=>x.source==="delta"&&x.destination==="otm")!;assert.equal(strike.commonPairUniverseN,1)});
test("each metric gets its own paired N",()=>{const result=buildMatchedComparisons([a("e",7,1000,"delta",1,null),a("e",14,1000,"delta",2,4)],"dte")[0]!;assert.equal(result.metrics.pnlUsd.effectivePairedN,1);assert.equal(result.metrics.totalFeesUsd.effectivePairedN,0);assert.equal(result.metrics.totalFeesUsd.missingN,1)});
test("interaction cells contain observed combinations only",()=>{const result=buildInteractionCells([a("e",7,1000,"delta",1),a("e",14,2000,"delta",2)],"dte_width","delta");assert.deepEqual(result.cells.map(x=>[x.x,x.y]),[[7,1000],[14,2000]]);assert.equal(result.cells.length,2)});
