import test from "node:test";
import assert from "node:assert/strict";
import { buildEstimatedPath, buildResearchExport, buildResearchOutcomes, estimateResearchSpread, scaleResearchEstimate, scaleResearchPath } from "../app/lib/research-valuation.ts";
import { executionClock, simulateTakerSpread, type ContractSeries, type ContractTrade, type RetrievedSpread } from "../app/lib/backtester.ts";
const T=Date.UTC(2024,0,1,12), expiry=T+7*864e5;
function trade(name:string,offsetMin:number,price:number,direction:"buy"|"sell",amount=1,iv=60):ContractTrade{return{instrumentName:name,timestamp:T+offsetMin*60000,price,indexPrice:40000,direction,amount,iv,ivApiPercent:iv,ivDecimal:iv/100};}
function series(name:string,strike:number,trades:ContractTrade[]):ContractSeries{return{instrumentName:name,strike,optionType:"P",expiryTimestamp:expiry,expiryLabel:"08JAN24",trades,firstTradeTimestamp:trades[0]?.timestamp??T,lastTradeTimestamp:trades.at(-1)?.timestamp??T,sourceFiles:[]};}
function spread(sold:ContractTrade[],bought:ContractTrade[]):RetrievedSpread{return{id:"x",targetDte:7,targetWidth:1000,anchorStrike:40000,soldStrike:39000,boughtStrike:38000,optionType:"P",spreadKind:"credit",structure:"39000/38000 P",buffered:false,soldContract:series("BTC-8JAN24-39000-P",39000,sold),boughtContract:series("BTC-8JAN24-38000-P",38000,bought),soldExistedAtEntry:true,boughtExistedAtEntry:true,retrievalStatus:"ready",retrievalNote:"ok",expiryTimestamp:expiry,expiryLabel:"08JAN24",actualWidth:1000};}
test("opposite directions and a pre-signal print price research but cannot fill strict tape",()=>{const s=spread([trade("BTC-8JAN24-39000-P",-10,.08,"buy")],[trade("BTC-8JAN24-38000-P",5,.03,"sell")]);const estimate=estimateResearchSpread({spread:s,targetTimestamp:T,targetIndex:40000,amount:1,slippageBps:10});assert.equal(estimate.status,"priced");if(estimate.status==="priced")assert.equal(estimate.estimateQuality,"green");const strict=simulateTakerSpread(s,executionClock({signalTimestamp:T,signalSourceTimestamp:T,signalTimePrecision:"second",configuredLatencyMs:0,maxFillWaitMs:30*60000}),1,0,60000);assert.equal(strict.status,"no-trade");});
test("smallest common direct window wins and 2h direct beats IV fallback",()=>{const s=spread([trade("BTC-8JAN24-39000-P",20,.08,"sell"),trade("BTC-8JAN24-39000-P",90,.5,"sell")],[trade("BTC-8JAN24-38000-P",25,.03,"buy")]);const e=estimateResearchSpread({spread:s,targetTimestamp:T,targetIndex:40000,slippageBps:0});assert.equal(e.status,"priced");if(e.status==="priced"){assert.equal(e.evidenceWindowMinutes,30);assert.equal(e.sold.unslippedPriceBtcPerContract,.08);assert.equal(e.priceSource,"direct-vwap");}});
test("IV normalization is bounded and missing path points remain gaps",()=>{const valid=spread([trade("BTC-8JAN24-39000-P",600,.08,"sell")],[trade("BTC-8JAN24-38000-P",610,.03,"buy")]);const entry=estimateResearchSpread({spread:valid,targetTimestamp:T,targetIndex:40000,slippageBps:0});assert.equal(entry.status,"priced");if(entry.status==="priced"){assert.equal(entry.priceSource,"model-reconstructed");assert.equal(entry.estimateQuality,"red");const path=buildEstimatedPath({spread:valid,timestamps:[T,T+2*864e5],indexAt:()=>40000,entry,slippageBps:0});assert.equal(path[1].status,"priced");assert.equal(path[1].ivSource,"constant-entry-IV");}const stale=spread([trade("BTC-8JAN24-39000-P",721,.08,"sell")],[trade("BTC-8JAN24-38000-P",721,.03,"buy")]);assert.equal(estimateResearchSpread({spread:stale,targetTimestamp:T,targetIndex:40000,slippageBps:0}).status,"unavailable");});
test("size scales without blocking, warns on liquidity, and export is explicit",()=>{const s=spread([trade("BTC-8JAN24-39000-P",0,.08,"sell",1)],[trade("BTC-8JAN24-38000-P",0,.03,"buy",1)]);const one=estimateResearchSpread({spread:s,targetTimestamp:T,targetIndex:40000,amount:1,slippageBps:0});const ten=estimateResearchSpread({spread:s,targetTimestamp:T,targetIndex:40000,amount:10,slippageBps:0});assert.equal(ten.status,"priced");if(one.status==="priced"&&ten.status==="priced"){assert.equal(ten.grossSpreadBtc,one.grossSpreadBtc*10);assert.equal(ten.liquidityWarning,"Historical tape does not prove execution of this size.");const out=buildResearchExport({event:{id:"e",label:"e",direction:"long",entryDate:"2024-01-01",entryPrice:40000},spread:s,entry:ten});assert.equal(out.mode,"research-estimate");assert.match(out.estimateDisclaimer,/not an actual or confirmed fill/);assert.equal(Object.hasOwn(out,"executedNetPnl"),false);}});
test("research calculator and every independent outcome remain estimate-based",()=>{const s={...spread([trade("BTC-8JAN24-39000-P",0,.08,"sell",.5)],[trade("BTC-8JAN24-38000-P",0,.03,"buy",.5)]),deliveryPrice:37000};const entry=estimateResearchSpread({spread:s,targetTimestamp:T,targetIndex:40000,amount:1,slippageBps:5});assert.equal(entry.status,"priced");if(entry.status!=="priced")return;const timestamps=Array.from({length:43},(_,i)=>T+i*4*36e5);const path=buildEstimatedPath({spread:s,timestamps,indexAt:()=>40000,entry,slippageBps:5});const event={id:"e",label:"e",direction:"long" as const,entryDate:"2024-01-01",entryTimestamp:T,entryPrice:40000,vpocTimestamp:T+864e5,invalidationPrice:39000};const candles=[{openTime:T+2*864e5,closeTime:T+2*864e5+36e5,open:40000,high:40100,low:38000,close:38000,volume:1}];const outcomes=buildResearchOutcomes({event,spread:s,entry,path,candles});assert.deepEqual(outcomes.map(outcome=>outcome.label),["VPOC","50% credit","70% credit","3D","5D","7D","Invalidation","Settlement"]);assert.ok(outcomes.every(outcome=>outcome.status==="estimated"||outcome.evidenceReason));const two=scaleResearchEstimate(entry,2);const fractional=scaleResearchEstimate(entry,.25);assert.equal(two.grossSpreadBtc,entry.grossSpreadBtc*2);assert.ok(two.openingFeesBtc>entry.openingFeesBtc);assert.ok(fractional.netOpeningCashFlowBtc>0);const scaledPath=scaleResearchPath(path,entry,2);assert.equal(scaledPath.length,path.length);const exported=buildResearchExport({event,spread:s,entry:two,path:scaledPath,outcomes});assert.equal(JSON.stringify(exported).includes("executedNetPnl"),false);assert.equal(exported.estimatedOutcomes.length,8);});
