import assert from "node:assert/strict";
import test from "node:test";
import type {AnalysisDataset} from "../app/lib/research-analysis.ts";
import type {Available,PositionEconomics} from "../app/lib/economics/position.ts";
import {availableReason,availableValue,projectResearchEconomicObservationsFromPositions,rawNumber,type ResearchLayerPositions} from "../app/lib/research-economics/project.ts";
import {buildResearchEconomicsReport} from "../app/lib/research-economics/report.ts";

const yes=(value:number):Available<number>=>({value,reason:null}),no=(reason:string):Available<number>=>({value:null,reason});
const opportunity=(economic_opportunity:unknown={status:"trade"},extra:Record<string,unknown>={})=>({event_id:"event-1",candidate_id:"candidate-1",structural_configuration_id:"config-1",structural_configuration:{targetDteFamilyDays:30,strikeMethod:"anchor",requestedWidth:2000,structureFamily:"credit_vertical"},economic_opportunity,...extra});
const dataset=(rows:readonly Record<string,unknown>[]):AnalysisDataset=>({filename:"schema-4.5.zip",schemaVersion:"4.5.0",migratedFrom:null,run:{},tables:{configuration_opportunities:rows,candidates:[],outcomes:[],margin_scenarios:[]},counts:{},venues:["deribit"],sourceRuns:["run"],eventUniverseComplete:true,capabilities:[]});
const position=(extra:Record<string,unknown>={}):PositionEconomics=>({eventId:"event-1",candidateId:"candidate-1",structuralConfigurationId:"config-1",direction:"short",actualDteDays:27.25,actualWidth:1975,structureType:"credit_vertical",exitPolicy:"thesis",analyticsTrack:"modeled_expected",status:"priced",diagnosticCode:null,missingReason:null,pnlUsd:125,pnlBtc:.0025,holdingDays:2,maximumStructuralLossUsd:yes(8000),trackMaximumNetLossUsd:yes(8100),grossOpeningCreditUsd:yes(500),openingFeesUsd:yes(12),netOpeningCashFlowUsd:yes(488),totalRealizedFeesUsd:yes(20),incrementalInitialMarginUsd:yes(4000),peakInitialMarginUsd:yes(4500),capitalDaysUsd:yes(9000),...extra} as unknown as PositionEconomics);
const layers=(rows:readonly PositionEconomics[]):ResearchLayerPositions=>({reference:rows,modeled_expected:rows,modeled_conservative:rows});
const splitLayers=(reference:readonly PositionEconomics[]=[],q50:readonly PositionEconomics[]=[],q90:readonly PositionEconomics[]=[]):ResearchLayerPositions=>({reference,modeled_expected:q50,modeled_conservative:q90});

test("typed raw and Available helpers distinguish values from evidence reasons",()=>{assert.equal(rawNumber(4),4);assert.equal(rawNumber(yes(4)),null);assert.equal(availableValue(yes(4)),4);assert.equal(availableValue(no("missing index")),null);assert.equal(availableReason(no("missing index"),"fallback"),"missing index")});
test("canonical Available USD values and reasons survive projection without spot conversion",()=>{const rows=projectResearchEconomicObservationsFromPositions(dataset([opportunity()]),"thesis",layers([position({entryIndex:999999})])),q50=rows.find(row=>row.analyticalTrack==="modeled_expected")!;assert.equal(q50.grossOpeningCreditUsd,500);assert.equal(q50.netOpeningCreditUsd,488);assert.equal(q50.totalRealizedFeesUsd,20);assert.equal(q50.openingInitialMarginUsd,4000);assert.equal(q50.peakInitialMarginUsd,4500);assert.equal(q50.capitalDaysUsd,9000);assert.equal(q50.pnlUsd,125);assert.equal(q50.maximumStructuralLossUsd,8000);assert.equal(q50.trackMaximumNetLossUsd,8100);assert.notEqual(q50.netOpeningCreditUsd,.0025*999999);const missing=projectResearchEconomicObservationsFromPositions(dataset([opportunity()]),"thesis",layers([position({netOpeningCashFlowUsd:no("entry index unavailable")} as unknown as Record<string,unknown>)]))[0]!;assert.equal(missing.netOpeningCreditUsd,null);assert.equal(missing.metricAvailability.netOpeningCreditUsd,"entry index unavailable")});
test("generation opportunity state is separate from per-layer evidence",()=>{const rows=projectResearchEconomicObservationsFromPositions(dataset([opportunity({status:"explicit_no_trade",reason_code:"empirical_nonpositive_credit_after_fees",reason:"No positive credit."})]),"thesis",splitLayers());assert.ok(rows.every(row=>row.generationOpportunityStatus==="explicit_no_trade"));const q50=rows.find(row=>row.analyticalTrack==="modeled_expected")!;assert.equal(q50.coverageStatus,"explicit_no_trade");assert.equal(q50.pnlUsd,0);assert.equal(rows.filter(row=>row.coverageStatus==="explicit_no_trade").length,1);assert.ok(rows.filter(row=>row.analyticalTrack!=="modeled_expected").every(row=>row.coverageStatus==="unavailable"))});
test("Q50 unavailable does not erase priced Reference or Q90 evidence",()=>{const rows=projectResearchEconomicObservationsFromPositions(dataset([opportunity({status:"unavailable",reason_code:"modeled_calibration_insufficient",reason:"Q50 calibration insufficient."})]),"thesis",splitLayers([position({analyticsTrack:"reference",pnlUsd:111})],[],[position({analyticsTrack:"modeled_conservative",pnlUsd:99})]));const reference=rows.find(row=>row.analyticalTrack==="reference")!,q50=rows.find(row=>row.analyticalTrack==="modeled_expected")!,q90=rows.find(row=>row.analyticalTrack==="modeled_conservative")!;assert.equal(reference.coverageStatus,"priced");assert.equal(reference.pnlUsd,111);assert.equal(q90.coverageStatus,"priced");assert.equal(q90.pnlUsd,99);assert.equal(q50.coverageStatus,"unavailable");assert.ok(rows.every(row=>row.generationOpportunityStatus==="unavailable"))});
test("Q50 explicit no-trade does not erase priced Reference evidence",()=>{const rows=projectResearchEconomicObservationsFromPositions(dataset([opportunity({status:"explicit_no_trade",reason_code:"empirical_nonpositive_credit_after_fees",reason:"No positive credit."})]),"thesis",splitLayers([position({analyticsTrack:"reference",pnlUsd:111})]));const reference=rows.find(row=>row.analyticalTrack==="reference")!,q50=rows.find(row=>row.analyticalTrack==="modeled_expected")!;assert.equal(reference.coverageStatus,"priced");assert.equal(reference.pnlUsd,111);assert.equal(q50.coverageStatus,"explicit_no_trade");assert.equal(q50.pnlUsd,0)});
test("priced Q50 contradicting canonical explicit no-trade is integrity-unavailable",()=>{const rows=projectResearchEconomicObservationsFromPositions(dataset([opportunity({status:"explicit_no_trade",reason_code:"empirical_nonpositive_credit_after_fees",reason:"No positive credit."})]),"thesis",splitLayers([],[position()]));const q50=rows.find(row=>row.analyticalTrack==="modeled_expected")!;assert.equal(q50.coverageStatus,"unavailable");assert.equal(q50.reasonCode,"explicit_no_trade_conflicts_with_priced_position");assert.equal(q50.pnlUsd,null)});
test("canonical unavailable remains unavailable on Q50 and preserves reason",()=>{const rows=projectResearchEconomicObservationsFromPositions(dataset([opportunity({status:"unavailable",reason_code:"missing_listing",reason:"Listing unavailable."},{event_id:"event-2",structural_configuration_id:"config-2",candidate_id:null})]),"thesis",splitLayers()),q50=rows.find(row=>row.eventId==="event-2"&&row.analyticalTrack==="modeled_expected")!;assert.equal(q50.coverageStatus,"unavailable");assert.equal(q50.reasonCode,"missing_listing");assert.equal(q50.metricAvailability.pnlUsd,"Listing unavailable.")});
test("unique positions enrich opportunities while ambiguous positions are never selected",()=>{const unique=projectResearchEconomicObservationsFromPositions(dataset([opportunity()]),"thesis",layers([position()])).find(row=>row.analyticalTrack==="modeled_expected")!;assert.equal(unique.coverageStatus,"priced");assert.equal(unique.candidateId,"candidate-1");const ambiguous=projectResearchEconomicObservationsFromPositions(dataset([opportunity({status:"trade"},{candidate_id:null})]),"thesis",layers([position(),position({candidateId:"candidate-2"})])).find(row=>row.analyticalTrack==="modeled_expected")!;assert.equal(ambiguous.coverageStatus,"unavailable");assert.equal(ambiguous.reasonCode,"ambiguous_event_configuration_position");assert.match(ambiguous.metricAvailability.pnlUsd,/found 2/)});
test("canonical target DTE defines family while actual DTE stays observational",()=>{const projected=projectResearchEconomicObservationsFromPositions(dataset([opportunity()]),"thesis",layers([position()]))[0]!;assert.equal(projected.dteFamily,"30D");assert.equal(projected.actualDteDays,27.25)});
test("incomplete structural identity stays in audit but not analytical dimension buckets",()=>{const invalid=opportunity({status:"trade"},{structural_configuration:{targetDteFamilyDays:null,strikeMethod:"anchor",requestedWidth:2000,structureFamily:"credit_vertical"}}),rows=projectResearchEconomicObservationsFromPositions(dataset([invalid]),"thesis",layers([position()]));assert.ok(rows.every(row=>row.structuralIdentityValid===false));assert.ok(rows.every(row=>row.dteFamily===null));const report=buildResearchEconomicsReport(rows,{researchExitPolicy:"thesis"});assert.equal(report.population.invalidStructuralIdentities,1);assert.equal(report.marginals.dte.length,0);assert.equal(report.configurationMatrix.length,0)});
test("no Research exit emits one policy-independent row per opportunity and layer",()=>{const rows=projectResearchEconomicObservationsFromPositions(dataset([opportunity()]),null,layers([position()]));assert.equal(rows.length,3);assert.deepEqual(rows.map(row=>row.exitPolicy),[null,null,null]);assert.ok(rows.every(row=>row.netOpeningCreditUsd===488&&row.openingInitialMarginUsd===4000));assert.ok(rows.every(row=>row.pnlUsd===null&&row.totalRealizedFeesUsd===null&&row.peakInitialMarginUsd===null&&row.capitalDaysUsd===null));assert.ok(rows.every(row=>row.metricAvailability.pnlUsd==="Exit policy required"))});
test("selected Research exit accepts only that policy and ignores Strategy selection state",()=>{const selected=position({exitPolicy:"capture_50",pnlUsd:150}),other=position({exitPolicy:"thesis",pnlUsd:125}),rows=projectResearchEconomicObservationsFromPositions(dataset([opportunity()]),"capture_50",layers([other,selected]));assert.equal(rows.length,3);assert.ok(rows.every(row=>row.exitPolicy==="capture_50"&&row.pnlUsd===150));const withStrategyNoise=dataset([{...opportunity(),selectedStructuralConfigurationId:"unrelated-strategy-selection"}]);assert.deepEqual(projectResearchEconomicObservationsFromPositions(withStrategyNoise,"capture_50",layers([selected])),rows)});
test("integration-shaped schema 4.5 tables retain exact counts and identities",()=>{const realistic={...dataset([opportunity()]),tables:{configuration_opportunities:[opportunity()],candidates:[{candidate_id:"candidate-1"}],outcomes:[{candidate_id:"candidate-1",net_pnl_usd:125}],margin_scenarios:[{candidate_id:"candidate-1",margin_status:"available"}]}} satisfies AnalysisDataset;const rows=projectResearchEconomicObservationsFromPositions(realistic,"thesis",layers([position()]));assert.equal(rows.length,3);assert.equal(new Set(rows.map(row=>`${row.eventId}|${row.structuralConfigurationId}`)).size,1);assert.deepEqual(rows.map(row=>row.analyticalTrack),["reference","modeled_expected","modeled_conservative"]);assert.ok(rows.every(row=>row.coverageStatus==="priced"&&row.pnlUsd===125))});
