import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import test from "node:test";
import {buildResearchEconomicsReport} from "../app/lib/research-economics/report.ts";
import {deriveUsdMetrics} from "../app/lib/research-economics/statistics.ts";

const shell=readFileSync(new URL("../app/components/shell/research-analytics.tsx",import.meta.url),"utf8"),nav=readFileSync(new URL("../app/components/research-section-nav.tsx",import.meta.url),"utf8"),component=readFileSync(new URL("../app/components/research-economics-report.tsx",import.meta.url),"utf8"),css=readFileSync(new URL("../app/globals.css",import.meta.url),"utf8"),strategy=readFileSync(new URL("../app/components/economic-analysis-report.tsx",import.meta.url),"utf8");
const observation=(dteFamily:string,requestedWidth:number,pnlUsd:number)=>deriveUsdMetrics({eventId:`event-${dteFamily}-${requestedWidth}`,candidateId:`candidate-${dteFamily}-${requestedWidth}`,structuralConfigurationId:`configuration-${dteFamily}-${requestedWidth}`,direction:"short",dteFamily,actualDteDays:Number(dteFamily.replace("D","")),strikeMethod:"anchor",requestedWidth,actualWidth:requestedWidth,structureFamily:"vertical",exitPolicy:"thesis",analyticalTrack:"modeled_expected",eligible:true,coverageStatus:"priced",reasonCode:null,grossOpeningCreditUsd:200,openingFeesUsd:4,netOpeningCreditUsd:196,maximumStructuralLossUsd:800,trackMaximumNetLossUsd:810,openingInitialMarginUsd:400,peakInitialMarginUsd:500,pnlUsd,holdingDays:2,totalRealizedFeesUsd:8,capitalDaysUsd:1000});

test("Comparative Economics is Research-only, ordered after Exit Policy and before Diagnostics",()=>{const exit=shell.indexOf('id="research-exit"'),economics=shell.indexOf('id="research-economics"'),audit=shell.indexOf('id="research-workbench"');assert.ok(exit<economics&&economics<audit);assert.equal(shell.slice(shell.indexOf('workspaceMode==="strategy"')).includes('id="research-economics"'),false);assert.ok(shell.includes('id="strategy-economics"'));const navExit=nav.indexOf('label:"Exit Policy"'),navEconomics=nav.indexOf('label:"Comparative Economics"'),navAudit=nav.indexOf('label:"Diagnostics & Audit"');assert.ok(navExit<navEconomics&&navEconomics<navAudit)});
test("Research Economics is memoized without selected configuration and keeps Research exit isolated",()=>{assert.match(shell,/projectResearchEconomicObservations\(d\)/);assert.match(shell,/buildResearchEconomicsReport\(researchEconomicObservations,\{researchExitPolicy,displayLayer:researchEconomicLayer/);assert.doesNotMatch(shell.slice(shell.indexOf("researchEconomicObservations"),shell.indexOf("futures=useMemo")),/selectedStructuralConfigurationId/);assert.match(shell,/useState<ResearchEconomicLayer>\(DEFAULT_RESEARCH_ECONOMIC_LAYER\)/);assert.match(shell,/onResearchExitPolicyChange=\{setResearchExitPolicy\}/)});
test("presentation controls are local, charts are accessible, and tables scroll locally",()=>{assert.match(component,/useState<Metric>\("pnl"\)/);assert.match(component,/aria-label=\{description\}/);assert.match(component,/aria-pressed=\{pinned===bucket.key\}/);assert.match(component,/className="exit-table-scroll"/);assert.match(css,/\.research-economics-report\{max-width:100%;overflow:hidden\}/);assert.match(css,/@media\(max-width:700px\)/)});
test("controlled comparisons and interaction cells expose exact N and missingness",()=>{assert.match(component,/common paired N/);assert.match(component,/eligible N \$\{cell.summary.eligibleN\}/);assert.match(component,/effective N \$\{statistic.effectiveN\}/);assert.match(component,/unavailable \$\{cell.summary.unavailableN\}/)});
test("matrix presentation sorts a copy by identity by default and introduces no performance rank",()=>{assert.match(component,/useState<SortKey>\("identity"\)/);assert.match(component,/\.toSorted\(/);assert.doesNotMatch(component,/rank number|optimal width|best DTE/i);assert.match(strategy,/Whole-matrix comparison now lives in Research → Comparative Economics/);assert.doesNotMatch(strategy,/title="Configuration-level economics"/)});
test("canonical USD report values remain intact for the accessible presentation",()=>{const source=[observation("30D",3000,90),observation("7D",1000,10)],snapshot=[...source],report=buildResearchEconomicsReport(source,{researchExitPolicy:"thesis"});assert.deepEqual(source,snapshot);assert.equal(report.marginals.dte.find(row=>row.key==="30D")!.summary.medianPnlUsd.value,90);assert.match(component,/Comparative Economics/);assert.match(component,/eligible N/);assert.match(component,/common paired N/);assert.match(component,/Full configuration matrix/);assert.doesNotMatch(component,/Best DTE|Optimal width|Winner/)});
