import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";

const component=await readFile(new URL("../app/components/research-economic-matrix-report.tsx",import.meta.url),"utf8");
const nav=await readFile(new URL("../app/components/research-section-nav.tsx",import.meta.url),"utf8");
const shell=await readFile(new URL("../app/components/shell/research-analytics.tsx",import.meta.url),"utf8");

test("Comparative Economics follows Exit Policy and precedes Diagnostics only in Research navigation",()=>{const research=nav.slice(nav.indexOf("RESEARCH_SECTION_LINKS"),nav.indexOf("ECONOMICS_SECTION_LINKS")),index=research.indexOf(`id:"research-economics"`);assert.ok(research.indexOf(`id:"research-exit"`)<index);assert.ok(index<research.indexOf(`id:"research-workbench"`));assert.doesNotMatch(nav.slice(nav.indexOf("ECONOMICS_SECTION_LINKS")),/id:"research-economics"/)});
test("Research section is mounted between Exit Policy and Diagnostics",()=>{const exit=shell.indexOf('id="research-exit"'),economics=shell.indexOf('id="research-economics"'),audit=shell.indexOf('id="research-workbench"');assert.ok(exit<economics&&economics<audit);assert.match(shell,/ResearchEconomicMatrixReport dataset=\{d!\}/);assert.doesNotMatch(shell,/ResearchEconomicMatrixReport[^>]+researchExitPolicy/)});
test("Q50 is local initial view and track changes cannot mutate Strategy configuration",()=>{assert.match(component,/useState<ResearchExecutionTrack>\("modeled_expected"\)/);assert.doesNotMatch(component,/setConfiguration|configuration\.exitPolicy|selectedStructuralConfigurationId/)});
test("metric units are exhaustive, currency-safe, and dimensionally explicit",()=>{assert.match(component,/MonetaryValue btc=\{btc\} usd=\{usd\} allowFallback=\{false\}/);assert.match(component,/value===null\)return <>Unavailable/);assert.match(component,/holdingDays",label:"Holding Days",domain:"days"/);assert.match(component,/capitalDays",label:"Capital-days",domain:"capital_days"/);assert.match(component,/BTC|currency\.toUpperCase\(\).*·days/);assert.match(component,/value\.toFixed\(1\)\} d/);assert.match(component,/domain==="ratio"/);assert.doesNotMatch(component,/money:boolean|money:true/)});
test("full matrix is collapsed, unranked, and interaction cells are accessible",()=>{assert.match(component,/<details className="exit-panel research-economics-full-matrix">/);assert.doesNotMatch(component,/best configuration|winner|ranking score/i);assert.match(component,/aria-label=\{`\$\{interaction\.replaceAll/);assert.match(component,/tabIndex=\{0\}/);assert.match(component,/role="img"/)});
test("Comparative Economics styles constrain grids and tables locally",async()=>{const css=await readFile(new URL("../app/globals.css",import.meta.url),"utf8");assert.match(css,/\.research-economics-panel-grid/);assert.match(css,/\.research-economics-heatmap/);assert.match(css,/overflow:hidden/);assert.match(css,/@media\(max-width:800px\)/)});
test("signed bars, value-encoded heatmap, and semantic audit labels are explicit",async()=>{const css=await readFile(new URL("../app/globals.css",import.meta.url),"utf8");assert.match(component,/is-signed/);assert.match(component,/d\.medianDelta<0/);assert.match(component,/--cell-intensity/);assert.match(css,/is-diverging\.is-negative/);assert.match(component,/Execution identities unpaired/);assert.doesNotMatch(component,/AuditAttentionControls|>Unusual</)});
test("visible values disclose metric-specific denominator units",()=>{assert.match(component,/effective independent events/);assert.match(component,/metric-eligible independent events/);assert.match(component,/eligible pairs/);assert.match(component,/priced opportunities/);assert.match(component,/canonical attempted opportunities/)});

test("policy economics restores exact paired-vs-Thesis evidence and Q50 tail labelling",()=>{assert.match(component,/Exit policies paired against Thesis/);assert.match(component,/common priced/);assert.match(component,/Q50 trade-conditional P10 \(fixed generation baseline\)/)});
test("audit distinguishes integrity, metric, margin, tail and Q50 generation states",()=>{assert.match(component,/Configurations with one or more unavailable canonical USD metrics/);assert.match(component,/Configurations with Q50 generation unavailable/);assert.match(component,/Margin capability/);assert.match(component,/Integrity:/);assert.match(component,/Tails:/);assert.doesNotMatch(component,/ResearchEvidenceBadge|>VALID</)});

test("evidence-first empty states, denominators, and reason distributions are explicit",()=>{assert.match(component,/Research integrity errors:/);assert.match(component,/integrityAffectedIdentityN>0/);assert.match(component,/Q50 contains no priced intended trades/);assert.match(component,/Q50 priced \/ canonical Q50 intended trades/);assert.match(component,/\$\{trackLabel\} priced \/ all canonical attempted opportunities/);assert.match(component,/Q50 generation unavailable reason distribution/);assert.match(component,/Not evaluable — neither track has priced evidence/);assert.match(component,/No common priced pair — delta not estimable/);assert.match(component,/minimum=\$\{x\.q50\.tailMinimum\}/)});

test("Comparative Economics owns a Thesis-default analytical exit-policy control",()=>{assert.match(component,/useState<PrimaryExitPolicy>\("thesis"\)/);assert.match(component,/label="Analytical exit policy"/);assert.match(component,/options=\{EXIT_POLICIES\}/);assert.doesNotMatch(component,/Research Exit Policy is not configured/);assert.doesNotMatch(component,/\{dataset,researchExitPolicy\}/);assert.match(component,/Does not change Strategy Configuration or other Research sections/)});
