import test from "node:test";import assert from "node:assert/strict";
import type {ResearchSelectionStore} from "../app/lib/research-selections.ts";
import {buildResearchBundle,RESEARCH_BUNDLE_FILES,REQUIRED_OUTCOMES,validateResearchBundle} from "../app/lib/research-bundle.ts";
const now="2026-08-16T00:00:00.000Z",ts=Date.parse(now),config={applicationBuild:"120adbb",pricingEngineVersion:"v1",qualityRulesVersion:"q1",feeScheduleVersion:"f1",dteWindows:{},expirySelectionMode:"all",executionMode:"taker",pricingAssumption:"research-estimate",pricingTracks:["vwap","iv"],historicalEvidenceWindows:{},synchronizationThresholds:{},qualityThresholds:{},feeAssumptions:{},settlementRules:{},valuationInterval:"4h",modelAssumptions:{},generatedAtUtc:now};
const cand=(id:string,status="priced")=>({candidateId:`deribit~${id}`,venue:"deribit" as const,selected:id<"d",status:status as "priced"|"unavailable",availabilityReasons:status==="priced"?[]:["missing"],targetHorizon:7,eligibleDteRange:{min:5,max:10},actualExpiryTimestamp:ts+7*864e5,actualDte:7,requestedStrikes:{short:100,long:90,width:10},actualStrikes:{short:100,long:90,width:10},structure:"credit",optionType:"P",strikeMethod:"anchor",entryQuality:status==="priced"?"red" as const:null});
const sel=(eventId:string,id:string)=>({selectionId:`selection~${id}`,eventId,candidateId:`deribit~${id}`,venue:"deribit" as const,selectedAtUtc:now,quantity:1,candidateSnapshot:{structure:"credit",optionType:"P",expiryTimestamp:ts+7*864e5,shortStrike:100,longStrike:90,actualWidth:10},entrySnapshot:{status:"priced",targetTimestamp:ts,entryTargetIndex:100,estimateQuality:"red",priceSource:"direct-vwap",sold:{priceBtcPerContract:.02},bought:{priceBtcPerContract:.01},openingFeesBtc:.001,netOpeningCashFlowBtc:.009},valuationPathSnapshot:[{timestamp:ts,status:"priced",targetIndex:100,rawEstimate:{sold:{priceBtcPerContract:.02},bought:{priceBtcPerContract:.01}},modelEstimate:{sold:{priceBtcPerContract:.02},bought:{priceBtcPerContract:.01}},closingFeesBtc:.001,estimatedNetPnlBtc:.008,estimateQuality:"red"},{timestamp:ts+144e5,status:"missing",unavailableReason:"missing-target-index",missingField:"targetIndex",estimateQuality:"unavailable"}],outcomeSnapshots:[],marginSnapshot:{},evidenceTradeSnapshots:[{instrumentName:"BTC-X",tradeId:"t1",timestamp:ts,price:.02,amount:1,indexPrice:100}]});
const store:ResearchSelectionStore={schemaVersion:"1.0.0",datasetId:"acceptance",updatedAtUtc:now,events:[{eventId:"e1",sourceRun:{event:{id:"e1",direction:"long",entryDate:"2026-08-16",entryTimestamp:ts,entryPrice:100}},generationSnapshot:{generatedAtUtc:now,configuration:config,candidates:[cand("a"),cand("b"),cand("u"),cand("z","unavailable")],underlyingHourlyPath:[{openTime:ts,closeTime:ts+36e5,open:100,high:101,low:99,close:100,volume:1}]},selectedStructures:[sel("e1","a"),sel("e1","b")]},{eventId:"e2",sourceRun:{event:{id:"e2",direction:"short",entryDate:"2026-08-16",entryTimestamp:ts,entryPrice:100}},generationSnapshot:{generatedAtUtc:now,configuration:{...config,pricingEngineVersion:"v2"},candidates:[cand("c"),cand("red")],underlyingHourlyPath:[]},selectedStructures:[sel("e2","c")]}]};
test("canonical persisted bundle semantics",()=>{const b=buildResearchBundle(structuredClone(store),now);assert.deepEqual(Object.keys(b.files),RESEARCH_BUNDLE_FILES);for(const [n,text] of Object.entries(b.files))if(n.endsWith("jsonl"))for(const line of text.trim().split("\n").filter(Boolean))assert.doesNotThrow(()=>JSON.parse(line));const c=b.files["candidates.jsonl"].trim().split("\n").map(JSON.parse),a=b.files["availability.jsonl"].trim().split("\n").map(JSON.parse),v=b.files["valuations.jsonl"].trim().split("\n").map(JSON.parse),o=b.files["outcomes.jsonl"].trim().split("\n").map(JSON.parse);assert.equal(c.length,3);assert.equal(a.length,6);assert.ok(!c.some(x=>x.candidate_id.includes("~u")));assert.ok(a.some(x=>x.status==="unavailable"));assert.ok(c.every(x=>x.venue==="deribit"&&x.native_currency==="BTC"));assert.equal(new Set(o.map(x=>x.outcome_type)).size,REQUIRED_OUTCOMES.length);assert.deepEqual(new Set(v.map(x=>x.pricing_track)),new Set(["raw_vwap","iv_normalized"]));assert.ok(v.some(x=>x.valuation_status==="unavailable"&&x.net_pnl_native===null));assert.equal(b.run.selected_structure_count,3);assert.equal(b.run.generated_denominator_count,6);assert.equal(validateResearchBundle(b.files).ok,true);assert.match(b.files["margin_scenarios.jsonl"],/verified_historical_margin_model_unavailable/);assert.match(b.files["futures_comparisons.jsonl"],/verified_futures_series_unavailable/);assert.match(b.files["evidence_trades.jsonl"],/"trade_id":"t1"/)});
test("validator rejects broken joins and versions",()=>{const b=buildResearchBundle(store,now);assert.equal(validateResearchBundle({...b.files,"candidates.jsonl":b.files["candidates.jsonl"].replace('"event_id":"e1"','"event_id":"gone"')}).ok,false);assert.equal(validateResearchBundle({...b.files,"run.json":b.files["run.json"].replace('"1.0.0"','"9.0.0"')}).ok,false)});
