/* eslint-disable @typescript-eslint/no-explicit-any -- tests inspect schema-open fixture rows */
import test from "node:test";import assert from "node:assert/strict";
import {reconcileCandidateSpread} from "../app/lib/semantic-spread.ts";
const base=(id:string,opt:"C"|"P",short:number,long:number)=>({candidate_id:id,event_id:`e-${id}`,option_type:opt,expiry_timestamp_utc:"2026-08-21T00:00:00.000Z",entry_index_price:100000,quantity:1,opening_fees_native:.001,gross_credit_debit_native:.01,net_opening_cash_flow_native:.009,actual_strikes:{short,long,width:Math.abs(short-long)},entry_legs:{short:{action:"sell",instrument:`BTC-21AUG26-${short}-${opt}`,price_native:.02},long:{action:"buy",instrument:`BTC-21AUG26-${long}-${opt}`,price_native:.01}}});
test("valid bear call credit",()=>assert.equal(reconcileCandidateSpread(base("call","C",110000,120000)).valid,true));
test("valid bull put credit",()=>assert.equal(reconcileCandidateSpread(base("put","P",90000,80000)).valid,true));
test("reversed call leg objects are repaired only with full evidence",()=>{const r=reconcileCandidateSpread({...base("rc","C",120000,110000),entry_legs:{short:{action:"buy",instrument:"BTC-21AUG26-120000-C",price_native:.01,mark:.011},long:{action:"sell",instrument:"BTC-21AUG26-110000-C",price_native:.02,mark:.021}}});assert.equal(r.valid,true);assert.equal(r.diagnostics[0].severity,"reconciled");assert.equal((r.row.entry_legs as any).short.instrument,"BTC-21AUG26-110000-C");assert.equal((r.row.entry_legs as any).short.price_native,.02)});
test("reversed put leg objects are repaired only with full evidence",()=>{const r=reconcileCandidateSpread({...base("rp","P",80000,90000),entry_legs:{short:{action:"buy",instrument:"BTC-21AUG26-80000-P",price_native:.01},long:{action:"sell",instrument:"BTC-21AUG26-90000-P",price_native:.02}}});assert.equal(r.valid,true);assert.equal((r.row.actual_strikes as any).short,90000)});
test("ambiguous reversed data is not silently repaired",()=>{const r=reconcileCandidateSpread({...base("bad","C",120000,110000),entry_legs:{short:{action:"sell",instrument:null,price_native:.02},long:{action:"buy",instrument:null,price_native:.01}}});assert.equal(r.valid,false);assert.match(r.diagnostics[0].reason,/bear call/)});
test("instrument strike and type disagreement invalidates candidate",()=>{assert.equal(reconcileCandidateSpread({...base("type","C",110000,120000),entry_legs:{short:{action:"sell",instrument:"BTC-21AUG26-110000-P",price_native:.02},long:{action:"buy",instrument:"BTC-21AUG26-120000-C",price_native:.01}}}).valid,false);assert.equal(reconcileCandidateSpread({...base("strike","C",110000,120000),entry_legs:{short:{action:"sell",instrument:"BTC-21AUG26-111000-C",price_native:.02},long:{action:"buy",instrument:"BTC-21AUG26-120000-C",price_native:.01}}}).valid,false)});
