import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {DEFAULT_ANALYSIS_CONFIGURATION} from "../app/lib/analysis-configuration.ts";
import {buildEconomicReport,pairedExecutionComparisons} from "../app/lib/economics/report.ts";
import type {AnalysisDataset} from "../app/lib/research-analysis.ts";

const component=await readFile(new URL("../app/components/economic-analysis-report.tsx",import.meta.url),"utf8");
const research=await readFile(new URL("../app/components/research-economic-matrix-report.tsx",import.meta.url),"utf8");
const shell=await readFile(new URL("../app/components/shell/research-analytics.tsx",import.meta.url),"utf8");
const configuration=(id:string)=>({targetDteFamilyDays:id==="a"?7:14,strikeMethod:"anchor",requestedWidth:1000,structureFamily:"credit_vertical"});
function dataset():AnalysisDataset{const candidates=["a","b"].flatMap(id=>(["reference","modeled_expected","modeled_conservative"] as const).map((track,i)=>({event_id:`event-${id}`,candidate_id:`candidate-${id}-${track}`,structure_execution_id:`execution-${id}-${track}`,structural_configuration_id:`cfg-${id}`,structural_configuration:configuration(id),analytics_track:track,execution_scenario:null,execution_scenario_status:"evaluated",structure_entry_timestamp_utc:"2026-01-01T00:00:00Z",expiry_timestamp_utc:"2026-01-08T00:00:00Z",actual_dte_days:7,direction:"long",option_type:"P",structure_type:"bull_put_credit",strike_method:"anchor",requested_width:1000,actual_strikes:{short:40000,long:39000,width:1000},entry_index_price:42000,quantity:1,entry_legs:{short:{price_native:.01-i*.001,unslipped_price_native:.01},long:{price_native:.002,unslipped_price_native:.002}},gross_credit_debit_native:.008-i*.001,opening_fees_native:.0001,net_opening_cash_flow_native:.0079-i*.001}))),outcomes=candidates.map((c,index)=>({candidate_id:c.candidate_id,event_id:c.event_id,analytics_track:c.analytics_track,execution_scenario:null,outcome_type:"settlement",status:"priced",trigger_status:"reached",decision_available_timestamp_utc:"2026-01-03T00:00:00Z",valuation_timestamp_utc:"2026-01-03T00:00:00Z",holding_hours:48,closing_fees_native:.0001,net_pnl_native:c.structural_configuration_id==="cfg-a"?.01-index*.0001:.05-index*.0001,net_pnl_usd:c.structural_configuration_id==="cfg-a"?420:2100})),configuration_opportunities=["a","b"].map(id=>({event_id:`event-${id}`,candidate_id:`candidate-${id}-modeled_expected`,structural_configuration_id:`cfg-${id}`,structural_configuration:configuration(id),economic_opportunity:{status:"trade"}}));return{filename:"boundary",schemaVersion:"4.5.0",migratedFrom:null,run:{},tables:{candidates,outcomes,valuations:[],margin_scenarios:[],structure_economics:[],configuration_opportunities},counts:{},venues:[],sourceRuns:[],eventUniverseComplete:true,capabilities:[]} as unknown as AnalysisDataset}
const base={...DEFAULT_ANALYSIS_CONFIGURATION,exitPolicy:"settlement_benchmark" as const};

test("no Strategy selection never falls back to pooled economics",()=>{const report=buildEconomicReport(dataset(),base);assert.equal(report.status,"not_selected");assert.equal(report.positions.length,0);assert.deepEqual(report.central.positions,[]);assert.equal(report.portfolio,null)});
test("selected Strategy configuration scopes every economic layer and changing selection changes its cohort",()=>{for(const id of ["a","b"]){const report=buildEconomicReport(dataset(),{...base,selectedStructuralConfigurationId:`cfg-${id}`});assert.equal(report.status,"available");for(const layer of [report.reference,report.central,report.conservative,report.observed.maker,report.observed.taker,report.delayed.delayed_maker,report.delayed.delayed_taker,report.modeled.penalty_sensitivity])assert.ok(layer.positions.every(p=>p.structuralConfigurationId===`cfg-${id}`));assert.ok(report.positions.every(p=>p.eventId===`event-${id}`));assert.equal(report.selectedConfiguration?.configurationId,`cfg-${id}`)}});
test("Strategy paired execution comparisons cannot cross selected configurations",()=>{const report=buildEconomicReport(dataset(),{...base,selectedStructuralConfigurationId:"cfg-a"}),pairs=pairedExecutionComparisons(report);assert.ok(pairs.every(p=>p.fromPricedN<=1&&p.toPricedN<=1&&p.commonN<=1));assert.ok(report.reference.positions.every(p=>p.structuralConfigurationId==="cfg-a"))});
test("workspace boundary leaves full matrix and controls in Research only",()=>{assert.doesNotMatch(component,/Full configuration matrix|Configuration-level economics|onSelectConfiguration/);assert.match(component,/Research → Comparative Economics/);assert.doesNotMatch(research,/setConfiguration|accountEquity|reconstructPortfolio/);assert.match(shell,/researchExitPolicy=\{researchExitPolicy\}/);assert.match(shell,/exitPolicy:configuration\.exitPolicy/)});
