import type {AnalysisDataset} from "../research-analysis.ts";
import {ANALYTICS_TRACKS,type AnalyticsTrack} from "../research-analytics-model.ts";
import type {PricingTrack} from "../analysis-configuration.ts";
import {canonicalOutcomeId} from "../research-outcomes.ts";
import {indexByCandidate,readCanonicalStructuralLoss} from "../canonical-structural-loss.ts";
import {EXIT_POLICIES,type ExitTrigger,type PolicyId} from "./policies.ts";

export type PolicyEvaluationStatus="priced"|"triggered_unpriced"|"unavailable"|"not_evaluated";
export type ExitDiagnosticCode="source_outcome_absent"|"source_outcome_unavailable"|"outcome_reached_unpriced"|"outcome_after_expiry"|"ambiguous_timing"|"pre_entry_outcome"|"routing_filter_exclusion"|"legacy_incompatibility";
export interface ReferenceMark {timestamp:string;pnlBtc:number}
export interface PolicyObservation {sourceRun:string;eventId:string;candidateId:string;structureExecutionId:string;analyticsTrack:AnalyticsTrack|null;executionScenario:"maker"|"taker"|null;executionScenarioStatus:"evaluated"|"unavailable"|"not_evaluated";legacyUndifferentiated:boolean;pricingTrack:PricingTrack|null;policyId:PolicyId;winningTrigger:ExitTrigger|null;triggerTimestamp:string|null;decisionTimestamp:string|null;valuationTimestamp:string|null;entryTimestamp:string|null;expiryTimestamp:string|null;status:PolicyEvaluationStatus;missingDataReason:string|null;sourceEvidenceReason:string|null;diagnosticCode:ExitDiagnosticCode|null;pnlBtc:number|null;pnlUsd:number|null;openingFeesBtc:number|null;closingFeesBtc:number|null;deliveryFeesBtc:number|null;totalFeesBtc:number|null;holdingHours:number|null;requiredCapitalBtc:number|null;capitalDaysBtc:number|null;capitalDaysReason:string|null;maximumStructuralLossBtc:number|null;structuralLossReason:string|null;maeBtc:number|null;referenceMarks:readonly ReferenceMark[];tieResolution:string|null;matchKey:string}
export interface ExitNormalizationOptions {capitalBasis?:"maximum_economic_loss"|"incremental_opening_margin"|"peak_required_capital"|null}
type Row=Readonly<Record<string,unknown>>;
const str=(x:unknown)=>typeof x==="string"?x:null,num=(x:unknown)=>typeof x==="number"&&Number.isFinite(x)?x:null;
const time=(x:unknown)=>{const value=str(x);if(value===null)return null;const parsed=Date.parse(value);return Number.isFinite(parsed)?parsed:null};
const analyticalTrack=(c:Row):AnalyticsTrack|null=>typeof c.analytics_track==="string"&&ANALYTICS_TRACKS.includes(c.analytics_track as AnalyticsTrack)?c.analytics_track as AnalyticsTrack:null;
const reason=(code:ExitDiagnosticCode,detail:string)=>`${code}: ${detail}`;

function holdingHoursOf(win:Row,entry:string|null,valuation:string|null):number|null{const canonical=win.holding_hours;if(typeof canonical==="number"&&Number.isFinite(canonical))return canonical>=0?canonical:null;if(canonical===null||!entry||!valuation)return null;const hours=(Date.parse(valuation)-Date.parse(entry))/36e5;return Number.isFinite(hours)&&hours>=0?hours:null;}

/** Freeze chronology before pricing. Projected analytical tracks produce one observation; only legacy unprojected rows fan out by pricing representation. */
export function normalizeExitPolicies(dataset:AnalysisDataset,options:ExitNormalizationOptions={}):readonly PolicyObservation[]{
 const candidates=dataset.tables.candidates??[],outcomes=dataset.tables.outcomes??[],margins=dataset.tables.margin_scenarios??[],valuations=dataset.tables.valuations??[],economics=indexByCandidate(dataset.tables.structure_economics),marginIndex=indexByCandidate(margins),result:PolicyObservation[]=[];const seenCandidates=new Set<string>();
 for(const c of candidates){const analyticsTrack=analyticalTrack(c),scenario=(c.execution_scenario??null) as "maker"|"taker"|null,candidateKey=[c.event_id,c.candidate_id,analyticsTrack??scenario,c.structure_entry_timestamp_utc].join("~");if(seenCandidates.has(candidateKey))continue;seenCandidates.add(candidateKey);
  const tracks:readonly (PricingTrack|null)[]=analyticsTrack?[null]:["raw_vwap","iv_normalized"];
  for(const pricingTrack of tracks){const sameCandidate=outcomes.filter(o=>o.candidate_id===c.candidate_id),relevant=sameCandidate.filter(o=>analyticsTrack?(!o.analytics_track||o.analytics_track===analyticsTrack)&&o.execution_scenario===scenario:o.execution_scenario===scenario);
   for(const policy of EXIT_POLICIES){const entry=str(c.structure_entry_timestamp_utc),expiry=str(c.expiry_timestamp_utc),entryMs=time(entry),expiryMs=time(expiry);
    if(c.execution_scenario_legacy_undifferentiated===true){result.push(base(null,c,analyticsTrack,scenario,pricingTrack,policy.id,"unavailable",reason("legacy_incompatibility","legacy execution direction/provenance is not trustworthy"),"legacy_incompatibility",entry,expiry));continue}
    if(c.execution_scenario_status!=="evaluated"){const status=c.execution_scenario_status==="not_evaluated"?"not_evaluated":"unavailable";result.push(base(null,c,analyticsTrack,scenario,pricingTrack,policy.id,status,reason("source_outcome_unavailable",String(c.execution_scenario_reason??"analytical track unavailable")),"source_outcome_unavailable",entry,expiry));continue}
    const policyRows=relevant.flatMap(o=>{const id=canonicalOutcomeId(o.outcome_type);return id&&policy.priority.includes(id as ExitTrigger)?[{row:o,id:id as ExitTrigger}]:[]}),admissible:{row:Row;id:ExitTrigger;decision:number}[]=[];let exclusion:{code:ExitDiagnosticCode;detail:string}|null=null;
    for(const item of policyRows){const decision=time(item.row.decision_available_timestamp_utc);if(item.row.trigger_status==="after_expiry"){exclusion??={code:"outcome_after_expiry",detail:`${item.id} occurs after expiry`};continue}if(item.row.trigger_status==="ambiguous"||(item.row.trigger_status==="reached"&&decision===null)){exclusion??={code:"ambiguous_timing",detail:`${item.id} has no determinate decision-available timestamp`};continue}if(item.row.trigger_status!=="reached")continue;if(entryMs!==null&&decision!<entryMs){exclusion??={code:"pre_entry_outcome",detail:`${item.id} decision precedes structure entry`};continue}if(expiryMs!==null&&decision!>expiryMs){exclusion??={code:"outcome_after_expiry",detail:`${item.id} decision occurs after expiry`};continue}admissible.push({...item,decision:decision!})}
    admissible.sort((a,b)=>a.decision-b.decision||policy.priority.indexOf(a.id)-policy.priority.indexOf(b.id));const winner=admissible[0];
    if(!winner){const expected=policy.priority.filter(id=>!policyRows.some(x=>x.id===id)),routingExcluded=sameCandidate.some(o=>{const id=canonicalOutcomeId(o.outcome_type);return id&&policy.priority.includes(id as ExitTrigger)})&&policyRows.length===0,diagnostic=exclusion??(routingExcluded?{code:"routing_filter_exclusion" as const,detail:"matching canonical outcomes were excluded by analytical-track routing"}:expected.length?{code:"source_outcome_absent" as const,detail:`canonical source outcome(s) absent: ${expected.join(", ")}`}:{code:"source_outcome_unavailable" as const,detail:"no policy trigger was reached"});result.push(base(null,c,analyticsTrack,scenario,pricingTrack,policy.id,"unavailable",reason(diagnostic.code,diagnostic.detail),diagnostic.code,entry,expiry));continue}
    const win=winner.row,tied=admissible.filter(x=>x.decision===winner.decision),valuation=str(win.valuation_timestamp_utc),valuationMs=time(valuation),statusKey=analyticsTrack?"status":pricingTrack==="raw_vwap"?"raw_status":"iv_normalized_status",pnlKey=analyticsTrack?"net_pnl_native":pricingTrack==="raw_vwap"?"raw_net_pnl_native":"iv_normalized_net_pnl_native",usdKey=analyticsTrack?"net_pnl_usd":pricingTrack==="raw_vwap"?"raw_net_pnl_usd":"iv_normalized_net_pnl_usd",pnl=num(win[pnlKey]),causalValuation=valuationMs!==null&&(entryMs===null||valuationMs>=entryMs)&&(expiryMs===null||valuationMs<=expiryMs),priced=String(win[statusKey])==="priced"&&pnl!==null&&causalValuation;
    let diagnostic:ExitDiagnosticCode|null=null,missing:string|null=null;if(!priced){diagnostic=valuationMs!==null&&entryMs!==null&&valuationMs<entryMs?"pre_entry_outcome":valuationMs!==null&&expiryMs!==null&&valuationMs>expiryMs?"outcome_after_expiry":win.source_status==="absent"?"source_outcome_absent":win.source_status==="unavailable"?"source_outcome_unavailable":"outcome_reached_unpriced";missing=reason(diagnostic,String(win.evidence_reason??`${winner.id} won chronologically but has no compatible valuation`))}
    const holding=priced?holdingHoursOf(win,entry,valuation):null,margin=marginIndex.get(String(c.candidate_id)),loss=readCanonicalStructuralLoss({economics:economics.get(String(c.candidate_id)),margin}),capital=capitalDays(margin,options.capitalBasis??null,entryMs,valuationMs,loss.btc),referenceMarks=valuations.filter(v=>v.candidate_id===c.candidate_id&&analyticsTrack==="reference"&&(v.analytics_track==="reference"||v.pricing_track==="reference")&&v.execution_scenario===null&&v.valuation_status==="priced").flatMap(v=>{const timestamp=str(v.timestamp_utc),value=num(v.net_pnl_native),ms=time(timestamp);return timestamp!==null&&value!==null&&ms!==null&&(entryMs===null||ms>=entryMs)&&(expiryMs===null||ms<=expiryMs)?[{timestamp,pnlBtc:value}]:[]}).sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp)),preExitMarks=new Map(referenceMarks.filter(v=>valuationMs!==null&&Date.parse(v.timestamp)<=valuationMs).map(v=>[Date.parse(v.timestamp),v.pnlBtc])),opening=num(c.opening_fees_native),closing=priced?num(win.closing_fees_native):null,delivery=priced?(winner.id==="settlement"?closing:0):null;
    if(priced&&analyticsTrack==="reference"&&valuationMs!==null&&pnl!==null)preExitMarks.set(valuationMs,pnl);
    result.push({...base(winner.id,c,analyticsTrack,scenario,pricingTrack,policy.id,priced?"priced":"triggered_unpriced",missing,diagnostic,entry,expiry),sourceEvidenceReason:str(win.evidence_reason),triggerTimestamp:str(win.trigger_timestamp_utc),decisionTimestamp:str(win.decision_available_timestamp_utc),valuationTimestamp:valuation,pnlBtc:priced?pnl:null,pnlUsd:priced?num(win[usdKey]):null,closingFeesBtc:closing,deliveryFeesBtc:delivery,totalFeesBtc:priced&&opening!==null&&closing!==null?opening+closing:null,holdingHours:holding,requiredCapitalBtc:capital.requiredCapital,capitalDaysBtc:priced?capital.value:null,capitalDaysReason:priced?capital.reason:"winning trigger unpriced",maximumStructuralLossBtc:loss.btc,structuralLossReason:loss.reason,maeBtc:preExitMarks.size?Math.min(0,...preExitMarks.values()):null,referenceMarks,tieResolution:tied.length>1?`${tied.map(x=>x.id).join(" = ")} → ${winner.id} by policy priority at the same decision timestamp`:null});
   }
  }
 }
 return result.sort((a,b)=>[a.candidateId,a.analyticsTrack,a.executionScenario,a.pricingTrack,a.policyId].join("~").localeCompare([b.candidateId,b.analyticsTrack,b.executionScenario,b.pricingTrack,b.policyId].join("~")));
}
function capitalDays(margin:Row|undefined,basis:ExitNormalizationOptions["capitalBasis"],entry:number|null,exit:number|null,maximumLoss:number|null):{value:number|null;reason:string|null;requiredCapital:number|null}{
 if(!basis)return{value:null,reason:"capital basis not supplied to normalization",requiredCapital:null};if(entry===null||exit===null||exit<entry)return{value:null,reason:"causal entry/exit timestamps unavailable",requiredCapital:null};
 if(basis==="maximum_economic_loss")return maximumLoss===null?{value:null,reason:"canonical maximum structural loss unavailable",requiredCapital:null}:{value:maximumLoss*(exit-entry)/864e5,reason:null,requiredCapital:maximumLoss};
 if(!margin||margin.margin_status!=="available")return{value:null,reason:"canonical margin path unavailable",requiredCapital:null};
 const opening=num(margin.incremental_initial_margin??margin.incremental_initial_margin_native);
 if(basis==="incremental_opening_margin")return opening===null?{value:null,reason:"canonical incremental opening margin unavailable",requiredCapital:null}:{value:opening*(exit-entry)/864e5,reason:null,requiredCapital:opening};
 const input=margin.margin_inputs&&typeof margin.margin_inputs==="object"?margin.margin_inputs as Row:{},raw=Array.isArray(input.path)?input.path:[],points=raw.flatMap(x=>{const row=x&&typeof x==="object"?x as Row:{},timestamp=num(row.timestamp),value=num(row.initialMarginBtc);return timestamp!==null&&value!==null?[{timestamp,value}]:[]}).filter(x=>x.timestamp>=entry&&x.timestamp<=exit).sort((a,b)=>a.timestamp-b.timestamp);
 if(!points.length||points[0]!.timestamp!==entry)return{value:null,reason:"causal initial-margin path does not begin at structure entry",requiredCapital:null};let integral=0;for(let i=0;i<points.length;i++){const start=points[i]!.timestamp,end=Math.min(exit,points[i+1]?.timestamp??exit);if(end>start)integral+=points[i]!.value*(end-start)/864e5}return{value:integral,reason:null,requiredCapital:Math.max(...points.map(x=>x.value))};
}
function base(trigger:ExitTrigger|null,c:Row,analyticsTrack:AnalyticsTrack|null,scenario:"maker"|"taker"|null,pricingTrack:PricingTrack|null,policyId:PolicyId,status:PolicyEvaluationStatus,missingDataReason:string|null,diagnosticCode:ExitDiagnosticCode|null,entry:string|null,expiry:string|null):PolicyObservation{return{sourceRun:String(c.source_run_id??""),analyticsTrack,eventId:String(c.event_id??""),candidateId:String(c.candidate_id??""),structureExecutionId:String(c.structure_execution_id??""),executionScenario:scenario,executionScenarioStatus:(c.execution_scenario_status??"unavailable") as PolicyObservation["executionScenarioStatus"],legacyUndifferentiated:c.execution_scenario_legacy_undifferentiated===true,pricingTrack,policyId,winningTrigger:trigger,triggerTimestamp:null,decisionTimestamp:null,valuationTimestamp:null,entryTimestamp:entry,expiryTimestamp:expiry,status,missingDataReason,sourceEvidenceReason:null,diagnosticCode,pnlBtc:null,pnlUsd:null,openingFeesBtc:num(c.opening_fees_native),closingFeesBtc:null,deliveryFeesBtc:null,totalFeesBtc:null,holdingHours:null,requiredCapitalBtc:null,capitalDaysBtc:null,capitalDaysReason:"winning exit unavailable",maximumStructuralLossBtc:null,structuralLossReason:null,maeBtc:null,referenceMarks:[],tieResolution:null,matchKey:[c.event_id,c.candidate_id,c.expiry_timestamp_utc,JSON.stringify(c.actual_strikes),c.option_type,c.direction,c.quantity,analyticsTrack??scenario,scenario,pricingTrack].join("~")};}
