import {observedPercentiles} from "../underlying-resolution/statistics.ts";
import type {PolicyObservation} from "./normalize.ts";

export interface Metric {value:number|null;n:number;reason:string|null;status:"available"|"not_estimable"|"unavailable"}
const metric=(xs:(number|null)[],kind:"mean"|"median"|"p10"|"p5"|"min"="mean",emptyStatus:"not_estimable"|"unavailable"="unavailable"):Metric=>{const v=xs.filter((x):x is number=>x!==null&&Number.isFinite(x));if(!v.length)return{value:null,n:0,reason:emptyStatus==="not_estimable"?"no compatible paired observations":"required canonical evidence unavailable",status:emptyStatus};if((kind==="p10"||kind==="p5")&&v.length<10)return{value:null,n:v.length,reason:"insufficient sample for percentile (minimum 10)",status:"not_estimable"};if(kind==="mean")return{value:v.reduce((a,b)=>a+b,0)/v.length,n:v.length,reason:null,status:"available"};if(kind==="min")return{value:Math.min(...v),n:v.length,reason:null,status:"available"};const [p50,p10,p05]=observedPercentiles(v,[.5,.1,.05]);return{value:kind==="median"?p50:kind==="p10"?p10:p05,n:v.length,reason:null,status:"available"}};
const differences=(pairs:readonly {subject:PolicyObservation;thesis:PolicyObservation}[],field:keyof PolicyObservation)=>pairs.map(({subject,thesis})=>{const a=subject[field],b=thesis[field];return typeof a==="number"&&typeof b==="number"?a-b:null});
const mean=(xs:number[])=>xs.reduce((a,b)=>a+b,0)/xs.length;
const equalEvent=(pairs:readonly {subject:PolicyObservation;thesis:PolicyObservation}[],field:keyof PolicyObservation)=>{const groups=new Map<string,number[]>();for(const pair of pairs){const value=differences([pair],field)[0];if(value===null)continue;const values=groups.get(pair.subject.eventId)??[];values.push(value);groups.set(pair.subject.eventId,values)}const effects=[...groups.values()].map(mean);return{eventN:effects.length,mean:metric(effects,"mean","not_estimable"),median:metric(effects,"median","not_estimable"),aggregation:"arithmetic mean per event, then equal event weight" as const}};

export function policyStatistics(rows:readonly PolicyObservation[]){
 const determinate=rows.filter(x=>x.winningTrigger!==null),priced=rows.filter(x=>x.status==="priced"),selected=rows.length;
 const triggerCounts=Object.fromEntries([...new Set(determinate.map(x=>x.winningTrigger!))].sort().map(t=>{const n=determinate.filter(x=>x.winningTrigger===t).length;return[t,{n,denominator:determinate.length,share:determinate.length?n/determinate.length:null}]}));
 const totalFees=priced.map(x=>x.totalFeesBtc);
 return{denominators:{selectedEligible:{n:selected},trackAvailable:{n:rows.filter(x=>x.executionScenarioStatus==="evaluated").length},trackUnavailable:{n:rows.filter(x=>x.executionScenarioStatus==="unavailable").length},triggerDeterminate:{n:determinate.length},pricedWinningExits:{n:priced.length},triggeredUnpriced:{n:rows.filter(x=>x.status==="triggered_unpriced").length},unavailable:{n:rows.filter(x=>x.status==="unavailable").length},notEvaluated:{n:rows.filter(x=>x.status==="not_evaluated").length}},pricingCoverage:{value:determinate.length?priced.length/determinate.length:null,numerator:priced.length,denominator:determinate.length},selectedCohortCoverage:{value:selected?priced.length/selected:null,numerator:priced.length,denominator:selected},pnlAmongPricedExits:{btc:{mean:metric(priced.map(x=>x.pnlBtc)),median:metric(priced.map(x=>x.pnlBtc),"median"),p10:metric(priced.map(x=>x.pnlBtc),"p10"),p5:metric(priced.map(x=>x.pnlBtc),"p5"),worst:metric(priced.map(x=>x.pnlBtc),"min")},usd:{mean:metric(priced.map(x=>x.pnlUsd)),median:metric(priced.map(x=>x.pnlUsd),"median"),p10:metric(priced.map(x=>x.pnlUsd),"p10"),p5:metric(priced.map(x=>x.pnlUsd),"p5"),worst:metric(priced.map(x=>x.pnlUsd),"min")}},maeAmongPricedExits:metric(priced.map(x=>x.maeBtc),"median"),holdingAmongPricedExits:{hours:metric(priced.map(x=>x.holdingHours),"median"),days:metric(priced.map(x=>x.holdingHours===null?null:x.holdingHours/24),"median")},feesAmongPricedExits:{opening:metric(priced.map(x=>x.openingFeesBtc)),closing:metric(priced.map(x=>x.closingFeesBtc)),delivery:metric(priced.map(x=>x.deliveryFeesBtc)),total:metric(totalFees)},capitalDaysAmongPricedExits:metric(priced.map(x=>x.capitalDaysBtc)),triggerCounts};
}

export function pairedComparison(subject:readonly PolicyObservation[],thesis:readonly PolicyObservation[]){
 const trustworthy=(x:PolicyObservation)=>x.status==="priced"&&!x.legacyUndifferentiated;
 const base=new Map(thesis.filter(trustworthy).map(x=>[x.matchKey,x])),pairs=subject.filter(trustworthy).flatMap(x=>{const b=base.get(x.matchKey);return b?[{subject:x,thesis:b}]:[]});
 const post=pairs.map(({subject:s,thesis:t})=>{if(!s.valuationTimestamp||!t.valuationTimestamp||s.pnlBtc===null||t.pnlBtc===null)return{opportunity:null,downside:null,evidenceN:0,reason:"paired exit timestamps or PnL unavailable"};const start=Date.parse(s.valuationTimestamp),end=Date.parse(t.valuationTimestamp);if(!Number.isFinite(start)||!Number.isFinite(end)||start>=end)return{opportunity:null,downside:null,evidenceN:0,reason:"alternative does not exit before Thesis"};const marks=new Map(s.referenceMarks.filter(x=>{const at=Date.parse(x.timestamp);return at>start&&at<=end}).map(x=>[Date.parse(x.timestamp),x.pnlBtc]));marks.set(end,t.pnlBtc);const future=[...marks.values()];return{opportunity:Math.max(0,Math.max(...future)-s.pnlBtc),downside:Math.max(0,s.pnlBtc-Math.min(...future)),evidenceN:future.length,reason:null}});
 const unmatchedSubject=subject.filter(x=>!trustworthy(x)||!base.has(x.matchKey)),subjectKeys=new Set(subject.filter(trustworthy).map(x=>x.matchKey)),unmatchedThesis=thesis.filter(x=>!trustworthy(x)||!subjectKeys.has(x.matchKey));
 const matchedEventN=new Set(pairs.map(x=>x.subject.eventId)).size;
 return{matchedN:pairs.length,matchedStructuresN:pairs.length,matchedEventN,pairingCoverage:{commonPriced:pairs.length,alternativeSelected:subject.length,thesisSelected:thesis.length,value:Math.max(subject.length,thesis.length)?pairs.length/Math.max(subject.length,thesis.length):null},unmatched:{subjectN:unmatchedSubject.length,thesisN:unmatchedThesis.length,reasons:[...new Set([...unmatchedSubject,...unmatchedThesis].map(x=>x.legacyUndifferentiated?"legacy provenance excluded":x.status!=="priced"?x.missingDataReason??`${x.status} winning exit`:"no exact compatible structure/track pair"))]},pnlDifferenceBtc:{mean:metric(differences(pairs,"pnlBtc"),"mean","not_estimable"),median:metric(differences(pairs,"pnlBtc"),"median","not_estimable")},pnlDifferenceUsd:{mean:metric(differences(pairs,"pnlUsd"),"mean","not_estimable"),median:metric(differences(pairs,"pnlUsd"),"median","not_estimable")},holdingDifferenceHours:{mean:metric(differences(pairs,"holdingHours"),"mean","not_estimable"),median:metric(differences(pairs,"holdingHours"),"median","not_estimable")},maeDifferenceBtc:{mean:metric(differences(pairs,"maeBtc"),"mean","not_estimable"),median:metric(differences(pairs,"maeBtc"),"median","not_estimable")},closingFeeDifferenceBtc:{mean:metric(differences(pairs,"closingFeesBtc"),"mean","not_estimable"),median:metric(differences(pairs,"closingFeesBtc"),"median","not_estimable")},totalFeeDifferenceBtc:{mean:metric(differences(pairs,"totalFeesBtc"),"mean","not_estimable"),median:metric(differences(pairs,"totalFeesBtc"),"median","not_estimable")},capitalDaysDifferenceBtc:{mean:metric(differences(pairs,"capitalDaysBtc"),"mean","not_estimable"),median:metric(differences(pairs,"capitalDaysBtc"),"median","not_estimable")},equalEvent:{pnlBtc:equalEvent(pairs,"pnlBtc"),holdingHours:equalEvent(pairs,"holdingHours"),maeBtc:equalEvent(pairs,"maeBtc"),totalFeesBtc:equalEvent(pairs,"totalFeesBtc"),capitalDaysBtc:equalEvent(pairs,"capitalDaysBtc")},postExitOpportunitySurrendered:{mean:metric(post.map(x=>x.opportunity),"mean","not_estimable"),median:metric(post.map(x=>x.opportunity),"median","not_estimable")},postExitDownsideAvoided:{mean:metric(post.map(x=>x.downside),"mean","not_estimable"),median:metric(post.map(x=>x.downside),"median","not_estimable")},postExitEvidenceCounts:post.map(x=>x.evidenceN),postExitUnavailableReasons:[...new Set(post.flatMap(x=>x.reason?[x.reason]:[]))],pairs};
}
