import {observedPercentiles} from "../underlying-resolution/statistics.ts";
import type {PolicyObservation} from "./normalize.ts";

export interface Metric {value:number|null;n:number;reason:string|null}
const metric=(xs:(number|null)[],kind:"mean"|"median"|"p10"|"p5"|"min"="mean"):Metric=>{const v=xs.filter((x):x is number=>x!==null&&Number.isFinite(x));if(!v.length)return{value:null,n:0,reason:"no compatible priced observations"};if((kind==="p10"||kind==="p5")&&v.length<10)return{value:null,n:v.length,reason:"insufficient sample for percentile (minimum 10)"};if(kind==="mean")return{value:v.reduce((a,b)=>a+b,0)/v.length,n:v.length,reason:null};if(kind==="min")return{value:Math.min(...v),n:v.length,reason:null};const [p50,p10,p05]=observedPercentiles(v,[.5,.1,.05]);return{value:kind==="median"?p50:kind==="p10"?p10:p05,n:v.length,reason:null}};
const differences=(pairs:readonly {subject:PolicyObservation;thesis:PolicyObservation}[],field:keyof PolicyObservation)=>pairs.map(({subject,thesis})=>{const a=subject[field],b=thesis[field];return typeof a==="number"&&typeof b==="number"?a-b:null});

export function policyStatistics(rows:readonly PolicyObservation[]){
 const determinate=rows.filter(x=>x.winningTrigger!==null),priced=rows.filter(x=>x.status==="priced"),selected=rows.length;
 const triggerCounts=Object.fromEntries([...new Set(determinate.map(x=>x.winningTrigger!))].sort().map(t=>{const n=determinate.filter(x=>x.winningTrigger===t).length;return[t,{n,denominator:determinate.length,share:determinate.length?n/determinate.length:null}]}));
 const totalFees=priced.map(x=>x.totalFeesBtc);
 return{denominators:{selectedEligible:{n:selected},triggerDeterminate:{n:determinate.length},pricedWinningExits:{n:priced.length},triggeredUnpriced:{n:rows.filter(x=>x.status==="triggered_unpriced").length},unavailable:{n:rows.filter(x=>x.status==="unavailable").length},notEvaluated:{n:rows.filter(x=>x.status==="not_evaluated").length}},pricingCoverage:{value:determinate.length?priced.length/determinate.length:null,numerator:priced.length,denominator:determinate.length},selectedCohortCoverage:{value:selected?priced.length/selected:null,numerator:priced.length,denominator:selected},pnlAmongPricedExits:{btc:{mean:metric(priced.map(x=>x.pnlBtc)),median:metric(priced.map(x=>x.pnlBtc),"median"),p10:metric(priced.map(x=>x.pnlBtc),"p10"),p5:metric(priced.map(x=>x.pnlBtc),"p5"),worst:metric(priced.map(x=>x.pnlBtc),"min")},usd:{mean:metric(priced.map(x=>x.pnlUsd)),median:metric(priced.map(x=>x.pnlUsd),"median"),p10:metric(priced.map(x=>x.pnlUsd),"p10"),p5:metric(priced.map(x=>x.pnlUsd),"p5"),worst:metric(priced.map(x=>x.pnlUsd),"min")}},maeAmongPricedExits:metric(priced.map(x=>x.maeBtc),"median"),holdingAmongPricedExits:{hours:metric(priced.map(x=>x.holdingHours),"median"),days:metric(priced.map(x=>x.holdingHours===null?null:x.holdingHours/24),"median")},feesAmongPricedExits:{opening:metric(priced.map(x=>x.openingFeesBtc)),closing:metric(priced.map(x=>x.closingFeesBtc)),delivery:metric(priced.map(x=>x.deliveryFeesBtc)),total:metric(totalFees)},capitalDaysAmongPricedExits:metric(priced.map(x=>x.capitalDaysBtc)),triggerCounts};
}

export function pairedComparison(subject:readonly PolicyObservation[],thesis:readonly PolicyObservation[]){
 const trustworthy=(x:PolicyObservation)=>x.status==="priced"&&!x.legacyUndifferentiated;
 const base=new Map(thesis.filter(trustworthy).map(x=>[x.matchKey,x])),pairs=subject.filter(trustworthy).flatMap(x=>{const b=base.get(x.matchKey);return b?[{subject:x,thesis:b}]:[]});
 const post=pairs.map(({subject:s,thesis:t})=>{if(!s.valuationTimestamp||!t.valuationTimestamp||s.pnlBtc===null)return{opportunity:null,downside:null,reason:"paired exit timestamps or PnL unavailable"};const start=Date.parse(s.valuationTimestamp),end=Date.parse(t.valuationTimestamp);if(!Number.isFinite(start)||!Number.isFinite(end)||start>=end)return{opportunity:null,downside:null,reason:"alternative does not exit before Thesis"};const future=s.referenceMarks.filter(x=>{const at=Date.parse(x.timestamp);return at>start&&at<=end});if(!future.length)return{opportunity:null,downside:null,reason:"insufficient causal post-exit Reference marks"};return{opportunity:Math.max(0,Math.max(...future.map(x=>x.pnlBtc))-s.pnlBtc),downside:Math.max(0,s.pnlBtc-Math.min(...future.map(x=>x.pnlBtc))),reason:null}});
 const unmatchedSubject=subject.filter(x=>!trustworthy(x)||!base.has(x.matchKey)),subjectKeys=new Set(subject.filter(trustworthy).map(x=>x.matchKey)),unmatchedThesis=thesis.filter(x=>!trustworthy(x)||!subjectKeys.has(x.matchKey));
 return{matchedN:pairs.length,unmatched:{subjectN:unmatchedSubject.length,thesisN:unmatchedThesis.length,reasons:[...new Set([...unmatchedSubject,...unmatchedThesis].map(x=>x.legacyUndifferentiated?"legacy provenance excluded":x.status!=="priced"?x.missingDataReason??`${x.status} winning exit`:"no exact compatible structure/track pair"))]},pnlDifferenceBtc:{mean:metric(differences(pairs,"pnlBtc")),median:metric(differences(pairs,"pnlBtc"),"median")},pnlDifferenceUsd:{mean:metric(differences(pairs,"pnlUsd")),median:metric(differences(pairs,"pnlUsd"),"median")},holdingDifferenceHours:{mean:metric(differences(pairs,"holdingHours")),median:metric(differences(pairs,"holdingHours"),"median")},maeDifferenceBtc:{mean:metric(differences(pairs,"maeBtc")),median:metric(differences(pairs,"maeBtc"),"median")},closingFeeDifferenceBtc:{mean:metric(differences(pairs,"closingFeesBtc")),median:metric(differences(pairs,"closingFeesBtc"),"median")},totalFeeDifferenceBtc:{mean:metric(differences(pairs,"totalFeesBtc")),median:metric(differences(pairs,"totalFeesBtc"),"median")},capitalDaysDifferenceBtc:{mean:metric(differences(pairs,"capitalDaysBtc")),median:metric(differences(pairs,"capitalDaysBtc"),"median")},postExitOpportunitySurrendered:metric(post.map(x=>x.opportunity)),postExitDownsideAvoided:metric(post.map(x=>x.downside)),postExitUnavailableReasons:[...new Set(post.flatMap(x=>x.reason?[x.reason]:[]))],pairs};
}
