import {MILLISECONDS_PER_YEAR,priceInverseOption} from "../inverse-option-pricing.ts";
export const EXPIRY_FORWARD_METHOD_VERSION="option-trade-implied-forward-v1" as const;
export const EXPIRY_FORWARD_MAX_AGE_MINUTES=60 as const;
export interface ForwardTradeEvidence{instrumentName:string;timestampMs:number;expiryTimestampMs:number;contractCreatedAtMs?:number|null;strike:number;optionType:"C"|"P";price?:number|null;ivApiPercent?:number|null;ivDecimal?:number|null;indexPrice?:number|null}
export type InferredForward={status:"available";forwardPrice:number;rate:number}|{status:"unavailable";reason:string};
export function inferForwardFromOptionTrade(trade:ForwardTradeEvidence):InferredForward{
 const index=trade.indexPrice,price=trade.price,iv=trade.ivDecimal??(typeof trade.ivApiPercent==="number"?trade.ivApiPercent/100:null),years=(trade.expiryTimestampMs-trade.timestampMs)/MILLISECONDS_PER_YEAR;
 if(!(typeof index==="number"&&index>0&&typeof price==="number"&&price>=0&&typeof iv==="number"&&iv>0&&years>0))return{status:"unavailable",reason:"invalid_option_forward_inputs"};
 const value=(forward:number)=>priceInverseOption({optionType:trade.optionType==="C"?"call":"put",indexPrice:index,strike:trade.strike,valuationTimestamp:trade.timestampMs,expiryTimestamp:trade.expiryTimestampMs,ivDecimal:iv,forwardPrice:forward});
 let lo=index/20,hi=index*20;const a=value(lo),b=value(hi);if(a.status!=="priced"||b.status!=="priced")return{status:"unavailable",reason:"forward_pricing_unavailable"};
 const increasing=b.priceBtc>a.priceBtc,min=Math.min(a.priceBtc,b.priceBtc),max=Math.max(a.priceBtc,b.priceBtc);if(price<min-1e-10||price>max+1e-10)return{status:"unavailable",reason:"premium_outside_forward_bracket"};
 for(let i=0;i<100;i++){const mid=(lo+hi)/2,r=value(mid);if(r.status!=="priced")return{status:"unavailable",reason:"forward_pricing_unavailable"};if((r.priceBtc<price)===increasing)lo=mid;else hi=mid}
 const forwardPrice=(lo+hi)/2,check=value(forwardPrice);if(check.status!=="priced"||!Number.isFinite(forwardPrice)||forwardPrice<=0||Math.abs(check.priceBtc-price)>1e-8)return{status:"unavailable",reason:"forward_inversion_failed"};return{status:"available",forwardPrice,rate:Math.log(forwardPrice/index)/years};
}
export interface ExpiryForwardEstimate{status:"available"|"unavailable";methodVersion:string;source:"option_trade_implied_forward"|"unavailable";forwardPrice:number|null;rate:number|null;targetTimestampMs:number;expiryTimestampMs:number;indexPrice:number;observationCount:number;uniqueInstrumentCount:number;uniqueStrikeCount:number;callCount:number;putCount:number;medianAbsoluteDeviation:number|null;freshestAgeMinutes:number|null;oldestAgeMinutes:number|null;evidenceTimestampMs:number|null;exclusions:Record<string,number>;unavailableReason:string|null}
const median=(x:number[])=>{const s=[...x].sort((a,b)=>a-b),m=Math.floor(s.length/2);return s.length%2?s[m]!:(s[m-1]!+s[m]!)/2};
export function resolveExpiryForward(input:{trades:readonly ForwardTradeEvidence[];targetTimestampMs:number;expiryTimestampMs:number;indexPrice:number;excludedInstruments?:readonly string[];maxAgeMinutes?:number}):ExpiryForwardEstimate{
 const maxAge=input.maxAgeMinutes??EXPIRY_FORWARD_MAX_AGE_MINUTES,excluded=new Set(input.excludedInstruments??[]),values:Array<{trade:ForwardTradeEvidence;forward:number}>=[],exclusions:Record<string,number>={};const reject=(reason:string)=>exclusions[reason]=(exclusions[reason]??0)+1;
 for(const trade of input.trades){if(trade.expiryTimestampMs!==input.expiryTimestampMs){reject("wrong_expiry");continue}if(excluded.has(trade.instrumentName)){reject("excluded_instrument");continue}if(trade.timestampMs>=input.targetTimestampMs){reject("not_strictly_prior");continue}if(trade.contractCreatedAtMs!=null&&trade.contractCreatedAtMs>input.targetTimestampMs){reject("contract_not_listed");continue}const age=(input.targetTimestampMs-trade.timestampMs)/60000;if(age>maxAge){reject("stale");continue}const inferred=inferForwardFromOptionTrade(trade);if(inferred.status!=="available"){reject(inferred.reason);continue}values.push({trade,forward:inferred.forwardPrice})}
 const base={methodVersion:EXPIRY_FORWARD_METHOD_VERSION,targetTimestampMs:input.targetTimestampMs,expiryTimestampMs:input.expiryTimestampMs,indexPrice:input.indexPrice,observationCount:values.length,uniqueInstrumentCount:new Set(values.map(v=>v.trade.instrumentName)).size,uniqueStrikeCount:new Set(values.map(v=>v.trade.strike)).size,callCount:values.filter(v=>v.trade.optionType==="C").length,putCount:values.filter(v=>v.trade.optionType==="P").length,freshestAgeMinutes:values.length?Math.min(...values.map(v=>(input.targetTimestampMs-v.trade.timestampMs)/60000)):null,oldestAgeMinutes:values.length?Math.max(...values.map(v=>(input.targetTimestampMs-v.trade.timestampMs)/60000)):null,evidenceTimestampMs:values.length?Math.max(...values.map(v=>v.trade.timestampMs)):null,exclusions};
 if(!values.length)return{...base,status:"unavailable",source:"unavailable",forwardPrice:null,rate:null,medianAbsoluteDeviation:null,unavailableReason:"no_causal_forward_evidence"};const forwardPrice=median(values.map(v=>v.forward)),deviations=values.map(v=>Math.abs(v.forward-forwardPrice));return{...base,status:"available",source:"option_trade_implied_forward",forwardPrice,rate:Math.log(forwardPrice/input.indexPrice)/((input.expiryTimestampMs-input.targetTimestampMs)/MILLISECONDS_PER_YEAR),medianAbsoluteDeviation:median(deviations),unavailableReason:null};
}
export const legacyIndexForwardDiagnostic=(indexPrice:number)=>({source:"legacy_index_forward_proxy" as const,forwardPrice:indexPrice,rate:0});
export interface DatedFutureForwardMark{timestampMs:number;expiryTimestampMs:number;markPrice:number;dteDays:number}
export function summarizeDatedFutureValidation(pairs:readonly {inferred:ExpiryForwardEstimate;future:DatedFutureForwardMark;optionType?:"C"|"P"}[]){const valid=pairs.filter(p=>p.inferred.status==="available"&&p.inferred.forwardPrice&&p.future.markPrice>0&&p.future.timestampMs<=p.inferred.targetTimestampMs),absolute=valid.map(p=>Math.abs(p.inferred.forwardPrice!-p.future.markPrice)).sort((a,b)=>a-b),bps=valid.map(p=>Math.abs(p.inferred.forwardPrice!-p.future.markPrice)/p.future.markPrice*10000).sort((a,b)=>a-b),q=(x:number[],v:number)=>x.length?x[Math.min(x.length-1,Math.ceil(x.length*v)-1)]!:null,byType=(type:"C"|"P")=>{const x=valid.filter(p=>p.optionType===type).map(p=>(p.inferred.forwardPrice!-p.future.markPrice)/p.future.markPrice*10000).sort((a,b)=>a-b);return{count:x.length,median_signed_bps:q(x,.5)}};return{count:valid.length,median_absolute_error:q(absolute,.5),median_bps_error:q(bps,.5),p90_bps_error:q(bps,.9),p95_bps_error:q(bps,.95),call:byType("C"),put:byType("P"),by_dte:Object.fromEntries([...new Set(valid.map(p=>String(Math.floor(p.future.dteDays))))].sort().map(bucket=>{const x=valid.filter(p=>String(Math.floor(p.future.dteDays))===bucket).map(p=>Math.abs(p.inferred.forwardPrice!-p.future.markPrice)/p.future.markPrice*10000).sort((a,b)=>a-b);return[bucket,{count:x.length,median_bps_error:q(x,.5)}]}))}}
