import type {AnalysisDataset} from "../research-analysis.ts";
import {projectVolatilityAnalytics,type AvailabilityTally} from "./volatility-analytics.ts";
import type {PolicyObservation} from "../exit-policy/normalize.ts";

export const REFERENCE_ANALYTICS_TRACK="reference_fair_value" as const;
export type Row=Readonly<Record<string,unknown>>;
const rows=(v:unknown):Row[]=>Array.isArray(v)?v.filter((x):x is Row=>!!x&&typeof x==="object"):[];
const n=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:null;
const s=(v:unknown)=>typeof v==="string"?v:null;
const observed=(v:unknown):Row|null=>{const x=v&&typeof v==="object"?v as Row:null;return x?.status==="available"&&x.observation==="observed"&&n(x.iv_decimal)!==null?x:null};
export const volatilityLeg=(r:Row,k:"short"|"long")=>observed(rows(r.legs).find(x=>x.leg===k));
export const volatilityDiff=(r:Row,k:string)=>rows(r.differentials).find(x=>x.differential===k&&x.status==="available")??null;
export const hasUsableStructureVolatility=(r:Row)=>Boolean(volatilityLeg(r,"short")||volatilityLeg(r,"long")||n((r.same_expiry_reference as Row|undefined)?.iv_decimal)!==null||["short_minus_reference_iv","long_minus_reference_iv","short_minus_long_iv"].some(k=>n(volatilityDiff(r,k)?.value)!==null));
/** Evidence completeness is focal: strike needs short/reference skew; width needs both legs; structure needs the full two-leg/reference comparison. */
export function structureEvidenceAssessment(r:Row,kind:"structure"|"strike"|"width"="structure"){const short=!!volatilityLeg(r,"short"),long=!!volatilityLeg(r,"long"),reference=n((r.same_expiry_reference as Row|undefined)?.iv_decimal)!==null,sr=!!volatilityDiff(r,"short_minus_reference_iv"),sl=!!volatilityDiff(r,"short_minus_long_iv"),available=kind==="strike"?[short,reference,sr]:kind==="width"?[short,long,sl]:[short,long,reference,sr,sl],usable=available.some(Boolean),complete=available.every(Boolean),reasons=structureEvidenceReasons(r,kind);return{status:!usable?"UNAVAILABLE" as const:complete?"VALID" as const:"PARTIAL" as const,reason:complete?null:reasons.join(" · ")||`Incomplete ${kind} volatility evidence.`}}
export function structureUnavailableReasons(r:Row){const focal=[...["short","long"].map(leg=>{const x=rows(r.legs).find(v=>v.leg===leg);return x?.status==="available"?null:`${leg}: ${s(x?.unavailable_reason)??s(x?.reason)??"unavailable"}`}),(()=>{const x=r.same_expiry_reference as Row|undefined;return x?.status==="available"?null:`Reference: ${s(x?.unavailable_reason)??s(x?.reason)??"unavailable"}`})(),...rows(r.differentials).filter(x=>x.status!=="available"&&s(x.unavailable_reason)).map(x=>`${String(x.differential)}: ${String(x.unavailable_reason)}`)];return [...new Set(focal.filter((x):x is string=>x!==null))]}
export function structureEvidenceReasons(r:Row,kind:"structure"|"strike"|"width"){const all=structureUnavailableReasons(r);return all.filter(reason=>kind==="structure"||(kind==="strike"?!reason.startsWith("long:")&&!reason.startsWith("short_minus_long"):!reason.startsWith("Reference:")&&!reason.startsWith("short_minus_reference")))}
export function partitionStructuresByEvidence(structures:readonly Row[],kind:"structure"|"strike"|"width"){return{usable:structures.filter(r=>structureEvidenceAssessment(r,kind).status!=="UNAVAILABLE"),unavailable:structures.filter(r=>structureEvidenceAssessment(r,kind).status==="UNAVAILABLE")}}
export function structuresForNominalHorizon(structures:readonly Row[],nominalDays:number){return structures.filter(r=>n(r.target_horizon_days)===nominalDays)}
export function skewVisualScale(series:readonly {p25:number|null;median:number|null;p75:number|null}[]){const all=series.flatMap(q=>[q.p25,q.median,q.p75]).filter((x):x is number=>x!==null),min=all.length?Math.min(...all):null,max=all.length?Math.max(...all):null;return{min,max,position:(value:number|null)=>value===null||min===null||max===null?null:min===max?60:10+(value-min)/(max-min)*100}}
export function endpointEvidenceAssessment(e:VolatilityEndpoint){const short=e.deltaShortIv!==null,long=e.deltaLongIv!==null,observed=e.shortIv!==null||e.longIv!==null;return{status:short&&long?"VALID" as const:short||long||observed?"PARTIAL" as const:"UNAVAILABLE" as const,reason:short&&long?null:e.reason??`Short ΔIV ${short?"usable":"unavailable"}; long ΔIV ${long?"usable":"unavailable"}.`}}
/** A path is complete only with repeated timestamps on both legs; one timestamp or one-leg depth is partial. */
export function pathEvidenceAssessment(p:PathDiagnostic){return{status:p.timestampCountAnyObserved===0?"UNAVAILABLE" as const:p.timestampCountBothObserved>=2?"VALID" as const:"PARTIAL" as const,reason:p.timestampCountBothObserved>=2?null:p.timestampCountAnyObserved===0?`No admissible observed path timestamp${p.missingTimestampObservationRows?`; ${p.missingTimestampObservationRows} observed row(s) lacked a canonical timestamp`:""}.`:`${p.timestampCountAnyObserved} observed timestamp(s), ${p.timestampCountBothObserved} with both legs; repeated both-leg evidence is required.`}}
/** Entry context requires at least two Reference tenors and one core RV or IV-minus-RV comparison; DVOL is optional. */
export function entryVolatilityEvidenceAssessment(r:Row){const references=rows(r.reference_iv).filter(x=>x.status==="available"&&n(x.iv_decimal)!==null).length,context=rows(r.realized_volatility).some(x=>x.status==="available"&&n(x.rv_decimal)!==null)||rows(r.iv_minus_rv).some(x=>x.status==="available"&&n(x.value)!==null),any=references>0||context;return{status:references>=2&&context?"VALID" as const:any?"PARTIAL" as const:"UNAVAILABLE" as const,reason:references>=2&&context?null:`Reference tenors ${references}; core RV/IV-minus-RV context ${context?"available":"unavailable"}. DVOL is optional.`}}
export const quantiles=(xs:readonly number[])=>{const a=[...xs].sort((x,y)=>x-y),q=(p:number)=>{if(!a.length)return null;const z=(a.length-1)*p,l=Math.floor(z),u=Math.ceil(z);return a[l]!+(a[u]!-a[l]!)*(z-l)};return{n:a.length,p25:q(.25),median:q(.5),p75:q(.75)}};
export const availableStateQuantiles=(subjects:readonly Row[],collection:string,identity:string,field:string)=>quantiles(subjects.flatMap(subject=>{const state=rows(subject[collection]).find(x=>x.nominal_tenor===identity||x.horizon===identity||x.slope===identity),value=state?.status==="available"?n(state[field]):null;return value===null?[]:[value]}));
const tally=(available:number,total:number,reason:string):AvailabilityTally=>({available,total,ratio:total?available/total:null,reasons:available===total?{}:{[reason]:total-available}});

export interface VolatilityEndpoint {id:string;label:string;candidateId:string;timestampUtc:string|null;entryShortIv:number|null;shortIv:number|null;deltaShortIv:number|null;shortDeltaReason:string|null;entryLongIv:number|null;longIv:number|null;deltaLongIv:number|null;longDeltaReason:string|null;status:"available"|"unavailable";reason:string|null}
export interface EndpointAggregate {id:string;label:string;n:number;shortN:number;longN:number;bothN:number;denominator:number;medianEntryShortIv:number|null;medianShortIv:number|null;medianDeltaShortIv:number|null;medianEntryLongIv:number|null;medianLongIv:number|null;medianDeltaLongIv:number|null;shortCompressionShare:number|null;shortExpansionShare:number|null}
export function aggregateVolatilityEndpoints(endpoints:readonly VolatilityEndpoint[]):EndpointAggregate[]{return[...new Map(endpoints.map(x=>[x.id,x.label])).entries()].map(([id,label])=>{const all=endpoints.filter(x=>x.id===id),short=all.filter(x=>x.entryShortIv!==null&&x.shortIv!==null),long=all.filter(x=>x.entryLongIv!==null&&x.longIv!==null),both=all.filter(x=>x.entryShortIv!==null&&x.shortIv!==null&&x.entryLongIv!==null&&x.longIv!==null),ds=short.map(x=>x.deltaShortIv!),dl=long.map(x=>x.deltaLongIv!);return{id,label,n:both.length,shortN:short.length,longN:long.length,bothN:both.length,denominator:all.length,medianEntryShortIv:quantiles(short.map(x=>x.entryShortIv!)).median,medianShortIv:quantiles(short.map(x=>x.shortIv!)).median,medianDeltaShortIv:quantiles(ds).median,medianEntryLongIv:quantiles(long.map(x=>x.entryLongIv!)).median,medianLongIv:quantiles(long.map(x=>x.longIv!)).median,medianDeltaLongIv:quantiles(dl).median,shortCompressionShare:ds.length?ds.filter(x=>x<0).length/ds.length:null,shortExpansionShare:ds.length?ds.filter(x=>x>0).length/ds.length:null}})}
export function volatilityEndpointsForCandidates(report:VolatilityReport,candidateIds:ReadonlySet<string>){const endpoints=report.endpoints.filter(x=>candidateIds.has(x.candidateId));return{endpoints,aggregates:aggregateVolatilityEndpoints(endpoints),candidateIds:[...candidateIds]}}
export function winningExitVolatility(report:VolatilityReport,policies:readonly {policyId:string;observations:readonly PolicyObservation[]}[],candidateIds:ReadonlySet<string>){
 const scoped=volatilityEndpointsForCandidates(report,candidateIds).endpoints;
 return policies.map(policy=>{const determinate=policy.observations.filter(x=>x.winningTrigger!==null),applicable=determinate.filter(x=>x.winningTrigger!=="settlement"),exact=applicable.flatMap(x=>{const endpoint=scoped.find(e=>e.candidateId===x.candidateId&&e.id===x.winningTrigger&&e.timestampUtc===x.valuationTimestamp);return endpoint?[endpoint]:[]}),any=exact.filter(x=>x.shortIv!==null||x.longIv!==null),short=exact.filter(x=>x.shortIv!==null),long=exact.filter(x=>x.longIv!==null),both=exact.filter(x=>x.shortIv!==null&&x.longIv!==null),ds=short.flatMap(x=>x.deltaShortIv===null?[]:[x.deltaShortIv]),dl=long.flatMap(x=>x.deltaLongIv===null?[]:[x.deltaLongIv]);return{policyId:policy.policyId,determinateN:determinate.length,ivApplicableN:applicable.length,settlementNotApplicableN:determinate.length-applicable.length,exactEndpointN:exact.length,anyLegObservedN:any.length,shortObservedN:short.length,longObservedN:long.length,bothObservedN:both.length,shortDeltaN:ds.length,longDeltaN:dl.length,bothDeltaN:exact.filter(x=>x.deltaShortIv!==null&&x.deltaLongIv!==null).length,completelyUnavailableN:applicable.length-any.length,medianEntryShortIv:quantiles(short.flatMap(x=>x.entryShortIv===null?[]:[x.entryShortIv])).median,medianExitShortIv:quantiles(short.map(x=>x.shortIv!)).median,medianDeltaShortIv:quantiles(ds).median,medianEntryLongIv:quantiles(long.flatMap(x=>x.entryLongIv===null?[]:[x.entryLongIv])).median,medianExitLongIv:quantiles(long.map(x=>x.longIv!)).median,medianDeltaLongIv:quantiles(dl).median,shortCompressionShare:ds.length?ds.filter(x=>x<0).length/ds.length:null,shortExpansionShare:ds.length?ds.filter(x=>x>0).length/ds.length:null}})
}
export interface PathDiagnostic {candidateId:string;shortPoints:number;longPoints:number;timestampCountAnyObserved:number;timestampCountBothObserved:number;missingTimestampObservationRows:number;shortMin:number|null;shortMax:number|null;shortRange:number|null;longMin:number|null;longMax:number|null;longRange:number|null}
export interface VolatilityReport {executionIndependent:true;coverage:ReturnType<typeof projectVolatilityAnalytics>["coverage"];eventDenominator:number;structureDenominator:number;events:readonly Row[];structures:readonly Row[];structureSummary:{total:number;usable:number;reference:number;short:number;long:number;both:number;unavailable:number};structureCoverage:{short:AvailabilityTally;long:AvailabilityTally;both:AvailabilityTally};aggregates:Readonly<Record<string,ReturnType<typeof quantiles>>>;endpoints:readonly VolatilityEndpoint[];endpointAggregates:readonly EndpointAggregate[];endpointCoverage:{short:AvailabilityTally;long:AvailabilityTally;both:AvailabilityTally};endpointSummary:{attempts:number;candidateAttempts:number;candidatesUsable:number;endpointShortObserved:number;endpointLongObserved:number;endpointBothObserved:number;shortDeltaUsable:number;longDeltaUsable:number;bothDeltaUsable:number;unavailableCandidates:number;attemptReasons:Readonly<Record<string,number>>;candidateReasons:Readonly<Record<string,number>>};paths:readonly PathDiagnostic[];pathSummary:{zero:number;one:number;multiple:number;shortTwoPlus:number;longTwoPlus:number;bothTwoPlus:number;medianShort:number|null;medianLong:number|null;histogram:readonly {points:number;candidates:number}[]}}

/** Descriptive market-IV analytics. Pricing/reconstructed IV is never admitted. */
export function buildVolatilityReport(dataset:AnalysisDataset):VolatilityReport{
 const p=projectVolatilityAnalytics(dataset.tables),candidateHorizon=new Map((dataset.tables.candidates??[]).map(r=>[String(r.candidate_id),n(r.target_horizon_days)])),structures=p.structures.map(r=>({...r,target_horizon_days:n(r.target_horizon_days)??candidateHorizon.get(String(r.candidate_id))??null}) as Row);
 const ids=structures.map(r=>String(r.candidate_id));if(new Set(ids).size!==ids.length)throw new Error("Integrity failure: structure_volatility_state must contain exactly one row per candidate_id.");
 const eventDenominator=dataset.tables.events?.length??p.events.length,structureDenominator=new Set((dataset.tables.candidates??[]).map(x=>String(x.candidate_id))).size||structures.length;
 const shortN=structures.filter(x=>volatilityLeg(x,"short")).length,longN=structures.filter(x=>volatilityLeg(x,"long")).length,bothN=structures.filter(x=>volatilityLeg(x,"short")&&volatilityLeg(x,"long")).length;
 const referenceN=structures.filter(x=>n((x.same_expiry_reference as Row|undefined)?.iv_decimal)!==null).length,usableN=structures.filter(hasUsableStructureVolatility).length;
 const metrics:Record<string,number[]>={short_iv:[],long_iv:[],reference_iv:[],short_minus_reference_iv:[],long_minus_reference_iv:[],short_minus_long_iv:[]};
 for(const r of structures){for(const [k,v] of [["short_iv",n(volatilityLeg(r,"short")?.iv_decimal)],["long_iv",n(volatilityLeg(r,"long")?.iv_decimal)],["reference_iv",n((r.same_expiry_reference as Row|undefined)?.iv_decimal)]] as const)if(v!==null)metrics[k]!.push(v);for(const k of ["short_minus_reference_iv","long_minus_reference_iv","short_minus_long_iv"]){const v=n(volatilityDiff(r,k)?.value);if(v!==null)metrics[k]!.push(v)}}
 const endpoints:VolatilityEndpoint[]=[];
 const labels:Record<string,string>={"4h":"+4h","12h":"+12h","1d":"+1D","3d":"+3D",vpoc:"VPOC",invalidation:"Invalidation",credit_capture_50:"50% capture",credit_capture_70:"70% capture",fixed_3d:"Fixed 3D",fixed_5d:"Fixed 5D",fixed_7d:"Fixed 7D",settlement:"Settlement"};
 const marketTarget=(v:unknown):Row|null=>{const x=v&&typeof v==="object"?v as Row:null;return x?.status==="available"&&n(x.iv_decimal)!==null&&x.source==="deribit_trade_iv"?x:null};
 for(const r of structures){const id=String(r.candidate_id),baseS=n(volatilityLeg(r,"short")?.iv_decimal),baseL=n(volatilityLeg(r,"long")?.iv_decimal);for(const point of rows(r.post_entry_market_iv)){const key=String(point.endpoint_id),ps=marketTarget(point.short),pl=marketTarget(point.long),sv=n(ps?.iv_decimal),lv=n(pl?.iv_decimal),ds=baseS!==null&&sv!==null?sv-baseS:null,dl=baseL!==null&&lv!==null?lv-baseL:null,ok=ds!==null||dl!==null,shortDeltaReason=ds!==null?null:sv===null?"endpoint_short_iv_unavailable":"entry_short_iv_unavailable",longDeltaReason=dl!==null?null:lv===null?"endpoint_long_iv_unavailable":"entry_long_iv_unavailable",reason=[shortDeltaReason,longDeltaReason].filter(Boolean).join(" · ")||null;endpoints.push({id:key,label:labels[key]??key,candidateId:id,timestampUtc:s(point.target_timestamp_utc),entryShortIv:baseS,shortIv:sv,deltaShortIv:ds,shortDeltaReason,entryLongIv:baseL,longIv:lv,deltaLongIv:dl,longDeltaReason,status:ok?"available":"unavailable",reason})}}

 const endpointAggregates=aggregateVolatilityEndpoints(endpoints);
 const paths=structures.map(r=>{const id=String(r.candidate_id),points=rows(r.market_iv_path),ss=points.flatMap(x=>{const z=marketTarget(x.short);return z?[n(z.iv_decimal)!]:[]}),ll=points.flatMap(x=>{const z=marketTarget(x.long);return z?[n(z.iv_decimal)!]:[]}),timestamps=new Map<string,{short:boolean;long:boolean}>();let missingTimestampObservationRows=0;for(const x of points){const short=marketTarget(x.short)!==null,long=marketTarget(x.long)!==null,key=s(x.target_timestamp_utc);if(!key){if(short||long)missingTimestampObservationRows++;continue}const state=timestamps.get(key)??{short:false,long:false};state.short ||= short;state.long ||= long;timestamps.set(key,state)}const timestampCountAnyObserved=[...timestamps.values()].filter(x=>x.short||x.long).length,timestampCountBothObserved=[...timestamps.values()].filter(x=>x.short&&x.long).length,q=(values:number[])=>({min:values.length?Math.min(...values):null,max:values.length?Math.max(...values):null}),a=q(ss),b=q(ll);return{candidateId:id,shortPoints:ss.length,longPoints:ll.length,timestampCountAnyObserved,timestampCountBothObserved,missingTimestampObservationRows,shortMin:a.min,shortMax:a.max,shortRange:a.min!==null&&a.max!==null?a.max-a.min:null,longMin:b.min,longMax:b.max,longRange:b.min!==null&&b.max!==null?b.max-b.min:null}});
 const endpointShort=endpoints.filter(x=>x.shortIv!==null).length,endpointLong=endpoints.filter(x=>x.longIv!==null).length,endpointBoth=endpoints.filter(x=>x.shortIv!==null&&x.longIv!==null).length;
 const candidateAttempts=new Set(endpoints.map(x=>x.candidateId)),candidatesUsable=new Set(endpoints.filter(x=>x.status==="available").map(x=>x.candidateId)),attemptReasons=endpoints.filter(x=>x.status==="unavailable").reduce<Record<string,number>>((a,x)=>{const key=x.reason??"unknown";a[key]=(a[key]??0)+1;return a},{}),unavailableIds=[...candidateAttempts].filter(id=>!candidatesUsable.has(id)),candidateReasons=unavailableIds.reduce<Record<string,number>>((a,id)=>{const reasons=endpoints.filter(x=>x.candidateId===id).map(x=>x.reason).filter((x):x is string=>x!==null),key=reasons.some(x=>x.includes("entry_"))?"entry_baseline_prevents_usable_delta":"no_usable_delta_iv";a[key]=(a[key]??0)+1;return a},{}),totals=paths.map(x=>x.timestampCountAnyObserved),histogram=[...new Set(totals)].sort((a,b)=>a-b).map(points=>({points,candidates:totals.filter(x=>x===points).length}));
 return{executionIndependent:true,coverage:p.coverage,eventDenominator,structureDenominator,events:p.events,structures,structureSummary:{total:structures.length,usable:usableN,reference:referenceN,short:shortN,long:longN,both:bothN,unavailable:structures.length-usableN},structureCoverage:{short:tally(shortN,structureDenominator,"short_market_iv_unavailable"),long:tally(longN,structureDenominator,"long_market_iv_unavailable"),both:tally(bothN,structureDenominator,"both_legs_not_observed")},aggregates:Object.fromEntries(Object.entries(metrics).map(([k,v])=>[k,quantiles(v)])),endpoints,endpointAggregates,endpointCoverage:{short:tally(endpointShort,endpoints.length,"endpoint_short_iv_unavailable"),long:tally(endpointLong,endpoints.length,"endpoint_long_iv_unavailable"),both:tally(endpointBoth,endpoints.length,"endpoint_both_iv_unavailable")},endpointSummary:{attempts:endpoints.length,candidateAttempts:candidateAttempts.size,candidatesUsable:candidatesUsable.size,endpointShortObserved:endpointShort,endpointLongObserved:endpointLong,endpointBothObserved:endpointBoth,shortDeltaUsable:endpoints.filter(x=>x.deltaShortIv!==null).length,longDeltaUsable:endpoints.filter(x=>x.deltaLongIv!==null).length,bothDeltaUsable:endpoints.filter(x=>x.deltaShortIv!==null&&x.deltaLongIv!==null).length,unavailableCandidates:unavailableIds.length,attemptReasons,candidateReasons},paths,pathSummary:{zero:totals.filter(x=>x===0).length,one:totals.filter(x=>x===1).length,multiple:totals.filter(x=>x>=2).length,shortTwoPlus:paths.filter(x=>x.shortPoints>=2).length,longTwoPlus:paths.filter(x=>x.longPoints>=2).length,bothTwoPlus:paths.filter(x=>x.timestampCountBothObserved>=2).length,medianShort:quantiles(paths.map(x=>x.shortPoints)).median,medianLong:quantiles(paths.map(x=>x.longPoints)).median,histogram}};
}
