/** Production-truth volatility acceptance: same store, materializer and bundle builder as the local endpoint. */
import {resolve} from "node:path";
import {ResearchSelectionService} from "./research-selection-service.ts";
import {materializeVolatilityStates} from "./materialize-volatility-states.ts";
import {buildResearchBundle,validateResearchBundle} from "../app/lib/research-bundle.ts";
import {buildVolatilityReport} from "../app/lib/volatility/volatility-report.ts";
import type {AnalysisDataset} from "../app/lib/research-analysis.ts";
const id=process.argv[2];if(!id)throw new Error("Usage: npm run audit:volatility-production -- <dataset-id> [selection-directory]");
const directory=resolve(process.argv[3]??"data/research-selections"),store=await new ResearchSelectionService(directory).read(id),volatility=await materializeVolatilityStates(store),bundle=buildResearchBundle(store,new Date().toISOString(),undefined,{volatility}),valid=validateResearchBundle(bundle.files);if(!valid.ok)throw new Error(valid.errors.join("\n"));
const tables=Object.fromEntries(Object.entries(bundle.files).filter(([name])=>name.endsWith(".jsonl")).map(([name,text])=>[name.replace(".jsonl",""),text.split(/\r?\n/).filter(Boolean).map(line=>JSON.parse(line))]));
const dataset={filename:`${id}.zip`,schemaVersion:String(bundle.run.schema_version),migratedFrom:null,run:bundle.run,tables,counts:{},venues:[],sourceRuns:[],eventUniverseComplete:true,capabilities:[]} as unknown as AnalysisDataset,report=buildVolatilityReport(dataset),events=volatility.events??[],structures=volatility.structures??[];
const available=(collection:unknown,key:string,value:string)=>Array.isArray(collection)&&(collection as Record<string,unknown>[]).some(x=>x[key]===value&&x.status==="available");
const eventMetric=(collection:string,key:string,values:readonly string[])=>Object.fromEntries(values.map(value=>[value,events.filter(e=>available((e as unknown as Record<string,unknown>)[collection],key,value)).length]));
const post=Object.fromEntries(report.endpointAggregates.map(x=>[x.id,{short:`${x.shortN}/${x.denominator}`,long:`${x.longN}/${x.denominator}`,both:`${x.bothN}/${x.denominator}`}]))
const shortPath=report.paths.map(x=>x.shortPoints),longPath=report.paths.map(x=>x.longPoints),hist=(xs:number[])=>Object.fromEntries([...new Set(xs)].sort((a,b)=>a-b).map(x=>[x,xs.filter(y=>y===x).length]));
process.stdout.write(JSON.stringify({dataset_id:id,state:{events:`${events.length}/${store.events.length}`,structures:`${structures.length}/${store.events.reduce((sum,e)=>sum+e.selectedStructures.length,0)}`},event:{reference_iv:eventMetric("reference_iv","nominal_tenor",["7d","14d","30d"]),realized_volatility:eventMetric("realized_volatility","horizon",["1d","3d","7d","14d","30d"]),percentile:eventMetric("reference_iv_percentile","nominal_tenor",["7d","14d","30d"]),dvol:events.filter(e=>e.broad_volatility_index.status==="available").length},structure:{same_expiry_reference:structures.filter(x=>x.same_expiry_reference.status==="available").length,short:structures.filter(x=>x.legs.find(l=>l.leg==="short")?.status==="available").length,long:structures.filter(x=>x.legs.find(l=>l.leg==="long")?.status==="available").length,both:structures.filter(x=>x.legs.every(l=>l.status==="available")).length},post_entry:post,path:{candidates_with_short:shortPath.filter(x=>x>0).length,candidates_with_long:longPath.filter(x=>x>0).length,short_point_distribution:hist(shortPath),long_point_distribution:hist(longPath)}},null,2)+"\n");
