#!/usr/bin/env node
import {mkdir,readFile,writeFile} from "node:fs/promises";
import {join} from "node:path";
import {fileURLToPath} from "node:url";
import {buildCalibrationObservation,CALIBRATION_EVIDENCE_CONTEXT_MINUTES,calibrationContentHash,calibrationRawShardId,calibrationTargets,CausalFeatureIndex,EXECUTION_CALIBRATION_DATASET_ID,EXECUTION_CALIBRATION_METHOD_VERSION} from "../app/lib/execution-calibration.ts";
import {dedupePrints} from "../app/lib/volatility/cross-section.ts";
import {LOCAL_ARCHIVE_MANIFEST,LOCAL_ARCHIVE_SOURCE,previousUtcDate,readLocalDay,type ArchiveManifest} from "./local-contract-archive.ts";
const DAY=86_400_000,MIN=60_000,DTE_MIN=1,DTE_MAX=46,MAX_MONEYNESS=.35,ROOT=".local-cache/execution-calibration";
export async function buildLocalCalibrationRange(tapeRoot:string,start:string,end:string,outputRoot=ROOT){const startMs=Date.parse(`${start}T00:00:00Z`),endMs=Date.parse(`${end}T00:00:00Z`);if(!Number.isFinite(startMs)||!Number.isFinite(endMs)||endMs<=startMs)throw new Error("end is exclusive and must follow start");const archive=JSON.parse(await readFile(join(tapeRoot,LOCAL_ARCHIVE_MANIFEST),"utf8")) as ArchiveManifest,base=join(outputRoot,EXECUTION_CALIBRATION_DATASET_ID);await mkdir(base,{recursive:true});const shards=[];
 for(let at=startMs;at<endMs;at+=DAY){const date=new Date(at).toISOString().slice(0,10),next=at+DAY,evidenceStart=at-CALIBRATION_EVIDENCE_CONTEXT_MINUTES*MIN,tape=[...await readLocalDay(tapeRoot,previousUtcDate(date)),...await readLocalDay(tapeRoot,date)].filter(r=>r.timestampMs>=evidenceStart&&r.timestampMs<next),deduped=[...dedupePrints(tape).prints],targets=calibrationTargets(deduped,at,next).filter(t=>{const dte=(t.expiryTimestampMs-t.timestampMs)/DAY;return dte>=DTE_MIN&&dte<=DTE_MAX}),features=new CausalFeatureIndex(deduped),sourceWindowComplete=archive.coverage_start!==null&&Date.parse(archive.coverage_start)<=evidenceStart,rawId=calibrationRawShardId(at,next,evidenceStart),rawHash=archive.data_content_fingerprint;
  const rows=targets.map(target=>buildCalibrationObservation({target,tape:deduped,features:features.features(target),sourceHost:LOCAL_ARCHIVE_SOURCE,retrievalShardId:rawId,retrievalContentHash:rawHash,sourceWindowComplete,directionSemanticsVerified:true})).filter(row=>row.log_moneyness===null||Math.abs(row.log_moneyness)<=MAX_MONEYNESS),hash=calibrationContentHash(rows),file=join(base,`${rawId}.${hash}.observations.jsonl`);await writeFile(file,rows.map(row=>JSON.stringify(row)).join("\n")+(rows.length?"\n":""));shards.push({id:rawId,file,row_count:rows.length,observation_content_hash:hash,raw_content_hash:rawHash,source_window_complete:sourceWindowComplete})}
 const manifest={dataset_id:EXECUTION_CALIBRATION_DATASET_ID,method_version:EXECUTION_CALIBRATION_METHOD_VERSION,source_host:LOCAL_ARCHIVE_SOURCE,source_provenance:{type:"observed_deribit_trades",archive_fingerprint:archive.data_content_fingerprint,archive_manifest:join(tapeRoot,LOCAL_ARCHIVE_MANIFEST),network_required:false},source_window_complete:shards.every(shard=>shard.source_window_complete),filter_configuration:{dte_days:[DTE_MIN,DTE_MAX],absolute_log_moneyness_max:MAX_MONEYNESS,evidence_context_minutes:CALIBRATION_EVIDENCE_CONTEXT_MINUTES,strictly_prior_evidence:true},target_start_utc:new Date(startMs).toISOString(),target_end_exclusive_utc:new Date(endMs).toISOString(),shards};const path=join(base,`local-manifest.${start}.${end}.${archive.data_content_fingerprint}.json`);await writeFile(path,JSON.stringify(manifest,null,2)+"\n");return manifest}
const [root,start,end]=process.argv.slice(2);if(process.argv[1]&&fileURLToPath(import.meta.url)===process.argv[1]){if(!root||!start||!end)throw new Error("usage: build-execution-calibration-local-range.ts TAPE_ROOT YYYY-MM-DD YYYY-MM-DD");console.log(JSON.stringify(await buildLocalCalibrationRange(root,start,end),null,2))}