#!/usr/bin/env node
import {createReadStream,createWriteStream} from "node:fs";
import {mkdir,mkdtemp,readFile,readdir,rm,rename,writeFile} from "node:fs/promises";
import {createHash} from "node:crypto";
import {createInterface} from "node:readline";
import {join,resolve} from "node:path";
import {tmpdir} from "node:os";
import {fileURLToPath} from "node:url";
import {calibrationEconomicIdentity,compileCalibrationRow,EMPIRICAL_TAKER_EXECUTION_VERSION,EXECUTION_BUCKET_POLICY_VERSION,QUANTILE_METHOD,type EmpiricalCalibrationRow} from "../app/lib/empirical-taker-execution.ts";
import {EXECUTION_CALIBRATION_DATASET_ID,EXECUTION_CALIBRATION_METHOD_VERSION,type ExecutionCalibrationObservation} from "../app/lib/execution-calibration.ts";
import {EXECUTION_ESTIMATOR_STORAGE_VERSION,type ExecutionEstimatorManifest} from "./execution-estimator-artifact.ts";

const ID_PARTITIONS=256;
async function files(root:string):Promise<string[]>{const out:string[]=[];for(const name of await readdir(root,{withFileTypes:true})){const path=join(root,name.name);if(name.isDirectory())out.push(...await files(path));else if(/\.(ndjson|jsonl)$/.test(name.name))out.push(path)}return out.sort()}
async function lines(path:string,visit:(line:string)=>Promise<void>|void){const input=createInterface({input:createReadStream(path),crlfDelay:Infinity});let n=0;for await(const line of input){n++;if(!line.trim())continue;try{await visit(line)}catch(error){throw new Error(`${path}:${n}: ${(error as Error).message}`)}}}
const hash=(s:string)=>createHash("sha256").update(s).digest("hex");
const write=(stream:ReturnType<typeof createWriteStream>,value:string)=>new Promise<void>((ok,fail)=>stream.write(value,(error?:Error|null)=>error?fail(error):ok()));
const close=(stream:ReturnType<typeof createWriteStream>)=>new Promise<void>((ok,fail)=>stream.end((error?:Error|null)=>error?fail(error):ok()));
type Progress={filesRead:number;rowsRead:number;eligibleRows:number;flushedPartitions:number;currentTargetMonth:string|null;outputBytes:number};
export interface CompileOptions{onProgress?:(progress:Readonly<Progress>)=>void;identityPartitions?:number}
/** Two-pass bounded compiler: hash-partition identities, then flush one month at a time. */
export async function compileExecutionEstimator(root:string,output:string,options:CompileOptions={}):Promise<ExecutionEstimatorManifest>{const count=options.identityPartitions??ID_PARTITIONS,temp=await mkdtemp(join(tmpdir(),"execution-estimator-")),progress:Progress={filesRead:0,rowsRead:0,eligibleRows:0,flushedPartitions:0,currentTargetMonth:null,outputBytes:0};try{
 const inputs=await files(root),spools=Array.from({length:count},(_,i)=>createWriteStream(join(temp,`identity-${i}.jsonl`)));for(const path of inputs){await lines(path,async line=>{progress.rowsRead++;let value:ExecutionCalibrationObservation;try{value=JSON.parse(line) as ExecutionCalibrationObservation}catch{throw new Error("malformed JSON")};if(!value||typeof value!=="object")throw new Error("observation must be an object");if(value.method_version!==EXECUTION_CALIBRATION_METHOD_VERSION||!value.taker_concession_eligible||!value.trade_id)return;const bucket=parseInt(hash(value.trade_id).slice(0,8),16)%count;await write(spools[bucket]!,JSON.stringify(value)+"\n")});progress.filesRead++;options.onProgress?.({...progress})}await Promise.all(spools.map(close));
 const monthStreams=new Map<string,ReturnType<typeof createWriteStream>>(),days=new Set<string>(),groups=new Set<string>();let start:number|null=null,end:number|null=null;for(let p=0;p<count;p++){const identities=new Map<string,string>();await lines(join(temp,`identity-${p}.jsonl`),async line=>{const value=JSON.parse(line) as ExecutionCalibrationObservation,id=value.trade_id!,identity=calibrationEconomicIdentity(value),prior=identities.get(id);if(prior!==undefined){if(prior!==identity)throw new Error(`Conflicting economic fields for duplicate trade_id ${id}`);return}identities.set(id,identity);const row=compileCalibrationRow(value);if(!row)return;const month=new Date(row.timestampMs).toISOString().slice(0,7),stream=monthStreams.get(month)??createWriteStream(join(temp,`month-${month}.jsonl`));monthStreams.set(month,stream);await write(stream,JSON.stringify(row)+"\n");progress.eligibleRows++;days.add(row.calendarDate);groups.add(row.expiryDayGroup);start=start===null?row.timestampMs:Math.min(start,row.timestampMs);end=end===null?row.timestampMs:Math.max(end,row.timestampMs)});progress.flushedPartitions++;options.onProgress?.({...progress})}await Promise.all([...monthStreams.values()].map(close));
 const staging=`${output}.staging-${process.pid}`;await rm(staging,{recursive:true,force:true});await mkdir(join(staging,"shards"),{recursive:true});const shardMeta:ExecutionEstimatorManifest["shards"]=[],logical=createHash("sha256"),idHash=createHash("sha256");for(const month of [...monthStreams.keys()].sort()){progress.currentTargetMonth=month;const rows:EmpiricalCalibrationRow[]=[];await lines(join(temp,`month-${month}.jsonl`),line=>{rows.push(JSON.parse(line) as EmpiricalCalibrationRow)});rows.sort((a,b)=>a.timestampMs-b.timestampMs||a.tradeId.localeCompare(b.tradeId));for(const row of rows)idHash.update(row.tradeId).update("\n");const columns={timestampMs:rows.map(r=>r.timestampMs),action:rows.map(r=>r.action==="buy"?0:1),dteBand:rows.map(r=>["1-3","3-7","7-14","14-30","30-46"].indexOf(r.dteBand)),amountBand:rows.map(r=>r.amountBand==="small"?0:1),concessionVolPoints:rows.map(r=>r.concessionVolPoints),referenceErrorVolPoints:rows.map(r=>r.referenceErrorVolPoints),calendarDate:rows.map(r=>r.calendarDate),expiryDayGroup:rows.map(r=>r.expiryDayGroup)},body=JSON.stringify(columns)+"\n",relative=`shards/${month}.columns.json`;await writeFile(join(staging,relative),body);const contentHash=hash(body);logical.update(month).update("\0").update(contentHash);progress.outputBytes+=Buffer.byteLength(body);shardMeta.push({path:relative,month,rowCount:rows.length,contentHash});options.onProgress?.({...progress})}
 let archiveFingerprint:string|undefined;for(const name of await readdir(root)){if(!name.includes("manifest")||!name.endsWith(".json"))continue;try{const v=JSON.parse(await readFile(join(root,name),"utf8")) as {source_provenance?:{archive_fingerprint?:string}};archiveFingerprint??=v.source_provenance?.archive_fingerprint}catch{/* unrelated manifest */}}
 const base={datasetId:EXECUTION_CALIBRATION_DATASET_ID,methodVersion:EXECUTION_CALIBRATION_METHOD_VERSION,estimatorVersion:EMPIRICAL_TAKER_EXECUTION_VERSION,bucketPolicyVersion:EXECUTION_BUCKET_POLICY_VERSION,quantileMethod:QUANTILE_METHOD,storageFormatVersion:EXECUTION_ESTIMATOR_STORAGE_VERSION,sourceDatasetFingerprint:idHash.digest("hex"),...(archiveFingerprint?{sourceArchiveFingerprint:archiveFingerprint}:{}),coverageStartMs:start,coverageEndMs:end,tradeCount:progress.eligibleRows,eligibleTradeCount:progress.eligibleRows,uniqueDays:days.size,uniqueExpiryDayGroups:groups.size,shardCount:shardMeta.length,shards:shardMeta},artifactHash=hash(JSON.stringify(base)+"\n"+logical.digest("hex")),manifest={...base,artifactHash};const manifestBody=JSON.stringify(manifest,null,2)+"\n";await writeFile(join(staging,"manifest.json"),manifestBody);progress.outputBytes+=Buffer.byteLength(manifestBody);await rm(output,{recursive:true,force:true});await rename(staging,output);options.onProgress?.({...progress});return manifest
 }finally{await rm(temp,{recursive:true,force:true})}}
async function main(){const root=process.argv[2],output=process.argv[3];if(!root||!output)throw new Error("Usage: node --experimental-strip-types scripts/compile-execution-estimator.ts <v4-cache-root> <artifact-directory>");const artifact=await compileExecutionEstimator(resolve(root),resolve(output),{onProgress:p=>console.error(JSON.stringify(p))});console.log(JSON.stringify(artifact,null,2))}
if(process.argv[1]&&fileURLToPath(import.meta.url)===process.argv[1])await main();
