import {readFile,stat} from "node:fs/promises";
import {createHash} from "node:crypto";
import {dirname,join} from "node:path";
import {amountBand,CONDITIONAL_SUPPORT,dteBand,EXECUTION_BUCKET_POLICY_VERSION,GLOBAL_SUPPORT,QUANTILE_METHOD,quantileR7,ExecutionCalibrationIndex,validateExecutionEstimatorArtifact,type AmountBand,type BucketEstimate,type DteBand,type ExecutionEstimatorArtifact,type ReferenceEstimate,type TakerAction} from "../app/lib/empirical-taker-execution.ts";
import {EXECUTION_CALIBRATION_DATASET_ID,EXECUTION_CALIBRATION_METHOD_VERSION} from "../app/lib/execution-calibration.ts";

export const EXECUTION_ESTIMATOR_STORAGE_VERSION="partitioned-columns-v1" as const;
type Columns={timestampMs:number[];action:number[];dteBand:number[];amountBand:number[];concessionVolPoints:number[];referenceErrorVolPoints:number[];calendarDate:string[];expiryDayGroup:string[]};
export interface ExecutionEstimatorManifest{datasetId:string;methodVersion:string;estimatorVersion:string;bucketPolicyVersion:string;quantileMethod:string;storageFormatVersion:typeof EXECUTION_ESTIMATOR_STORAGE_VERSION;sourceDatasetFingerprint:string;sourceArchiveFingerprint?:string;coverageStartMs:number|null;coverageEndMs:number|null;tradeCount:number;eligibleTradeCount:number;uniqueDays:number;uniqueExpiryDayGroups:number;shardCount:number;artifactHash:string;shards:Array<{path:string;month:string;rowCount:number;contentHash:string}>}
const bands:DteBand[]=["1-3","3-7","7-14","14-30","30-46"],amounts:AmountBand[]=["small","larger"];
const isManifest=(v:unknown):v is ExecutionEstimatorManifest=>!!v&&typeof v==="object"&&(v as ExecutionEstimatorManifest).storageFormatVersion===EXECUTION_ESTIMATOR_STORAGE_VERSION;
function validateManifest(v:unknown):ExecutionEstimatorManifest{if(!isManifest(v))throw new Error("Invalid partitioned execution estimator manifest");if(v.datasetId!==EXECUTION_CALIBRATION_DATASET_ID||v.methodVersion!==EXECUTION_CALIBRATION_METHOD_VERSION||v.bucketPolicyVersion!==EXECUTION_BUCKET_POLICY_VERSION||v.quantileMethod!==QUANTILE_METHOD)throw new Error("Incompatible partitioned execution estimator manifest");if(!Array.isArray(v.shards)||v.shardCount!==v.shards.length||v.tradeCount!==v.eligibleTradeCount)throw new Error("Invalid partitioned execution estimator summary");return v}
const support=(indices:readonly number[],c:Columns)=>({tradeCount:indices.length,calendarDayCount:new Set(indices.map(i=>c.calendarDate[i]!)).size,expiryDayGroupCount:new Set(indices.map(i=>c.expiryDayGroup[i]!)).size});
const adequate=(s:ReturnType<typeof support>,global=false)=>s.tradeCount>=(global?GLOBAL_SUPPORT.trades:CONDITIONAL_SUPPORT.trades)&&s.calendarDayCount>=10&&s.expiryDayGroupCount>=20;
/** Compact, immutable column store. Queries are memoized at the modeled-execution key granularity. */
export class PartitionedExecutionCalibrationIndex{
 readonly artifact:ExecutionEstimatorArtifact;readonly #c:Columns;readonly #executionCache=new Map<string,BucketEstimate|null>();readonly #referenceCache=new Map<string,ReferenceEstimate|null>();
 constructor(manifest:ExecutionEstimatorManifest,columns:Columns){this.#c=columns;this.artifact={...manifest,rows:[]} as unknown as ExecutionEstimatorArtifact}
 execution(target:{action:TakerAction;dteDays:number;amount:number;forwardMoneyness:number;cutoffMs:number}):BucketEstimate|null{const band=dteBand(target.dteDays);if(!band||Math.abs(target.forwardMoneyness)>.35)return null;const ab=amountBand(target.amount),key=`${target.cutoffMs}|${target.action}|${band}|${ab}`;if(this.#executionCache.has(key))return this.#executionCache.get(key)!;const ai=target.action==="buy"?0:1,di=bands.indexOf(band),mi=amounts.indexOf(ab),all:number[]=[];for(let i=0;i<this.#c.timestampMs.length&&this.#c.timestampMs[i]!<target.cutoffMs;i++)all.push(i);const levels=[{name:"action_dte_amount" as const,x:all.filter(i=>this.#c.action[i]===ai&&this.#c.dteBand[i]===di&&this.#c.amountBand[i]===mi)},{name:"action_dte" as const,x:all.filter(i=>this.#c.action[i]===ai&&this.#c.dteBand[i]===di)},{name:"action" as const,x:all.filter(i=>this.#c.action[i]===ai)},{name:"global" as const,x:all}];let result:BucketEstimate|null=null;for(const level of levels){const s=support(level.x,this.#c);if(adequate(s,level.name==="global")){const values=level.x.map(i=>this.#c.concessionVolPoints[i]!);result={fallbackLevel:level.name,...s,q50VolPoints:quantileR7(values,.5)!,q90VolPoints:quantileR7(values,.9)!,dteBand:band,amountBand:ab};break}}this.#executionCache.set(key,result);return result}
 reference(target:{dteDays:number;cutoffMs:number}):ReferenceEstimate|null{const band=dteBand(target.dteDays);if(!band)return null;const key=`${target.cutoffMs}|${band}`;if(this.#referenceCache.has(key))return this.#referenceCache.get(key)!;const di=bands.indexOf(band),all:number[]=[];for(let i=0;i<this.#c.timestampMs.length&&this.#c.timestampMs[i]!<target.cutoffMs;i++)all.push(i);const levels=[{name:"dte" as const,x:all.filter(i=>this.#c.dteBand[i]===di)},{name:"global" as const,x:all}];let result:ReferenceEstimate|null=null;for(const level of levels){const s=support(level.x,this.#c);if(adequate(s,level.name==="global")){result={fallbackLevel:level.name,...s,q90VolPoints:quantileR7(level.x.map(i=>this.#c.referenceErrorVolPoints[i]!),.9)!,dteBand:band};break}}this.#referenceCache.set(key,result);return result}
}
export type ExecutionCalibrationProvider=ExecutionCalibrationIndex|PartitionedExecutionCalibrationIndex;
/** Load either a legacy portable JSON file, a manifest, or an artifact directory. */
export async function loadExecutionCalibration(path:string):Promise<ExecutionCalibrationProvider>{let candidate=path;if((await stat(path)).isDirectory())candidate=join(path,"manifest.json");let parsed:unknown;try{parsed=JSON.parse(await readFile(candidate,"utf8"))}catch(error){throw new Error(`Unable to read execution estimator artifact ${candidate}: ${(error as Error).message}`)}if(!isManifest(parsed))return new ExecutionCalibrationIndex(validateExecutionEstimatorArtifact(parsed));const manifest=validateManifest(parsed),root=dirname(candidate),combined:Columns={timestampMs:[],action:[],dteBand:[],amountBand:[],concessionVolPoints:[],referenceErrorVolPoints:[],calendarDate:[],expiryDayGroup:[]},logical=createHash("sha256");for(const shard of manifest.shards){const body=await readFile(join(root,shard.path),"utf8"),digest=createHash("sha256").update(body).digest("hex");if(digest!==shard.contentHash)throw new Error(`Partitioned estimator shard hash mismatch: ${shard.path}`);logical.update(shard.month).update("\0").update(digest);const columns=JSON.parse(body) as Columns,keys=Object.keys(combined) as Array<keyof Columns>;if(keys.some(key=>!Array.isArray(columns[key])||columns[key].length!==shard.rowCount))throw new Error(`Partitioned estimator malformed columns: ${shard.path}`);for(const key of keys)for(const value of columns[key] as Array<number|string>)(combined[key] as Array<number|string>).push(value)}const {artifactHash,...base}=manifest,expected=createHash("sha256").update(JSON.stringify(base)+"\n"+logical.digest("hex")).digest("hex");if(expected!==artifactHash)throw new Error("Partitioned estimator logical artifact hash mismatch");if(combined.timestampMs.length!==manifest.tradeCount||combined.timestampMs.some((v,i)=>i>0&&combined.timestampMs[i-1]!>v))throw new Error("Partitioned estimator row count/order does not match manifest");return new PartitionedExecutionCalibrationIndex(manifest,combined)}
