import type {ResearchSelectionStore} from "../app/lib/research-selections.ts";
import type {ResearchVolatilityStates} from "../app/lib/research-bundle.ts";
import {resolveEventTiming} from "../app/lib/event-timing.ts";
import {canonicalOutcomeId} from "../app/lib/research-outcomes.ts";
import {buildEventVolatilityState,buildStructureVolatilityState,type BroadVolatilityState,type LegVolatilitySnapshot} from "../app/lib/volatility/volatility-state.ts";
import {DERIBIT_OPTION_INDEX_UNDERLYING,DVOL_FIRST_AVAILABLE_MS,DVOL_METHOD_VERSION,DVOL_SERIES_ID,OPTION_HISTORY_HOST,REFERENCE_SERIES_ID,buildExpiryReferenceRow,buildReferenceSeriesRows,buildUnavailableReferenceSeriesRows,isCurrentReferenceRow,isReferenceTimestampComplete,referenceSeriesContentHash,type ListedExpiry,type ReferenceSeriesRow} from "../app/lib/volatility/reference-series.ts";
import {MARKET_IV_MAX_AGE_MINUTES,type RawIvTradeCandidate} from "../app/lib/volatility/market-iv-evidence.ts";
import {causalIvPercentile,MINIMUM_PRIOR_OBSERVATIONS,type ReferenceObservation} from "../app/lib/volatility/iv-percentile.ts";
import {HOUR_MS,realizedVolatilityProfile,type HourlyClose} from "../app/lib/volatility/realized-volatility.ts";
import {DeribitPerpetualHistoryService} from "./deribit-perpetual-history.ts";
import {VolatilityReferenceRetrieval,listCachedShards,readDvolShard,readReferenceShard,VOLATILITY_CACHE_ROOT,writeDvolShards,writeReferenceShards} from "./volatility-reference-cache.ts";

type R=Record<string,unknown>;const o=(v:unknown):R=>v&&typeof v==="object"&&!Array.isArray(v)?v as R:{};const a=(v:unknown):R[]=>Array.isArray(v)?v.map(o):[];const n=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:null;const s=(v:unknown)=>typeof v==="string"&&v?v:null;
const TENORS=["7d","14d","30d"] as const;
export const PERCENTILE_BACKFILL_BATCH_HOURS=168 as const;
export const MAX_PERCENTILE_BACKFILL_HOURS=5*366*24;

export interface VolatilityMaterializationRetrieval {readonly requestCount?:number;readonly localDayShardReads?:number;readonly localRowsScanned?:number;readonly exactBatchDayShardsRead?:number;instrumentManifest():ReturnType<VolatilityReferenceRetrieval["instrumentManifest"]>;ivTrades(name:string,start:number,end:number):ReturnType<VolatilityReferenceRetrieval["ivTrades"]>;ivTradesMany?(windows:ReadonlyMap<string,{start:number;end:number}>):Promise<Map<string,Awaited<ReturnType<VolatilityReferenceRetrieval["ivTrades"]>>>>;ivTradesByCurrency(start:number,end:number):ReturnType<VolatilityReferenceRetrieval["ivTradesByCurrency"]>;dvolRange(start:number,end:number):ReturnType<VolatilityReferenceRetrieval["dvolRange"]>}
export interface VolatilityMaterializationDiagnostics {volatilitySource:"local"|"http";referenceBackfillTargets:number;exactBatchDayShardsRead:number;localDayShardReads:number;localRowsScanned:number;percentileBatchRuns:number;percentileTargetsEvaluated:number;currentV2CachedTargetsReused:number;exactInstrumentsRequested:number;eventCrossSectionRequests:number;dvolRequests:number;referenceRetrievalHttpRequests:number;percentileMs:number;exactTapeMs:number;crossSectionMs:number;dvolMs:number;rvMs:number}
export interface VolatilityMaterializationDependencies {retrieval?:VolatilityMaterializationRetrieval;perpetualBars?:(startMs:number,endMs:number)=>Promise<HourlyClose[]>;populateMissing?:boolean;allowReferenceBackfill?:boolean;volatilitySource?:"local"|"http";historyHours?:number;diagnostics?:VolatilityMaterializationDiagnostics}
function eventEntry(event:ResearchSelectionStore["events"][number]){return resolveEventTiming({sourceRun:event.sourceRun,underlyingHourlyPath:event.generationSnapshot.underlyingHourlyPath}).entryTimestamp}
function instrumentNames(selected:ResearchSelectionStore["events"][number]["selectedStructures"][number]){const resolution=o(selected.contractResolution),candidate=o(selected.candidateSnapshot),legacy=o(candidate.instruments);return{short:s(o(resolution.short).instrumentName)??s(legacy.short),long:s(o(resolution.long).instrumentName)??s(legacy.long)}}
type Meta=Awaited<ReturnType<VolatilityReferenceRetrieval["instrumentManifest"]>>[number];type Trade=Awaited<ReturnType<VolatilityReferenceRetrieval["ivTrades"]>>[number];
function raw(meta:Meta,trade:Trade):RawIvTradeCandidate{return{instrumentName:meta.instrumentName,tradeId:trade.tradeId,tradeSeq:trade.tradeSeq,strike:meta.strike,optionType:meta.optionType,expiryTimestampMs:meta.expiryTimestampMs,settlementPeriod:meta.settlementPeriod,contractCreatedAtMs:meta.createdAtMs,timestampMs:trade.timestampMs,ivApiPercent:trade.ivApiPercent,indexPrice:trade.indexPrice}}
function leg(trades:readonly RawIvTradeCandidate[],instrument:string|null,target:number):LegVolatilitySnapshot|null{const hit=trades.filter(x=>x.instrumentName===instrument&&x.timestampMs<=target&&target-x.timestampMs<=MARKET_IV_MAX_AGE_MINUTES*60_000&&n(x.ivApiPercent)!==null&&x.ivApiPercent!>0).sort((x,y)=>y.timestampMs-x.timestampMs)[0];return hit?{ivDecimal:hit.ivApiPercent!/100,ivApiPercent:hit.ivApiPercent,ivSource:"deribit_trade_iv",ivSourceTimestampMs:hit.timestampMs,observation:"observed"}:null}
function listedAt(manifest:readonly Meta[],target:number):ListedExpiry[]{const groups=new Map<number,Meta[]>();for(const m of manifest)if(m.createdAtMs!==null&&m.createdAtMs<=target&&m.expiryTimestampMs>target)groups.set(m.expiryTimestampMs,[...(groups.get(m.expiryTimestampMs)??[]),m]);return[...groups].map(([expiryTimestampMs,ms])=>({expiryTimestampMs,createdAtMs:Math.min(...ms.map(x=>x.createdAtMs!)),settlementPeriod:ms[0]!.settlementPeriod,strikes:ms.map(x=>x.strike)}))}
function causalIndex(trades:readonly {timestampMs:number;indexPrice?:number|null}[],target:number){return [...trades].filter(x=>n(x.indexPrice)!==null&&x.timestampMs<=target&&target-x.timestampMs<=MARKET_IV_MAX_AGE_MINUTES*60_000).sort((x,y)=>y.timestampMs-x.timestampMs)[0]?.indexPrice??null}
function referenceRows(target:number,trades:readonly Trade[],manifest:readonly Meta[]):ReferenceSeriesRow[]{const byName=new Map(manifest.map(x=>[x.instrumentName,x])),candidates=trades.flatMap(t=>{const m=byName.get(t.instrumentName);return m?[raw(m,t)]:[]}),underlying=causalIndex(trades,target);return underlying===null?[...buildUnavailableReferenceSeriesRows({timestampMs:target,listedExpiries:listedAt(manifest,target),tenors:TENORS})]:[...buildReferenceSeriesRows({timestampMs:target,underlyingInstrument:DERIBIT_OPTION_INDEX_UNDERLYING,underlyingPrice:underlying,listedExpiries:listedAt(manifest,target),candidates,tenors:TENORS}).rows]}
function contiguousHourlyRuns(targets:readonly number[]):number[][]{const sorted=[...targets].sort((x,y)=>x-y),runs:number[][]=[];for(const target of sorted){const run=runs.at(-1),previous=run?.at(-1);if(run&&previous!==undefined&&target-previous===HOUR_MS)run.push(target);else runs.push([target])}return runs}
interface Targets{endpoints:{id:string;timestamp:number}[];path:number[]}
function selectedTargets(selected:ResearchSelectionStore["events"][number]["selectedStructures"][number],entry:number,expiry:number|null):Targets{const reference=o(selected.referenceValuation),path=a(reference.valuationPathSnapshot).map(x=>n(x.timestamp)).filter((x):x is number=>x!==null&&x>entry&&(expiry===null||x<expiry));const endpoints=[{id:"4h",timestamp:entry+4*HOUR_MS},{id:"12h",timestamp:entry+12*HOUR_MS},{id:"1d",timestamp:entry+24*HOUR_MS},{id:"3d",timestamp:entry+72*HOUR_MS}];for(const x of a(reference.outcomeSnapshots)){const id=canonicalOutcomeId(x.label),timestamp=n(x.valuationTimestamp);if(id&&["vpoc","invalidation","credit_capture_50","credit_capture_70","fixed_3d","fixed_5d","fixed_7d","settlement"].includes(id)&&timestamp!==null&&(expiry===null||timestamp<expiry))endpoints.push({id,timestamp})}return{endpoints:[...new Map(endpoints.filter(x=>x.timestamp>entry&&(expiry===null||x.timestamp<expiry)).map(x=>[x.id,x])).values()],path:[...new Set(path)].sort((x,y)=>x-y)}}

/** IO boundary: populate/reuse canonical caches, then build network-free bundle state rows. */
export async function materializeVolatilityStates(store:ResearchSelectionStore,cacheRoot:string=VOLATILITY_CACHE_ROOT,deps:VolatilityMaterializationDependencies={}):Promise<ResearchVolatilityStates>{
 const retrieval:VolatilityMaterializationRetrieval=deps.retrieval??new VolatilityReferenceRetrieval(),populate=deps.populateMissing??true,readOnlyReference=deps.allowReferenceBackfill===false,allowReferenceBackfill=deps.allowReferenceBackfill??populate,maxBackfillHours=deps.historyHours??MAX_PERCENTILE_BACKFILL_HOURS,batchTargetCount=Math.min(PERCENTILE_BACKFILL_BATCH_HOURS,maxBackfillHours+1);
 const diagnostics=deps.diagnostics,requestStart=retrieval.requestCount??0,dayReadsStart=retrieval.localDayShardReads??0,rowsStart=retrieval.localRowsScanned??0,batchReadsStart=retrieval.exactBatchDayShardsRead??0,reusedTargets=new Set<number>();if(diagnostics)Object.assign(diagnostics,{volatilitySource:deps.volatilitySource??"http",referenceBackfillTargets:0,exactBatchDayShardsRead:0,localDayShardReads:0,localRowsScanned:0,percentileBatchRuns:0,percentileTargetsEvaluated:0,currentV2CachedTargetsReused:0,exactInstrumentsRequested:0,eventCrossSectionRequests:0,dvolRequests:0,referenceRetrievalHttpRequests:0,percentileMs:0,exactTapeMs:0,crossSectionMs:0,dvolMs:0,rvMs:0});
 const targets=store.events.map(event=>({event,entry:eventEntry(event)}));for(const x of targets)if(x.entry===null)throw new Error(`Volatility materialization cannot resolve canonical entry timing for event ${x.event.eventId}.`);
 const valid=targets as {event:ResearchSelectionStore["events"][number];entry:number}[];
 const cached:ReferenceSeriesRow[]=[];for(const shard of await listCachedShards(REFERENCE_SERIES_ID,cacheRoot))cached.push(...(await readReferenceShard(shard,cacheRoot)).filter(isCurrentReferenceRow));
 let manifest:Meta[]=[];if(populate&&valid.length)try{manifest=await retrieval.instrumentManifest()}catch(error){if(!allowReferenceBackfill)throw error/* legacy HTTP mode keeps unavailable behavior */}
 // Event-specific backward scans stop on 720 VALID observations per tenor, not
 // attempted hours. Their timestamp union is implicit in the shared cache/set;
 // large calendar gaps between events are never traversed.
 if(readOnlyReference)for(const {entry} of valid)if(!isReferenceTimestampComplete(cached,entry))throw new Error(`Precomputed volatility reference cache is incomplete at ${new Date(entry).toISOString()}. Run npm run volatility:precompute-local.`);
 const percentileStarted=performance.now();if(allowReferenceBackfill&&manifest.length&&valid.length){const venueBoundary=Math.min(...manifest.map(x=>x.createdAtMs).filter((x):x is number=>x!==null)),attempted=new Set<number>();for(const {entry} of valid){let cursor=entry,scanned=0,scanFloor=entry;const validCounts=()=>Object.fromEntries(TENORS.map(tenor=>[tenor,cached.filter(r=>r.timestamp_ms<entry&&r.timestamp_ms>=scanFloor&&r.nominal_tenor===tenor&&r.passes_market_state_rule&&r.tenor_tolerance_passed&&n(r.reference_iv_decimal)!==null).length])) as Record<(typeof TENORS)[number],number>;while(scanned<=maxBackfillHours&&cursor>=venueBoundary&&TENORS.some(t=>validCounts()[t]<MINIMUM_PRIOR_OBSERVATIONS)){const chunk=Math.min(batchTargetCount-1,maxBackfillHours-scanned),logicalTargets=Array.from({length:chunk+1},(_,i)=>cursor-i*HOUR_MS).filter(target=>target>=venueBoundary),missing=logicalTargets.filter(target=>{if(isReferenceTimestampComplete(cached,target)){reusedTargets.add(target);return false}return!attempted.has(target)});scanFloor=Math.min(scanFloor,...logicalTargets);for(const run of contiguousHourlyRuns(missing)){for(const target of run)attempted.add(target);if(diagnostics)diagnostics.percentileBatchRuns+=1;try{const tape=await retrieval.ivTradesByCurrency(run[0]!-MARKET_IV_MAX_AGE_MINUTES*60_000,run.at(-1)!);const fresh=run.flatMap(target=>referenceRows(target,tape,manifest));if(diagnostics){diagnostics.percentileTargetsEvaluated+=run.length;diagnostics.referenceBackfillTargets+=run.length}for(const row of fresh){const key=`${row.timestamp_ms}:${row.nominal_tenor}`,at=cached.findIndex(x=>`${x.timestamp_ms}:${x.nominal_tenor}`===key);if(at>=0)cached[at]=row;else cached.push(row)}if(fresh.length)await writeReferenceShards({rows:fresh,root:cacheRoot})}catch{/* failed/incomplete runs write no completeness and retry on a later export */}if(TENORS.every(t=>validCounts()[t]>=MINIMUM_PRIOR_OBSERVATIONS))break}cursor-=(chunk+1)*HOUR_MS;scanned+=chunk+1;if(chunk===0)break}}}if(diagnostics)diagnostics.percentileMs=performance.now()-percentileStarted;
 // Build the union of exact-instrument windows once. Every endpoint and every
 // canonical path target is resolved from this independent tape.
 const targetByCandidate=new Map<string,Targets>(),windowByInstrument=new Map<string,{start:number;end:number}>();
 for(const {event,entry} of valid)for(const selected of event.selectedStructures){const expiry=n(o(selected.candidateSnapshot).expiryTimestamp),t=selectedTargets(selected,entry,expiry);targetByCandidate.set(selected.candidateId,t);for(const name of Object.values(instrumentNames(selected)))if(name){const all=[entry,...t.endpoints.map(x=>x.timestamp),...t.path],start=Math.min(...all)-MARKET_IV_MAX_AGE_MINUTES*60_000,end=Math.max(...all),old=windowByInstrument.get(name);windowByInstrument.set(name,{start:old?Math.min(old.start,start):start,end:old?Math.max(old.end,end):end})}}
 const exactTapeStarted=performance.now(),exactTape=new Map<string,RawIvTradeCandidate[]>(),byName=new Map(manifest.map(x=>[x.instrumentName,x]));if(populate){if(diagnostics)diagnostics.exactInstrumentsRequested=windowByInstrument.size;if(retrieval.ivTradesMany){const batches=await retrieval.ivTradesMany(windowByInstrument);for(const [name,trades] of batches){const meta=byName.get(name);if(meta)exactTape.set(name,trades.map(t=>raw(meta,t)))}}else await Promise.all([...windowByInstrument].map(async([name,w])=>{const meta=byName.get(name);if(!meta)return;try{exactTape.set(name,(await retrieval.ivTrades(name,w.start,w.end)).map(t=>raw(meta,t)))}catch{exactTape.set(name,[])}}))}if(diagnostics)diagnostics.exactTapeMs=performance.now()-exactTapeStarted;
 const crossSectionStarted=performance.now(),crossTapeByEvent=new Map<string,RawIvTradeCandidate[]>();if(populate)for(const {event,entry} of valid){if(!event.selectedStructures.some(x=>Object.values(instrumentNames(x)).some(Boolean)))continue;if(diagnostics)diagnostics.eventCrossSectionRequests+=1;try{const trades=await retrieval.ivTradesByCurrency(entry-MARKET_IV_MAX_AGE_MINUTES*60_000,entry);crossTapeByEvent.set(event.eventId,trades.flatMap(t=>{const meta=byName.get(t.instrumentName);return meta?[raw(meta,t)]:[]}))}catch{crossTapeByEvent.set(event.eventId,[])}}if(diagnostics)diagnostics.crossSectionMs=performance.now()-crossSectionStarted;
 const dvolStarted=performance.now();if(populate)for(const {entry} of valid)try{if(diagnostics)diagnostics.dvolRequests+=1;await writeDvolShards({points:await retrieval.dvolRange(Math.max(DVOL_FIRST_AVAILABLE_MS,entry-HOUR_MS),entry),root:cacheRoot})}catch{/* unavailable */}if(diagnostics)diagnostics.dvolMs=performance.now()-dvolStarted;
 const dvol=(await Promise.all((await listCachedShards(DVOL_SERIES_ID,cacheRoot)).map(x=>readDvolShard(x,cacheRoot)))).flat(),history:ReferenceObservation[]=cached.filter(x=>x.passes_market_state_rule&&typeof x.reference_iv_decimal==="number").map(x=>({timestampMs:x.timestamp_ms,ivDecimal:x.reference_iv_decimal!,tenor:x.nominal_tenor,referenceSeriesId:REFERENCE_SERIES_ID})),hash=referenceSeriesContentHash(cached),events=[],structures=[];
 const bars=deps.perpetualBars??(async(start,end)=>{const service=new DeribitPerpetualHistoryService(OPTION_HISTORY_HOST);const result=await service.referenceSeries("BTC-PERPETUAL",start,end,60);return result.points.map(x=>({timestampMs:x.timestamp,close:x.close}))});
 for(const {event,entry} of valid){const atEntry=cached.filter(x=>x.timestamp_ms===entry),percentiles=Object.fromEntries(TENORS.map(t=>[t,causalIvPercentile({subjectIvDecimal:atEntry.find(x=>x.nominal_tenor===t)?.reference_iv_decimal??null,targetTimestampMs:entry,history,tenor:t,referenceSeriesId:REFERENCE_SERIES_ID,referenceSeriesContentHash:hash})]));let rv={};const rvStarted=performance.now();if(populate||deps.perpetualBars)try{rv=realizedVolatilityProfile({bars:await bars(entry-31*86_400_000,entry),targetTimestampMs:entry})}catch{/* unavailable */}if(diagnostics)diagnostics.rvMs+=performance.now()-rvStarted;const broad=dvol.filter(x=>x.timestamp_ms<=entry&&entry-x.timestamp_ms<=HOUR_MS).sort((x,y)=>y.timestamp_ms-x.timestamp_ms)[0],broadState:BroadVolatilityState|undefined=broad?{series_id:DVOL_SERIES_ID,method_version:DVOL_METHOD_VERSION,value_decimal:broad.dvol_decimal,observation_timestamp_utc:broad.timestamp_utc,age_minutes:(entry-broad.timestamp_ms)/60_000,status:"available",unavailable_reason:null,substitution_permitted:false}:undefined,indexPrice=atEntry.find(x=>n(x.underlying_price)!==null)?.underlying_price??null;events.push(buildEventVolatilityState({eventId:event.eventId,entryTimestampMs:entry,underlyingInstrument:DERIBIT_OPTION_INDEX_UNDERLYING,entryUnderlyingPrice:indexPrice,referenceSeriesId:REFERENCE_SERIES_ID,referenceSeriesContentHash:hash,referenceRows:atEntry,realizedVolatility:rv,percentiles,broadVolatility:broadState}));
  for(const selected of event.selectedStructures){const c=o(selected.candidateSnapshot),expiry=n(c.expiryTimestamp),names=instrumentNames(selected),shortTape=names.short?exactTape.get(names.short)??[]:[],longTape=names.long?exactTape.get(names.long)??[]:[],t=targetByCandidate.get(selected.candidateId)??{endpoints:[],path:[]},listed=expiry===null?undefined:manifest.find(x=>x.expiryTimestampMs===expiry),cross=crossTapeByEvent.get(event.eventId)??[],underlying=causalIndex(cross,entry),ref=underlying===null||!listed?null:buildExpiryReferenceRow({timestampMs:entry,underlyingInstrument:DERIBIT_OPTION_INDEX_UNDERLYING,underlyingPrice:underlying,expiry:{expiryTimestampMs:listed.expiryTimestampMs,createdAtMs:listed.createdAtMs,settlementPeriod:listed.settlementPeriod,strikes:manifest.filter(x=>x.expiryTimestampMs===listed.expiryTimestampMs).map(x=>x.strike)},candidates:cross,excludedInstruments:[names.short,names.long].filter((x):x is string=>!!x)});structures.push(buildStructureVolatilityState({eventId:event.eventId,candidateId:selected.candidateId,entryTimestampMs:entry,actualExpiryTimestampMs:expiry,actualDteDays:expiry===null?null:(expiry-entry)/86_400_000,shortStrike:n(c.shortStrike),longStrike:n(c.longStrike),optionType:s(c.optionType),shortInstrument:names.short,longInstrument:names.long,referenceSeriesId:REFERENCE_SERIES_ID,referenceSeriesContentHash:hash,shortLeg:leg(shortTape,names.short,entry),longLeg:leg(longTape,names.long,entry),reference:ref,postEntryMarketIv:t.endpoints.map(x=>({endpointId:x.id,targetTimestampMs:x.timestamp,short:leg(shortTape,names.short,x.timestamp),long:leg(longTape,names.long,x.timestamp)})),marketIvPath:t.path.map(timestamp=>({targetTimestampMs:timestamp,short:leg(shortTape,names.short,timestamp),long:leg(longTape,names.long,timestamp)}))}))}
 }
 if(diagnostics){diagnostics.currentV2CachedTargetsReused=reusedTargets.size;diagnostics.referenceRetrievalHttpRequests=(retrieval.requestCount??requestStart)-requestStart;diagnostics.localDayShardReads=(retrieval.localDayShardReads??dayReadsStart)-dayReadsStart;diagnostics.localRowsScanned=(retrieval.localRowsScanned??rowsStart)-rowsStart;diagnostics.exactBatchDayShardsRead=(retrieval.exactBatchDayShardsRead??batchReadsStart)-batchReadsStart}return{events,structures};
}
export {MINIMUM_PRIOR_OBSERVATIONS};
