import {createHash} from "node:crypto";
import {readFile,writeFile,mkdir} from "node:fs/promises";
import {join,dirname} from "node:path";
import {pathToFileURL} from "node:url";
import {performance} from "node:perf_hooks";
import {DERIBIT_OPTION_INDEX_UNDERLYING,REFERENCE_SERIES_ID,REFERENCE_SERIES_METHOD_VERSION,buildReferenceSeriesRows,buildUnavailableReferenceSeriesRows,isCurrentReferenceRow,type ListedExpiry,type ReferenceSeriesRow} from "../app/lib/volatility/reference-series.ts";
import {MARKET_IV_MAX_AGE_MINUTES,type NominalTenor,type RawIvTradeCandidate} from "../app/lib/volatility/market-iv-evidence.ts";
import {HOUR_MS} from "../app/lib/volatility/realized-volatility.ts";
import {LOCAL_INSTRUMENT_MANIFEST,LOCAL_OPTION_TAPE_DIRECTORY,LocalVolatilityRetrieval,localDataRoot} from "./local-volatility-retrieval.ts";
import {readLocalDay} from "./local-contract-archive.ts";
import {VOLATILITY_CACHE_ROOT,listCachedShards,readReferenceShard,writeReferenceShards,type DeribitIvTradeRow,type DeribitOptionInstrument} from "./volatility-reference-cache.ts";

const TENORS=["7d","14d","30d"] as const,DAY=86_400_000,WINDOW=MARKET_IV_MAX_AGE_MINUTES*60_000;
export const LOCAL_PRECOMPUTE_MANIFEST="local-precompute-manifest.json" as const;
export interface LocalPrecomputeDiagnostics{dayShardsOpened:number;rowsStreamed:number;peakRawRowsBuffered:number;targetsProcessed:number;targetsReused:number;hourlyTargetsProduced:number}
export interface LocalPrecomputeManifest{archiveFingerprint:string;instrumentManifestFingerprint:string;referenceSeriesId:string;referenceSeriesMethodVersion:string;coverageStart:string;coverageEnd:string;targetCoverageStart:string;targetCoverageEnd:string;hourlyTargetsAttempted:number;availableCounts:Record<NominalTenor,number>;unavailableCounts:Record<string,number>;generatedAtUtc:string;archiveFingerprintChanged:boolean;instrumentManifestFingerprintChanged:boolean}
export interface StreamingInput{targets:readonly number[];trades:readonly DeribitIvTradeRow[];instruments:readonly DeribitOptionInstrument[];diagnostics?:LocalPrecomputeDiagnostics}

const listedAt=(manifest:readonly DeribitOptionInstrument[],target:number):ListedExpiry[]=>{const groups=new Map<number,DeribitOptionInstrument[]>();for(const m of manifest)if(m.createdAtMs!==null&&m.createdAtMs<=target&&m.expiryTimestampMs>target){const rows=groups.get(m.expiryTimestampMs);if(rows)rows.push(m);else groups.set(m.expiryTimestampMs,[m])}return [...groups].map(([expiryTimestampMs,rows])=>({expiryTimestampMs,createdAtMs:Math.min(...rows.map(x=>x.createdAtMs!)),settlementPeriod:rows[0]!.settlementPeriod,strikes:rows.map(x=>x.strike)}))};
const candidate=(m:DeribitOptionInstrument,t:DeribitIvTradeRow):RawIvTradeCandidate=>({instrumentName:m.instrumentName,tradeId:t.tradeId,tradeSeq:t.tradeSeq,strike:m.strike,optionType:m.optionType,expiryTimestampMs:m.expiryTimestampMs,settlementPeriod:m.settlementPeriod,contractCreatedAtMs:m.createdAtMs,timestampMs:t.timestampMs,ivApiPercent:t.ivApiPercent,indexPrice:t.indexPrice});

/** Pure chronological implementation: each print enters and leaves the causal window once. */
export function buildStreamingReferenceRows(input:StreamingInput):ReferenceSeriesRow[]{
 const targets=[...input.targets].sort((a,b)=>a-b),trades=input.trades,byName=new Map(input.instruments.map(x=>[x.instrumentName,x])),active:DeribitIvTradeRow[]=[],out:ReferenceSeriesRow[]=[];let cursor=0,head=0;
 for(const target of targets){while(cursor<trades.length&&trades[cursor]!.timestampMs<=target){active.push(trades[cursor++]!);input.diagnostics&&(input.diagnostics.rowsStreamed+=1)}while(head<active.length&&active[head]!.timestampMs<target-WINDOW)head++;if(head>4096){active.splice(0,head);head=0}const window=active.slice(head),underlying=[...window].reverse().find(x=>typeof x.indexPrice==="number"&&x.indexPrice>0)?.indexPrice??null,listed=listedAt(input.instruments,target);out.push(...(underlying===null?buildUnavailableReferenceSeriesRows({timestampMs:target,listedExpiries:listed,tenors:TENORS}):buildReferenceSeriesRows({timestampMs:target,underlyingInstrument:DERIBIT_OPTION_INDEX_UNDERLYING,underlyingPrice:underlying,listedExpiries:listed,candidates:window.flatMap(t=>{const m=byName.get(t.instrumentName);return m?[candidate(m,t)]:[]}),tenors:TENORS}).rows));input.diagnostics&&(input.diagnostics.hourlyTargetsProduced+=1)}return out;
}
const floorHour=(x:number)=>Math.floor(x/HOUR_MS)*HOUR_MS,ceilHour=(x:number)=>Math.ceil(x/HOUR_MS)*HOUR_MS,day=(x:number)=>new Date(x).toISOString().slice(0,10);
const sha256=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex");
async function cachedRows(root:string){const rows:ReferenceSeriesRow[]=[];for(const shard of await listCachedShards(REFERENCE_SERIES_ID,root))rows.push(...(await readReferenceShard(shard,root)).filter(isCurrentReferenceRow));return rows}

function dateBound(value:string|undefined,name:"start"|"end",fallback:number){if(value===undefined)return fallback;if(!/^\d{4}-\d{2}-\d{2}$/.test(value))throw new Error(`--${name} must use YYYY-MM-DD.`);const parsed=Date.parse(`${value}T00:00:00.000Z`);if(!Number.isFinite(parsed)||new Date(parsed).toISOString().slice(0,10)!==value)throw new Error(`--${name} must be a valid YYYY-MM-DD date.`);return parsed}

export async function precomputeLocalVolatility(options:{dataRoot?:string;cacheRoot?:string;start?:string;end?:string;generatedAtUtc?:string;onDayPersisted?:(date:string)=>void|Promise<void>}={}){
 const started=performance.now(),dataRoot=localDataRoot(options.dataRoot),cacheRoot=options.cacheRoot??VOLATILITY_CACHE_ROOT,retrieval=new LocalVolatilityRetrieval(dataRoot),source=await retrieval.sourceManifest(),archive=await retrieval.archiveManifest(),instruments=await retrieval.instrumentManifest();void source;
 const coverageStart=Date.parse(archive.coverage_start??""),coverageEnd=Date.parse(archive.coverage_end??"");if(!Number.isFinite(coverageStart)||!Number.isFinite(coverageEnd))throw new Error("The local option archive has no usable coverage.");
 const targetStart=dateBound(options.start,"start",coverageStart),targetEnd=dateBound(options.end,"end",coverageEnd);if(targetStart<coverageStart||targetStart>coverageEnd)throw new Error(`Requested --start falls outside local archive coverage [${new Date(coverageStart).toISOString()}, ${new Date(coverageEnd).toISOString()}].`);if(targetEnd<coverageStart||targetEnd>coverageEnd)throw new Error(`Requested --end falls outside local archive coverage [${new Date(coverageStart).toISOString()}, ${new Date(coverageEnd).toISOString()}].`);if(targetStart>targetEnd)throw new Error("Requested --start must not be after --end.");
 const instrumentText=await readFile(join(dataRoot,"aux",LOCAL_INSTRUMENT_MANIFEST)),instrumentFingerprint=sha256(instrumentText),manifestFile=join(cacheRoot,REFERENCE_SERIES_ID,LOCAL_PRECOMPUTE_MANIFEST);let previous:LocalPrecomputeManifest|null=null;try{previous=JSON.parse(await readFile(manifestFile,"utf8")) as LocalPrecomputeManifest}catch{}
 const fingerprintChanged=previous!==null&&previous.archiveFingerprint!==archive.data_content_fingerprint,instrumentFingerprintChanged=previous!==null&&previous.instrumentManifestFingerprint!==instrumentFingerprint,appendOnlyGrowth=previous!==null&&previous.coverageStart===new Date(coverageStart).toISOString()&&Date.parse(previous.coverageEnd)<coverageEnd;if((fingerprintChanged||instrumentFingerprintChanged)&&!appendOnlyGrowth)throw new Error("Local archive/instrument fingerprint changed non-append-only; stale derived reference data must not be trusted. Use a new --cache-root or remove the old cache.");
 const existing=await cachedRows(cacheRoot),completeTenors=new Map<number,Set<NominalTenor>>();for(const row of existing){let set=completeTenors.get(row.timestamp_ms);if(!set){set=new Set;completeTenors.set(row.timestamp_ms,set)}set.add(row.nominal_tenor)}const complete=new Set([...completeTenors].filter(([,set])=>TENORS.every(t=>set.has(t))).map(([timestamp])=>timestamp)),allTargets:Array<number>=[];for(let t=ceilHour(targetStart);t<=floorHour(targetEnd);t+=HOUR_MS)allTargets.push(t);const missing=allTargets.filter(t=>!complete.has(t));
 const diagnostics:LocalPrecomputeDiagnostics={dayShardsOpened:0,rowsStreamed:0,peakRawRowsBuffered:0,targetsProcessed:0,targetsReused:allTargets.length-missing.length,hourlyTargetsProduced:0};let rowsWritten=0;
 // Day shards are already canonically sorted. Persist each target day before
 // releasing it; only its final causal hour can survive into the next loop.
 if(missing.length){const targetsByDay=new Map<number,number[]>();for(const target of missing){const d=Math.floor(target/DAY)*DAY,list=targetsByDay.get(d);if(list)list.push(target);else targetsByDay.set(d,[target])}const firstDay=Math.min(...targetsByDay.keys()),lastDay=Math.max(...targetsByDay.keys());let carry:DeribitIvTradeRow[]=[];for(let d=firstDay-DAY;d<=lastDay;d+=DAY){diagnostics.dayShardsOpened++;const shard=(await readLocalDay(join(dataRoot,LOCAL_OPTION_TAPE_DIRECTORY),day(d))).map(row=>({instrumentName:row.instrumentName,tradeId:row.tradeId??null,tradeSeq:row.tradeSeq??null,timestampMs:row.timestampMs,ivApiPercent:row.ivApiPercent??null,price:row.price??null,markPrice:row.markPrice??null,indexPrice:row.indexPrice??null,direction:row.direction??null,amount:row.amount??null}));diagnostics.rowsStreamed+=shard.length;const buffered=[...carry,...shard];diagnostics.peakRawRowsBuffered=Math.max(diagnostics.peakRawRowsBuffered,buffered.length);const targets=targetsByDay.get(d)??[];if(targets.length){const rows=buildStreamingReferenceRows({targets,trades:buffered,instruments});await writeReferenceShards({rows,root:cacheRoot,generatedAtUtc:options.generatedAtUtc});rowsWritten+=rows.length;diagnostics.targetsProcessed+=targets.length;diagnostics.hourlyTargetsProduced+=targets.length;await options.onDayPersisted?.(day(d))}const nextStart=d+DAY;carry=buffered.filter(row=>row.timestampMs>=nextStart-WINDOW&&row.timestampMs<nextStart)}}
 const combined=(await cachedRows(cacheRoot)).filter(row=>row.timestamp_ms>=targetStart&&row.timestamp_ms<=targetEnd),availableCounts={"7d":0,"14d":0,"30d":0} as Record<NominalTenor,number>,unavailableCounts:Record<string,number>={};for(const row of combined){if(row.passes_market_state_rule)availableCounts[row.nominal_tenor]++;else unavailableCounts[row.unavailable_reason_code??"unknown"]=(unavailableCounts[row.unavailable_reason_code??"unknown"]??0)+1}
 const generatedAtUtc=options.generatedAtUtc??new Date().toISOString(),manifest:LocalPrecomputeManifest={archiveFingerprint:archive.data_content_fingerprint,instrumentManifestFingerprint:instrumentFingerprint,referenceSeriesId:REFERENCE_SERIES_ID,referenceSeriesMethodVersion:REFERENCE_SERIES_METHOD_VERSION,coverageStart:new Date(coverageStart).toISOString(),coverageEnd:new Date(coverageEnd).toISOString(),targetCoverageStart:new Date(targetStart).toISOString(),targetCoverageEnd:new Date(targetEnd).toISOString(),hourlyTargetsAttempted:allTargets.length,availableCounts,unavailableCounts,generatedAtUtc,archiveFingerprintChanged:fingerprintChanged,instrumentManifestFingerprintChanged:instrumentFingerprintChanged};await mkdir(dirname(manifestFile),{recursive:true});await writeFile(manifestFile,JSON.stringify(manifest,null,2)+"\n");return{manifest,diagnostics,targetsProcessed:diagnostics.targetsProcessed,targetsReused:diagnostics.targetsReused,rowsWritten,runtimeMs:performance.now()-started};
}
function arg(name:string){const i=process.argv.indexOf(name);return i<0?undefined:process.argv[i+1]}
if(import.meta.url===pathToFileURL(process.argv[1]??"").href){const result=await precomputeLocalVolatility({dataRoot:arg("--data-root"),cacheRoot:arg("--cache-root"),start:arg("--start"),end:arg("--end")});console.log(JSON.stringify({archiveCoverage:[result.manifest.coverageStart,result.manifest.coverageEnd],targetCoverage:[result.manifest.targetCoverageStart,result.manifest.targetCoverageEnd],targetsProcessed:result.targetsProcessed,targetsReused:result.targetsReused,rowsWritten:result.rowsWritten,diagnostics:result.diagnostics,available:result.manifest.availableCounts,unavailable:result.manifest.unavailableCounts,sourceFingerprints:{archive:result.manifest.archiveFingerprint,instruments:result.manifest.instrumentManifestFingerprint},runtimeMs:Math.round(result.runtimeMs)},null,2))}
