import type {IncomingMessage,ServerResponse} from "node:http";
import {resolve} from "node:path";
import type {Plugin} from "vite";
import {buildResearchBundle} from "../app/lib/research-bundle.ts";
import {ResearchSelectionService} from "./research-selection-service.ts";
const PREFIX="/__local/research-bundle/",SAFE=/^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/;
function crc32(data:Uint8Array){let crc=0xffffffff;for(const byte of data){crc^=byte;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0)}return(crc^0xffffffff)>>>0}
export function createResearchBundleZip(files:Record<string,string>){const encoder=new TextEncoder(),chunks:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0;const u16=(v:number)=>[v&255,v>>>8&255],u32=(v:number)=>[v&255,v>>>8&255,v>>>16&255,v>>>24&255];for(const [bare,text] of Object.entries(files)){const name=encoder.encode(`research_bundle/${bare}`),data=encoder.encode(text),crc=crc32(data);const local=new Uint8Array([0x50,0x4b,3,4,...u16(20),0,0,0,0,0,0,...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),0,0,...name,...data]);chunks.push(local);central.push(new Uint8Array([0x50,0x4b,1,2,...u16(20),...u16(20),0,0,0,0,0,0,...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),0,0,0,0,0,0,0,0,0,0,...u32(offset),...name]));offset+=local.length}const centralSize=central.reduce((n,c)=>n+c.length,0),end=new Uint8Array([0x50,0x4b,5,6,0,0,0,0,...u16(central.length),...u16(central.length),...u32(centralSize),...u32(offset),0,0]);return Buffer.concat([...chunks,...central,end].map(x=>Buffer.from(x)))}
export function researchBundleApiPlugin(directory=resolve(process.cwd(),"data/research-selections")):Plugin{const selections=new ResearchSelectionService(directory);return{name:"local-research-bundle",configureServer(server){server.middlewares.use(async(req:IncomingMessage,res:ServerResponse,next)=>{const path=new URL(req.url??"/","http://local").pathname;if(!path.startsWith(PREFIX))return next();try{if(req.method!=="GET")throw Object.assign(new Error("Method not allowed."),{status:405});const id=decodeURIComponent(path.slice(PREFIX.length));if(!SAFE.test(id))throw Object.assign(new Error("Invalid dataset ID."),{status:400});const generated=new Date().toISOString(),bundle=buildResearchBundle(await selections.read(id),generated),payload=createResearchBundleZip(bundle.files),stamp=generated.replace(/[:.]/g,"-");res.statusCode=200;res.setHeader("Content-Type","application/zip");res.setHeader("Content-Disposition",`attachment; filename="research-bundle-${id}-${stamp}.zip"`);res.setHeader("Content-Length",payload.length);res.end(payload)}catch(error){const e=error as Error&{status?:number};res.statusCode=e.status??422;res.setHeader("Content-Type","application/json");res.end(JSON.stringify({error:e.message}))}})}}}
