import type {AnalysisDataset} from "../research-analysis.ts";
import {DEFAULT_ANALYSIS_CONFIGURATION} from "../analysis-configuration.ts";
import {datasetForAnalyticsTrack,type AnalyticsTrack} from "../research-analytics-model.ts";
import {EXIT_POLICIES} from "../exit-policy/policies.ts";
import {normalizeExitPolicies} from "../exit-policy/normalize.ts";
import {normalizePositionEconomics,type PositionEconomics} from "../economics/position.ts";
import {applyCanonicalTrackEvidence,canonicalTrackOpportunities,indexUniqueStructuralEvidence,positionStructuralEvidenceKey,structuralEvidenceKey} from "../economics/track-evidence.ts";
import {classifyEconomicOpportunity} from "../economics/opportunity.ts";
import {structuralConfigurationIdentity} from "../economics/strategy-configuration.ts";
import {buildResearchEconomicsReport,configurationEvidenceStatus} from "./report.ts";

type Row=Readonly<Record<string,unknown>>;
export const FORENSIC_TRACKS=["reference","modeled_expected","modeled_conservative"] as const satisfies readonly AnalyticsTrack[];
const text=(value:unknown)=>typeof value==="string"?value:null;
const finite=(value:unknown):value is number=>typeof value==="number"&&Number.isFinite(value);
const arrayStrings=(value:unknown)=>Array.isArray(value)?value.filter((item):item is string=>typeof item==="string"):[];
const configurationId=(row:Row)=>text(row.structural_configuration_id)??structuralConfigurationIdentity(row).id;
const candidateIdentity=(row:Row)=>structuralEvidenceKey(String(row.event_id??""),configurationId(row)??"");
const candidateIds=(rows:readonly Row[])=>[...new Set(rows.map(row=>text(row.candidate_id)).filter((id):id is string=>id!==null))].sort();
const config=(exitPolicy:(typeof EXIT_POLICIES)[number]["id"])=>({...DEFAULT_ANALYSIS_CONFIGURATION,exitPolicy,capitalBasis:"peak_required_capital" as const});
const reasonCounts=(reasons:readonly (string|null)[])=>Object.fromEntries([...new Set(reasons.filter((reason):reason is string=>Boolean(reason)))].sort().map(reason=>[reason,reasons.filter(value=>value===reason).length]));
const rowsForCandidates=(rows:readonly Row[],ids:ReadonlySet<string>)=>rows.filter(row=>ids.has(String(row.candidate_id??"")));

function indexPositions(positions:readonly PositionEconomics[]){const index=indexUniqueStructuralEvidence(positions);return{index,allByIdentity:new Map([...new Set(positions.map(positionStructuralEvidenceKey))].map(identity=>[identity,positions.filter(position=>positionStructuralEvidenceKey(position)===identity)]))}}

function valueReason(position:PositionEconomics|undefined,field:string,currency:"btc"|"usd"):{available:boolean;reason:string|null}{if(!position)return{available:false,reason:"normalized position absent"};const unavailable=(reason:string|null|undefined)=>({available:false,reason:reason??position.missingReason??"canonical field unavailable"});switch(field){case"pnl":return currency==="btc"?(finite(position.pnlBtc)?{available:true,reason:null}:unavailable(position.missingReason)):(finite(position.pnlUsd)?{available:true,reason:null}:unavailable(position.missingReason));case"gross_credit":return currency==="btc"?(finite(position.grossOpeningCreditBtc)?{available:true,reason:null}:unavailable(position.missingReason)):(finite(position.grossOpeningCreditUsd.value)?{available:true,reason:null}:unavailable(position.grossOpeningCreditUsd.reason));case"net_credit":return currency==="btc"?(finite(position.netOpeningCashFlowBtc)?{available:true,reason:null}:unavailable(position.missingReason)):(finite(position.netOpeningCashFlowUsd.value)?{available:true,reason:null}:unavailable(position.netOpeningCashFlowUsd.reason));case"fees":return currency==="btc"?(finite(position.totalRealizedFeesBtc)?{available:true,reason:null}:unavailable(position.missingReason)):(finite(position.totalRealizedFeesUsd.value)?{available:true,reason:null}:unavailable(position.totalRealizedFeesUsd.reason));case"opening_im":return currency==="btc"?(finite(position.incrementalInitialMarginBtc.value)?{available:true,reason:null}:unavailable(position.incrementalInitialMarginBtc.reason)):(finite(position.incrementalInitialMarginUsd.value)?{available:true,reason:null}:unavailable(position.incrementalInitialMarginUsd.reason));case"peak_im":return currency==="btc"?(finite(position.peakInitialMarginBtc.value)?{available:true,reason:null}:unavailable(position.peakInitialMarginBtc.reason)):(finite(position.peakInitialMarginUsd.value)?{available:true,reason:null}:unavailable(position.peakInitialMarginUsd.reason));default:return currency==="btc"?(finite(position.capitalDaysBtc.value)?{available:true,reason:null}:unavailable(position.capitalDaysBtc.reason)):(finite(position.capitalDaysUsd.value)?{available:true,reason:null}:unavailable(position.capitalDaysUsd.reason))}}

export function buildResearchEconomicsForensicAudit(dataset:AnalysisDataset){
 const opportunities=dataset.tables.configuration_opportunities??[],candidates=dataset.tables.candidates??[],availability=dataset.tables.availability??[],valuations=dataset.tables.valuations??[],outcomes=dataset.tables.outcomes??[],structureEconomics=dataset.tables.structure_economics??[],canonical=canonicalTrackOpportunities(dataset),canonicalKeys=new Set(canonical.map(row=>structuralEvidenceKey(row.eventId,row.structuralConfigurationId)));
 const candidateRowsByIdentity=new Map<string,Row[]>();for(const candidate of candidates){const identity=candidateIdentity(candidate),rows=candidateRowsByIdentity.get(identity)??[];rows.push(candidate);candidateRowsByIdentity.set(identity,rows)}
 const opportunityLedger=opportunities.map((row,index)=>{const eventId=String(row.event_id??""),identityResult=structuralConfigurationIdentity(row),structuralConfigurationId=configurationId(row)??"",identity=structuralEvidenceKey(eventId,structuralConfigurationId),mapped=candidateRowsByIdentity.get(identity)??[],status=classifyEconomicOpportunity(row.economic_opportunity),attemptIds=arrayStrings(row.attempt_candidate_ids),canonicalCandidate=text(row.candidate_id);return{identity,opportunityId:text(row.opportunity_id)??identity,eventId,structuralConfigurationId,structuralConfiguration:identityResult.fields,attemptCandidateIds:attemptIds,canonicalCandidateId:canonicalCandidate,candidateMaterialized:canonicalCandidate!==null&&candidates.some(candidate=>candidate.candidate_id===canonicalCandidate),canonicalCandidate:canonicalCandidate===null?null:candidates.find(candidate=>candidate.candidate_id===canonicalCandidate)??null,q50GenerationStatus:status.status,q50ReasonCode:status.reasonCode,q50Reason:status.reason,candidateRowCount:mapped.length,candidateIds:candidateIds(mapped),candidates:mapped.map(candidate=>({candidateId:text(candidate.candidate_id),selected:candidate.is_selected!==false,researchOnly:candidate.is_research_only===true||candidate.research_only===true,researchRole:text(candidate.research_role)})),sourceRowIndex:index}}).sort((a,b)=>a.identity.localeCompare(b.identity)||a.sourceRowIndex-b.sourceRowIndex);
 const trackData=Object.fromEntries(FORENSIC_TRACKS.map(track=>{const projected=datasetForAnalyticsTrack(dataset,track,{cohort:"all"}),raw=normalizePositionEconomics(projected,config("thesis")),gate=applyCanonicalTrackEvidence(canonical,raw,track),thesis=indexPositions(gate.admissiblePositions),settlement=indexPositions(normalizePositionEconomics(projected,config("settlement_benchmark"))),projectedCandidates=projected.tables.candidates??[];return[track,{projected,raw,gate,thesis,settlement,projectedCandidates}]})) as Record<(typeof FORENSIC_TRACKS)[number],{projected:AnalysisDataset;raw:readonly PositionEconomics[];gate:ReturnType<typeof applyCanonicalTrackEvidence>;thesis:ReturnType<typeof indexPositions>;settlement:ReturnType<typeof indexPositions>;projectedCandidates:readonly Row[]}>;
 const trackMaterialization=opportunityLedger.flatMap(opportunity=>FORENSIC_TRACKS.map(track=>{const data=trackData[track],mapped=data.projectedCandidates.filter(candidate=>candidateIdentity(candidate)===opportunity.identity),ids=new Set([...candidateIds(mapped),...opportunity.attemptCandidateIds,...(opportunity.canonicalCandidateId?[opportunity.canonicalCandidateId]:[])]),trackValuations=rowsForCandidates(valuations,ids).filter(row=>!row.analytics_track||row.analytics_track===track),trackOutcomes=rowsForCandidates(outcomes,ids).filter(row=>!row.analytics_track||row.analytics_track===track),thesis=data.thesis.index.unique.get(opportunity.identity),settlement=data.settlement.index.unique.get(opportunity.identity),raw=data.raw.filter(position=>positionStructuralEvidenceKey(position)===opportunity.identity),descriptorTrack=track==="reference"?"reference_fair_value":track,descriptors=structureEconomics.filter(row=>ids.has(String(row.candidate_id??""))).flatMap(row=>Array.isArray(row.tracks)?row.tracks:[]).filter(raw=>raw&&typeof raw==="object"&&(raw as Row).track===descriptorTrack) as Row[];return{identity:opportunity.identity,eventId:opportunity.eventId,structuralConfigurationId:opportunity.structuralConfigurationId,track,opportunityCount:opportunities.filter(row=>candidateIdentity(row)===opportunity.identity).length,trackExists:descriptors.length>0,trackStatus:[...new Set(descriptors.map(row=>text(row.status)??"unknown"))].sort(),trackReasonCodes:[...new Set(descriptors.map(row=>text(row.reason_code)).filter((reason):reason is string=>reason!==null))].sort(),trackReasons:[...new Set(descriptors.map(row=>text(row.reason)).filter((reason):reason is string=>reason!==null))].sort(),materializedCandidateRowCount:mapped.length,entryExists:mapped.some(row=>text(row.structure_entry_timestamp_utc)!==null),valuationPathPointCount:trackValuations.length,outcomeCount:trackOutcomes.length,pricedThesisOutcome:thesis?.status==="priced",pricedSettlementOutcome:settlement?.status==="priced",normalizedPositionStatus:thesis?.status??(data.gate.duplicateIdentities.includes(opportunity.identity)||data.thesis.index.duplicates.has(opportunity.identity)?"duplicate":"absent"),missingReason:thesis?.missingReason??(data.gate.duplicateIdentities.includes(opportunity.identity)||data.thesis.index.duplicates.has(opportunity.identity)?"duplicate event × configuration track evidence":raw[0]?.missingReason??"normalized position absent"),joinIdentity:opportunity.identity,normalizedPositionCount:raw.length,q50Contradiction:data.gate.contradictions.find(item=>item.identity===opportunity.identity)?.reasonCode??null}}));
 const integrity=new Map<string,{identities:Set<string>;configurations:Set<string>}>();const addIntegrity=(reason:string,identity:string,configuration:string)=>{const bucket=integrity.get(reason)??{identities:new Set<string>(),configurations:new Set<string>()};bucket.identities.add(identity);bucket.configurations.add(configuration);integrity.set(reason,bucket)};
 for(const [identity,rows]of new Map(opportunityLedger.map(row=>[row.identity,opportunityLedger.filter(other=>other.identity===row.identity)])))if(rows.length>1)addIntegrity("duplicate canonical opportunity identity",identity,rows[0]!.structuralConfigurationId);
 for(const row of opportunityLedger){const source=opportunities[row.sourceRowIndex]!,computed=structuralConfigurationIdentity(source);if(computed.reason)addIntegrity(`invalid structural configuration identity: ${computed.reason}`,row.identity,row.structuralConfigurationId);if(row.candidateIds.length>1)addIntegrity("multiple candidate IDs for one canonical event × configuration",row.identity,row.structuralConfigurationId);if(text(source.structural_configuration_id)!==null&&computed.id!==null&&source.structural_configuration_id!==computed.id)addIntegrity("structural configuration ID mismatch",row.identity,row.structuralConfigurationId)}
 for(const track of FORENSIC_TRACKS){for(const contradiction of trackData[track].gate.contradictions)addIntegrity(contradiction.reasonCode,contradiction.identity,contradiction.structuralConfigurationId);for(const identity of trackData[track].gate.duplicateIdentities)addIntegrity("duplicate selected-track event × configuration evidence",identity,identity.split("|").at(-1)!)}
 const integrityReasons=[...integrity].sort(([a],[b])=>a.localeCompare(b)).map(([reason,affected])=>({reason,affectedIdentityCount:affected.identities.size,affectedStructuralConfigurationCount:affected.configurations.size,identities:[...affected.identities].sort(),structuralConfigurationIds:[...affected.configurations].sort()}));
 const unavailableRows=opportunityLedger.filter(row=>row.q50GenerationStatus==="unavailable"),unavailableReasonDistribution=[...new Set(unavailableRows.map(row=>row.q50ReasonCode??"other"))].sort().map(reasonCode=>{const identities=[...new Set(unavailableRows.filter(row=>(row.q50ReasonCode??"other")===reasonCode).map(row=>row.identity))].sort();return{reasonCode,count:identities.length,identities}});
 const identityReconciliation=candidates.map(candidate=>{const candidateId=String(candidate.candidate_id??""),eventId=String(candidate.event_id??""),candidateConfigurationId=configurationId(candidate),computed=structuralConfigurationIdentity(candidate),opportunityIds=opportunityLedger.filter(row=>row.eventId===eventId&&(row.canonicalCandidateId===candidateId||row.attemptCandidateIds.includes(candidateId)||row.candidateIds.includes(candidateId))).map(row=>row.structuralConfigurationId),availabilityIds=[...new Set(availability.filter(row=>row.candidate_id===candidateId).map(configurationId).filter((id):id is string=>id!==null))],normalizedIds=[...new Set(FORENSIC_TRACKS.flatMap(track=>trackData[track].raw.filter(position=>position.candidateId===candidateId).map(position=>position.structuralConfigurationId).filter((id):id is string=>id!==null)))],allIds=[...new Set([...opportunityIds,...availabilityIds,...(candidateConfigurationId?[candidateConfigurationId]:[]),...normalizedIds])];return{candidateId,eventId,configurationOpportunityIds:opportunityIds.sort(),availabilityConfigurationIds:availabilityIds.sort(),candidateConfigurationId,computedCandidateConfigurationId:computed.id,normalizedPositionConfigurationIds:normalizedIds.sort(),mismatch:allIds.length>1||computed.reason!==null,mismatchReason:computed.reason??(allIds.length>1?`identity sources disagree: ${allIds.sort().join(", ")}`:null)}}).sort((a,b)=>a.candidateId.localeCompare(b.candidateId));
 const coverageFields=["pnl","gross_credit","net_credit","fees","opening_im","peak_im","capital_days"] as const,marginAndUsdCoverage=FORENSIC_TRACKS.flatMap(track=>{const indexed=trackData[track].thesis.index;return[...new Set(opportunityLedger.map(row=>row.structuralConfigurationId))].sort().map(structuralConfigurationId=>{const canonicalRows=opportunityLedger.filter(row=>row.structuralConfigurationId===structuralConfigurationId),eligibleRows=canonicalRows.filter(row=>track!=="modeled_expected"||row.q50GenerationStatus==="trade"),eligibleIdentities=[...new Set(eligibleRows.map(row=>row.identity))],resolved=eligibleIdentities.map(identity=>({identity,position:indexed.unique.get(identity),duplicate:indexed.duplicates.has(identity)}));return{track,structuralConfigurationId,eligibleOpportunityIdentityCount:new Set(canonicalRows.map(row=>row.identity)).size,metricEligibleIdentityCount:eligibleIdentities.length,pricedPositionCount:resolved.filter(row=>row.position?.status==="priced").length,absentPositionIdentityCount:resolved.filter(row=>!row.position&&!row.duplicate).length,duplicatePositionIdentityCount:resolved.filter(row=>row.duplicate).length,fields:Object.fromEntries(coverageFields.map(field=>[field,Object.fromEntries((["btc","usd"] as const).map(currency=>{const observations=resolved.map(row=>row.duplicate?{available:false,reason:"duplicate event × configuration track evidence"}:valueReason(row.position,field,currency));return[currency,{availableN:observations.filter(row=>row.available).length,metricEligibleIdentityN:eligibleIdentities.length,missingN:observations.filter(row=>!row.available).length,missingReasons:reasonCounts(observations.map(row=>row.reason))}]}))]))}})});
 const comparativeReport=buildResearchEconomicsReport(dataset,"thesis","modeled_expected"),configurationEvidenceLedger=comparativeReport.configurations.map(configuration=>({structuralConfigurationId:configuration.configurationId,q50:configuration.q50,selectedTrackCoverage:configuration.trackCoverage,integrity:configuration.integrity,evidenceAssessment:configurationEvidenceStatus(configuration),usdMetricStates:Object.fromEntries(Object.entries(configuration.metrics).map(([metric,value])=>[metric,{status:value.usd.status,reason:value.usd.reason,effectiveEventN:value.usd.effectiveEventN,eligibleEventN:value.usd.eligibleEventN,missingEventN:value.usd.missingEventN}]))}));
 const exitPolicyCoverage=FORENSIC_TRACKS.flatMap(track=>{const projected=trackData[track].projected,observations=normalizeExitPolicies(projected,{capitalBasis:"peak_required_capital"});return EXIT_POLICIES.map(policy=>{const policyRows=observations.filter(row=>row.policyId===policy.id),positionGate=applyCanonicalTrackEvidence(canonical,normalizePositionEconomics(projected,config(policy.id)),track);return{track,policyId:policy.id,label:policy.label,eligibleOpportunityIdentityCount:canonicalKeys.size,trackPositionCount:positionGate.admissiblePositions.length,pricedOutcomeCount:policyRows.filter(row=>row.status==="priced").length,reachedButUnpricedCount:policyRows.filter(row=>row.status==="triggered_unpriced"||row.diagnosticCode==="outcome_reached_unpriced").length,sourceOutcomeAbsentCount:policyRows.filter(row=>row.diagnosticCode==="source_outcome_absent").length,sourceOutcomeUnavailableCount:policyRows.filter(row=>row.diagnosticCode==="source_outcome_unavailable").length,preEntryCount:policyRows.filter(row=>row.diagnosticCode==="pre_entry_outcome").length,afterExpiryCount:policyRows.filter(row=>row.diagnosticCode==="outcome_after_expiry").length,ambiguousCount:policyRows.filter(row=>row.diagnosticCode==="ambiguous_timing").length}})});
 return{schemaVersion:dataset.schemaVersion,summary:{canonicalOpportunityRowCount:opportunities.length,canonicalOpportunityIdentityCount:new Set(opportunityLedger.map(row=>row.identity)).size,structuralConfigurationCount:new Set(opportunityLedger.map(row=>row.structuralConfigurationId)).size,independentEventCount:new Set(opportunityLedger.map(row=>row.eventId)).size,q50StatusCounts:Object.fromEntries(["trade","explicit_no_trade","unavailable"].map(status=>[status,opportunityLedger.filter(row=>row.q50GenerationStatus===status).length])),selectedQ50PricedOpportunityCount:comparativeReport.configurations.reduce((count,row)=>count+row.trackCoverage.pricedOpportunityN,0),configurationEvidenceStatusCounts:reasonCounts(configurationEvidenceLedger.map(row=>row.evidenceAssessment.status)),configurationsWithUnavailableCanonicalUsdMetrics:configurationEvidenceLedger.filter(row=>Object.values(row.usdMetricStates).some(metric=>metric.status==="unavailable")).length,lowNTailConfigurationCount:configurationEvidenceLedger.filter(row=>row.q50.tailPricedN<row.q50.tailMinimum).length,integrityAffectedIdentityCount:new Set(integrityReasons.flatMap(row=>row.identities)).size,integrityAffectedStructuralConfigurationCount:new Set(integrityReasons.flatMap(row=>row.structuralConfigurationIds)).size},canonicalOpportunityLedger:opportunityLedger,trackMaterializationLedger:trackMaterialization,integrityReasonDistribution:integrityReasons,q50UnavailableReasonDistribution:unavailableReasonDistribution,identityReconciliation,configurationEvidenceLedger,marginAndUsdCoverage,exitPolicyCoverage}}

export type ResearchEconomicsForensicAudit=ReturnType<typeof buildResearchEconomicsForensicAudit>;
