import type {PositionEconomics} from "../economics/position.ts";
import type {StructuralConfigurationFields} from "../economics/strategy-configuration.ts";
import {finite,median,metricValue,type ResearchMetric} from "./statistics.ts";

export type ComparisonDimension="dte"|"width"|"strike";
export const MATCHED_METRICS:readonly ResearchMetric[]=["pnlUsd","grossCreditUsd","netCreditUsd","openingFeesUsd","totalFeesUsd","peakImUsd","openingImUsd","trackMaximumNetLossUsd","capitalDaysUsd","holdingDays","returnOnPeakCapital","feeDrag"];
const fields=(p:PositionEconomics)=>p.structuralConfiguration as StructuralConfigurationFields|null;
const category=(p:PositionEconomics,d:ComparisonDimension)=>{const f=fields(p);return d==="dte"?f?.targetDteFamilyDays??null:d==="width"?f?.requestedWidth??null:f?.strikeMethod??null};
const controls=(p:PositionEconomics,d:ComparisonDimension)=>{const f=fields(p);if(!f)return null;const values=d==="dte"?[f.strikeMethod,f.requestedWidth,f.structureFamily]:d==="width"?[f.targetDteFamilyDays,f.strikeMethod,f.structureFamily]:[f.targetDteFamilyDays,f.requestedWidth,f.structureFamily];return values.some(x=>x===null)?null:JSON.stringify([p.eventId,...values,p.exitPolicy,p.analyticsTrack])};
export interface MatchedMetricDelta{medianDelta:number|null;effectivePairedN:number;missingN:number}
export interface MatchedComparison{dimension:ComparisonDimension;source:string|number;destination:string|number;commonPairUniverseN:number;unpairedN:number;metrics:Readonly<Record<ResearchMetric,MatchedMetricDelta>>;missingReasons:Readonly<Record<string,number>>}
export function buildMatchedComparisons(positions:readonly PositionEconomics[],dimension:ComparisonDimension):readonly MatchedComparison[]{const groups=new Map<string,PositionEconomics[]>();for(const p of positions){const key=controls(p,dimension);if(key===null||category(p,dimension)===null)continue;const rows=groups.get(key)??[];rows.push(p);groups.set(key,rows)}const categories=[...new Set(positions.map(p=>category(p,dimension)).filter((x):x is string|number=>x!==null))].sort((a,b)=>typeof a==="number"&&typeof b==="number"?a-b:String(a).localeCompare(String(b))),out:MatchedComparison[]=[];for(let i=0;i<categories.length;i++)for(let j=i+1;j<categories.length;j++){const source=categories[i]!,destination=categories[j]!,pairs:{a:PositionEconomics;b:PositionEconomics}[]=[],reasons:Record<string,number>={};let oneSided=0;for(const rows of groups.values()){const a=rows.filter(p=>category(p,dimension)===source),b=rows.filter(p=>category(p,dimension)===destination);if(a.length===1&&b.length===1)pairs.push({a:a[0]!,b:b[0]!});else if(a.length||b.length){oneSided++;const reason=a.length>1||b.length>1?"duplicate category within matched identity":a.length===0?"source absent":"destination absent";reasons[reason]=(reasons[reason]??0)+1}}const metrics=Object.fromEntries(MATCHED_METRICS.map(metric=>{const deltas=pairs.flatMap(({a,b})=>{const left=metricValue(a,metric),right=metricValue(b,metric);return finite(left)&&finite(right)?[right-left]:[]});return[metric,{medianDelta:median(deltas),effectivePairedN:deltas.length,missingN:pairs.length-deltas.length}]})) as Record<ResearchMetric,MatchedMetricDelta>;out.push({dimension,source,destination,commonPairUniverseN:pairs.length,unpairedN:oneSided,metrics,missingReasons:reasons})}return out}
