import type {PositionEconomics} from "../economics/position.ts";
import type {StructuralConfigurationFields} from "../economics/strategy-configuration.ts";
import {finite,median,metricValue,type Currency,type ResearchMetric} from "./statistics.ts";

export type ComparisonDimension="dte"|"width"|"strike";
export interface ResearchEconomicOpportunity {eventId:string;structuralConfigurationId:string;structuralConfiguration:StructuralConfigurationFields;candidateId:string|null;q50GenerationStatus:"trade"|"explicit_no_trade"|"unavailable";q50ReasonCode:string|null;q50Reason:string|null;integrityReason:string|null}
export const MATCHED_METRICS:readonly ResearchMetric[]=["pnl","grossCredit","netCredit","openingFees","totalFees","peakIm","openingIm","trackMaximumNetLoss","capitalDays","holdingDays","returnOnPeakCapital","feeDrag"];
const category=(o:ResearchEconomicOpportunity,d:ComparisonDimension)=>d==="dte"?o.structuralConfiguration.targetDteFamilyDays:d==="width"?o.structuralConfiguration.requestedWidth:o.structuralConfiguration.strikeMethod;
const controls=(o:ResearchEconomicOpportunity,d:ComparisonDimension)=>{const f=o.structuralConfiguration,values=d==="dte"?[f.strikeMethod,f.requestedWidth,f.structureFamily]:d==="width"?[f.targetDteFamilyDays,f.strikeMethod,f.structureFamily]:[f.targetDteFamilyDays,f.requestedWidth,f.structureFamily];return values.some(x=>x===null)?null:JSON.stringify([o.eventId,...values])};
export interface MatchedMetricDelta {btc:{medianDelta:number|null;effectivePairedN:number;missingPairedN:number};usd:{medianDelta:number|null;effectivePairedN:number;missingPairedN:number}}
export interface MatchedComparison {dimension:ComparisonDimension;source:string|number;destination:string|number;eligiblePairUniverseN:number;sourceOpportunityN:number;destinationOpportunityN:number;pricedBothN:number;sourceOnlyEvidenceN:number;destinationOnlyEvidenceN:number;metrics:Readonly<Record<ResearchMetric,MatchedMetricDelta>>;missingReasons:Readonly<Record<string,number>>}
export function buildMatchedComparisons(opportunities:readonly ResearchEconomicOpportunity[],positions:readonly PositionEconomics[],dimension:ComparisonDimension):readonly MatchedComparison[]{const positionByKey=new Map(positions.map(p=>[`${p.eventId}|${p.structuralConfigurationId}`,p])),groups=new Map<string,ResearchEconomicOpportunity[]>();for(const o of opportunities){const key=controls(o,dimension);if(key===null||category(o,dimension)===null)continue;const rows=groups.get(key)??[];rows.push(o);groups.set(key,rows)}const categories=[...new Set(opportunities.map(o=>category(o,dimension)).filter((x):x is string|number=>x!==null))].sort((a,b)=>typeof a==="number"&&typeof b==="number"?a-b:String(a).localeCompare(String(b))),out:MatchedComparison[]=[];for(let i=0;i<categories.length;i++)for(let j=i+1;j<categories.length;j++){const source=categories[i]!,destination=categories[j]!,pairs:{a:ResearchEconomicOpportunity;b:ResearchEconomicOpportunity}[]=[],reasons:Record<string,number>={};let sourceOpportunityN=0,destinationOpportunityN=0;for(const rows of groups.values()){const a=rows.filter(o=>category(o,dimension)===source),b=rows.filter(o=>category(o,dimension)===destination);if(a.length)sourceOpportunityN++;if(b.length)destinationOpportunityN++;if(a.length===1&&b.length===1)pairs.push({a:a[0]!,b:b[0]!});else if(a.length>1||b.length>1){const reason="duplicate canonical opportunity identity";reasons[reason]=(reasons[reason]??0)+1}}const evidence=pairs.map(({a,b})=>({a:positionByKey.get(`${a.eventId}|${a.structuralConfigurationId}`),b:positionByKey.get(`${b.eventId}|${b.structuralConfigurationId}`)})),pricedBothN=evidence.filter(x=>x.a?.status==="priced"&&x.b?.status==="priced").length,sourceOnlyEvidenceN=evidence.filter(x=>x.a?.status==="priced"&&x.b?.status!=="priced").length,destinationOnlyEvidenceN=evidence.filter(x=>x.a?.status!=="priced"&&x.b?.status==="priced").length,metrics=Object.fromEntries(MATCHED_METRICS.map(metric=>[metric,Object.fromEntries((["btc","usd"] as Currency[]).map(currency=>{const deltas=evidence.flatMap(({a,b})=>{if(a?.status!=="priced"||b?.status!=="priced")return[];const left=metricValue(a,metric,currency),right=metricValue(b,metric,currency);return finite(left)&&finite(right)?[right-left]:[]});return[currency,{medianDelta:median(deltas),effectivePairedN:deltas.length,missingPairedN:pairs.length-deltas.length}]}))])) as unknown as Record<ResearchMetric,MatchedMetricDelta>;out.push({dimension,source,destination,eligiblePairUniverseN:pairs.length,sourceOpportunityN,destinationOpportunityN,pricedBothN,sourceOnlyEvidenceN,destinationOnlyEvidenceN,metrics,missingReasons:reasons})}return out}
