import type {ResearchEconomicObservation,Statistic,TailStatistic} from "./types.ts";

const finite=(v:number|null):v is number=>v!==null&&Number.isFinite(v);
export const median=(values:readonly number[])=>{if(!values.length)return null;const s=[...values].sort((a,b)=>a-b),m=Math.floor(s.length/2);return s.length%2?s[m]!:(s[m-1]!+s[m]!)/2};
export const mean=(values:readonly number[])=>values.length?values.reduce((a,b)=>a+b,0)/values.length:null;
export const quantile=(values:readonly number[],q:number)=>{if(!values.length)return null;const s=[...values].sort((a,b)=>a-b),i=(s.length-1)*q,lo=Math.floor(i),hi=Math.ceil(i);return s[lo]!+(s[hi]!-s[lo]!)*(i-lo)};
export function statistic(rows:readonly ResearchEconomicObservation[],pick:(row:ResearchEconomicObservation)=>number|null,aggregate:(v:readonly number[])=>number|null=median,reason="No finite observations."):Statistic{const values=rows.map(pick).filter(finite);return{value:aggregate(values),rawDenominator:rows.length,effectiveN:values.length,unavailableCount:rows.length-values.length,reason:values.length?null:reason}}
export function tail(rows:readonly ResearchEconomicObservation[],pick:(row:ResearchEconomicObservation)=>number|null,q:number,minimumN:number):TailStatistic{const values=rows.map(pick).filter(finite),ok=values.length>=minimumN;return{value:ok?quantile(values,q):null,rawDenominator:rows.length,effectiveN:values.length,unavailableCount:rows.length-values.length,minimumN,reason:ok?null:`Requires at least ${minimumN} priced observations; ${values.length} are available.`}}
export function deriveUsdMetrics(row:Omit<ResearchEconomicObservation,"feeDragUsd"|"returnOnStructuralLossUsd"|"returnOnOpeningImUsd"|"returnOnPeakImUsd"|"pnlPerCapitalDayUsd">):ResearchEconomicObservation{const ratio=(n:number|null,d:number|null)=>n!==null&&Number.isFinite(n)&&d!==null&&Number.isFinite(d)&&d>0?n/d:null;return{...row,feeDragUsd:ratio(row.totalRealizedFeesUsd,row.grossOpeningCreditUsd),returnOnStructuralLossUsd:ratio(row.pnlUsd,row.maximumStructuralLossUsd),returnOnOpeningImUsd:ratio(row.pnlUsd,row.openingInitialMarginUsd),returnOnPeakImUsd:ratio(row.pnlUsd,row.peakInitialMarginUsd),pnlPerCapitalDayUsd:ratio(row.pnlUsd,row.capitalDaysUsd)}}

export function equalEventStatistic(rows:readonly ResearchEconomicObservation[],pick:(row:ResearchEconomicObservation)=>number|null,aggregate:(v:readonly number[])=>number|null):Statistic{const events=new Map<string,number[]>();for(const row of rows){const value=pick(row);if(!finite(value))continue;const values=events.get(row.eventId)??[];values.push(value);events.set(row.eventId,values)}const eventValues=[...events.values()].map(v=>mean(v)!).filter(finite);return{value:aggregate(eventValues),rawDenominator:new Set(rows.map(r=>r.eventId)).size,effectiveN:eventValues.length,unavailableCount:new Set(rows.map(r=>r.eventId)).size-eventValues.length,reason:eventValues.length?null:"No event has a finite observation."}}
