import type {Available,PositionEconomics} from "../economics/position.ts";

export type ResearchMetric="pnlUsd"|"grossCreditUsd"|"netCreditUsd"|"openingFeesUsd"|"totalFeesUsd"|"peakImUsd"|"openingImUsd"|"maximumStructuralLossUsd"|"trackMaximumNetLossUsd"|"capitalDaysUsd"|"holdingDays"|"returnOnPeakCapital"|"returnOnTrackMaximumLoss"|"feeDrag";
export const median=(values:readonly number[])=>{if(!values.length)return null;const x=[...values].sort((a,b)=>a-b),m=x.length>>1;return x.length%2?x[m]!:(x[m-1]!+x[m]!)/2};
export const mean=(values:readonly number[])=>values.length?values.reduce((a,b)=>a+b,0)/values.length:null;
export const finite=(value:number|null|undefined):value is number=>value!==null&&value!==undefined&&Number.isFinite(value);
export function metricValue(position:PositionEconomics,metric:ResearchMetric):number|null{switch(metric){case"pnlUsd":return position.pnlUsd;case"grossCreditUsd":return position.grossOpeningCreditUsd.value;case"netCreditUsd":return position.netOpeningCashFlowUsd.value;case"openingFeesUsd":return position.openingFeesUsd.value;case"totalFeesUsd":return position.totalRealizedFeesUsd.value;case"peakImUsd":return position.peakInitialMarginUsd.value;case"openingImUsd":return position.incrementalInitialMarginUsd.value;case"maximumStructuralLossUsd":return position.maximumStructuralLossUsd.value;case"trackMaximumNetLossUsd":return position.trackMaximumNetLossUsd.value;case"capitalDaysUsd":return position.capitalDaysUsd.value;case"holdingDays":return position.holdingDays;case"returnOnPeakCapital":return position.returnOnPeakCapital.value;case"returnOnTrackMaximumLoss":return position.returnOnTrackMaximumNetLoss.value;case"feeDrag":return finite(position.totalRealizedFeesUsd.value)&&finite(position.grossOpeningCreditUsd.value)&&position.grossOpeningCreditUsd.value>0?position.totalRealizedFeesUsd.value/position.grossOpeningCreditUsd.value:null}}
export function completeStatistic(values:readonly(number|null)[],requiredN:number):Available<number>&{effectiveN:number;requiredN:number}{const present=values.filter(finite);return present.length===requiredN?{value:median(present),reason:null,effectiveN:present.length,requiredN}:{value:null,reason:`Canonical USD coverage is ${present.length} / ${requiredN}; partial-cohort statistic is not reported.`,effectiveN:present.length,requiredN}}
/** One observation per event. Multiple generated variants are collapsed before aggregation. */
export function eventWeightedValues(positions:readonly PositionEconomics[],metric:ResearchMetric){const byEvent=new Map<string,number[]>();for(const p of positions){const value=metricValue(p,metric);if(!finite(value))continue;const values=byEvent.get(p.eventId)??[];values.push(value);byEvent.set(p.eventId,values)}return[...byEvent.values()].map(values=>median(values)!)}
