import type {MetricAvailability,ResearchEconomicMetric,ResearchEconomicObservation,Statistic,TailStatistic} from "./types.ts";

const finite=(value:number|null):value is number=>value!==null&&Number.isFinite(value);
export const median=(values:readonly number[])=>{if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b),middle=Math.floor(sorted.length/2);return sorted.length%2?sorted[middle]!:(sorted[middle-1]!+sorted[middle]!)/2};
export const mean=(values:readonly number[])=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:null;
export const quantile=(values:readonly number[],q:number)=>{if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b),index=(sorted.length-1)*q,lower=Math.floor(index),upper=Math.ceil(index);return sorted[lower]!+(sorted[upper]!-sorted[lower]!)*(index-lower)};

export function statistic(rows:readonly ResearchEconomicObservation[],pick:(row:ResearchEconomicObservation)=>number|null,aggregate:(values:readonly number[])=>number|null=median,reason="Canonical evidence is unavailable."):Statistic{const values=rows.map(pick).filter(finite);return{value:aggregate(values),status:values.length?"available":"unavailable",rawDenominator:rows.length,effectiveN:values.length,unavailableCount:rows.length-values.length,reason:values.length?null:reason,weighting:"identity_pair"}}

/** One event receives one value: the mean across qualifying configurations in that event. */
export function equalEventStatistic(rows:readonly ResearchEconomicObservation[],pick:(row:ResearchEconomicObservation)=>number|null,aggregate:(values:readonly number[])=>number|null=median):Statistic{const eligibleByEvent=new Map<string,number>(),availableByEvent=new Map<string,number[]>();for(const row of rows){eligibleByEvent.set(row.eventId,(eligibleByEvent.get(row.eventId)??0)+1);const picked=pick(row);if(finite(picked)){const values=availableByEvent.get(row.eventId)??[];values.push(picked);availableByEvent.set(row.eventId,values)}}const eventValues=[...availableByEvent.values()].map(values=>mean(values)!).filter(finite),completeEventN=[...eligibleByEvent].filter(([eventId,n])=>(availableByEvent.get(eventId)?.length??0)===n).length,partialEventN=[...eligibleByEvent].filter(([eventId,n])=>{const available=availableByEvent.get(eventId)?.length??0;return available>0&&available<n}).length,zeroEventN=eligibleByEvent.size-completeEventN-partialEventN,metricAvailableObservationN=[...availableByEvent.values()].reduce((n,values)=>n+values.length,0),coverage={eligibleObservationN:rows.length,metricAvailableObservationN,independentEligibleEventN:eligibleByEvent.size,completeEventN,partialEventN,zeroEventN,effectiveEventN:eventValues.length};return{value:aggregate(eventValues),status:eventValues.length?"available":"unavailable",rawDenominator:eligibleByEvent.size,effectiveN:eventValues.length,unavailableCount:eligibleByEvent.size-eventValues.length,reason:eventValues.length?null:"No independent event has finite canonical evidence.",weighting:"equal_event",coverage}}

export function equalEventTail(rows:readonly ResearchEconomicObservation[],pick:(row:ResearchEconomicObservation)=>number|null,q:number,minimumN:number):TailStatistic{const base=equalEventStatistic(rows,pick,values=>quantile(values,q)),enough=base.effectiveN>=minimumN,missingEvidence=base.effectiveN===0&&base.unavailableCount>0;return{...base,value:enough?base.value:null,status:enough?"available":missingEvidence?"unavailable":"insufficient_sample",minimumN,reason:enough?null:missingEvidence?"Unavailable — no independent event has the required canonical evidence.":`Not estimable — requires ${minimumN} independent events; effective independent event N=${base.effectiveN}.`,unavailableCount:base.unavailableCount}}

const availabilityKeys:readonly ResearchEconomicMetric[]=["grossOpeningCreditUsd","openingFeesUsd","netOpeningCreditUsd","totalRealizedFeesUsd","maximumStructuralLossUsd","trackMaximumNetLossUsd","openingInitialMarginUsd","peakInitialMarginUsd","pnlUsd","holdingDays","capitalDaysUsd","feeDragUsd","returnOnStructuralLossUsd","returnOnOpeningImUsd","returnOnPeakImUsd","pnlPerCapitalDayUsd"];
type Derivable=Omit<ResearchEconomicObservation,"feeDragUsd"|"returnOnStructuralLossUsd"|"returnOnOpeningImUsd"|"returnOnPeakImUsd"|"pnlPerCapitalDayUsd"|"metricAvailability"> & {metricAvailability?:Partial<MetricAvailability>};
const ratio=(numerator:number|null,denominator:number|null,label:string)=>numerator===null?{value:null,reason:"Numerator is unavailable."}:denominator===null?{value:null,reason:`${label} is unavailable.`}:denominator<=0?{value:null,reason:`${label} must be positive.`}:{value:numerator/denominator,reason:null};
export function deriveUsdMetrics(row:Derivable):ResearchEconomicObservation{const feeDrag=ratio(row.totalRealizedFeesUsd,row.grossOpeningCreditUsd,"Gross opening credit USD"),structuralReturn=ratio(row.pnlUsd,row.maximumStructuralLossUsd,"Maximum structural loss USD"),openingReturn=ratio(row.pnlUsd,row.openingInitialMarginUsd,"Opening IM USD"),peakReturn=ratio(row.pnlUsd,row.peakInitialMarginUsd,"Peak IM USD"),capitalDayReturn=ratio(row.pnlUsd,row.capitalDaysUsd,"Capital-days USD");const derived={feeDragUsd:feeDrag.value,returnOnStructuralLossUsd:structuralReturn.value,returnOnOpeningImUsd:openingReturn.value,returnOnPeakImUsd:peakReturn.value,pnlPerCapitalDayUsd:capitalDayReturn.value},derivedReasons:Partial<MetricAvailability>={feeDragUsd:feeDrag.reason,returnOnStructuralLossUsd:structuralReturn.reason,returnOnOpeningImUsd:openingReturn.reason,returnOnPeakImUsd:peakReturn.reason,pnlPerCapitalDayUsd:capitalDayReturn.reason},metricAvailability=Object.fromEntries(availabilityKeys.map(key=>[key,row.metricAvailability?.[key]??derivedReasons[key]??((row[key as keyof Derivable] as number|null)===null?"Canonical USD value is unavailable.":null)])) as unknown as MetricAvailability;return{...row,...derived,metricAvailability}}
